from pathlib import Path
import json, subprocess, hashlib, re, collections

ROOT=Path('D:/Projects/open-skills/ComposioHQ/awesome-claude-skills')
OUT=Path('D:/Projects/prompt-context-patterns-refresh/docs/audit')
COMMIT=subprocess.check_output(['git','-C',str(ROOT),'rev-parse','HEAD'],text=True).strip()
assert COMMIT=='be2a406907dbc61b73e6827ded415c96139d13a2', 'Frozen source HEAD changed; review before regenerating.'
REPO='ComposioHQ/awesome-claude-skills'
candidates=[]

def source(path, start, end, section):
    lines=(ROOT/path).read_text(encoding='utf-8').splitlines()
    assert 1 <= start <= end <= len(lines), (path,start,end,len(lines))
    parent=Path(path).parent
    while parent != Path('.') and not (ROOT/parent/'LICENSE.txt').exists(): parent=parent.parent
    lp=str(parent/'LICENSE.txt').replace('\\','/') if parent!=Path('.') else None
    license='no-explicit-license'
    if lp:
        text=(ROOT/lp).read_text(encoding='utf-8')
        license='Apache-2.0' if 'Apache License' in text else 'Anthropic proprietary / source-available; no reproduction'
    if path=='langsmith-fetch/SKILL.md':license='MIT declared in skill footer; no standalone license file'
    return dict(repo=REPO,commit=COMMIT,path=path,line_start=start,line_end=end,section=section,license=license,license_path=lp,role='observed-example',url=f'https://github.com/{REPO}/blob/{COMMIT}/{path}#L{start}-L{end}')

def add(key,en,zh,category,src,en_content,zh_content,ids=None,status=None,tags=None):
    names=['description','scenario','mechanism','bad','good','why','expected','boundaries']
    assert len(en_content)==len(zh_content)==8
    ids=ids or []
    candidates.append(dict(key='composio-'+key,name={'en':en,'zh':zh},category=category,tags=tags or [category,'composio'],status=status or ('merged' if ids else 'active'),reason=('Same core mechanism as existing pattern; enrich its sources and examples instead of adding a new ID.' if ids else 'Distinct reusable procedural mechanism; editorial examples make its observable contract and limits explicit.'),suggested_existing_ids=ids,content={'en':dict(zip(names,en_content)),'zh':dict(zip(names,zh_content))},example_origin='project-authored-teaching-construction',sources=[source(*s) for s in src],scores={'scenario':2,'mechanism':2,'contrast':2,'observable':2,'boundaries':2},quality_total=10,efficacy_status='editorial-review-only',original_origin_status='earliest-origin-not-established'))

add('discover-connect-execute','Discover, connect, execute','发现工具、连接账号、执行','tools',[('composio-skills/ably-automation/SKILL.md',29,78,'Tool Discovery / Core Workflow Pattern')],
['Find the actual tool contract and active account before calling a service.','Export Ably resources using an MCP toolkit not yet used in this session.','Search the specific task, inspect returned schemas, confirm ACTIVE connection, then execute with the same session.','Call a guessed ABLY_EXPORT endpoint with remembered fields.','Search export resources; select the returned slug/schema; confirm the account is ACTIVE; execute its exact fields.','The invocation is grounded in a discovered contract and authenticated account.','The record contains discovery result, account state, execution result and session ID.','Discovery does not authorize writes; retain task-specific authorization and validate results.'],
['调用服务前先找到真实工具契约并确认账号连接。','使用本会话尚未调用过的 MCP 工具包导出 Ably 资源。','按具体任务检索，阅读返回的 schema，确认 ACTIVE 连接，再在同一会话执行。','凭记忆猜测 ABLY_EXPORT 接口和参数。','检索导出资源，选择返回的工具及 schema，确认账号 ACTIVE，再按实际字段执行。','调用依据是已发现的契约和账号状态。','记录中可检查发现结果、账号状态、执行结果和会话 ID。','发现工具不等于获得写入授权；仍须遵守任务授权并检查结果。'],[109])

add('schema-reference-expansion','Resolve schema references before arguments','先展开 schema 引用再构造参数','tools',[('composio-skills/anthropic_administrator-automation/SKILL.md',93,108,'Known Pitfalls')],
['Load a referenced schema before constructing tool arguments.','A discovered upload tool returns schemaRef rather than inline fields.','Fetch the full schema, inspect required fields/types, then construct and validate arguments.','Treat schemaRef as a complete schema and guess file/content fields.','Resolve schemaRef; inspect required file object and format fields; submit only supported fields.','A reference names information; it does not contain that information.','The execution payload matches a full schema fetched in this workflow.','Do not expand unrelated tool schemas; refresh if the service changes the contract.'],
['工具只返回 schema 引用时，先加载完整定义。','检索到的上传工具返回 schemaRef，没有内联字段。','展开引用，检查必填字段及类型，再构造并校验参数。','把 schemaRef 当成完整定义，猜测 file 和 content 字段。','展开 schemaRef，检查实际文件对象与格式字段，再提交受支持字段。','引用只指向信息，本身不包含契约内容。','执行参数可与本流程加载的完整 schema 一一核对。','只展开本任务相关的 schema；契约变化后重新获取。'])

add('pagination-completion','Prove paginated retrieval is complete','提供分页读取完成证据','tools',[('composio-skills/mailerlite-automation/SKILL.md',115,121,'Known Pitfalls'),('composio-skills/gorgias-automation/SKILL.md',116,120,'Known Pitfalls')],
['Follow each endpoint’s continuation contract and distinguish complete from partial retrieval.','Calculate engagement across all subscribers.','Accumulate pages until the documented terminal cursor; record page count, record count and any failure/cap.','Compute all-subscriber engagement from the first 50 returned records.','Follow meta.next_cursor until null; aggregate records; label partial if fetching fails or a cap is reached.','A successful page response says nothing about unrequested pages.','The report records terminal cursor and page count, or explicitly says partial.','Completeness is relative to filter and permissions; never bypass quotas to finish.'],
['按各接口的续页契约读取，并区分完整与部分结果。','计算全部订阅者的互动指标。','循环读取至规定的终止游标，记录页数、记录数及失败或上限。','用首页的 50 条记录计算全部订阅者指标。','沿 meta.next_cursor 读到 null 后聚合；失败或到达上限时明确标为部分结果。','单页请求成功不能证明未请求页面的内容完整。','报告包含终止游标及页数，或明确说明结果不完整。','完整性仍受过滤范围和权限限制；不得绕过配额。'])

add('resolve-scoped-identities','Resolve opaque IDs within their scope','在所属范围解析不透明 ID','tools',[('composio-skills/clockify-automation/SKILL.md',126,130,'Known Pitfalls'),('composio-skills/googletasks-automation/SKILL.md',114,119,'Known Pitfalls')],
['Translate human names into service IDs while retaining parent scope.','Update a task named Budget in the Finance task list.','List the intended parent, resolve task ID inside that parent and pass both identifiers.','Use task_id=Budget and tasklist_id=Finance because those are their labels.','Resolve Finance to list L7; find Budget inside L7 as task T9; update using L7 and T9.','Labels are not IDs, and child IDs may depend on the parent.','The request includes IDs returned by lookup in the chosen parent.','Disambiguate duplicate names; do not reuse IDs across workspaces.'],
['把人类名称解析成服务 ID，并保留父级范围。','修改 Finance 任务列表中名为 Budget 的任务。','先找到目标父级，再在其中解析任务 ID，提交两者。','直接传 task_id=Budget、tasklist_id=Finance。','解析 Finance 为列表 L7，再找到其中 Budget 的任务 T9，用 L7 和 T9 更新。','名称不是 ID，子资源 ID 还可能受父级限制。','请求使用目标父级查找结果中的真实 ID。','同名资源需消歧；不跨工作区复用 ID。'])

add('tenant-bound-routing','Bind actions to the selected tenant','将操作绑定到选定租户','safety',[('composio-skills/xero-automation/SKILL.md',181,188,'Known Pitfalls')],
['Select the intended organization explicitly instead of accepting a first-account default.','Read invoices for the user’s subsidiary B while two organizations are connected.','List connections, match the intended organization and include its tenant_id in subsequent calls.','Omit tenant_id and assume the first connected organization is B.','List connections; match subsidiary B to tenant TB; read invoices with tenant_id=TB.','An authenticated account can still address the wrong organization.','Every relevant call and report identifies tenant TB.','Ask when the user’s organization cannot be uniquely matched; redact credentials.'],
['明确选择目标组织，避免默认使用第一个连接账号。','两个组织已连接，用户要读取子公司 B 的发票。','列出连接并匹配目标组织，后续调用显式带 tenant_id。','省略 tenant_id，假定第一个连接组织就是 B。','列出连接，将子公司 B 匹配为 TB，使用 tenant_id=TB 读取发票。','账号已认证仍可能操作错误组织。','相关调用和报告均指明租户 TB。','无法唯一匹配组织时询问；不展示凭据。'])

add('fresh-version-update','Read fresh version tokens before update','更新前读取最新版本令牌','tools',[('composio-skills/contentful-automation/SKILL.md',86,92,'Known Pitfalls'),('composio-skills/quickbooks-automation/SKILL.md',138,143,'Known Pitfalls')],
['Use the resource’s current concurrency token for a write.','Rename a shared space after another user might have edited it.','Read immediately before writing, send the returned version, and re-read/reconcile on conflict.','Reuse yesterday’s sys.version to rename the space.','Read the current space and version 12; submit the rename with 12; reconcile after a conflict rather than forcing the old snapshot.','The server can detect intervening edits.','The write references a fresh read and conflict handling is visible.','A fresh read is not a lock; conflicts still require intent-preserving reconciliation.'],
['写入时使用资源当前的并发版本令牌。','其他人可能修改过一个共享空间，现在需要重命名。','紧邻写入前读取，携带返回版本；冲突时重读并协调。','使用昨天缓存的 sys.version 重命名。','读取当前空间及版本 12，用 12 提交重命名；冲突后协调，不强推旧快照。','服务端可发现读取后发生的其他修改。','写入对应一次最新读取，并有明确冲突处理。','最新读取不是锁；冲突仍须保留各方意图。'])

add('replace-versus-patch','Check replace semantics before editing','编辑前区分替换与局部更新','tools',[('composio-skills/googledocs-automation/SKILL.md',96,108,'Common Patterns / Known Pitfalls'),('composio-skills/lever-automation/SKILL.md',125,129,'Known Pitfalls')],
['Choose an update method according to whether it replaces or patches content.','Append one paragraph to an existing project report.','Inspect tool semantics; use append for additions or read/merge/full payload for a replacement endpoint.','Send only the new paragraph to a tool that replaces the entire document.','Use the append tool at the end; if only replacement exists, read the report, merge the paragraph and submit the complete content.','The intended edit is preserved without dropping untouched content.','The resulting document still contains the old sections plus the new paragraph.','Read-back verification is needed; concurrent edits may require version checks.'],
['依据工具是整份替换还是局部修改来选择编辑方式。','在已有项目报告末尾增加一段文字。','检查工具语义；增加内容使用 append，整份替换接口则先读、合并、再提交完整内容。','向整份替换工具仅提交新段落。','使用末尾追加工具；如果只有替换接口，先读报告，合并新段落后提交全文。','实现所需修改同时保留未涉及的内容。','结果仍有旧章节及新增段落。','须读回验证；并发编辑还可能要求版本检查。'])

add('per-item-batch-status','Validate per-item outcomes inside batch success','批量成功时仍检查逐项结果','tools',[('composio-skills/firecrawl-automation/SKILL.md',147,155,'Known Pitfalls'),('composio-skills/apollo-automation/SKILL.md',138,144,'Known Pitfalls')],
['Inspect nested item results instead of accepting a successful envelope as total success.','Scrape 10 URLs and produce a coverage report.','Inspect each item’s status/error, separate completed/failed/missing items, then retry only appropriate failures.','HTTP 200 means all 10 pages were scraped successfully.','Read each item; report 8 complete and 2 DNS failures; retain failed URLs for follow-up.','Transport success and business-operation success are different layers.','Completed plus failed/missing items reconcile to the requested inputs.','Validate response shape from actual output; do not invent missing results.'],
['检查嵌套的逐项结果，不把成功响应外壳等同全部成功。','抓取 10 个 URL 并提供覆盖报告。','检查每项状态及错误，区分完成、失败和缺失，再按类别处理失败项。','HTTP 200 就代表 10 个页面全成功。','检查每项后报告 8 个完成、2 个 DNS 失败，并保留失败 URL。','传输成功与业务操作成功处于不同层次。','完成、失败和缺失项总数可与输入数量核对。','根据实际响应结构解析；不编造缺失结果。'])

add('error-directed-recovery','Recover according to failure class','按失败类别选择恢复动作','tools',[('composio-skills/apollo-automation/SKILL.md',138,144,'Known Pitfalls'),('composio-skills/firecrawl-automation/SKILL.md',147,149,'Known Pitfalls'),('composio-skills/hunter-automation/SKILL.md',129,135,'Known Pitfalls')],
['Treat authorization, invalid input, throttling and empty data as different outcomes.','A contact lookup returns HTTP 403.','Inspect service error details; repair credentials/permissions for auth failures, arguments for validation, backoff for throttling, and accept documented empty results.','Retry the identical 403 request ten times.','Read the access error; stop retries; identify missing permission and resume only after credentials are repaired.','Retries do not repair deterministic configuration errors.','The recovery action matches the recorded error class.','Status codes alone may be ambiguous; use service error details and bounded retries.'],
['将授权、参数错误、限流与空数据分开处理。','联系人查询返回 HTTP 403。','结合服务错误详情判断：授权问题修凭据，参数问题修输入，限流退避，规定的空结果正常处理。','连续重试十次相同的 403 请求。','读取访问错误，停止重试，明确缺失权限，修复凭据后再继续。','重复请求不能修复确定性的配置错误。','恢复动作与记录的失败类别一致。','仅凭状态码可能有歧义；需结合详情并限制重试次数。'])

add('async-terminal-state','Wait for a job’s terminal state','等待异步任务到达终态','workflow',[('composio-skills/firecrawl-automation/SKILL.md',152,153,'Known Pitfalls'),('composio-skills/heygen-automation/SKILL.md',98,104,'Known Pitfalls')],
['Separate accepted jobs from completed outputs.','Generate a video whose creation response returns job_id=J3.','Save job ID, poll status within a task budget, retrieve output after completion, and report pending/failed states honestly.','Publish the creation response as if the video already exists.','Save J3; poll until completed; then retrieve the video URL; if the budget expires report J3 as pending.','Job acceptance does not establish usable output.','The report contains terminal status and output, or a resumable pending job ID.','Set bounded polling and cancellation policy; temporary output URLs may expire.'],
['区分任务被接受与产物已完成。','视频生成接口返回 job_id=J3。','保存任务 ID，在任务预算内轮询；完成后获取产物，并如实报告等待或失败。','把创建响应当成已生成视频直接发布。','保存 J3，轮询至 completed 再获取视频 URL；预算用尽则报告 J3 仍在等待。','接受异步任务不能证明产物可用。','报告包含终态及产物，或可继续跟踪的等待任务 ID。','限定轮询次数与取消规则；产物临时 URL 可能过期。'])

add('stable-external-key-upsert','Reuse stable external keys for upsert','使用稳定外部键进行 upsert','tools',[('composio-skills/netsuite-automation/SKILL.md',190,210,'Recommended Execution Plan / Known Pitfalls')],
['Use one consistent external identity across repeated sync runs.','Sync CRM customer C42 into an ERP twice.','Derive and persist a stable external key, inspect existing records, upsert by that key and verify the returned record.','Generate a new random external ID for C42 on every sync.','Use crm:C42 for both runs; upsert by crm:C42 and verify the same ERP record is updated.','A changing key makes an upsert behave like repeated creation.','Both runs return the same target identity with the intended latest fields.','Requires actual upsert semantics and stable source identities; handle collisions explicitly.'],
['在重复同步时复用同一外部身份键。','把 CRM 客户 C42 两次同步到 ERP。','生成并保存稳定外部键，检查已有记录，按键 upsert，再验证返回资源。','每次同步 C42 都生成一个新的随机外部 ID。','两次都使用 crm:C42，按该键 upsert 并验证更新的是同一 ERP 记录。','每次改变键会把 upsert 变成重复创建。','两次返回相同目标身份，字段更新符合预期。','须确认真实 upsert 语义及来源身份稳定；显式处理键冲突。'])

add('checkpoint-bulk-progress','Checkpoint partial bulk progress','为批处理保存部分进度','workflow',[('composio-skills/lemlist-automation/SKILL.md',113,117,'Known Pitfalls'),('composio-skills/gorgias-automation/SKILL.md',116,120,'Known Pitfalls')],
['Process bounded batches and persist completed work for safe resume.','Import 120 leads while intermittent failures are possible.','Chunk within service limits, record successful item IDs and continuation state, then resume unresolved work only.','Restart the entire import after batch three fails.','Import bounded chunks; save successful IDs after each chunk; resume remaining IDs after the failure.','A checkpoint preserves acknowledged work across interruptions.','The resume list excludes already acknowledged items and reconciles every requested ID.','Checkpointing alone does not ensure exactly-once writes; combine with idempotency keys or lookups.'],
['分批处理并保存已确认进度，以便中断后继续。','导入 120 条潜客记录，期间可能发生间歇失败。','按服务上限分块，保存成功 ID 与续页状态，只继续处理未解决项。','第三批失败后重新导入全部记录。','使用有界批次，每批保存成功 ID；失败后从剩余 ID 继续。','检查点在中断后保留已确认的工作。','恢复列表不含已确认项，并覆盖每个请求 ID。','检查点本身不保证恰好一次写入；结合幂等键或现有资源查询。'])

add('pilot-fixed-extraction-contract','Pilot a fixed extraction contract','先小样本验证固定抽取契约','evaluation',[('composio-skills/firecrawl-automation/SKILL.md',147,155,'Known Pitfalls')],
['Freeze extraction fields and validate a small sample before scaling.','Extract title and price from 1,000 product pages.','Fix schema and null/error rules, test representative pages, inspect results and only scale after the contract is usable.','Change requested fields per page and launch 1,000 extracts immediately.','Fix title:string and price:number-or-null; test several distinct page layouts; inspect missing fields before scaling.','The sample exposes contract mismatch before broad execution.','Pilot outputs conform to the same schema and failures are recorded.','A passing sample does not prove full population correctness; retain per-item validation.'],
['固定抽取字段，在扩大执行前验证小样本。','从 1,000 个商品页抽取标题和价格。','固定 schema 与空值/错误规则，测试代表性页面，检查结果后再扩展。','每个页面临时改变字段，直接发起 1,000 次抽取。','固定 title 字符串和 price 数字或空值；测试不同布局，扩展前检查缺失字段。','小样本可暴露契约与页面不匹配。','试跑结果使用同一 schema，失败有记录。','样本通过不证明全体正确；仍需逐项校验。'])

add('truncation-with-continuation','Signal truncation and provide continuation','说明截断并提供继续获取方式','context',[('mcp-builder/reference/mcp_best_practices.md',143,151,'Character Limits and Truncation')],
['Bound tool output while exposing what was omitted and how to retrieve it.','A search finds 2,000 records but the agent needs a short result.','Return a useful slice with truncation/continuation metadata and suggested filters.','Return the first 20 records under the title All results.','Return 20 records; state truncated=true and next_cursor=C20; offer a narrower filter or continuation.','The agent can distinguish a bounded view from the complete dataset.','Output has explicit truncation status and a usable continuation/filter.','Do not silently truncate records needed for exact totals; use programmatic aggregation when appropriate.'],
['限制工具输出，同时说明省略范围与继续获取办法。','检索找到 2,000 条记录，代理目前只需简短结果。','返回有用片段，并提供截断及续页信息和缩小范围建议。','只返回前 20 条，却标为全部结果。','返回 20 条，标 truncated=true 和 next_cursor=C20，提供过滤或继续读取方式。','代理可以分辨有界视图与完整数据集。','输出有明确截断状态和可用续页或过滤参数。','精确总计不能静默截断；必要时使用程序聚合。'])

add('tool-metadata-is-not-authorization','Tool annotations are not authorization','工具标注不等于授权','safety',[('mcp-builder/reference/mcp_best_practices.md',269,272,'Tool Annotations'),('mcp-builder/reference/mcp_best_practices.md',895,905,'Best practices for tool annotations')],
['Treat tool safety annotations as descriptive hints, not enforcement.','A third-party tool claims readOnlyHint=true.','Check the actual operation, server trust and task authorization; enforce permissions outside the model’s reliance on hints.','Allow every call solely because readOnlyHint is true.','Inspect the operation’s effects and enforce a read-only account policy; reject any unauthorized write regardless of its hint.','An untrusted server can misdescribe its side effects.','The access decision records actual permissions and operation effects rather than only annotations.','Hints remain useful for presentation; they cannot replace server-side checks.'],
['把工具安全标注视为说明性提示，而非权限执行机制。','第三方工具声明 readOnlyHint=true。','检查真实操作、服务信任及任务授权，在模型判断之外执行权限限制。','仅因 readOnlyHint=true 就允许任意调用。','检查操作副作用并限制只读账号权限；无论标注如何都拒绝未授权写入。','不可信服务可能错误描述副作用。','权限决策依据实际权限和操作行为，不能只有标注。','标注可帮助展示，但不能替代服务端权限检查。'])

add('stable-readonly-evaluation','Stable read-only evaluation oracle','稳定的只读评测答案','evaluation',[('mcp-builder/reference/evaluation.md',45,76,'Core Requirements / Complexity'),('mcp-builder/reference/evaluation.md',103,155,'Stability / Answer Guidelines')],
['Use independent read-only tasks with a verified answer from a frozen period.','Evaluate whether an agent can traverse an issue tracker correctly.','Select closed historical data, verify the answer, specify its format and ensure no task depends on another task’s writes.','Ask how many issues are open now and compare against last week’s count.','Ask who closed the most eligible issues in a fixed archived quarter; verify the username and require that exact format.','Changing live state cannot act as a stable answer key.','Repeated runs against the same archived snapshot compare to the same verified answer.','Exact match tests format and result, not reasoning quality; inspect traces separately.'],
['使用互相独立的只读任务，并从固定时期验证答案。','评测代理是否能正确遍历问题跟踪系统。','选择已结束的历史数据，验证答案，指定格式，避免任务依赖其他任务的写入。','问现在有多少未关闭问题，却用上周的数量作答案。','问固定归档季度里谁关闭最多符合条件的问题，验证用户名并要求该格式。','实时变化的状态不能作为稳定答案键。','对相同归档快照重复评测，使用同一已验证答案。','精确匹配检查格式和结果，不代表推理质量；另行检查轨迹。'])

add('runtime-trace-first','Inspect runtime traces before explanations','先检查运行轨迹再解释','evaluation',[('langsmith-fetch/SKILL.md',84,99,'Deep Dive Specific Trace'),('langsmith-fetch/SKILL.md',228,256,'Common Use Cases')],
['Ground an agent failure diagnosis in the observed execution sequence.','The agent updated the wrong record.','Fetch the specific trace, inspect available tools, actual arguments and returned results, then propose a supported cause.','Explain the mistake from what agents usually do without examining this run.','Fetch trace R7; locate the lookup and update arguments; identify the mismatched record ID and recommend a scoped lookup.','The cause connects to the actual actions of the failing run.','The diagnosis cites the trace and tool calls that support it.','No trace may mean tracing is disabled; absence of traces is not proof no execution occurred.'],
['用实际执行序列支持代理失败诊断。','代理修改了错误记录。','获取对应轨迹，检查当时工具、真实参数及返回结果，再提出有依据的原因。','不看本次运行，凭代理通常行为解释错误。','获取轨迹 R7，找到查询与更新参数，指出记录 ID 不一致并建议范围内查询。','原因与失败运行中真实动作相连。','诊断引用支持判断的轨迹及工具调用。','无轨迹可能是追踪关闭，不能据此证明没有执行。'],[26])

add('progressive-disclosure','Progressive skill context loading','逐层加载技能上下文','context',[('skill-creator/SKILL.md',46,85,'Bundled Resources / Progressive Disclosure')],
['Separate trigger metadata, core procedure and on-demand references/assets.','A document skill supports several unrelated editing workflows.','Keep discovery metadata short, load core instructions on activation, and load only references needed by the selected branch.','Load every API guide and asset into every conversation.','Read the trigger summary; for a redline task load its procedure and redline reference; use output assets without pasting their contents.','Resources have different roles and loading times.','The context includes only relevant procedure/reference text; asset paths remain usable.','Critical global constraints must remain in the loaded core; referenced files must exist.'],
['区分触发元数据、核心流程和按需参考资料及资产。','文档技能支持多个互不相关的编辑流程。','保留简短发现信息，触发后加载核心流程，分支确定后加载所需参考。','每次会话都加载所有 API 指南和资产内容。','先读触发摘要；修订任务只读对应流程与参考，输出资产直接引用路径。','不同资源承担不同角色，应在不同时间加载。','上下文只包含相关流程及参考文本，资产路径仍可用。','全局关键约束必须留在已加载核心中；参考文件必须存在。'],[100])

add('intent-reference-routing','Route intent to a named reference','按意图路由到具名参考文件','context',[('internal-comms/SKILL.md',19,29,'How to use this skill')],
['Map the requested communication type to a specific guideline file.','Write a weekly team Progress/Plans/Problems update.','Classify the type, load its named file, and apply that file’s audience and format rules.','Use company newsletter rules for a team status update.','Recognize a 3P update; load examples/3p-updates.md; use its Progress, Plans and Problems format.','Routing avoids mixing neighboring but different output contracts.','The selected reference matches the requested communication type.','Unknown types require format clarification or an explicitly suitable general reference.'],
['将请求的沟通类型对应到具体指南文件。','编写团队每周进展、计划与问题更新。','识别类型，加载具名文件，遵守该文件的受众和格式。','把公司通讯规则用于团队状态更新。','识别为 3P 更新，加载 examples/3p-updates.md，使用 Progress、Plans、Problems 格式。','路由避免相邻任务的输出契约混杂。','选定参考文件与请求沟通类型一致。','未知类型需澄清格式，或明确采用合适的通用指南。'],[85])

add('helper-blackbox','Use a helper through its contract','按契约使用辅助脚本','context',[('webapp-testing/SKILL.md',11,14,'Helper Scripts Available'),('webapp-testing/SKILL.md',83,96,'Best Practices')],
['Read a helper’s usage contract before loading its implementation.','Test a web application using a bundled server manager.','Inspect help, invoke the supported interface, and read source only for a concrete customization need.','Paste the entire server manager into context before discovering its arguments.','Read the helper’s help; pass the server/port/test command it documents; inspect source only if required behavior is unsupported.','The task needs an interface contract before implementation details.','The invocation uses documented arguments without unnecessary source loading.','Run helpers only when their source/provenance and task authorization permit execution.'],
['先读取辅助脚本的使用契约，再决定是否加载实现。','用随附服务管理脚本测试网页应用。','查看帮助，按接口调用；存在具体定制需求时再读源码。','未了解参数就把整份服务管理源码贴进上下文。','读取帮助并按说明传 server、port、test 命令；只有功能不支持时才读实现。','任务首先需要接口契约，而非实现细节。','调用参数符合说明，避免不必要的源码加载。','只有来源可信且任务允许执行时才运行辅助脚本。'],[104])

add('rendered-reconnaissance','Inspect rendered state before UI actions','操作前检查渲染状态','tools',[('webapp-testing/SKILL.md',16,33,'Decision Tree'),('webapp-testing/SKILL.md',65,81,'Reconnaissance-Then-Action')],
['Wait for meaningful readiness and inspect the rendered UI before selecting actions.','Click the Export button in a dynamically loaded dashboard.','Navigate, wait for the actual target UI, inspect DOM/screenshot and act on the discovered selector.','Click a guessed selector while the dashboard is still loading.','Wait until the Export control is visible; inspect its role/name; click that discovered control and verify the result.','Selectors refer to the rendered state the user actually sees.','The target exists in observed rendered state and the expected action result is checked.','Network idle is one source example, not a universal readiness signal; polling apps need condition-based waits.'],
['等待有意义的就绪条件，并检查渲染后的界面再操作。','点击动态加载仪表盘中的 Export 按钮。','导航后等待目标界面，检查 DOM 或截图，再对发现的选择器操作。','仪表盘尚在加载时点击猜测的选择器。','等待 Export 控件可见，检查角色和名称，点击已发现的控件并验证结果。','选择器对应用户实际看到的渲染状态。','目标存在于已观察界面，且检查了动作结果。','network idle 只是来源示例，不适合所有应用；持续轮询应用需要条件等待。'],[103])

add('managed-helper-lifecycle','Manage helper process lifetime','管理辅助进程生命周期','workflow',[('webapp-testing/scripts/with_server.py',63,101,'main lifecycle')],
['Start dependencies, wait for readiness, execute the task and always clean up owned processes.','Run a browser test that needs a frontend and backend server.','Track started processes, bound readiness waiting, propagate the test result, and clean up in a finally block.','Start servers and leave them running after a failed browser test.','Start both servers; wait within a timeout; run the test; preserve its exit status; stop owned servers on success or failure.','Task failure must not skip resource cleanup.','The command returns the test outcome and owned processes are terminated.','A listening port does not prove application health; production helpers need stronger readiness and process-tree handling.'],
['启动依赖，等待就绪，运行任务，并始终清理自己启动的进程。','运行依赖前端与后端服务的浏览器测试。','记录启动进程，限制等待时间，传播测试结果，用 finally 清理。','启动服务后，浏览器测试失败也不停止服务。','启动两个服务并限时等就绪，运行测试，保留退出状态，无论成败均停止自己启动的服务。','任务失败不能跳过资源清理。','命令返回测试结果，所启动的进程已终止。','端口可连不代表应用健康；生产辅助工具应加强就绪检查和进程树清理。'])

add('creative-philosophy','Creative philosophy before rendering','渲染前建立创作理念','prompt',[('canvas-design/SKILL.md',15,51,'Design Philosophy Creation')],
['Describe the visual principles before implementing an open-ended art brief.','Create a poster about a community garden.','Write a concise philosophy for hierarchy, color, space and rhythm, then use it to guide the canvas.','Choose unrelated colors and decorative elements while drawing.','Set a philosophy of clustered organic forms and sparse labels; use it to choose composition and palette.','A shared conceptual scaffold makes local choices assessable.','The canvas can be reviewed against explicit visual principles.','A philosophy cannot replace legibility checks or the user’s requested information.'],
['开放式艺术任务先写明视觉原则，再实现画面。','为社区花园制作海报。','先简要说明层级、色彩、空间和节奏，再据此创作画布。','边画边随意选不相关颜色和装饰。','确定有机聚合形态与少量标签的理念，再用它决定构图及配色。','共同概念框架让局部选择可以评估。','最终画布可与明确视觉原则对照审核。','理念不能替代可读性检查或用户要求的信息。'],[101])

add('refinement-pass','Refine the existing artifact','对已有产物进行精修','workflow',[('canvas-design/SKILL.md',120,126,'Final Step')],
['Reserve a pass for improving the existing composition rather than adding more elements.','A poster draft has crowded labels and uneven spacing.','Inspect the draft, reduce collisions, adjust spacing and hierarchy, then recheck.','Add more shapes to make the crowded draft look more polished.','Align existing labels, remove overlap, simplify distractions and review the same canvas again.','Refinement addresses specific defects in the current artifact.','The revised artifact resolves named layout problems without unexplained extra content.','Critique must be based on the actual artifact; do not invent a user complaint.'],
['保留一轮改进已有构图，而不是不断添加元素。','海报初稿标签拥挤，间距不一致。','检查初稿，减少冲突，调整间距与层级，再复查。','为让拥挤初稿更精致而增加更多形状。','对齐已有标签，去除重叠，简化干扰，再检查同一画布。','精修针对当前产物的具体缺陷。','修订解决已指出的问题，没有无依据新增内容。','批评必须依据实际产物；不得虚构用户不满。'],[102])

add('collaborative-section-drafting','Review writing section by section','逐段协作写作与评审','workflow',[('content-research-writer/SKILL.md',202,262,'Section-by-Section Feedback / Preserve Voice'),('content-research-writer/SKILL.md',449,457,'Blog Post Workflow')],
['Alternate drafting and focused feedback while preserving the author’s voice.','Write a technical blog post with the user’s existing outline.','Draft one section, review clarity/evidence/flow with concrete edits, capture feedback and continue.','Rewrite the entire article in a generic voice before showing any section.','Draft the introduction; offer specific edits and reasons; incorporate tone feedback before the next section.','Feedback arrives before problems spread through the whole draft.','Each review names a section and concrete changes; the final draft reflects recorded preferences.','Use this interaction level when collaboration is desired; autonomous batch writing may need fewer interruptions.'],
['交替进行写作和聚焦反馈，并保留作者语气。','基于用户已有提纲撰写技术博客。','先写一个章节，具体评审清晰度、证据与衔接，记录反馈后继续。','未展示章节就把全文重写为通用语气。','先写引言，给出具体修改及理由，吸收语气反馈后再写下节。','问题尚未扩散到全文时即可得到反馈。','每次评审指出具体章节和修改，终稿反映记录的偏好。','适用于用户希望协作的任务；自主批量写作可以减少打断。'],[106])

add('audience-purpose-calibration','Calibrate output to audience and purpose','按受众与目的校准输出','output',[('internal-comms/examples/general-comms.md',5,16,'General communication principles'),('internal-comms/examples/company-newsletter.md',23,34,'Prioritization')],
['Choose scope, tone and detail according to who will read the output and why.','Convert engineering updates into a company-wide newsletter.','Identify audience/purpose, prioritize company impact and omit irrelevant implementation detail.','Copy every task-level debugging note into the company newsletter.','Select company-wide outcomes with source links; summarize each in one or two sentences using the chosen tone.','The output’s information budget serves the actual reader.','Each included item has audience-relevant impact and a traceable source.','Do not drop breaking changes or risks merely to be concise.'],
['依据读者与目的选择范围、语气和细节。','把工程更新转成全公司通讯。','明确受众和目的，优先公司层面影响，去除无关实现细节。','把每条任务调试日志都复制进公司通讯。','选择全公司相关成果，附来源链接，按所选语气用一两句说明。','输出信息预算服务实际读者。','各条内容有受众相关影响及可追溯来源。','不能为了简短删去破坏性变化或风险。'],[83])

add('validate-before-package','Validate metadata before packaging','打包前验证元数据','skill-authoring',[('skill-creator/scripts/package_skill.py',41,74,'Validation before ZIP'),('skill-creator/scripts/quick_validate.py',11,56,'validate_skill')],
['Run a deterministic validation gate before producing a distributable skill.','Package a new skill for review.','Verify the required entry file, frontmatter and naming rules, abort on errors, then package.','Zip the directory while its skill entry file is missing.','Check SKILL.md and required frontmatter fields; fix the invalid name; create the archive only after those checks pass.','Mechanical defects are caught before distribution.','Invalid metadata produces no archive; a valid package retains its folder structure.','This source validator is minimal; passing it does not prove behavior, reference integrity or semantic description quality.'],
['生成可分发技能前运行确定性验证关口。','打包新技能供审核。','验证入口文件、frontmatter 和命名规则，错误时终止，通过后再打包。','技能入口文件缺失也直接压缩目录。','检查 SKILL.md 与必要元数据，修复非法名称，通过后才生成压缩包。','在分发前发现机械性缺陷。','无效元数据不会产出压缩包；有效包保留目录结构。','来源校验器范围很小；通过不代表行为、引用或描述语义正确。'],[51])

add('bounded-artifact-validation','Validate measured artifact constraints','验证可测量的产物约束','evaluation',[('slack-gif-creator/core/validators.py',11,56,'check_slack_size'),('slack-gif-creator/SKILL.md',520,536,'Optimization Strategies')],
['Measure the produced artifact against its delivery constraints and apply targeted corrections.','Create a GIF for a channel with a known file-size limit.','Generate, measure actual bytes/dimensions, report the failing constraint, adjust a relevant parameter and remeasure.','Declare the GIF upload-ready because its animation looks good.','Measure the file; if over the known limit reduce frame count or palette; remeasure before reporting readiness.','Visual appeal alone does not establish technical deliverability.','The final report includes measured values and the limit used.','Verify current platform constraints separately; this frozen source is not a current policy authority.'],
['对生成产物测量交付约束，并有针对性修正。','为有已知文件大小限制的渠道制作 GIF。','生成后测量真实字节及尺寸，指出失败条件，调整相关参数并重测。','动画看着不错就宣称可上传。','测量文件；超出已知上限则减少帧或色板，重新测量后再报告就绪。','视觉效果不能证明技术交付条件满足。','报告包含最终测量值及使用的上限。','平台当前限制需另行核实；冻结来源不是现行政策依据。'])

add('unavailable-capability','Report unavailable capability without fabrication','能力不可用时报告事实','tools',[('composio-skills/ring-central-automation/SKILL.md',11,34,'Status / Setup / Current Status'),('composio-skills/zoho-desk-automation/SKILL.md',11,33,'Unavailable toolkit')],
['Preserve a failed capability discovery instead of inventing service-specific operations.','The user requests RingCentral calls, but discovery returns only other providers.','Report the requested capability as unavailable in this discovery, show evidence and offer explicit alternatives.','Pretend a ClickSend tool is a RingCentral endpoint and claim completion.','Report no matching RingCentral slug was found; retain the discovery evidence; offer a supported alternative subject to user intent.','A neighboring result cannot prove the requested service exists.','The report distinguishes requested capability, observed absence and alternative provider.','Availability is a timestamped observation; rerun discovery before future use.'],
['保留能力发现失败的事实，不虚构服务专属操作。','用户请求 RingCentral 通话，发现结果却只有其他提供者。','报告本次发现未找到请求能力，列出依据，并明确给出替代选择。','把 ClickSend 工具当作 RingCentral 接口并宣称完成。','报告未找到对应 RingCentral slug，保存发现依据，按用户意图提供受支持替代服务。','邻近搜索结果不能证明请求服务存在。','报告区分请求能力、观察到的缺失与替代提供者。','可用性是带时间的观察；未来使用前须重新发现。'],[173])

add('catalog-with-generated-fallback','Preset catalog with custom fallback','预设目录与定制回退','prompt',[('theme-factory/SKILL.md',19,26,'Usage Instructions'),('theme-factory/SKILL.md',43,59,'Application Process / Create Your Own Theme')],
['Use a preset specification when it fits; generate an explicit custom specification otherwise.','Apply a coherent theme to a slide deck.','Present relevant presets, read the selected specification and apply consistently; create/review a new specification only if no preset fits.','Choose unrelated colors on every slide despite a selected preset.','Load the selected theme’s colors/fonts and apply them throughout; if unsuitable, create and review one custom theme before applying it.','Both preset and fallback paths produce a concrete reusable specification.','The deck uses one named, inspectable specification across all slides.','Preset choice remains subject to existing brand conventions and user preferences.'],
['预设规格适合时复用，不适合时生成明确的定制规格。','为整套幻灯片应用一致主题。','展示相关预设，加载选定规格并统一应用；没有适合预设时再生成并评审新规格。','已经选定主题，却每页使用不相关颜色。','加载选定主题色与字体并全套应用；不适合则先创建并评审一个定制主题。','预设和回退路线都会形成可复用的具体规格。','整套幻灯片使用同一个具名、可检查规格。','主题选择仍服从既有品牌规范和用户偏好。'],[143])

add('workflow-tool-design','Design tools around complete tasks','围绕完整任务设计工具','tools',[('mcp-builder/SKILL.md',23,54,'Agent-Centric Design Principles')],
['Expose useful task-level operations with concise results and actionable errors.','Design an MCP tool for booking meetings.','Model the complete booking workflow, provide clear constraints/output and return corrections the agent can act on.','Expose hundreds of low-level HTTP wrappers with opaque results and generic errors.','Provide a clearly scoped booking operation with availability checks, chosen-slot evidence and a conflict message naming the next supported action.','The interface reflects the agent’s task rather than only the provider’s endpoint layout.','The tool contract supports the task and makes success/failure inspectable.','Composite tools must expose side effects and retain authorization boundaries; do not hide irreversible actions.'],
['暴露有用的任务级操作，返回简洁结果和可操作错误。','设计安排会议的 MCP 工具。','围绕完整预约流程，提供清晰约束及输出，并返回代理可采取的纠正动作。','暴露大量底层 HTTP 包装，结果不透明，错误只有通用文字。','提供范围明确的预约操作，检查可用时间，返回所选时段依据，冲突时指出下一可用动作。','接口对应代理任务，而不仅是提供者的端点布局。','工具契约支持完成任务，成功和失败可检查。','组合工具仍须说明副作用及授权边界；不能隐藏不可逆动作。'],[144])

add('reversible-file-operation-ledger','Keep an undo ledger for file operations','文件操作保留撤销记录','safety',[('file-organizer/SKILL.md',212,217,'Important Rules'),('invoice-organizer/SKILL.md',195,205,'Copy to preserve originals')],
['Preserve originals or record reversible source-to-destination moves before reorganizing files.','Reorganize 40 invoices into vendor directories.','Prepare a mapping, preserve original data, resolve conflicts and record each completed move/copy.','Move and rename everything without a record of original paths.','Copy the invoices to agreed destinations; record original path, destination and checksum; retain a review list for ambiguous files.','A transformation becomes inspectable and recoverable.','Every processed file has a recorded origin/destination and recoverable original.','Undo is only valid while destinations remain unchanged; destructive deletion needs its own authorization.'],
['整理文件前保留原件，或记录可逆的原路径到目标路径映射。','把 40 张发票整理到供应商目录。','先建立映射，保留原始数据，解决名称冲突，逐项记录完成的移动或复制。','全部重命名移动，却不记录原路径。','按确定目的地复制发票，记录原路径、目标与校验值；不明确文件留待审核。','转换过程可检查，也能恢复。','每个处理文件有来源与去向记录，原件可恢复。','目标之后变化会影响撤销有效性；删除仍需要独立授权。'])

add('persist-expiring-output','Materialize expiring outputs before handoff','交付前保存会过期的产物','workflow',[('composio-skills/elevenlabs-automation/SKILL.md',104,113,'Known Pitfalls'),('composio-skills/uploadcare-automation/SKILL.md',130,137,'Known Pitfalls')],
['Treat temporary URLs and temporary stored files as expiring access, not permanent deliverables.','Hand over generated audio for a report that will be read next month.','Inspect output lifetime, download or persist through an authorized durable destination, verify content and record the durable path.','Give only an expiring presigned URL and call it a permanent archive.','Save the audio in the agreed durable folder; verify its bytes and provide that path with the original job identity.','A temporary retrieval token is different from retained content.','The artifact remains accessible through a verified durable destination.','Respect privacy and retention policy; do not extend retention without task authorization.'],
['把临时 URL 和临时文件视为会过期的访问方式，而非永久交付。','交付生成音频，供下个月阅读的报告使用。','检查产物寿命，按授权下载或持久化到约定位置，验证内容并记录长期路径。','只给会过期的签名 URL，却称之为永久归档。','把音频保存到约定的长期目录，核对字节，并提供路径与原任务身份。','临时访问令牌与保留内容不同。','产物可以通过已验证的长期位置访问。','遵守隐私与保留政策；不得未经任务授权延长保存。'])

add('delta-token-sync','Use delta tokens for recurring synchronization','使用增量令牌进行周期同步','context',[('composio-skills/ashby-automation/SKILL.md',138,144,'Known Pitfalls'),('composio-skills/share-point-automation/SKILL.md',135,145,'Track List Changes')],
['Carry a server-issued change token between recurring reads.','Refresh an already indexed list of recruiting candidates each day.','Complete an initial snapshot, persist its sync token, request changes on the next run and apply additions/updates/deletions before advancing the token.','Download every candidate daily and assume missing records were deleted.','Use the returned sync token to fetch changes; apply the documented change types; advance the checkpoint after successful processing.','Change APIs distinguish actual changes from omissions caused by pagination or permissions.','The next checkpoint follows applied changes and changed records retain their IDs.','Handle expired tokens with a fresh snapshot; never advance beyond unprocessed changes.'],
['在周期读取之间保存服务端提供的变更令牌。','每天刷新已经建立索引的招聘候选人列表。','完成初始快照，保存同步令牌；下次请求变更，应用新增、修改和删除后再推进令牌。','每天下载全部候选人，并假设未返回记录就是被删除。','用返回的 sync token 获取变化，处理文档规定的变化类型，成功处理后再更新检查点。','变更接口能区分实际变化与分页或权限造成的遗漏。','新检查点位于已应用变更之后，记录身份保持一致。','令牌过期时重建快照；未处理的变化不能被检查点跳过。'])

add('metadata-capability-selection','Choose capabilities from current metadata','按当前元数据选择能力','tools',[('composio-skills/groqcloud-automation/SKILL.md',95,101,'Known Pitfalls'),('composio-skills/elevenlabs-automation/SKILL.md',104,113,'Known Pitfalls')],
['Discover available identifiers and supported features before selecting a model or voice.','Choose a speech model compatible with the requested output.','List accessible models, inspect capability metadata and select a compatible identifier; handle missing identifiers explicitly.','Use an old model name and assume every option supports speech.','List accessible models, filter for the speech capability, choose a returned identifier and use its supported parameters.','An identifier’s remembered existence does not establish current accessibility or feature support.','Selected identifier and required capability appear together in observed metadata.','Metadata can change between discovery and execution; handle removal and refresh without fabricating substitutes.'],
['选择模型或声音前发现可用标识及支持能力。','选择与所需输出兼容的语音模型。','列出可访问模型，检查能力元数据，再选择兼容标识；缺失标识需明确处理。','使用旧模型名称，并假设所有选项都支持语音。','列出可访问模型，按语音能力过滤，选择返回标识并使用受支持参数。','凭记忆知道某标识存在，不能证明当前可访问或具备所需能力。','选定标识与所需能力同时出现在已观察元数据中。','执行前元数据仍可能变化；处理移除并重新发现，不虚构替代。'])

add('baseline-preserving-edit-oracle','Revert edits to verify the baseline','撤回本次编辑后验证原始基线','evaluation',[('document-skills/docx/ooxml.md',558,568,'Validation Rules / Tracked Change Patterns')],
['Verify edit isolation by removing the intended changes and comparing to the original.','Change one phrase in a document with another author’s tracked edits.','Record the baseline, apply the new isolated change, revert only that change in a check view and compare remaining content to the baseline.','Check only that the new phrase appears, ignoring other authors’ text.','After adding the phrase change, revert only the new edit in a validation view; require the old content and pre-existing edits to match the baseline.','A positive spot-check cannot detect unrelated alterations.','Reverting only the new edits restores the original semantic content.','The comparison must preserve pre-existing edits and distinguish intentional metadata from content.'],
['通过移除本次预期修改再比较原文，验证编辑范围。','在包含他人修订的文档中修改一个短语。','保存基线，独立应用新修改；验证视图只撤回本次修改，再与基线比较。','只检查新短语出现，不管其他作者文字是否被改。','新增短语修订后，在验证视图仅撤回本次修改，要求原内容及已有修订与基线一致。','正向抽查无法发现无关内容被改变。','只撤回本次编辑后，原始语义内容恢复。','比较须保留原有修订，并区分有意元数据变更和内容。'],[176])

add('capability-branch-routing','Branch workflows on observed input capabilities','按观察到的输入能力选择流程','workflow',[('document-skills/pdf/forms.md',1,8,'Fillable check / Fillable fields'),('document-skills/pdf/forms.md',78,89,'Non-fillable fields')],
['Choose a workflow from an inspected property of the actual input.','Fill a PDF that may contain form fields or only a scanned layout.','Inspect whether interactive fields exist, then follow field-ID filling or visual placement according to the result.','Assume every PDF is a fillable form and invent field IDs.','Inspect the PDF; if real fields exist use their IDs; otherwise inspect rendered input areas and validate placements.','The branch depends on the actual artifact rather than its filename or the agent’s guess.','The chosen branch has an observed capability result and matching validation.','Both routes require the same user-supplied values; do not infer missing personal data.'],
['依据实际输入中检查到的属性选择执行路线。','填写一个可能有表单字段，也可能只是扫描版的 PDF。','检查交互字段是否存在，再按结果选择字段 ID 填写或视觉定位。','假设每个 PDF 都可填写，并虚构字段 ID。','检查 PDF；有真实字段则使用其 ID，没有则检查渲染输入区域并验证放置位置。','分支依据真实产物，而非文件名或代理猜测。','选择的路线有观察到的能力结果与对应校验。','两条路线都使用用户提供的值，不推测缺失个人信息。'],[113])

add('visible-action-confirmation','Confirm user-visible side effects','确认用户可见的副作用','safety',[('composio-skills/facebook-automation/SKILL.md',115,123,'Send Messages / Mark as Seen')],
['Make externally visible effects concrete before an authorization gate.','The user asks to inspect a conversation without requesting a reply.','Inspect read-only data; before sending a message or marking it seen, identify the actual effect and obtain the required authorization.','Mark the message seen during inspection because it sounds like a read operation.','Inspect the thread without state changes; explain that marking seen changes the sender-visible state and wait for explicit authorization when required.','Read-like names can conceal externally visible state changes.','No visible state change occurs before applicable authorization.','Existing explicit task authorization remains valid; do not add unnecessary confirmation loops.'],
['进入授权关口前明确对外可见的具体影响。','用户要求查看对话，没有要求回复。','只读查看；发送消息或标记已读前指出具体副作用，并取得所需授权。','查看时顺手标记已读，因为名称像读取动作。','不改状态地检查线程；说明已读会改变发送方可见状态，需要明确授权时等待授权。','像读取的名称也可能包含外部可见状态变更。','适用授权之前未发生可见状态改变。','已有明确任务授权持续有效；不增加多余确认循环。'],[8])

add('secret-bearing-composite','Redact secrets inside composite outputs','遮蔽复合输出中的秘密','safety',[('composio-skills/neon-automation/SKILL.md',113,119,'Known Pitfalls')],
['Inspect composite values for embedded credentials before reporting them.','Return the result of a database connection lookup.','Classify the complete URI as sensitive, redact embedded credentials and expose only needed non-secret metadata.','Paste the entire connection URI into the report because it is just a URL.','Report database and role names plus a redacted URI; store the actual credential only through the authorized secret destination.','Credentials may be embedded in a larger value.','The visible report contains no password/token-bearing URI.','Redaction must cover alternate encodings and query parameters; do not claim a transformed secret is public.'],
['输出复合值前检查其中是否嵌入凭据。','返回数据库连接查询结果。','把完整连接 URI 判为敏感，遮蔽凭据，只展示必要非秘密元数据。','认为只是 URL，就把完整连接 URI 贴进报告。','报告数据库和角色名称及遮蔽 URI；真实凭据仅写入获授权的秘密目的地。','凭据可能隐藏在较大的复合值中。','可见报告没有携带密码或令牌的 URI。','遮蔽还需覆盖编码变化和查询参数；不能把变形秘密称为公开值。'],[11])

add('eval-feedback-improvement','Improve tools from evaluation feedback','依据评测反馈改进工具','evaluation',[('mcp-builder/reference/evaluation.md',572,594,'Review report / Low Accuracy'),('mcp-builder/scripts/evaluation.py',21,44,'Evaluation prompt')],
['Use task outcomes and recorded tool feedback to refine a tool interface.','A tool evaluation fails several retrieval tasks.','Inspect failed task traces, compare expected/actual answers, identify description/payload/error problems and rerun affected tasks after fixes.','Rewrite tool descriptions from intuition while ignoring failing cases.','Inspect the failed cases; shorten oversized output and clarify the ambiguous parameter; rerun those same cases.','The change is linked to an observed failure rather than an unsupported preference.','Affected cases have before/after results and a documented interface change.','Agent feedback is evidence to inspect, not an unquestioned verdict; keep a stable evaluation set.'],
['依据任务结果和记录的工具反馈改进接口。','工具评测中若干检索任务失败。','检查失败轨迹、预期及实际答案，找出描述、返回量或错误处理问题，修复后复跑相关任务。','忽视失败案例，凭直觉改写工具描述。','检查失败案例，缩短过大输出并澄清歧义参数，再复跑相同案例。','修改与实际失败关联，而非无依据偏好。','相关案例有前后结果及已记录接口变化。','代理反馈是待审证据，不能直接当最终裁决；保留稳定评测集。'],[119])

add('verified-randomness-claim','Verified randomness claims','可验证的随机性主张','evaluation',[('raffle-winner-picker/SKILL.md',19,26,'What This Skill Does'),('raffle-winner-picker/SKILL.md',92,96,'Fair Selection'),('raffle-winner-picker/SKILL.md',143,149,'Privacy / Fairness')],
['Record unsupported fairness promises as a rejected extraction rather than teaching them as guarantees.','Audit a raffle skill that claims cryptographic randomness and reproducible seeded results.','Require a specified algorithm, entropy/seed protocol, eligibility rules and executable evidence before approving a technical randomness guarantee.','Assume a natural-language claim proves unbiased and manipulation-proof sampling.','Retain the output-format idea separately; reject cryptographic/fairness guarantees until a mechanism and reproducible audit are supplied.','The source contains promises without the implementation needed to assess them.','The unsupported guarantee is excluded from active teaching entries.','A real randomization implementation can be reviewed later; this decision concerns the source evidence present now.'],
['将缺少证据的公平承诺记为被拒绝的提取，不当保证来教学。','审核声称密码学随机且可用种子复现的抽奖技能。','批准技术保证前，要求算法、熵或种子协议、资格规则及可执行证据。','把自然语言承诺当成无偏且无法操纵的证明。','单独保留输出格式思路；算法及可复核审核未提供前，拒绝密码学与公平保证。','来源只有承诺，缺少评估保证所需实现。','不受支持的保证不进入有效教学条目。','以后可审核真实随机化实现；此结论仅针对当前来源证据。'],status='rejected')
candidates[-1]['scores']={'scenario':2,'mechanism':0,'contrast':1,'observable':0,'boundaries':1}
candidates[-1]['quality_total']=4
candidates[-1]['reason']='Source promises secure, unbiased, seeded/verifiable and manipulation-proof selection without implementation or an audit protocol; insufficient evidence for a transferable technical guarantee.'

def classify(p):
    if p.endswith('.ttf') or p.endswith('.pdf') or p.endswith('.gz'):return 'binary-asset','excluded','Bundled font, showcase or component archive; asset data has no prompt procedure and is not copied.'
    if p.endswith('.xsd'):return 'standard-schema','excluded','External OOXML schema grammar; standardized format definition, not a prompt/context mechanism.'
    if 'canvas-fonts/' in p:return 'asset-license','excluded','Font-specific attribution/OFL; no fonts are reused in this harvest.'
    if p=='README.md':return 'repository-index','excluded','Navigation and promotion index; underlying tracked skills audited separately; linked outside repositories out of this repository scope.'
    if p.startswith('.github/') or p.endswith('marketplace.json') or p.endswith('requirements.txt'):return 'repository-support','excluded','Packaging/dependency/CI metadata, not an agent procedure.'
    if p.startswith('document-skills/') and not p.endswith(('.md','LICENSE.txt')):
        return 'domain-document-implementation','excluded','Low-level file-format parsing, XML serialization, rendering and drawing implementation; transferable workflow/validation/context rules are reviewed conceptually in the entry skills and references. No source implementation is copied.'
    if p.startswith('slack-gif-creator/') and p.endswith('.py') and not p.endswith('core/validators.py'):return 'domain-animation-implementation','excluded','Drawing/easing/frame animation math and template code; generic composition/validation method audited in SKILL.md and validators.py.'
    if p.endswith('LICENSE.txt'):return 'license','analyzed','Local license boundary recorded independently of repository popularity and availability.'
    if p.startswith('composio-skills/') and p.endswith('SKILL.md'):return 'automation-skill','analyzed','Agent reviewed procedural family, whole-body substitutions/differences, domain contracts and failure cases; domain API recipes do not become separate patterns.'
    return ('skill' if p.endswith('SKILL.md') else 'reference-example-support'),'analyzed','Procedural instruction, reference, example or helper contract reviewed for transferable mechanism; domain parameters are not treated as current API facts.'

groups=json.loads((OUT/'composio-family-groups.json').read_text(encoding='utf-8'))
semantic_notes=json.loads((OUT/'composio-semantic-notes.json').read_text(encoding='utf-8'))
family_by_path={f['path']:g for g in groups for f in g['files']}
base=max(groups,key=lambda g:len(g['files']));enhanced=[g for g in groups if len(g['files'])==26][0]
family_keys=['composio-discover-connect-execute','composio-schema-reference-expansion','composio-pagination-completion']
files=subprocess.check_output(['git','-C',str(ROOT),'ls-files'],text=True).splitlines()
coverage=[];seen={}
for p in files:
    raw=(ROOT/p).read_bytes();normalized=raw.replace(b'\r\n',b'\n').replace(b'\r',b'\n');hash=hashlib.sha256(normalized).hexdigest()
    cl,disp,reason=classify(p)
    keys=[c['key'] for c in candidates if any(s['path']==p for s in c['sources'])]
    z=dict(path=p,hash=hash,classification=cl,disposition=disp,reason=reason,candidate_keys=keys)
    z['raw_hash']=hashlib.sha256(raw).hexdigest()
    z['hash_kind']='sha256-lf-normalized-content'
    owner=Path(p).parts[0]
    if p.startswith('document-skills/') and len(Path(p).parts)>1:owner=Path(p).parts[1]
    if owner in semantic_notes['non_automation_skills']:
        z['semantic_conclusion']=semantic_notes['non_automation_skills'][owner]
        if not keys:z['reason']+=' No independent new mechanism beyond the owning skill conclusion.'
    if p in family_by_path:
        g=family_by_path[p];z['family_comparison']={'normalized_sha':g['normalized_sha'],'representative':g['files'][0]['path'],'substitutions':next(f for f in g['files'] if f['path']==p),'body_equivalence_is_not_exact_hash_dedup':True}
        z['candidate_keys']=list(dict.fromkeys(keys+family_keys))
        if g is base:z['reason']='Base discovery/connect/execute scaffold; complete body differs only by audited name/title/toolkit and description/use-case substitutions; no extra domain-specific method.'
        elif g is enhanced:z['candidate_keys']+=['composio-error-directed-recovery'];z['reason']='Enhanced scaffold adds prerequisite response chaining, search-before-create, response-error checks, authentication recovery, bounded requests/backoff and full-schema expansion; no independent per-app method.'
        else:z['reason']='Detailed workflow reviewed individually; tool contracts and common pitfalls retained in per-file notes; reusable mechanisms consolidated, domain-only recipes not added as patterns.'
        stem=Path(p).parts[1].removesuffix('-automation')
        if stem in semantic_notes['automation_residuals']:z['semantic_conclusion']=semantic_notes['automation_residuals'][stem]
        else:z['semantic_conclusion']=z['reason']
        if stem in ['ring-central','wave-accounting','zoho-desk']:
            z['candidate_keys']=['composio-unavailable-capability']
        z['tool_contract_review']={'tool_slugs_in_source':sorted(set(re.findall(r'\b[A-Z][A-Z0-9_]+_[A-Z0-9_]+\b',raw.decode('utf-8')))),'authority':'frozen source only; re-discover before actual execution'}
    if disp=='analyzed' and hash in seen:
        z['disposition']='duplicate';z['duplicate_of']=seen[hash];z['reason']='Exact content hash duplicate of an analyzed tracked file; occurrence and local path/license remain recorded.'
    elif disp=='analyzed':seen[hash]=p
    coverage.append(z)

families=[dict(key='rube-base',count=len(base['files']),representative=base['files'][0]['path'],summary='Discovery → ACTIVE connection → exact-schema execution; workflow session reuse; pagination continuation. App aliases add no new mechanism.',candidate_keys=family_keys),dict(key='rube-enhanced',count=26,representative=enhanced['files'][0]['path'],summary='Base plus prerequisite chaining, resource lookup before creation, nested failure awareness, auth recovery, backoff, schemaRef expansion and bulk workbench; variations are use-case labels.',candidate_keys=family_keys+['composio-error-directed-recovery']),dict(key='domain-specific-workflows',count=75,summary='Each residual body was reviewed separately, including detailed workflows, a few scaffold-normalization exceptions, and unavailable placeholders. Differences include actual workflows, opaque identity types/scopes, parameter shape, pagination, temporal windows, quota and endpoint behavior. Methods are consolidated by mechanism, not toolkit name. Three files explicitly report unavailable native toolkit; several titles contain provider mismatches.',candidate_keys=[c['key'] for c in candidates if c['status']=='active']),dict(key='root-skills-and-references',count=32,summary='Writing, evidence-based feedback, reversible organization, art philosophy/refinement, named-reference routing, skill resources/packaging, tool design/evaluation, helper execution and artifact checks. Generic examples are independent teaching constructions; quantitative sample claims are not measured evidence.',candidate_keys=[c['key'] for c in candidates if c['status']=='merged'])]

summary={'tracked_files':len(files),'skill_files':sum(p.endswith('/SKILL.md') for p in files),'automation_skills':832,'other_skills':32,'coverage_counts':dict(collections.Counter(z['disposition'] for z in coverage)),'candidate_counts':dict(collections.Counter(c['status'] for c in candidates)),'original_source_scripts_executed':False,'analysis_method':'Whole tracked inventory and normalized hashes; whole-body source family comparison with each alias/task substitution retained; semantic review of procedures and detailed contract/failure differences; low-level domain assets/syntax/implementation excluded explicitly. Family-equivalent files are analyzed, never falsely marked exact duplicates.','limitations':['No tool/provider calls or model experiments were run. Frozen source API specifics, performance claims and availability are observations, not verified current behavior.','Document references were conceptually reviewed for routing, validation, preservation and bounded-context principles. Low-level document implementation/schema assets are excluded for domain-specific scope, not solely because of their restrictive license. No protected code or long examples are reproduced.','Domain example outputs are illustrative, not measured results. Source archive/font/OOXML schema content is excluded with explicit reasons.'],'license_findings':['No root LICENSE tracked. Nine core non-document directories contain Apache-2.0. Four document skill directories contain restrictive Anthropic proprietary terms. Other directories have no explicit local license except langsmith-fetch footer declaring MIT.','skill-share frontmatter points to a missing LICENSE.txt; it is not assumed Apache-2.0.'],'source_anomalies':['braintree-automation contains STRIPE_* tools','googleads-automation contains GOOGLE_ANALYTICS_* tools','googlebigquery-automation contains METABASE_* tools','ring-central, wave-accounting, zoho-desk detailed files explicitly unavailable while underscore variants may contain generic scaffolds','quick_validate validates only entry/frontmatter/name/basic description syntax, not all resource references claimed by the prose','with_server waits on listening TCP ports and terminates tracked shell process, not a verified process tree']}

result={'repo':REPO,'commit':COMMIT,'coverage':coverage,'families':families,'candidates':candidates,'summary':summary}
result['summary']['semantic_notes_file']='composio-semantic-notes.json'
(OUT/'harvest-composio.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
md=['# Composio skill-pattern harvest','',f'Frozen repository: [{REPO}](https://github.com/{REPO}/tree/{COMMIT}), commit {COMMIT}.','',f'Tracked files: {len(files)}; automation skills: 832; other skills: 32. Candidates: '+', '.join(f'{k}={v}' for k,v in summary['candidate_counts'].items())+'.','', '## Method and boundaries','',summary['analysis_method'],'']
md += [f'- {x}' for x in summary['limitations']]
md+=['','## Family findings','']
md += [f'- **{f["key"]}** ({f["count"]}): {f["summary"]}' for f in families]
md+=['','## Local licenses','']+[f'- {x}' for x in summary['license_findings']]
md+=['','The [document license](https://github.com/'+REPO+'/blob/'+COMMIT+'/document-skills/docx/LICENSE.txt) explicitly differs from the [Apache license](https://github.com/'+REPO+'/blob/'+COMMIT+'/skill-creator/LICENSE.txt). No original source assets, code or lengthy examples are reproduced in blog teaching samples.','', '## Source anomalies requiring caution','']+[f'- {x}' for x in summary['source_anomalies']]
md+=['','## Transferable mechanisms','']
for c in candidates:
    links=', '.join('['+s['path']+':'+str(s['line_start'])+'–'+str(s['line_end'])+']('+s['url']+')' for s in c['sources'])
    md.append(f'- **{c["name"]["en"]} / {c["name"]["zh"]}** ({c["status"]}'+ ('; existing '+','.join(map(str,c['suggested_existing_ids'])) if c['suggested_existing_ids'] else '')+'): '+c['content']['en']['description']+' '+links+'.')
md+=['','The JSON records exact line ranges, local license scope, all tracked occurrences and editorial scores. Source role is observed-example; no claim of earliest invention or measured model improvement is made.','']
(OUT/'harvest-composio.md').write_text('\n'.join(md),encoding='utf-8')
print(json.dumps(summary,ensure_ascii=False,indent=2))
