from pathlib import Path
_namespace={'__name__':'core_helpers'}
exec(compile(Path(__file__).with_name('core-update.py').read_text(encoding='utf-8'),'core-update.py','exec'),_namespace)
globals().update({k:v for k,v in _namespace.items() if not k.startswith('__')})
R='obra/superpowers';P='skills/subagent-driven-development/SKILL.md';W='skills/writing-plans/SKILL.md'

locators=[(161,204,214,'Explicit model selection'),(162,251,266,'Brief and report file handoff'),(163,267,271,'Do not paste task history'),(166,325,334,'Verbatim global constraints'),(160,335,338,'Do not repeat unchanged tests'),(156,339,344,'No pre-judging findings'),(158,366,371,'Plan-mandated finding adjudication'),(164,458,464,'One final fix dispatch')]
keys=[merged('superpowers-existing-'+str(id),id,[(R,P,start,end,section)]) for id,start,end,section in locators]
keys.append(merged('superpowers-review-task-size',165,[(R,W,34,41,'Task Right-Sizing')]))
keys.append(merged('superpowers-task-interfaces',167,[(R,W,102,106,'Interfaces')]))
keys.append(merged('superpowers-cost-model-routing',35,[(R,P,184,219,'Model Selection')]))
keys.append(merged('superpowers-bounded-review-loop',41,[(R,P,354,429,'Fix Loop and Breaker')]))
keys.append(merged('superpowers-precise-context',36,[(R,P,251,271,'Implementer handoff')]))
keys.append(merged('superpowers-continuous-execution',150,[(R,P,17,31,'Continuous execution boundaries')]))
keys.append(merged('superpowers-rationalization-table',146,[(R,P,489,501,'Common Rationalizations')]))

kledger=add('plan-owned-resumption-ledger','Resume from a plan-owned ledger','从所属计划的账本恢复执行','context',[(R,P,131,160,'Setup ledger ownership')],
['Bind progress to a specific plan identity and recover from persisted completion evidence after context loss.','Resume a multi-task implementation session after compaction while a sibling plan also has scratch files.','Match the ledger’s plan identity, trust its commit-backed completed tasks, resume the first incomplete task or saved fix round, and leave sibling ledgers alone.','Read any progress.md found nearby and redispatch every task from memory.','Open the ledger whose first line names this plan; verify recorded commits; resume the recorded incomplete task and round without touching another plan’s workspace.','A named ownership boundary prevents both duplicate work and cross-plan state confusion.','Resumed execution starts at the ledger’s first incomplete state and recorded commits remain inspectable.','Validate stale/corrupted ledger entries against repository evidence; a scratch ledger is not a substitute for durable version history.'],
['将进度绑定到具体计划身份，上下文丢失后依据持久化完成证据恢复。','压缩后恢复多任务实现会话，旁边还有另一个计划的临时文件。','匹配账本计划身份，核对提交支持的完成任务，恢复首个未完成任务或修复轮次，保留其他计划账本。','随便读取附近 progress.md，并凭记忆重新派发全部任务。','打开首行标明本计划的账本，核验记录提交，从未完成任务及轮次继续，不触碰其他计划工作区。','具名归属边界避免重复工作和跨计划状态混淆。','恢复执行从账本首个未完成状态开始，历史提交可检查。','对陈旧或损坏账本核对仓库证据；临时账本不能替代持久版本历史。'])
keys.append(kledger)
kpreflight=add('plan-interface-preflight','Check task-pair interfaces before implementation','实现前核对任务间接口','orchestration',[(R,P,162,182,'Preflight table')],
['Make cross-task consistency checks explicit with producer/consumer evidence.','Execute a plan where one task creates parseRecord and another consumes parseRow.','List task pairs sharing files/interfaces, compare produced and consumed names/types/values, record conflicts and resolve them before dispatch.','Say the plan is consistent after skimming it without checking any task pairs.','Record the producer parseRecord and consumer parseRow mismatch in a table; settle the intended name against the spec and propagate it into both task briefs.','A pairwise artifact exposes dependencies that isolated task reading can miss.','Each shared interface has a checked producer/consumer row and conflicts have a traceable resolution.','The scan cannot predict all integration failures; retain implementation tests and review gates.'],
['用生产者与消费者证据明确检查跨任务一致性。','执行一个前项创建 parseRecord、后项调用 parseRow 的计划。','列出共享文件或接口的任务对，比较名称、类型与值，记录冲突并在派发前解决。','略读后宣称计划一致，却未检查任何任务对。','在表中记录 parseRecord 与 parseRow 不匹配，依据规格确定名称，并同步到两份任务说明。','成对检查产物暴露单任务阅读容易遗漏的依赖。','每个共享接口都有已检查的生产/消费行，冲突有可追溯解决。','扫描不能预测全部集成失败；仍保留实现测试和评审关口。'])
keys.append(kpreflight)
kruling=add('reversible-ruling-ledger','Record reversible decisions with their rationale and cost','记录可逆决策的理由与代价','workflow',[(R,P,19,31,'Rulings and stop boundaries'),(R,P,473,480,'Report rulings before cleanup')],
['Record an authorized implementation decision, its evidence and cost if wrong, then include it in the final handoff.','An approved plan has two inconsistent internal names but the binding spec settles the behavior.','Resolve within authorized reversible scope using the spec, record the ruling and its rework cost, carry it to affected briefs and expose it in the final report.','Silently choose a name and delete the scratch record before the user can review the decision.','Record the selected name, spec basis and affected callers; update relevant briefs; include this ruling and its correction cost in the final report.','The decision remains reviewable after implementation and scratch cleanup.','Every recorded ruling appears in the final handoff with its rationale and impact.','Do not turn this into permission for security-sensitive, destructive or externally visible actions outside the user’s authorization.'],
['记录已授权实现决策、依据及判断错误的代价，并纳入最终交接。','批准的计划有两个不一致内部名称，但绑定规格已明确行为。','在已授权可逆范围内按规格解决，记录判断及返工代价，同步相关说明并在最终报告披露。','默默选名称，用户查看之前就删掉临时记录。','记录名称、规格依据和受影响调用，同步说明，最终报告列出该决策和修正代价。','实现及清理临时文件后，决策仍可审核。','每个记录的判断都在最终交接中出现，并说明理由与影响。','不得据此进行超出用户授权的安全敏感、破坏性或外部可见操作。'])
keys.append(kruling)
review(R,P,'Complete body reviewed: precise fresh contexts, bounded role/model routing, plan-owned ledger recovery, task-pair preflight table, file-based briefs/reports/diffs, spec/quality gates, scoped fix rounds/escalation, cap adjudication and final one-wave repair. Runtime cost observations are unverified; stop/authorization policy is source-specific.',keys)
wkeys=[c['key'] for c in DATA['candidates'] if c['key'] in ['core-superpowers-review-task-size','core-superpowers-task-interfaces','core-plan-interface-preflight']]
review(R,W,'Complete body reviewed: spec-to-task coverage, exact interfaces/values/assertions, independent reviewer-sized deliverables, bounded step content, review-focus coverage, self-review against spec and preserved execution preference. Historical local paths are defaults, not mandatory in this project.',wkeys)
v='skills/verification-before-completion/SKILL.md';vkeys=[merged('superpowers-proof-before-claim',26,[(R,v,22,48,'Gate function / evidence requirements')]),merged('superpowers-two-axis-completion',193,[(R,v,40,48,'Requirements vs test evidence')]),merged('superpowers-iron-law-framing',145,[(R,v,14,20,'Iron Law')])]
review(R,v,'Complete body and examples reviewed: fresh claim-specific command/output, red/green regression proof, requirements checklist separate from test passing, independent checking of delegated reports. Re-running every check for every sentence is source wording, not a general efficiency prescription.',vkeys)
u='skills/using-superpowers/SKILL.md';ukeys=[merged('superpowers-skill-announcement',147,[(R,u,18,24,'Invoke / announce')]),merged('superpowers-harness-reference-routing',172,[(R,u,52,61,'Platform adaptation')])]
review(R,u,'Complete body reviewed: subagent exclusion, process-before-domain routing, announce-on-entry, harness-specific references, user precedence and rationalization table. Its 1% invocation threshold is an unverified trigger preference; source instructions were not obeyed as task instructions.',ukeys)
q='skills/requesting-code-review/SKILL.md';review(R,q,'Complete body reviewed: contextual reviewer dispatch, actual base/head range, severity routing and evidence-based pushback. HEAD~1 is offered only as one possible base and can miss multi-commit tasks; do not generalize it as correct task range. Whole-session context is deliberately excluded.',['core-superpowers-precise-context','core-superpowers-existing-163'])
save()
