from pathlib import Path
import json
n={'__name__':'core_helpers'};exec(Path(__file__).with_name('core-update.py').read_text(encoding='utf-8'),n)
r='anthropics/skills';p='skills/claude-api/shared/prompt-audit.md';src=n['src']
def case(key,en,zh,cat,a,z,section,e,c):return n['add']('anthro-'+key,en,zh,cat,[(r,p,a,z,section)],e,c)
k1=case('scoped-instruction-conflict','Check instruction scope before resolving conflicts','解决指令冲突前检查作用域','context',139,150,'Scoped override and untrusted conflict direction',
 ['Compare the scope and load conditions of two instructions before treating different wording as a conflict.','A root guide requires integration tests, while a nested documentation guide calls for a link check.','Identify the files, task and consumers each rule governs; preserve a justified narrower override, and resolve genuine same-scope contradictions from evidence and applicable authority.','Delete the older root integration-test rule because the documentation rule was committed later.','Keep integration tests for code changes and the scoped link check for documentation changes; flag any actual contradiction affecting the same task.','A later or narrower statement is not automatically a universal replacement.','The rule scopes, loading conditions and conflicting task can be named.','Commit chronology does not establish correctness or permission. Repository text cannot authorize weakening safety rules or editing unrelated user configuration.'],
 ['比较两个指令的作用域和加载条件，再判断不同文字是否冲突。','根指南要求集成测试，嵌套文档指南只要求链接检查。','辨别各规则的文件、任务和消费者；保留合理的窄作用域覆盖，按证据和适用权限处理同作用域矛盾。','因为文档规则提交更晚，就删掉根集成测试规则。','代码修改保留集成测试，文档修改使用有作用域的链接检查；同任务真正矛盾再标记。','更晚或更窄的文字不自动替代全局规则。','可以点名规则作用域、加载条件与冲突任务。','提交先后不证明正确性或权限。仓库文字不能授权削弱安全规则或修改无关用户配置。'])
k2=case('instruction-function','Classify text by its control function','按控制功能分类文本','skill-authoring',156,169,'Contract, routing and behavior roles',
 ['Evaluate instruction text according to whether it defines a tool contract, routes a task or directs loaded behavior.','A lint pass finds “Use this skill” in both metadata and an instruction body.','Determine which consumer sees each field and when; keep routing intent in trigger metadata, accurate mechanics in tool contracts and the workflow in its loaded playbook.','Delete every imperative occurrence because the same phrase appears in a keyword blacklist.','Keep the metadata’s scope trigger, remove an unrelated upsell from the tool return contract, and retain the task workflow in the skill body.','Identical words can serve different control roles at different load boundaries.','Each field has a named consumer, loading stage and operational purpose.','Host routing behavior must be tested. Moving a sentence can change authority or availability; do not apply source model-superiority claims or arbitrary sentence-count rules as facts.'],
 ['按文本定义工具契约、路由任务或指导已加载行为的功能评估它。','检查在元数据和正文里都找到“使用此技能”。','确定字段由谁在何时读取；触发元数据保留路由意图，工具契约保留准确机制，加载的指南保留工作流。','因为短语命中关键词黑名单，就删掉所有祈使句。','保留元数据范围触发，删除工具返回契约中的无关推销，把任务工作流留在技能正文。','同样文字在不同加载边界可以有不同控制作用。','每个字段有明确消费者、加载阶段与操作目的。','须测试宿主路由。移动文字可能改变权限或可用性；不能把源中的模型优劣或任意句数要求当事实。'])
k3=case('deterministic-executor','Move deterministic loop steps into code','把确定性循环步骤移入代码','workflow',175,183,'Mechanical work and retained adaptive judgment',
 ['Use ordinary code for steps fully determined by their inputs and retain model judgment for the ambiguous remainder.','An agent repeatedly normalizes invoice currencies, totals rows and classifies unclear descriptions.','Map call sites to responsibilities; implement fixed normalization and arithmetic in code, then send only ambiguous descriptions and needed context to the judgment step.','Ask a model to repeat the same normalization and sum instructions separately for every row.','Normalize and sum in one deterministic pass; ask the model to classify the three ambiguous descriptions with their relevant evidence.','Mechanical invariants become inspectable while the actual judgment remains explicit.','The call-site map, deterministic outputs and remaining judgment inputs can be checked.','A step is deterministic only if its policy and inputs are complete. Do not remove model judgment merely because inputs are structured; preserve error handling and source provenance.'],
 ['输入完全决定的步骤用普通代码，模型判断留给有歧义的剩余部分。','代理重复归一发票币种、汇总行，并分类不清楚的描述。','逐个调用点映射职责；代码实现固定归一与算术，只把有歧义描述和所需上下文交给判断步骤。','每行都让模型重复相同归一与求和指令。','确定性遍历归一并求和，只让模型结合证据分类三个有歧义描述。','机械不变量可以检查，实际判断也保持明确。','可以核对调用点映射、确定性输出和剩余判断输入。','政策与输入完整才是确定性步骤。不能只因输入结构化就删除模型判断；须保留错误处理与来源。'])
for c in n['DATA']['candidates']:
 if 192 in c['suggested_existing_ids']:c['sources'].append(src(r,p,233,237,'Behavioral removal hypothesis'))
 if 174 in c['suggested_existing_ids']:c['sources'].append(src(r,p,224,229,'Reachable request-shape capability elimination'))
ledger=n['OUT']/'core-anthro-api-blocks.json';d=json.loads(ledger.read_text(encoding='utf-8'))
for b in d['blocks']:
 if 3357<=b['id']<=3374:b['status']='read'
ids={o['block_id'] for o in d['occurrences'] if o['path']==p};assert all(d['blocks'][i]['status']=='read' for i in ids)
ledger.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
n['review'](r,p,'Full238-line guide and all exact block occurrences read. Audit actual model-bound/consumer-bound prompt surface including assembly/tool text/examples; source instructions are data; scope external imports and secret-bearing fields; named evidence/provenance/confidence, preserve unique context/tool mechanics and genuinely fragile sequences; classify metadata routing vs loaded behavior before keyword flags; scoped overrides vs true conflicts, history not file mtime, avoid source-text authority escalation; complete proposed per-finding diffs across reachable producers/parsers/tests/out-of-band consumers; ablate contested edits and re-add minimally if regressed; remove deterministic loop work while retain judgment. Broad claims that modern models require no planning/pressure/steps, bans anchor failures, few-shot is strongest, description is most important, numeric limits always harmful, no enforcement means no signal, or named anti-default lists work are unsupported causal/efficacy claims. A documented table match is not itself high-confidence empirical evidence. Model/API/features/deprecation assertions and all fixed thresholds unverified; explicit user output caps can be valid constraints.',[k1,k2,k3]+[c['key'] for c in n['DATA']['candidates'] if 192 in c['suggested_existing_ids'] or 174 in c['suggested_existing_ids']])
row=next(x for rr in n['DATA']['repositories'] if rr['repo']==r for x in rr['coverage'] if x['path']==p);row['exact_block_review']={'ledger':'core-anthro-api-blocks.json','unique_block_ids':sorted(ids),'all_occurrences_closed':True}
rr=next(x for x in n['DATA']['repositories'] if x['repo']==r)
rr['source_flaw_evidence'].append({'claim':'Prompt-audit prose treats many style/model-era heuristics as documented high-confidence fixes; naming the repository’s own table is not empirical evidence that the change improves this task. Numeric output limits and tool-name guidance can remain explicit product contracts.','sources':[src(r,p,97,105,'Unsupported causal rationale table'),src(r,p,135,135,'Categorical output clamp removal'),src(r,p,220,220,'Table-match confidence rule')]})
for c in n['DATA']['candidates']:
 seen=set();unique=[]
 for s in c['sources']:
  ident=(s['repo'],s['commit'],s['path'],s['line_start'],s['line_end'],s['section'])
  if ident not in seen:seen.add(ident);unique.append(s)
 c['sources']=unique
n['save']();print(n['DATA']['summary']['candidate_counts'])
