from pathlib import Path
_namespace={'__name__':'core_helpers'}
exec(compile(Path(__file__).with_name('core-update.py').read_text(encoding='utf-8'),'core-update.py','exec'),_namespace)
globals().update({k:v for k,v in _namespace.items() if not k.startswith('__')})
R='obra/superpowers'
kt=add('behavioral-red-green-cycle','Prove behavioral RED before minimal GREEN','先证明行为失败，再实现最小通过','workflow',[(R,'skills/test-driven-development/SKILL.md',113,202,'Verify RED / GREEN / Refactor')],
['Verify that a behavioral test fails for the intended missing behavior before implementing the smallest change that passes it.','Reject an empty email currently accepted by a form.','Write the rejection assertion, observe the actual behavioral failure rather than setup error, implement the required rule and refactor only while the relevant checks remain green.','Write a passing test around the current behavior after implementing the fix and call it a regression proof.','Assert empty email produces the required error; see it fail against the old form; add the rule; verify the same assertion passes and relevant existing behavior remains intact.','The failing run demonstrates sensitivity to the named defect.','The record contains expected RED, resulting GREEN and the code state each run covered.','Test necessity depends on change risk; do not delete unrelated user work or pretend an import error is behavioral evidence.'],
['实现前确认行为测试因预期缺失行为而失败，再用最小修改使其通过。','拒绝目前被表单接受的空邮件。','写出拒绝断言，观察真实行为失败而非准备错误，实现必要规则，只在相关检查通过时重构。','修复后围绕现状写一个通过测试，就称为回归证明。','断言空邮件产生规定错误，观察旧表单失败，增加规则，再验证同一断言通过且相关已有行为保持。','失败运行证明测试对所指缺陷敏感。','记录包含预期 RED、之后 GREEN 及各运行覆盖的代码状态。','测试需要取决于变更风险；不得删除无关用户工作，也不能把导入错误当行为证据。'])
kw=add('fresh-predicate-wait','Wait on a fresh observable predicate','等待新鲜的可观察条件','tools',[(R,'skills/systematic-debugging/condition-based-waiting.md',34,93,'Core Pattern / Implementation / Mistakes')],
['Replace guessed delays with a fresh readiness predicate and a bounded timeout.','Read a result produced asynchronously under variable load.','Observe the relevant state or event repeatedly within a time budget; return only when the actual predicate holds, otherwise report timeout.','Sleep 50 ms and assume the result exists.','Within the agreed timeout, check the live result getter until the target result exists; on expiry report the unmet predicate.','Elapsed delay alone does not establish the needed state.','The read follows an observed readiness condition or a visible timeout result.','Timing-behavior tests have a different oracle; choose polling/event strategy and interval for the actual workload.'],
['用新鲜就绪条件和有限超时替代猜测的延迟。','读取在变化负载下异步生成的结果。','在时间预算内反复观察相关状态或事件，实际条件成立才返回，否则报告超时。','等待 50 毫秒就假定结果存在。','在约定超时内检查实时 getter，直到目标结果存在，超时则报告未满足条件。','仅经过一段时间不能证明所需状态。','读取发生在观察到就绪之后，或明确返回超时。','测试计时行为需要其他判据；轮询、事件方式和间隔由实际负载决定。'])
ko=add('independent-mutation-sensitive-oracle','Use an independent, mutation-sensitive oracle','使用独立且对错误敏感的判据','evaluation',[(R,'skills/test-driven-development/writing-good-tests.md',20,45,'Independent expectations'),(R,'skills/test-driven-development/writing-good-tests.md',157,169,'Mutation Check')],
['Derive expected values independently and check that plausible wrong behavior would fail the test.','Verify serialization of a search filter.','Use a hand-checked literal expected output and consider wrong quoting, missing field or wrong branch mutations.','Compute both expected and actual with the same query builder.','Compare the builder result to a manually verified literal; confirm that omitting the filter or changing its quoting would fail the assertion.','A shared implementation can repeat the same defect on both sides of an equality.','At least the relevant plausible defects change the asserted outcome.','Mutation sensitivity is scoped to identified risks, not proof that every possible bug is covered.'],
['独立推导预期值，并检查合理的错误行为能否使测试失败。','验证搜索过滤条件的序列化。','使用手工核对的字面预期，并考虑错误引用、字段缺失或分支错误。','预期和实际都由同一个查询构造器计算。','将结果与手工核验字面值比较，确认漏过滤条件或引用错误会使断言失败。','共享实现可能在比较两边重复同一个缺陷。','相关合理缺陷至少会改变被断言结果。','错误敏感性只针对已识别风险，不证明覆盖所有可能缺陷。'])
kb=add('backward-origin-tracing','Trace invalid data back to its origin','把无效数据回溯到来源','evaluation',[(R,'skills/systematic-debugging/root-cause-tracing.md',32,64,'Tracing Process')],
['Walk backward from a failing effect through callers and values to identify where the bad input originated.','A workspace operation runs in the wrong directory.','Inspect the effect’s actual directory value, identify its caller, follow the value through the call chain and verify the originating initialization/decision.','Patch the failing operation to ignore errors without inspecting its input path.','Observe the empty directory at the operation, trace it to a pre-initialization test value, fix that origin and verify the directory contract.','The visible failure may occur several boundaries after the defective decision.','The explanation records the observed value and each causal call-path hop supporting the identified origin.','A call-path hypothesis needs runtime or static evidence; defensive validation alone does not prove the origin or impossibility of recurrence.'],
['从失败副作用沿调用者与数值回溯，识别错误输入最初产生处。','工作区操作在错误目录执行。','检查真实目录值，找到调用者，沿调用链追踪值，并核验最初初始化或决策。','不检查路径，就让失败操作忽略错误。','观察操作收到空目录，追溯到测试初始化前读取的值，修复来源并验证目录契约。','可见失败可能发生在错误决策之后多个边界。','解释记录真实值及支持来源判断的每个调用链节点。','调用链假说需要运行或静态证据；防御检查本身不能证明来源或永不复发。'])
kf=add('fragility-calibrated-specificity','Calibrate instruction specificity to fragility','按脆弱程度调整指令具体度','skill-authoring',[(R,'skills/writing-skills/anthropic-best-practices.md',59,130,'Degrees of freedom')],
['Choose broad guidance, parameterized recipes or exact commands according to the task’s justified variation and failure cost.','Write instructions for a flexible review and a fragile migration.','Permit judgment where multiple safe approaches exist; provide configurable procedure for bounded variation; pin sequence/arguments when a verified narrow path is required.','Use the same rigid command recipe for every task, or leave a destructive migration as do what seems best.','Allow evidence-based review judgment; for the verified migration use its documented exact command and validation/backup preconditions.','The allowed degrees of freedom match the actual operation rather than an arbitrary style preference.','Instructions identify which choices are flexible and which are contract-bound.','Exactness cannot authorize unsafe execution or replace current tool-contract checks; do not invent universal safe defaults.'],
['根据合理变化空间和失败代价，选择宽泛指导、参数化配方或精确命令。','为灵活评审和脆弱迁移分别编写说明。','多种安全路线可行时允许判断，有限变化提供可配置流程，只有已验证窄路径时固定顺序及参数。','所有任务都套同一僵硬命令，或把破坏性迁移描述为自行决定。','评审允许基于证据判断；已验证迁移使用规定命令及验证、备份前提。','可选自由度对应真实操作，而非任意写作偏好。','说明明确哪些可灵活选择，哪些受契约绑定。','精确指令不能授权不安全执行或替代当前工具检查，也不能虚构普遍安全默认。'])
ks=add('capability-sentinel-probe','Prove a capability with a sentinel probe','用标记探针证明能力生效','tools',[(R,'docs/porting-to-a-new-harness.md',190,205,'Unique marker test'),(R,'docs/porting-to-a-new-harness.md',245,250,'Hook system versus specific event')],
['Test the claimed mechanism with an observable unique marker instead of inferring capability from names or files.','Verify a session-start context hook in a new harness.','Inject a controlled marker through the claimed surface, start an isolated session and inspect whether it reached context through that surface without an unrelated read.','A binary contains SessionStart, so assume the hook injects context.','Use a throwaway marker in the declared hook; inspect a fresh session’s input/event evidence to confirm delivery before asserting support.','Presence of vocabulary is different from execution of the required mechanism.','The probe records surface, unique marker, observed delivery and any intervening tool read.','Probe only within authorized test scope; one passing probe does not establish all future sessions or other capabilities.'],
['用可观察唯一标记测试所声称机制，而不是从名称或文件推断能力。','验证新执行环境的会话启动上下文钩子。','通过目标入口注入受控标记，启动独立会话，检查是否经该入口进入上下文，而非其他读取。','二进制含 SessionStart 就假定钩子能注入上下文。','在声明钩子中放临时标记，检查新会话的输入及事件证据，确认传递后才断言支持。','存在词汇与所需机制真实执行不同。','探针记录入口、唯一标记、实际传递及中间工具读取。','仅在授权测试范围探测；单次通过不能证明未来所有会话或其他能力。'],ids=[177])
kp=merged('superpowers-pressure-tdd',149,[(R,'skills/writing-skills/SKILL.md',554,575,'Skill RED GREEN REFACTOR')])
kl=merged('superpowers-progressive-reference-context',100,[(R,'skills/writing-skills/anthropic-best-practices.md',235,357,'Progressive disclosure / shallow references')])
kquick=merged('superpowers-helper-help-contract',104,[(R,'skills/writing-skills/SKILL.md',222,231,'Move details to tool help')])
updates={
 'skills/test-driven-development/SKILL.md':[kt],
 'skills/systematic-debugging/SKILL.md':[kb],
 'skills/systematic-debugging/condition-based-waiting.md':[kw],
 'skills/systematic-debugging/condition-based-waiting-example.ts':[kw],
 'skills/systematic-debugging/root-cause-tracing.md':[kb],
 'skills/test-driven-development/writing-good-tests.md':[ko],
 'skills/writing-skills/SKILL.md':[kp,kquick],
 'skills/writing-skills/testing-skills-with-subagents.md':[kp],
 'skills/writing-skills/anthropic-best-practices.md':[kf,kl],
 'docs/porting-to-a-new-harness.md':[ks]
}
rr=next(r for r in DATA['repositories'] if r['repo']==R)
for path,keys in updates.items():
    row=next(x for x in rr['coverage'] if x['path']==path);row['candidate_keys']=list(dict.fromkeys(row['candidate_keys']+keys))
save()
