from pathlib import Path
import json,collections
n={'__name__':'core_helpers'};exec(Path(__file__).with_name('core-update.py').read_text(encoding='utf-8'),n)
r='anthropics/skills';p='skills/claude-api/shared/evals/eval-hillclimb.md';src=n['src']
def case(key,en,zh,a,z,title,e,c):return n['add']('anthro-'+key,en,zh,'evaluation',[(r,p,a,z,title)],e,c)
k1=case('criterion-regrade','Regrade all variants after a criterion change','评分标准变化后重评所有变体',267,291,'Recorded metrics and grader-version comparison',
 ['When a metric or grader changes, apply it consistently to stored outputs from every compared variant before recommending a winner.','A review benchmark adds an omitted factual-accuracy criterion after several rounds.','Version the new criterion, regrade frozen outputs for baseline and all candidates, retain old-versus-new comparisons, and reconsider the winner if rankings change.','Score only the latest candidate with the new criterion and compare it to the old baseline number.','Regrade the same saved outputs from every round with the new criterion, publish both grading versions, and reassess the earlier recommendation.','A change in measurement is separated from a change in the generated artifact.','Criterion versions, fixed output identities and ranking changes can be checked.','Stored outputs may omit required evidence. Model judges add variance and cost; if the original search optimized the wrong signal, regrading alone does not undo that selection history.'],
 ['指标或评分器变化时，推荐赢家前统一重评所有已比较变体的保存输出。','评审基准运行数轮后，新增此前遗漏的事实准确性标准。','版本化新标准，对基线和全部候选的冻结输出重评，保留新旧比较；排名变化时重新考虑赢家。','只用新标准评最新候选，却与旧基线数值比较。','新标准重评每轮相同保存输出，公开两版评分，并重新评估先前建议。','把测量方式变化与生成产物变化分开。','可以核对标准版本、固定输出身份及排名变化。','保存输出可能缺少所需证据。模型评分增加变异和费用；原搜索若优化错误信号，重评本身不能撤销选择历史。'])
k2=case('drift-control','Use fresh no-change controls after drift','条件漂移后使用新无改动对照',217,219,'Environment fingerprint and contemporaneous control',
 ['When execution conditions change, compare a candidate against a contemporaneous unchanged control rather than only an old baseline number.','A prompt candidate is evaluated a week after the baseline, after the serving environment changed.','Record the environment and artifact fingerprints; rerun the unchanged control under current conditions, rebuilding any stochastic intermediate artifact, then compare the candidate in that same setting.','Attribute the difference from last week’s baseline entirely to the prompt edit.','Run the unchanged prompt and candidate in the current environment on the same case design; retain the old score as historical evidence.','Environmental movement is not silently attributed to the candidate change.','Fingerprints, no-change runs and contemporaneous comparisons are recorded.','A fingerprint cannot capture every hidden provider change. Controls need comparable cache/state conditions and appropriate replication; they do not alone prove causation.'],
 ['执行条件变化时，用同时期未改动对照比较候选，而非只依赖旧基线数值。','提示候选在基线一周后评估，服务环境已经改变。','记录环境和产物指纹；在当前条件重跑未改动对照，重建随机中间产物，再在相同设置比较候选。','把与上周基线的差异全部归因于提示修改。','当前环境下使用相同案例设计运行原提示与候选，旧分数保留作历史证据。','环境变化不会默默归因于候选修改。','指纹、无改动运行与同时期比较有记录。','指纹无法覆盖所有隐藏提供方变化。对照需可比缓存与状态和适当重复；本身不证明因果。'])
k3=case('optimization-layer-triage','Classify the failing layer when optimization stalls','优化停滞时分类失败层',279,300,'Artifact, grader, harness, structure and variance',
 ['When repeated edits fail to move an evaluation, classify remaining failures by the layer that could explain them before adding more instructions.','A retrieval-agent benchmark stays flat after several prompt reminders to use search.','Read representative traces and artifacts; separate missing knowledge, wrong grading, unavailable wiring, unreachable content and ordinary variability, then target the evidenced layer.','Add another stronger “always search” instruction after every flat round.','If traces show search was never registered, repair the harness; if it ran correctly but the grader rejects valid citations, revise and regrade the criterion.','The tuned prompt is not assumed to be the bottleneck for every failure.','Each failure bucket has concrete case evidence and a layer-specific next action.','The taxonomy is a diagnostic aid, not proof of root cause. Cases can cross layers; validate the proposed explanation with a controlled probe and preserve unknowns.'],
 ['连续编辑无法改变评估结果时，先按可能解释剩余失败的层级分类，再增加指令。','多轮提醒使用搜索后，检索代理基准仍持平。','读取代表轨迹和产物，区分知识缺失、评分错误、接线不可用、内容不可达与普通变异，再针对有证据的层。','每轮持平后再加更强“始终搜索”指令。','轨迹显示搜索未注册就修宿主；若已正确搜索却拒绝有效引用，就修标准并重评。','不假定每个失败的瓶颈都是正在调整的提示。','每个失败类别有具体案例证据与层级对应行动。','分类是诊断辅助，不证明根因。案例可跨层，需对照探测解释并保留未知。'])
for c in n['DATA']['candidates']:
 if c['key']=='core-anthro-heldout-channel':c['sources'].append(src(r,p,205,215,'Two-way selection versus optional untouched final test'))
 if c['key']=='core-addy-activation-not-outcome':c['sources'].append(src(r,p,271,271,'Engagement versus outcome'))
 if c['key']=='core-anthro-attempt-result-coherence':c['sources'].append(src(r,p,247,253,'Resolved run scope, canary and complete result record'))
ledger=json.loads((n['OUT']/'core-anthro-api-blocks.json').read_text(encoding='utf-8'));ids={o['block_id'] for o in ledger['occurrences'] if o['path']==p};assert all(ledger['blocks'][i]['status']=='read' for i in ids)
n['review'](r,p,'Full339-line guide and all exact block occurrences read. Runnable/valid eval preconditions and same-call trace/grade/usage; model/config propagation through subagents; stochastic build variance separate from scorer reps; explicit optimization target and non-regression constraints, scope/offlimits/check-in/spend contract; harness path hash is change detector, command allowlist not hash described as execution boundary; durable per-round snapshots, random stratified fixed split and withheld analyzer inputs; frozen env fingerprints and contemporaneous unchanged controls; one hypothesis across multiple hunks, predicted recoveries and regressions, trace-cited changes; API acceptance/resolvedscope/canary before expensive full pass; completeness before reporting, costs from all billed attempts; newmetrics regrade all variants, suspiciousjudge/engagement indicators distinct; stall taxonomy and breadth coverage with attribution tradeoff; finaltest if truly withheld and required-versus-tuning edits. Declared source train/test isolation is instruction-based handoff, not a structural access guarantee; baseline-failure review occurs before split and can contaminate later withheld cases; default so-called test selects winner each round, so it is validation. Reps do not remove shared-build dependence. Every CI/count/plateau/example efficacy/model/cost/budget heuristic is unverified; interval overlap is not a substitute for a paired effect analysis, unchanged engagement does not prove no quality effect, and flat-score diagnoses are hypotheses. Scrubbing short zero outcomes can conceal real no-op failures; preserve raw/excluded totals and fixed predicates. Runner/report behavior still pending implementation review.',[k1,k2,k3,'core-anthro-build-score-variance','core-anthro-heldout-channel','core-anthro-attempt-result-coherence','core-addy-activation-not-outcome'])
row=next(x for rr in n['DATA']['repositories'] if rr['repo']==r for x in rr['coverage'] if x['path']==p);row['exact_block_review']={'ledger':'core-anthro-api-blocks.json','unique_block_ids':sorted(ids),'all_occurrences_closed':True}
rr=next(x for x in n['DATA']['repositories'] if x['repo']==r);rr['source_flaw_evidence'].append({'claim':'Hillclimb default uses its named test set every round to select the best variant, so that set is validation. Passing only train paths to an analyzer is a prompt-level restriction; the guide does not provide a structural access boundary, and baseline failure review occurs before the split.','sources':[src(r,p,35,39,'Baseline-failure review'),src(r,p,205,215,'Default split and selection'),src(r,p,225,239,'Analyzer handoff and claimed isolation')]})
for c in n['DATA']['candidates']:
 seen=set();unique=[]
 for s in c['sources']:
  ident=(s['repo'],s['commit'],s['path'],s['line_start'],s['line_end'],s['section'])
  if ident not in seen:seen.add(ident);unique.append(s)
 c['sources']=unique
n['save']();print(n['DATA']['summary']['candidate_counts'],collections.Counter(b['status'] for b in ledger['blocks']))
