from pathlib import Path
import json
p=Path(__file__).parent;n={'__name__':'core_helpers'};exec((p/'core-update.py').read_text(encoding='utf-8'),n)
r='anthropics/skills';path='skills/claude-api/shared/evals/eval-hillclimb.md'
n['add']('anthro-build-score-variance','Separate build variance from scoring variance','区分构建变异与评分变异','evaluation',[(r,path,41,43,'Stochastic artifact build and propagated control')],
 ['When a prompt builds an artifact that is later evaluated, measure build variability separately from repeated scoring of one artifact.','A prompt generates a retrieval index, and several query repetitions score that single generated index.','Rebuild the unchanged baseline independently, score each build with the same query design, and preserve build identity in candidate comparisons; estimate uncertainty at the levels where randomness occurs.','Rescore one baseline index many times and treat its tight score spread as the uncertainty of changing the index-building prompt.','Build several baseline indexes with the same prompt, score each, and compare candidate builds while keeping between-build and within-build variation visible.','Repeated scoring of one build cannot reveal variability from the generation step that was sampled only once.','Build identities, unchanged-prompt replicas and scores grouped by build can be inspected.','Replicas must actually be independent at the intended level; shared caches or fixtures can couple them. The source’s example percentages and fixed replication counts are not verified guarantees.'],
 ['提示先构建产物再评估时，构建变异应与同一产物重复评分的变异分开。','提示生成检索索引，多个查询重复都评分这一个索引。','独立重建未改动基线，对每次构建使用相同查询设计，候选比较保留构建身份；在随机性实际发生的层级估计不确定性。','把一个基线索引重评分多次，将很小的评分波动当成修改构建提示的全部不确定性。','同一提示生成多个基线索引，各自评分；比较候选构建时同时展示构建间与构建内变异。','重复评分单次构建无法暴露只采样一次的生成步骤变异。','可以检查构建身份、未变提示副本以及按构建分组的分数。','副本需在所需层级真正独立；共享缓存或夹具可能关联它们。源示例百分比与固定重复次数不是已核验保证。'])
rr=next(x for x in n['DATA']['repositories'] if x['repo']==r)
rr['summary']['notes']=['Partial source audit:19/20 skill bodies are closed; claude-api body is pending. Ten complete shared API references, all skill-creator sources, current PDF/GIF helpers and art templates are read. Remaining method-bearing support code and API references are pending; no source scripts or live models executed. Public audit records contain independent summaries/examples and frozen locator/hash/range evidence; verbatim reading caches are local under ignored .tools/core-reading-cache.']
row=next(x for x in rr['coverage'] if x['path']=='skills/pdf/forms.md');row['exact_line_reuse']=next(x for x in json.loads((p/'core-anthro-deltas.json').read_text(encoding='utf-8')) if x['path']==row['path'])
n['save']()
f=p/'core-next-turn.md';s=f.read_text(encoding='utf-8')
s=s.replace("{'read': 659, 'pending': 3095}","{'read': 684, 'pending': 3070}",1).replace("{'active': 101, 'merged': 54, 'rejected': 2}","{'active': 102, 'merged': 54, 'rejected': 2}",1)
s=s.replace('core-anthro-api-blocks.json preserves full raw blocks and every path/span/hash occurrence;','core-anthro-api-blocks.json is a public hash/path/span/status ledger with no raw text. Verbatim API blocks live under ignored .tools/core-reading-cache/core-anthro-api-blocks.raw.json; the reader reconstructs frozen Git spans if that cache is absent. The protected PDF forms delta likewise lives under ignored .tools/core-reading-cache; its public stub and core-anthro-deltas.json contain only hash/range/pointer evidence. Every occurrence remains preserved;')
s=s.replace('- cost-hillclimb only its firstfour unique blocks1332–1335 are read; it is still pending. Do not infer full reading.','- cost-hillclimb only unique blocks1332–1335 are read; eval-hillclimb only1455–1479 are read. Both guides remain pending. A complete bilingual build-versus-scoring-variance candidate is already authored from eval-hillclimb L41–43; it does not claim the rest of the guide was read.')
f.write_text(s,encoding='utf-8');print(n['DATA']['summary']['candidate_counts'])
