from pathlib import Path
_namespace={'__name__':'core_helpers'}
exec(compile(Path(__file__).with_name('core-update.py').read_text(encoding='utf-8'),'core-update.py','exec'),_namespace)
globals().update({k:v for k,v in _namespace.items() if not k.startswith('__')})
R='obra/superpowers';D='skills/diagnosing-superpowers/'
kc=add('counter-semantics-before-totals','Establish counter semantics before totals','汇总前确认计数器语义','evaluation',[(R,D+'prompts/cost-and-time.md',8,17,'Tokens and wall-clock'),(R,D+'references/session-discovery.md',21,25,'Record meanings')],
['Determine whether metrics are increments or cumulative observations before aggregating them.','Compute token usage between observations 100, 140 and 200 from a cumulative counter.','Record semantics, units and interval boundaries; difference cumulative values for the interval and preserve missing observations as unknown.','Add 100+140+200 and report 440 tokens used during that interval.','For the interval after the 100 baseline, report 200-100=100 tokens; do not assign unobserved per-turn values when an intermediate record is missing.','Cumulative samples repeat earlier usage and cannot be summed as independent increments.','The calculation names the counter type, unit, baseline and supported interval total.','Counter resets and parent/child attribution require explicit handling; missing data is not zero.'],
['先确定指标是增量还是累计观察，再进行聚合。','根据累计计数器的 100、140、200 三次观察，计算观察间 token 使用量。','记录语义、单位和区间边界；对累计值做差，并将缺失观察保留为未知。','将 100+140+200 相加，报告该区间用了 440 token。','以 100 为区间起点，报告 200-100=100；中间记录缺失时，不虚构逐轮用量。','累计采样重复包含先前用量，不能当独立增量相加。','计算注明计数器类型、单位、基线与有证据区间总量。','计数器重置和父子会话归属需单独处理；缺失数据不是零。'])
ka=add('actor-provenance-before-intent','Identify the actor before inferring intent','判断意图前确认记录发出者','context',[(R,D+'prompts/analyst-common.md',19,21,'Human prompts'),(R,D+'templates/case.md',51,64,'Discovered record meanings')],
['Separate human requests from parent-agent dispatches, injected text and tool results.','Audit whether a human requested an external action from a child-agent transcript.','Establish record meanings and parent/child relationships, then attribute intent only to records proven to be human-typed.','Treat every role=user message inside the child transcript as direct human permission.','Identify the role=user record as a parent dispatch; locate the actual human request in the parent history before stating authorization.','A serialized role label does not uniquely identify the originating actor.','The report records actor provenance and the source of any claimed human instruction.','When the human record is unavailable, report the limitation rather than inventing intent.'],
['区分人类请求、父代理派发、注入文本和工具结果。','依据子代理记录审核人类是否请求了一个外部动作。','先确认记录语义及父子关系，只把证明为人类输入的记录用于意图归因。','把子记录中每个 role=user 消息都当成人类直接授权。','确认该 user 记录是父代理派发，先在父记录中找到真实人类请求，再陈述授权。','序列化角色标签不能唯一确定原始发出者。','报告记录发出者来源，以及声称人类指令的具体依据。','人类记录不可用时说明限制，不虚构意图。'])
kp=add('time-qualified-source-provenance','Qualify observations by when they were captured','按采集时间区分来源状态','evaluation',[(R,D+'templates/case.md',33,41,'Historical provenance'),(R,D+'templates/bundle-README.md',8,11,'Environment provenance')],
['Distinguish historical evidence, unverified snapshots, current observations and unknown state.','Determine which skill version influenced a session recorded last month.','Use captured bodies/archives for historical claims, current checkout for present observations, and label unresolved version fields explicitly.','Use today’s HEAD as proof of the version loaded last month.','Cite the captured skill body and its hash for last month; label today’s checkout separately; leave uncaptured installation version unknown.','Current state cannot authenticate past state, and one captured file cannot prove an entire installation.','Every version field has a time/provenance label and supporting location.','Preserved copies may be valid evidence even if original paths are gone; verify their provenance.'],
['区分历史证据、未验证快照、当前观察与未知状态。','确定上个月记录会话受到哪个技能版本影响。','历史主张使用捕获正文或归档，当前观察使用现有检出，未解决版本字段明确标注。','用今天 HEAD 证明上个月加载的版本。','用捕获的技能正文及哈希支持上个月情况，今天检出单独标注，未捕获安装版本保持未知。','当前状态不能认证过去状态，单个文件也不能证明整个安装。','每个版本字段有时间和来源标签及支持位置。','原路径消失时，保留副本仍可能是证据，但需验证来源。'])
ks=add('stable-redaction-linkage','Preserve linkage with stable redaction placeholders','用稳定遮蔽占位符保留关联','safety',[(R,D+'prompts/scrub.md',15,28,'Stable replacements / safe log'),(R,D+'references/redaction-policy.md',17,34,'Evidence-preserving redaction')],
['Use consistent substitutions across an export while retaining safe identity and evidence structure.','Redact the same private account in a report and its supporting transcript.','Map the value to one stable placeholder in every copy, preserve source markers and log only placeholder/category/count.','Replace one occurrence with ACCOUNT-1 and another with REDACTED, while storing the secret replacement map in the bundle.','Use ORG-1 consistently in report and transcript; keep original line markers; write only ORG-1/category/count to the log.','Stable anonymous identity preserves relationships without exposing the original value.','Citations and cross-file relationships remain checkable and the export contains no plaintext mapping.','If privacy removes evidence support, report the limitation instead of retaining secrets.'],
['在导出中一致替换敏感值，同时保留安全身份与证据结构。','遮蔽报告及支持记录中同一个私有账号。','在各副本中映射到同一占位符，保留来源标记，日志只写占位符、类别和数量。','一处替成 ACCOUNT-1，另一处替成 REDACTED，还把真实替换映射放进导出包。','报告及记录都使用 ORG-1，保留原行标记，日志仅记 ORG-1、类别和数量。','稳定匿名身份保留关联而不暴露原值。','引用和跨文件关系仍可检查，导出没有明文映射。','隐私处理移除支持证据时报告限制，不为证据保留秘密。'])
ke=add('privacy-and-evidence-export-checks','Check privacy and evidence usefulness separately','分别检查导出隐私与证据可用性','safety',[(R,D+'templates/bundle-README.md',58,77,'Evidence reconciliation / privacy audit'),(R,D+'prompts/scrub-audit.md',15,33,'Privacy audit scope')],
['Verify that an export is scrubbed and independently verify that its remaining evidence still supports its claims.','Deliver a redacted failure-analysis archive.','Audit all exported files for sensitive values, then resolve each finding to included evidence; reconcile files and verify the final archive matches the reviewed set.','Treat a CLEAN privacy result as proof every exported diagnosis remains supported.','Record privacy CLEAN and evidence limited for a claim whose tool-result body was withheld; state that limitation and archive exactly the reviewed files.','Removing secrets and preserving proof are different objectives.','The handoff states separate privacy and evidence outcomes and names unsupported findings.','A privacy audit is not exhaustive certification; edits after review require affected checks again.'],
['确认导出已遮蔽，并独立确认剩余证据仍支持主张。','交付一个经过遮蔽的失败分析压缩包。','审核全部导出文件的敏感值，再把各发现对应到随包证据，协调文件并验证压缩包与审核集合一致。','把隐私 CLEAN 当成全部导出诊断仍有支持的证明。','记录隐私 CLEAN，但因工具结果被隐藏而将某主张标为证据有限；说明限制并压缩已审核文件。','去除秘密与保留证明是不同目标。','交接分别说明隐私和证据结果，并列明不受支持发现。','隐私审核不是穷尽认证；审核后改动须重跑受影响检查。'])

notes={
 'prompts/analyst-common.md':('Read-only case-bound analysis with exact actor provenance, bounded field extraction and path:line findings; empty findings still name checked scope.',[ka]),
 'prompts/cost-and-time.md':('Counters establish incremental/cumulative units before arithmetic; missing observations remain absent; event timestamps and supported association bound durations/cost claims.',[kc]),
 'prompts/plan-adherence.md':('Recover agreed plan from observed human agreement, map steps to execution and structural events; skipped/invented/out-of-order/drift states cite both plan and action.',['core-plan-owned-resumption-ledger']),
 'prompts/quality-evidence.md':('Audit claim-to-run evidence, commit messages against observed work and acceptance met/not-met/not-checked states; process audit explicitly differs from code review.',['core-superpowers-proof-before-claim']),
 'prompts/repeated-work.md':('Group exact normalized tool/key events, inspect changes or compaction between repetitions and distinguish justified rereads from unproductive repetition. Thresholds are heuristic flags, not proof of waste.',[]),
 'prompts/request-conflicts.md':('Attribute human instructions correctly, pair contradictory requests/loaded rules and record the actual resolution without judging the user.',[ka]),
 'prompts/scrub-audit.md':('Independent auditor reads every export file, including quotes and encoded payloads; reports residual policy misses without original sensitive values. CLEAN concerns privacy only.',[ks,ke]),
 'prompts/scrub.md':('Scope mutation to bundle copies, use stable cross-file replacements, recount final non-log occurrences and never persist plaintext originals in the scrub log.',[ks]),
 'prompts/similar-session.md':('Verified candidate identity and explicit marker hit/miss/unknown with evidence; unknown fields cannot be counted as misses. Marker matching is not causal diagnosis.',[ka,kp]),
 'prompts/skill-timeline.md':('Separate invocation, loaded-file and attribution meanings per harness; compare request to trigger and report mismatch without declaring it wrong.',[ka,kp]),
 'prompts/stumbles.md':('Trace actual failure, retry, reversal, correction and recovery events; group repeated failures while preserving line/turn and recovery status.',[]),
 'references/context-safety.md':('Measure bytes/lines and long records before reading; locate line numbers then extract bounded fields; never modify original session data.',[]),
 'references/github-issues.md':('Search open/closed issues before filing, preserve exact reviewed text via body-file and fall back according to real available tooling. API quotas/URL-size claims are frozen source statements requiring current verification.',[]),
 'references/redaction-policy.md':('Classify sensitive values with supplied public/proprietary lists, retain safe linkage and mark redacted quotations; ambiguous classification escalates; opaque non-evidence payload is omitted.',[ks,ke]),
 'references/session-discovery.md':('Verify requested identity using content/timestamps/paths and discover record semantics rather than borrowing another harness schema; preserve rejected candidates and uncertainty.',[kc,ka,kp]),
 'templates/bundle-README.md':('Conceptual whole-template review: level-specific body inclusion, source-line anchor preservation, independent privacy/evidence checks, final-file reconciliation and delivered-archive equality.',[kp,ks,ke]),
 'templates/case.md':('Conceptual whole-template review: agreed observable statement, verified identities, historical/current/unverified/unknown environment labels, field semantics and unresolved information.',[kc,ka,kp]),
 'templates/issue.md':('Conceptual whole-template review: dedup search, provenance fields, involvement versus cause, scrubbed reproduction and actual delivered-archive/attachment state.',[kp,ke]),
 'templates/report.md':('Conceptual whole-template review: claim evidence, independent analysis dimensions, honest not-read/in-progress/unsupported capability notes and optional similar-session section.',[ka,kp,ke])
}
for path,(note,keys) in notes.items():review(R,D+path,note,keys)
save()
