from pathlib import Path
N={'__name__':'core_helpers'};exec(Path(__file__).with_name('core-update.py').read_text(encoding='utf-8'),N)
globals().update({k:v for k,v in N.items() if k not in ['__name__','__file__']})
R='addyosmani/agent-skills'
def case(key,en,zh,cat,p,a,b,d,m,s,bad,good,e,lim,zd,zm,zs,zb,zg,ze,zlim,ids=None):
 return add('addy-'+key,en,zh,cat,[(R,p,a,b,en)],[d,s,m,bad,good,'The contract names which evidence may be reused and which decision remains unresolved, so the result can be checked.',e,lim],[zd,zs,zm,zb,zg,'契约明确哪些证据可复用、哪些决定仍未解决，从而可检查结果。',ze,zlim],ids=ids or [])
case('reconcile-reviewer','Ordered reconciliation of reviewer findings','有序协调评审发现','evaluation','skills/doubt-driven-development/SKILL.md',168,179,
 'Treat reviewer output as hypotheses and classify against the actual artifact before acting.','Check contract misread first, then actionable defect, accepted tradeoff and context-caused noise; fix the contract before repeating review when it caused the error.','Review a cache that intentionally returns stale data under a stated tolerance.','Fix every reviewer complaint or dismiss all disagreement as noise.','Re-read each finding: clarify the missing tolerance first; fix a real unbounded-staleness path; record an accepted latency tradeoff separately.','The artifact changes only for validated actionable findings, with contract failures distinguished.','Classification is an editorial judgment; a reviewer disagreement alone proves neither author nor reviewer correct.','将评审输出视为假设，行动前按实际产物分类。','先查契约误读，再查可行动缺陷、接受权衡、背景噪声；契约致误则先修契约再评审。','评审明确容忍一定陈旧的数据缓存。','每条意见都修，或全当噪声。','逐条复读：先补缺失容忍；修真正无界陈旧路径；单独记可接受延迟权衡。','只为已验证可行动发现改产物，区分契约缺陷。','分类是编辑判断；分歧本身不证明作者或评审者正确。')
case('cached-reading-relevance','Resource freshness versus reading relevance','资源新鲜度与解读相关性','context','hooks/SDD-CACHE.md',57,80,
 'A fresh resource validator does not make a previously transformed answer relevant to a different question.','Record both source version and transformation question; reuse a derived reading only when it covers the new task, otherwise refetch or rederive from raw content.','Reuse documentation first read for an API signature while researching its error semantics.','Origin says 304, so the old signature-only summary answers the error question.','Check the original extraction prompt; if it only requested signatures, fetch the missing error section or rederive from the unchanged raw page.','Unchanged source content is not mistaken for complete coverage of the new question.','The observed hook is URL-only and leaves relevance judgment to the agent; it does not enforce this invariant automatically.','源验证器确认新鲜，不使旧变换答案适合另一问题。','同时记录来源版本与变换问题；派生解读覆盖新任务才复用，否则重取或按原文重新解读。','错误语义研究复用之前只读接口签名的文档。','来源304，所以旧签名摘要能答错误问题。','检查原提取提示；只问签名则取缺失错误章节，或按未变原页面重推。','不把来源未变误作新问题已完整覆盖。','观察到的钩子只以URL为键，把相关性留给代理判断，并不自动强制不变量。')
case('derived-validator-binding','Bind a derived artifact to its actual input revision','将派生产物绑定实际输入修订','evaluation','hooks/sdd-cache-post.sh',75,135,
 'Validate derivation order so a later source revision cannot be attached to an earlier derived body.','Capture content and its validator from the same fetch, or re-fetch when a later validation may refer to another revision.','Cache a model extraction of a changing documentation page.','Extract revision A, then issue HEAD after revision B appears and tag the A summary with B ETag.','Store the response validator that accompanied A; if only a later HEAD is available, verify the body again before binding that validator.','A later 304 cannot falsely certify an older derived summary.','This is a static source-race inference; the audit did not execute or reproduce it against a live server.','核对派生顺序，避免将后来的来源版本贴到早期派生正文。','同次获取正文与验证器；后验证可能属别版本时重取。','缓存变化文档页的模型摘要。','提取A后页面变B，再HEAD并用B的ETag标A摘要。','存伴随A响应的验证器；仅有后HEAD时，绑定前重新核正文。','后来的304不误认证更旧摘要。','这是静态来源竞争推断，本审计未运行或向服务复现。',ids=[178])
case('safe-artifact-channel','Pass review artifacts through inert input channels','通过惰性输入通道传评审产物','safety','skills/doubt-driven-development/SKILL.md',127,152,
 'Preserve artifact text as data when invoking an external reviewer.','Write the full artifact/contract prompt to a file and feed stdin; verify the tool and use a read-only execution boundary.','Review code containing backticks and command-substitution syntax.','Interpolate the source directly into a shell command argument.','Write the exact prompt to a file, pass the file on stdin to the verified read-only reviewer, and retain the invocation/result provenance.','Shell metacharacters in the artifact do not become shell instructions.','A read-only wrapper limits filesystem effects, not all prompt-injection or external-data risk; host flags must be verified.','调用外部评审时保持产物文本为数据。','完整产物契约提示写文件，经标准输入传递；验证工具并用只读边界。','评审含反引号与命令替换语法的代码。','源内容直接插入shell命令参数。','确切提示写文件，标准输入传给已验证只读评审，保留调用结果来源。','产物元字符不成为shell指令。','只读包装限制文件影响，非所有提示注入和外部数据风险；宿主标志须核。')

case('check-lifecycle-cost','Place checks by feedback cost','按反馈成本安排检查','workflow','skills/constraint-driven-development/SKILL.md',186,200,
 'Keep fast feedback near edits and place expensive checks at explicit later gates.','Name each check target, lifecycle phase and cost budget; reuse existing evidence rather than running the same unchanged suite twice.','Verify a frontend change with types, browser accessibility and mutation checks.','Run every full-repository check after every keystroke.','Run affected types/lint after edits, related tests at task end and costly browser/mutation checks at preview or CI, each with its declared result.','Fast iteration retains an inspectable final quality gate.','Cost estimates and source tool commands need local measurement/version verification; moving a check must not silently remove it.','快速反馈近编辑，昂贵检查在明确后门。','为每检查命名目标、阶段和成本，复用已有证据，不重复跑未变整套。','以类型、浏览器可访问和突变检查验证界面变化。','每敲字都运行所有整库检查。','编辑后跑受影响类型lint，任务末跑相关测试，浏览器突变检查在预览或CI，均明确结果。','快速迭代仍有可审最终质量门。','成本命令须本地测量核版本；后移检查不可暗删。')
case('guard-quality-bar','Review changes to the quality bar itself','评审质量门槛自身变化','evaluation','skills/constraint-driven-development/SKILL.md',202,225,
 'Review the validator as well as the implementation so green cannot be bought by weakening the contract.','Compare baseline thresholds, skipped/deleted tests, removed assertions, suppressions, stubs and new exceptions; require explained scoped exceptions.','Fix a failing coverage gate.','Lower the required coverage and skip a failing test, then report green.','Compare the gate against the branch baseline; keep its threshold, fix the uncovered behavior or record an owned expiring exception for review.','A successful verdict retains the originally accepted bar.','A shallow diff guard can false-flag legitimate rewrites and miss semantic weakening; findings require review.','评审验证器与实现，防止削弱契约换绿。','比较基准阈值、跳过删除测试、移除断言、抑制、桩和新例外，例外须解释且限定。','修复失败覆盖门。','降低覆盖要求并跳过失败测试，再报绿。','对照分支基准，保持阈值，修未覆行为或提交有负责人到期的例外待评审。','成功结论保留原接受门槛。','浅层diff护栏可误报合法改写，漏语义削弱；须复核发现。')
case('measured-ratchet','Measured baseline ratchet','测量基准棘轮','evaluation','skills/constraint-driven-development/SKILL.md',226,233,
 'Adopt a measured nonregression direction when an arbitrary target would fail the inherited baseline.','Record metric value, measurement conditions, allowed direction and tolerance; compare equivalent runs and update improved baselines.','Set a quality gate on a legacy project.','Demand an invented80% threshold the inherited project cannot pass.','Measure the current changed-line coverage, record the baseline/command and require no comparable regression; define separate improvement work.','The gate detects deterioration without pretending the inherited state is already ideal.','Changing denominator/workload can invalidate comparison; a ratchet is not proof of sufficient absolute quality.','任意目标使继承基准必败时采用实测不退步方向。','记录值、条件、允许方向及容差，比较等价运行，改善时更新基准。','为遗留项目设质量门。','强设继承项目无法达的80%。','测当前覆盖，记录基准与命令，要求可比条件下不退步；改善另立工作。','门能检退化而不假装继承状态已理想。','分母或负载变化使比较失效；棘轮不证明绝对质量足够。')
case('check-tristate','Distinguish check violation from inability to run','区分检查违规与无法运行','tools','skills/constraint-driven-development/references/floor-guard.md',7,14,
 'Keep clean, violation and unavailable-check outcomes distinct.','Return separate statuses and forbid inability-to-run from being reported as a clean result.','Run a diff guard in a shallow checkout without its base ref.','Map every nonfatal guard exit to passed.','Report unable to run because merge base is missing; restore the baseline or leave the gate unresolved, separate from a detected violation.','No unchecked change is certified by a missing-check path.','Exit conventions are local contracts; the invoking wrapper must preserve their meanings.','分清干净、违规和检查不可用。','返回不同状态，禁止无法运行被报干净。','浅克隆缺基准引用时跑差异护栏。','所有非致命退出都映成通过。','报缺合并基准无法运行；补基准或保留门未解决，与发现违规分开。','检查缺失不认证未检变更。','退出约定属局部契约，调用包装须保留语义。',ids=[175])
case('verification-invalidation','Reuse verification until its assumptions change','假设变更前复用验证','evaluation','skills/incremental-implementation/SKILL.md',199,211,
 'Repeat a successful check only when relevant code or baseline assumptions have changed.','Record command, artifact revision and scope; invalidate evidence on an edit affecting that check, not on nervousness alone.','Finish a tested parser change while editing its README.','Re-run the identical full build repeatedly on unchanged code.','Retain the parser test result for its unchanged revision; run documentation checks for the README edit; rerun parser tests only if parser input or code changes.','Verification effort follows an explicit evidence invalidation rule.','External dependencies, nondeterminism or changed fixtures may invalidate results even without source edits.','仅相关代码或基准假设变更时重复成功检查。','记录命令、产物修订和范围；影响检查的编辑使证据失效，而非仅因不安。','已测解析器变化完成时改README。','不变代码反复跑相同整构建。','保留不变解析器修订的测试结果；文档改动跑文档检查；代码或输入变后才再测解析器。','验证成本遵循明确证据失效规则。','外部依赖、不确定性或夹具变更可在无源编辑时使结果失效。')

case('noise-aware-intervention','Noise-aware intervention comparison','考虑噪声的干预比较','evaluation','skills/performance-optimization/SKILL.md',368,389,
 'Compare one change under equivalent measurement conditions and require signal beyond normal variance.','Keep command, workload and budget constant; repeat measurements, preserve correctness gates and decide against the observed noise range.','Evaluate a parser optimization.','Compare a cold baseline once with a warm optimized run and call a small delta a win.','Run both revisions on the same workload and cache conditions; compare repeated timings and retain the change only if the effect exceeds normal variation while correctness holds.','The measured effect is attributable to the tested intervention.','Variance estimates depend on sample quality; changes with intentional nonperformance benefits need a separate benefit contract.','在等价测量条件比较单个变化，并要求超过正常波动。','固定命令负载预算，重复测量，保留正确性门，再按噪声范围决定。','评估解析器优化。','一次冷基准对一次暖优化，小差就称赢。','相同负载缓存条件测两修订，比较重复计时，仅差异超过正常波动且正确性保持才留。','测量效果可归因于所试干预。','方差估计依赖样本质量；另有明确非性能收益的变化需要另立收益契约。')
case('failed-attempt-memory','Retain rejected experiment evidence','保留被拒实验依据','context','skills/performance-optimization/SKILL.md',391,401,
 'Preserve attempted ideas and their rejection evidence even when the implementation is reverted.','Record idea, baseline/result, verdict and reason; consult that ledger before retrying the same proposal.','Optimize a slow list rendering path.','Delete the reverted memoization attempt and propose it again next session.','Record memoization unchanged within noise, with workload and result; test virtualization next and link its accepted evidence.','A later agent can distinguish unexplored ideas from already rejected ones.','New workloads or code may justify repeating an old idea; qualify the recorded context rather than treating rejection as permanent truth.','实现被撤回时仍保留尝试与拒绝依据。','记录想法、基准结果、结论理由，下次相同提案先查台账。','优化慢列表渲染。','删除无效memo尝试，下轮再提。','记memo在噪声内无变化及负载结果；再测虚拟列表并链接接受证据。','后代理可区分未探索与已拒想法。','新负载代码可使旧想法值得重试；限定记录背景，不把拒绝视永久真理。')
case('cache-response-inputs','Cache keys encode response-changing inputs','缓存键包含改变响应的输入','safety','skills/performance-optimization/SKILL.md',354,366,
 'Derive a cache key from every input that affects the visible response.','Inventory tenant, viewer permissions, locale and feature state; state staleness/invalidation explicitly and reject reuse across unmatched response contexts.','Cache a localized per-tenant report.','Key only by the report URL and serve the first cached user result to everyone.','Key by report version, tenant, locale and authorization context; require a stated freshness policy before reusing a response.','A speed improvement does not erase response identity or confidentiality boundaries.','A complete key can be expensive or unstable; verify the actual dependency set and avoid caching freshness-critical data.','以所有影响可见响应的输入导出缓存键。','清点租户、查看者权限、地区及功能状态，明确陈旧失效策略，不跨不匹配背景复用。','缓存每租户本地化报告。','仅用URL，把首用户缓存给所有人。','报告版本租户地区授权背景为键，明确新鲜策略后才复用。','性能改善不抹去响应身份与保密边界。','完整键可能昂贵易变；须核实际依赖集，不缓存必须即时新鲜数据。')

for p,s in {
'hooks/SDD-CACHE.md':'Full cache design read: conditional origin validators, fail-open/no-validator miss, URL-keyed prompt-shaped reading with original prompt metadata and explicit reuse relevance limit. Extra HEAD after derived WebFetch content can bind later revision to earlier summary; docs fresh-verification guarantee is stronger than code establishes.',
'hooks/sdd-cache-pre.sh':'Full source read: graceful missing dependencies/malformed input, URL SHA256 prefix key, validators required, only304 hit, inert printf framing and original question metadata. URL-only key cannot guarantee transformed-question coverage; host result-on-exit2 behavior is frozen assumption.',
'hooks/sdd-cache-post.sh':'Full source read: response-shape fallbacks, derived body before extra HEAD, final redirect header parsing, validators required, JSON serialization and temp rename. LaterHEAD validator race and unchecked tool_response.code can cache mismatched/error content. Debug mode logs first400rawpayload bytes and URL; sensitive-data guarantee absent.',
'hooks/sdd-cache-test.sh':'Full test source read without executing it: deterministic curl stub exercises miss/malformed/no-validator/non304/network/empty-content/unknownshape/redirect-final/header-write/hit/roundtrip shell metacharacter cases. It does not model source changing between WebFetch and HEAD, new-question adequacy, error-content validity, private-URL access, or trailing-newline byte preservation.'
}.items():
 keys=[c['key'] for c in DATA['candidates'] if any(x['repo']==R and x['path']==p for x in c['sources'])]
 review(R,p,s,keys)
for p in ['skills/context-engineering/SKILL.md','skills/using-agent-skills/SKILL.md','skills/source-driven-development/SKILL.md','skills/doubt-driven-development/SKILL.md','skills/incremental-implementation/SKILL.md','skills/planning-and-task-breakdown/SKILL.md','skills/spec-driven-development/SKILL.md','skills/constraint-driven-development/SKILL.md','skills/constraint-driven-development/references/floor-guard.md','skills/performance-optimization/SKILL.md']:
 row=next(f for r in DATA['repositories'] if r['repo']==R for f in r['coverage'] if f['path']==p)
 row['candidate_keys']=[c['key'] for c in DATA['candidates'] if any(x['repo']==R and x['path']==p for x in c['sources'])]
save()
print('Addy checkpoint retained;',len(DATA['candidates']),'total candidates')
