from pathlib import Path
N={'__name__':'core_helpers'};exec(Path(__file__).with_name('core-update.py').read_text(encoding='utf-8'),N)
globals().update({k:v for k,v in N.items() if k not in ['__name__','__file__']})
def evidence(repo,claim,ranges):
 return {'claim':claim,'sources':[src(repo,p,a,b,'source quality review') for p,a,b in ranges],'status':'observed-source-limit','efficacy_status':'editorial-review-only'}
R='mattpocock/skills';rr=next(r for r in DATA['repositories'] if r['repo']==R)
rr['source_flaw_evidence']=[
 evidence(R,'The commentary claims redaction is missing; the frozen canonical body explicitly requires it. Unfixed-status anecdotes are not reliable current-state evidence.',[('docs/engineering/diagnosing-bugs.md',70,74),('skills/engineering/diagnosing-bugs/SKILL.md',12,16)]),
 evidence(R,'The design commentary says no lint rule is shipped, but the frozen beta source ships path-depth dependency rules. Read canonical artifacts before trusting secondary summaries.',[('docs/engineering/codebase-design.md',50,56),('skills/in-progress/setup-ts-deep-modules/dependency-cruiser.config.cjs',24,74)]),
 evidence(R,'Wizard commentary claims time-remaining display; the current library only announces stage index/total. The source changelog records removal of time estimates.',[('docs/engineering/wizard.md',42,46),('skills/engineering/wizard/template.sh',49,56),('CHANGELOG.md',13,15)]),
 evidence(R,'The purported self-contained architecture report loads Tailwind and Mermaid remotely, with Mermaid securityLevel loose. Its template alone does not establish offline renderability or safe handling of arbitrary labels.',[('skills/engineering/improve-codebase-architecture/HTML-REPORT.md',1,17)]),
 evidence(R,'The Git hook matches substrings rather than parsed Git invocations; global flags/whitespace can evade intended patterns and quoted prose can false-match. Wizard raw KEY=VALUE serialization does not encode arbitrary multiline values.',[('skills/misc/git-guardrails-claude-code/scripts/block-dangerous-git.sh',3,25),('skills/engineering/wizard/template.sh',128,139)]),
 evidence(R,'Teaching copy distinguishes runtime input from source references with the same relative-path notation, and requires equal option lengths without a quiz-position randomizer. These instructions are not evidence of assessed prior knowledge or long-term learning efficacy.',[('skills/productivity/teach/SKILL.md',12,20),('skills/productivity/teach/SKILL.md',81,110)])]
R='Leonxlnx/taste-skill';rr=next(r for r in DATA['repositories'] if r['repo']==R)
rr['source_flaw_evidence']=[
 evidence(R,'The GPT variant calls simulated Python output true randomization. Mock output cannot establish tool execution or randomness.',[('skills/gpt-tasteskill/SKILL.md',13,22),('skills/gpt-tasteskill/SKILL.md',68,74)]),
 evidence(R,'The redesign variant asks for randomized dates and invented organic-looking metrics. Taste v2 instead requires actual source data or mock labels for precise-looking figures; these variants are materially different.',[('skills/redesign-skill/SKILL.md',87,104),('skills/taste-skill/SKILL.md',321,330)]),
 evidence(R,'Research text presents percentage improvements, seasonal causality and strong model/provider explanations, while its reference list lacks direct study links or reproducible experiment metadata. The audit does not admit these efficacy claims.',[('research/laziness/findings/empirical-results.md',35,58),('research/laziness/findings/references.md',1,20)]),
 evidence(R,'The static design example explicitly marks motion as later code-phase intent. A static mockup therefore is not evidence that runtime animation exists or achieves the claimed performance.',[('skills/stitch-skill/DESIGN.md',91,99)]),
 evidence(R,'Taste v2 declares a block-library schema and future file layout, but the frozen tree contains no block implementation files. The contract is an authoring method, not a shipped component library.',[('skills/taste-skill/SKILL.md',835,892)]),
 evidence(R,'Long image workflows repeat an unbounded generate/refine-until-strong rule. Readable units and artifact count are useful contracts; fixed image counts and fresh-generation-over-crop are source preferences, not demonstrated fidelity or efficiency gains.',[('skills/image-to-code-skill/SKILL.md',133,198),('skills/image-to-code-skill/SKILL.md',202,229),('skills/imagegen-frontend-mobile/SKILL.md',1262,1288)])]
R='addyosmani/agent-skills';rr=next(r for r in DATA['repositories'] if r['repo']==R)
rr['source_flaw_evidence']=[
 evidence(R,'Cache documentation claims unchanged origin freshness for a model-shaped reading. The post hook obtains validators after the response body; an intervening source change can attach a newer validator to an older summary. This is a static race inference, not an executed reproduction.',[('hooks/SDD-CACHE.md',3,9),('hooks/sdd-cache-post.sh',31,63),('hooks/sdd-cache-post.sh',79,135)]),
 evidence(R,'The cache is URL-only while its content is prompt-shaped. A 304 validates the source resource, not coverage of a new extraction question; the docs themselves leave that relevance decision to the agent.',[('hooks/SDD-CACHE.md',53,80),('hooks/SDD-CACHE.md',154,158)]),
 evidence(R,'Source tests use deterministic network stubs and cover basic cache paths and shell metacharacters. They do not exercise body-versus-later-validator races, new-question completeness or trailing-newline byte preservation. No source tests were executed by this audit.',[('hooks/sdd-cache-test.sh',1,12),('hooks/sdd-cache-test.sh',138,154),('hooks/sdd-cache-test.sh',219,246)])]
save()
