from pathlib import Path
import struct,subprocess,xml.etree.ElementTree as ET,collections
N={'__name__':'core_helpers'};exec(Path(__file__).with_name('core-update.py').read_text(encoding='utf-8'),N)
globals().update({k:v for k,v in N.items() if k not in ['__name__','__file__']})
R='Leonxlnx/taste-skill'
def case(key,en,zh,cat,p,a,b,d,m,s,bad,good,e,lim,zd,zm,zs,zb,zg,ze,zlim,ids=None,status=None,reason=None):
 k=add('leon-'+key,en,zh,cat,[(R,p,a,b,en)],[d,s,m,bad,good,'The stated contract changes what the agent selects, preserves or verifies, and makes the difference inspectable.',e,lim],[zd,zs,zm,zb,zg,'明确契约改变代理选择、保留或验证的内容，使差别可检查。',ze,zlim],ids=ids or [],status=status)
 if reason:next(x for x in DATA['candidates'] if x['key']==k)['reason']=reason
 return k
T='skills/taste-skill/SKILL.md'
case('declared-design-read','Declare the inferred design brief','声明推断设计简报','prompt',T,13,36,
 'Make the task interpretation visible before acting on a broad visual request.','Infer surface, audience, existing assets and constraints; state one design read and clarify only a materially diverging branch.','Design a calm service landing page.','Jump directly to a cinematic dark site.','Reading this as a service page for first-time applicants, using restrained hierarchy and the existing brand; use that interpretation for the build.','The user can correct a concrete interpretation before it drives implementation.','Inference is provisional; the one-question rule is a local interaction heuristic.','广泛视觉任务执行前公开解释。','推断表面、受众、资产和约束；声明设计理解，只澄清会明显分岔的条件。','设计平静的服务着陆页。','直接做电影感暗站。','理解为初次申请人的服务页，采用克制层级及现有品牌；据此构建。','用户可在解释驱动实现前纠正。','推断暂定；一次一问是局部交互启发式。')
case('contextual-rule-precedence','Contextual rule precedence','条件规则优先级','prompt',T,165,211,
 'Gate aesthetic defaults by the task context and preserve explicit brand or user constraints.','Declare default, triggering condition and override condition together; carry the selected interpretation through the whole artifact.','Modernize an existing purple-branded site.','Apply the no-purple aesthetic ban and replace the brand color.','Keep the supplied purple brand as the explicit override; apply restrained contrast and spacing rules around it.','The output follows the actual brief rather than a universal recipe.','Source numeric style dials and subjective bans are unvalidated editorial choices.','以任务背景门控美学默认，保留明确品牌与用户约束。','默认、触发条件和覆盖条件同处声明，选择贯穿产物。','现代化已有紫色品牌站。','套用禁紫规则并替换品牌色。','所给紫色品牌为明确覆盖；周边采用克制对比与间距。','产物服从简报而非通用配方。','数值风格旋钮与主观禁止为未验证编辑选择。')
case('semantic-token-contract','Semantic token handoff contract','语义令牌交接契约','context','skills/stitch-skill/SKILL.md',37,45,
 'Express design tokens as semantic names, exact values and functional roles.','Pair a human description with a machine-usable value and where it applies, then use the same vocabulary throughout the handoff.','Hand a palette to an implementation agent.','Use dark text and a nice blue.','Primary ink #18181B for body text; action blue #2563EB for primary buttons and focus indication; preserve these roles across screens.','The receiver can distinguish identity, value and intended usage.','Exact values require rendering/contrast checks; a token name alone does not validate usability.','设计令牌写语义名、精确值和功能角色。','人类描述配机器可用值及适用处，交接中词汇一致。','向实现代理交接调色板。','用暗文字和漂亮蓝。','正文主墨#18181B；主按钮与聚焦标识用行动蓝#2563EB；各屏保持角色。','接收者可区分身份、值和用途。','精确值仍须渲染对比检查，名字不验证可用性。')
case('artifact-invariant-variation','Lock invariants, vary composition','锁定不变量、变化构图','context','skills/imagegen-frontend-mobile/SKILL.md',260,319,
 'Keep shared identity fixed while varying individual artifact purpose and composition.','Write a common design bible before generating the set; distinguish invariant palette/type/navigation from allowed layout and emphasis changes.','Generate checkout, receipt and order-detail mockups.','Choose a fresh palette and navigation for each screen.','Lock palette, type scale and bottom navigation; vary the checkout form, receipt summary and detail composition according to purpose.','The set varies without becoming unrelated products.','An internal bible is a plan; compare actual outputs before claiming consistency.','变化个别产物目的构图时固定共享身份。','生成前写共同设计约定；区别固定颜色字级导航与允许布局重点变化。','生成结算、收据、订单详情模型。','每屏换颜色与导航。','固定颜色、字级和底导航；按用途变化结算表单、收据摘要、详情构图。','集合有变化但不是不同产品。','内部约定是计划；须比实际产物才能宣称一致。')
case('flow-state-carry','Successor screens require an action and carried state','后继屏幕须有动作与传递状态','evaluation','skills/imagegen-frontend-mobile/SKILL.md',323,345,
 'Validate a visual sequence as a causal user journey, not just a screen count.','For each successor name the preceding action/navigation and the state carried into it.','Storyboard cart to payment confirmation.','Show attractive cart, login and receipt screens in arbitrary order.','Map pay on the populated cart to checkout with the same items, then successful payment to a receipt with the same total.','Every screen transition has a declared cause and state continuity.','Static images illustrate the intended flow; they do not prove implemented behavior.','以因果旅程验证视觉序列，不只数屏。','每个后继说明前动作或导航及携带状态。','分镜购物车到付款确认。','随意排列漂亮购物车、登录、收据屏。','购物车付款动作进入相同商品结算，付款成功到相同总额收据。','每次转场有明确原因和连续状态。','静态图说明预期流程，不证明已实现行为。')
case('specimen-before-translation','Inspect the specimen before translating it','翻译前检查原型样本','workflow','skills/image-to-code-skill/SKILL.md',289,364,
 'Extract an explicit visual contract before coding from a reference artifact.','Inspect readable text, relative typography, spacing, colors, components and uncertainties; implement against that extracted contract.','Implement a supplied landing-page reference.','Glance at the image and code a familiar card template.','Record the headline/CTA, two-column ratio, type hierarchy and unknown hover behavior, then build those observed relationships.','The implementation can be checked against named observations instead of vague inspiration.','A raster cannot establish hidden behavior or exact font identity; label inference and ask or refine uncertain detail.','从参考产物编码前抽取明确视觉契约。','检查可读文字、相对字体、间距、颜色、组件及未知点；按抽取契约实现。','实现给定着陆页参考。','看一眼图就写熟悉卡片模板。','记录标题CTA、两列比例、字级及未知悬停行为，再构建观察关系。','可按命名观察检查实现，而非模糊灵感。','栅格不证明隐藏行为或精确字体；标推断并澄清或细化。')
case('readable-units','Match reference granularity to inspection needs','按检查需求选择参考粒度','context','skills/image-to-code-skill/SKILL.md',133,198,
 'Break dense references into units that preserve the details needed downstream.','Count requested units, give each a readable artifact, and add detail views only where inspection is uncertain.','Hand eight page sections to a coding agent.','Compress all sections into a tiny collage.','Provide one readable section view per section, plus a labelled button-detail view where the original is unclear.','Downstream work can inspect text and spacing without guessing from tiny pixels.','Fresh generation may change details; the source blanket no-crop preference is not a universal guarantee.','将密集参考拆成可保留下游所需细节的单元。','清点所需单元，各有可读产物，不明确处才加细节视图。','向编码代理交接八个页面章节。','全部压成小拼贴。','每章节一个可读视图，按钮原图不清时加有标记细节视图。','下游可看文字间距，不须猜小像素。','重新生成可能改细节；源的全面禁裁剪偏好非普遍保证。')
case('continuation-cursor','Clean-break continuation cursor','清晰断点续接游标','output','skills/output-skill/SKILL.md',25,43,
 'Preserve output quality at a generation boundary using an explicit progress count and next unit.','Stop at a complete structural unit, state completed/total and exact resume point, then resume without repeating prior units.','Deliver twelve independent reference sections.','Shrink the final six into a vague summary to fit.','Finish section six intact; report 6/12 complete, next section seven; resume from seven when continuation is available.','Missing work remains explicit and subsequent output starts at the right unit.','This is output continuity, not permission to mark the whole task done or pause autonomously where continuation is available.','生成边界以进度计数及下一单元保留质量。','完整结构单元处停，说明完成/总数及准确续点，随后不重复已完单元。','交付十二个独立参考章节。','为塞进长度把后六节压成模糊摘要。','完整完成第六节，报6/12和下一第七节；可继续时从七续。','缺失工作明确，后续从正确单元开始。','这是输出续接，不是可用续轮时自主暂停或称整任务完成。')
case('tool-run-provenance','Separate simulated from observed tool results','分清模拟与观察工具结果','tools','skills/gpt-tasteskill/SKILL.md',13,22,
 'Keep tool provenance explicit when using generated or deterministic selections.','State whether computation ran, was simulated or is only a proposed procedure; never label a mock output executed evidence.','Choose a layout using a seeded selection.','Print mock Python output and call it true random execution.','Either run the seeded selector and record its actual seed/result, or label the choice as a hand-selected proposal with no execution claim.','The reader can distinguish computation evidence from illustrative text.','The observed source requests simulated RNG; this candidate is a corrective editorial contrast, not proof that the source enforces it.','使用生成或确定选择时明确工具来源。','说明计算已运行、模拟或仅拟议，不把假输出标执行证据。','以种子选择布局。','打印假Python输出并称真正随机执行。','实际运行并记种子结果，或标为人工选择提案且不声称运行。','读者可分计算证据与示意文字。','源要求模拟随机；此是纠错教学对照，不证明源已实施。',ids=[175],reason='Observed source flaw enriches the existing provenance mechanism; fake execution is rejected, not adopted.')
case('approximation-provenance','Label implementation approximation provenance','标注实现近似来源','output',T,106,119,
 'Distinguish an official implementation from an inspired approximation.','Use authoritative packages when required; otherwise label the visual inspiration and approximation without claiming official API status.','Build a web surface inspired by a native material.','Call custom CSS the official native material package.','Describe the effect as a web approximation inspired by the native material and cite the platform documentation separately from the implementation.','The receiver knows what is official evidence and what the project constructed.','The source particular platform/package claims are frozen observations; verify them before relying on present API availability.','区分官方实现与灵感近似。','要求官方实现时用权威包，否则标明灵感和近似，不声称官方接口。','构建受原生材料启发的网页。','自写CSS称官方原生材料包。','描述为受原生材料启发的网页近似，平台文档与自写实现分别引用。','接收者知道哪些官方证据，哪些项目构造。','源中平台包具体声明是冻结观察，依赖当前可用性前须核查。')
case('mock-precision','Provenance for precise-looking mock content','貌似精确样例内容的来源','safety',T,321,330,
 'Require a source or visible mock status for factual-looking metrics and specifications.','Inspect every displayed number; retain sourced values, label samples and remove invented precision presented as fact.','Mock up an analytics homepage.','Invent 47.2% growth to make it look real.','Use the provided growth figure, or display Sample data beside 47.2%; keep unsupported performance claims out of the published copy.','Realism does not silently convert invented content into evidence.','Comments alone may not be visible to the audience; choose disclosure appropriate to the artifact.','貌似事实的指标规格要求来源或可见样例标记。','检查每个数字，有源保留，样例标注，去除以事实呈现的虚构精度。','模拟分析首页。','编47.2%增长让它逼真。','使用提供的增长数，或在47.2%旁显示样例数据；公开文案不含无依据表现声明。','逼真感不暗中把虚构转成证据。','注释可能不可见；按受众选择产物披露方式。')
case('redesign-contract','Audit and preserve redesign contracts','审计并保留改版契约','workflow',T,783,831,
 'Classify redesign intent and inventory nonvisual contracts before changing presentation.','Detect preserve versus overhaul, record brand/content/routes/tracking/accessibility, then apply focused visual changes within that contract.','Modernize a working checkout page.','Replace the layout, field names and route slugs while restyling.','Audit checkout routes, event names, field identity and focus behavior; restyle spacing and typography while preserving those contracts.','Visual changes can be reviewed separately from accidental behavior/identity drift.','Explicitly authorized structural changes require their own migration and verification, not blanket preservation.','改视觉前分类改版意图并清点非视觉契约。','区别保留与大改，记录品牌内容路由跟踪可访问，再在契约内做聚焦视觉变化。','现代化可用结算页。','重设样式时替换布局字段名与路由。','审计结算路由、事件名、字段身份、聚焦行为；调整间距字体并保留契约。','可分别评审视觉改动与意外行为身份漂移。','明确授权结构变化需要自身迁移验证，而非一概保留。')
case('motivation-gate','Behavioral motivation before adding effects','添加效果前的行为动机门','prompt',T,352,363,
 'Add an effect only after naming its communicative job.','Require a reason tied to hierarchy, narrative, feedback or state change; omit effects with only decorative rationale.','Add motion to a saved-item interaction.','Animate every component because an animation library is available.','Animate the saved-item state transition so its new position is clear; keep the informational heading still.','Each selected effect has a reviewable purpose.','A stated purpose does not prove the effect works; render it and inspect reduced-motion behavior.','添加效果前说明传播作用。','理由关联层级、叙事、反馈或状态变化，纯装饰理由则省略。','给保存条目交互加动画。','有动画库所以全部组件动。','动画表现保存后新位置；信息标题静止。','每个选中效果有可评审用途。','说明用途不证明有效；渲染并检查减弱动作状态。')
case('capability-intent','Distinguish artifact capability from implementation intent','区分产物能力与实现意图','output','skills/stitch-skill/DESIGN.md',91,99,
 'Mark behavior descriptions as future implementation intent when the produced artifact cannot execute them.','Separate what a static artifact shows from the motion/interaction contract a later coding phase must implement and verify.','Hand a static dashboard mockup to a developer.','Claim the exported image has working animated status updates.','Label status pulse as code-phase intent; state the current deliverable is static and hand off the required behavior separately.','The artifact does not inherit capabilities from its prose description.','Actual host capability must be verified in the target environment; this is a contract distinction.','产物不能执行的行为描述标为后续实现意图。','区分静态产物所示与后续编码须实现验证的动作交互契约。','向开发者交接静态仪表板模型。','称导出图片有可工作的动态状态更新。','状态脉冲标代码阶段意图；当前交付静态，单独交接所需行为。','产物不从文字描述继承能力。','目标环境须核真实宿主能力；此仅契约区分。',ids=[173])

case('unsubstantiated-laziness','Unsubstantiated laziness efficacy explanation','无依据懒惰效能解释','evaluation','research/laziness/findings/empirical-results.md',35,58,
 'The source presents quantitative prompting and seasonal claims without directly locatable primary study evidence.','Require identified primary experiments, population, intervention, metric and comparison before admitting an efficacy claim.','Describe whether a tipping phrase improves task completion.','Repeat a 45% improvement and seasonal causal story as established.','State that this corpus asserts those effects but does not supply an auditable primary experiment; withhold efficacy language.','The claim is rejected pending support rather than laundering a percentage through a skills repo.','This audit does not establish the opposite causal claim either.','源无可定位原始研究证据却给出数值提示和季节声明。','有效性声明需明确原始实验、群体、干预、指标与对照。','解释给小费措辞是否改善任务完成。','把45%改善及季节因果当确定事实复述。','说明该库声称效果但未供可审原始实验，暂不采用效能措辞。','不给技能库百分数包装成证据，待支持前拒绝。','此审计也不证明相反因果。',status='rejected',reason='Quantitative causal efficacy claims lack directly locatable primary citations and reproducible evaluation details; not admitted.')
bad=next(c for c in DATA['candidates'] if c['key']=='core-leon-unsubstantiated-laziness')
bad['scores']={'scenario':2,'mechanism':0,'contrast':2,'observable':0,'boundaries':2};bad['quality_total']=6

SUM={
'brandkit':'Strategy/category/audience/metaphor precede logo concepting; coherent palette/logo across application panels, sparse readable copy and reference feature extraction rather than copying identity. Subjective premium superiority claims unverified.',
'brutalist-skill':'Select one Swiss-light or telemetry-dark archetype and substrate, consistent type/palette/grid/semantic tag constraints and analog effects. Style recipe is contextual; no blanket aesthetic or efficacy truth.',
'gpt-tasteskill':'Pre-code design plan, seeded layout/component choices, AIDA ordering, grid-density and contrast checks. Explicitly requests simulated Python RNG while calling it true randomization; that execution claim is a source flaw. Mandatory motion lacks reduced-motion branch.',
'image-to-code-skill':'Generate → inspect → extract visual contract → implement; section-readable reference units, extra detail when uncertain, multi-image invariant lock and anti-drift. Repeated no-crop/fresh-generation preference and unbounded image count are heuristics; no actual rendered-code comparison procedure.',
'imagegen-frontend-mobile':'Images-only output with chosen platform mode, explicit screen count, readable per-screen/detail units, shared design bible, safe-area/frame consistency and event/state carry across logical flow. Variety allowed only outside product invariants; static images do not prove runtime UX.',
'imagegen-frontend-web':'One horizontal image per declared section, labelled progress/cardinality, brief-adapted direction, controlled cross-section composition/background variation and palette invariants. Narrative spine/second-read motif, conversion purpose and mock readability are distinct creative controls; no measured conversion proof.',
'minimalist-skill':'Editorial monochrome style constraints, typography/component/icon hierarchy, subtle transforms and explicit mobile/layout execution. Gradient ban conflicts with later gradient background guidance; style and perf claims not universal.',
'output-skill':'Count required deliverables, generate whole units, cross-check original scope and continue at clean breakpoint with completed/total and next cursor. Blanket production-critical/all-placeholder bans are contextual, not universal requirements.',
'redesign-skill':'Scan existing framework/styles, audit design/state/content/import issues, apply focused upgrades while preserving stack/function and checking after changes. Instructions to randomize dates and invent organic metrics as realistic content are rejected as factual-provenance defects.',
'soft-skill':'Pick one vibe and layout archetype, explicit mobile collapse, nested material/token/motion constraints and final matrix. Price/quality guarantees and always-moving UI are unverified subjective claims; device performance is not established by a styling rule.',
'stitch-skill':'Translate visual atmosphere into semantic label + exact value + functional role DESIGN.md contract, contextual dials, state/layout/motion intentions and anti-pattern limits. Host behavior/API claims are frozen; static output does not execute intent.',
'taste-skill-v1':'Three baseline/user-overridden dials gate styling, density and motion; installed-dependency checks, client-leaf isolation, full interaction states and preflight. Strong aesthetic bans/infinite motion differ materially from v2; realistic invented numbers require mock disclosure.',
'taste-skill':'v2 fully read including code/appendices: declared design read, contextual overrides, design-system versus inspired approximation, motivated effects/reduced motion, real reference provenance, factual/mock copy, mode/view checks, redesign contracts and block schema. Actual block files do not exist; fixed aesthetic limits and regulatory/API claims unverified.'}
repo=next(r for r in DATA['repositories'] if r['repo']==R)
for f in repo['coverage']:
 p=f['path'];keys=[c['key'] for c in DATA['candidates'] if any(s['repo']==R and s['path']==p for s in c['sources'])]
 if p.endswith('/SKILL.md'):review(R,p,SUM[p.split('/')[-2]],keys)
 elif p=='skills/stitch-skill/DESIGN.md':review(R,p,'Full example contract inspected: semantic token roles, four adjustable dials, fixed responsive/mode gates and motion explicitly labelled later code-phase intent; contradictory body minimum 1rem/14px and unverified FPS claims noted.',keys)
 elif p.startswith('research/'):
  review(R,p,'Full text inspected. '+('Structured no-placeholder examples, complete-unit continuation cursor and original-request cross-check; internal reasoning-output demand not adopted.' if p.endswith('reference-prompts.md') else 'Lazy disclosure, retrieved evidence, structured input roles, claim verification questions, component chunking and self-grading are observed procedural ideas. Fixed percentages, seasonal/training/economic causality, token-cost/context caps and API parameter/quality claims lack directly locatable primary experiments and are not admitted.'),keys)
 elif p=='LICENSE':review(R,p,'MIT root license and 2026 author notice inspected; concepts restated through independent examples.')
 elif p=='README.md':review(R,p,'Full routing/install/update/settings/example narrative inspected; differentiates image-only versus code workflows and v1 versus v2. Sponsor model/pricing/statistical and framework-agnostic promises are unverified marketing, not extraction evidence.',keys)
 elif p=='.github/copilot-instructions.md':review(R,p,'Host adapter repeats style/full-output constraints and points to local bodies; automatic discovery and stopping generic output are source claims, not guarantees.',keys)
 elif p=='skills/llms.txt':review(R,p,'All13 routing summaries inspected; wrapper identity/type match reviewed bodies; no additional procedure. Path/install-name differences retained.',keys)
 elif p=='skill.sh':review(R,p,'Read-only source path registry for13skills inspected. Merely echoes matching path; does not load/validate capabilities or execute the skill. No source execution occurred.',keys)
 elif p.startswith('examples/'):
  review(R,p,'Rendered Git-blob image inspected: botanical landing-page visual with hierarchy, flower imagery, staggered grids, testimonial blocks, CTA and footer. Static illustration only; no comparative efficacy, runtime, testimonial authenticity or method compliance proof.',keys)
  f['depth']='rendered-visual-example-inspection'
 elif p.startswith('scripts/'):
  review(R,p,'Full supporting image-preparation source inspected: fixed sponsor/readme inputs, flood-fill edge background removal, alpha bounds/cropping, format/size conversion or compositing. No prompt/tool orchestration; hardcoded local Downloads paths and missing package manifest limit reproducibility.',excluded='Repo presentation-media implementation, outside transferable prompt/context/workflow mechanisms; read before exclusion.')
 elif p.startswith('assets/'):
  meta=next(x for x in BY_REPO[R]['files'] if x['path']==p)
  raw=subprocess.check_output(['git','-C','D:/Projects/open-skills/'+R,'cat-file','blob',meta['blob']])
  if p.endswith('.svg'):
   x=ET.fromstring(raw);tags=collections.Counter(y.tag.split('}')[-1] for y in x.iter());assert 'script' not in tags
   desc='SVG geometry inspected ('+str(dict(tags))+'); README sponsor/badge/link decoration, no embedded script or method text.'
  elif raw:
   if raw.startswith(b'\x89PNG\r\n\x1a\n'):fmt='PNG';w,h=struct.unpack('>II',raw[16:24])
   elif raw[:4]==b'RIFF' and raw[8:12]==b'WEBP':
    fmt='WEBP';kind=raw[12:16];payload=raw[20:]
    if kind==b'VP8X':w=1+int.from_bytes(payload[4:7],'little');h=1+int.from_bytes(payload[7:10],'little')
    elif kind==b'VP8L':v=int.from_bytes(payload[1:5],'little');w=1+(v&16383);h=1+((v>>14)&16383)
    else:
     marker=payload.index(b'\x9d\x01\x2a');w,h=struct.unpack('<HH',payload[marker+3:marker+7]);w&=16383;h&=16383
   else:raise AssertionError(('Unexpected raster',p))
   desc=f'{fmt} raster {w}x{h}; role established by fully-read README as sponsor/logo/navigation/banner presentation asset, not method reference.'
  else:desc='Empty tracked presentation-directory placeholder inspected.'
  review(R,p,desc,excluded='Repository branding/sponsorship presentation asset; format/content role inspected, no in-scope instruction method.')
 elif p in ['CHANGELOG.md','.github/FUNDING.yml','.claude-plugin/plugin.json','.claude-plugin/marketplace.json']:
  review(R,p,'Release/sponsor/distribution scope inspected; v1→v2 semantic deltas read at both full canonical bodies and changelog. Plugin manifests contain display/version metadata only, not independent host workflow.',excluded='Repo-specific release or distribution/sponsorship metadata; canonical methods separately analyzed.')
 else:raise AssertionError(p)
finish_repo(R,['prompt','context','workflow','tools','evaluation','output','safety','skill-authoring'],['All13 skill bodies and their material variants read in full, including long image-generation procedures, code skeletons/appendices and all research text. Supporting source and three rendered examples inspected; branding assets excluded after content-role inspection.','MIT locally scoped. Stars, sponsor/model/pricing claims, subjective luxury quality and statistical laziness efficacy do not establish method quality.','Source flaws: mock RNG called true execution, invented dates/organic metrics, source-unsupported causal/efficacy statistics, contradictory hard style bans, unbounded image/refinement loops and capability descriptions mistaken for execution.','v2 explicitly adds factual/mock number disclosure, contextual constraints and reduced motion relative to v1. No purported block implementation files exist, only schema.'])
save();print(repo['summary'])
