from pathlib import Path
N={'__name__':'core_helpers'};exec(Path(__file__).with_name('core-update.py').read_text(encoding='utf-8'),N)
globals().update({k:v for k,v in N.items() if k not in ['__name__','__file__']})
R='addyosmani/agent-skills'
def case(key,en,zh,cat,p,a,b,d,m,s,bad,good,e,lim,zd,zm,zs,zb,zg,ze,zlim,ids=None):
 return add('addy-'+key,en,zh,cat,[(R,p,a,b,en)],[d,s,m,bad,good,'The procedure preserves the stated identity or evidence boundary instead of allowing a plausible shortcut to stand in for it.',e,lim],[zd,zs,zm,zb,zg,'流程保留明确的身份或证据边界，不让貌似合理的捷径代替它。',ze,zlim],ids=ids or [])
P='skills/api-and-interface-design/SKILL.md'
case('intent-stable-key','Intent-stable retry identity','意图稳定的重试身份','workflow',P,158,171,
 'Identify one intended action independently from its delivery attempts.','Generate an identity once at the initiating intent and reuse it across retries; distinct intents get distinct identities.','Retry an asset-upload job after a timeout.','Create a new UUID on every retry.','Assign the upload intent its key once, retain that key in the task ledger and reuse it on all attempts; a new upload receives a new key.','Retries can be recognized without collapsing distinct actions.','The receiver must honor the identity; a header alone does not make side effects idempotent.','将一次预期动作的身份与送达尝试分离。','在意图发起处生成一次身份并重试复用，不同意图不同身份。','资产上传超时后重试。','每次重试生成新UUID。','上传意图只赋一次键，保留在台账并每次复用；新上传用新键。','可识别重试而不合并不同动作。','接收方须落实身份，只有请求头不能使副作用幂等。')
case('atomic-claim-payload','Atomic claim with payload binding','原子认领与载荷绑定','orchestration',P,173,202,
 'Claim an action in one operation and bind its identity to the original payload.','Use an atomic uniqueness gate before execution; reject a reused key whose canonical payload differs, and define in-flight duplicate behavior.','Two workers receive the same publish request.','Both check not seen, publish, then record the key.','One unique claim wins before publishing; the duplicate waits or returns pending; a changed article under the same key is rejected.','Concurrent delivery does not bypass the same-intent guard.','An atomic local claim cannot prove an external effect completed; crash recovery still needs the unknown-outcome protocol.','以单操作认领动作，并将身份绑定原载荷。','执行前原子唯一门控；同键规范载荷不同则拒绝，明确运行中重复行为。','两工作者收到同一发布请求。','都先查未见，再发布后记键。','发布前唯一认领一方获胜；重复等待或返回处理中；同键不同文章拒绝。','并发送达不绕过同意图门。','本地原子认领不证明外部效果完成，崩溃仍需未知结果恢复。')
case('unknown-effect','Preserve unknown side-effect outcomes','保留未知副作用结果','safety',P,204,215,
 'A timeout is an unknown effect outcome, not evidence that the action failed.','Record intent before the external call, preserve pending/unknown state and reconcile the effect before blindly repeating it; retain identity through the longest redelivery path.','A remote issue-creation call times out.','Treat timeout as failure and create the issue again with a new key.','Keep the recorded request as unknown, check the remote request/result identity, and only retry through the same guarded intent after reconciliation.','An uncertain acknowledgment does not silently duplicate an external action.','Recovery depends on destination lookup/idempotency support; report unresolved uncertainty when it cannot be reconciled.','超时是效果未知，不是动作失败的证据。','外部调用前记意图，保留待定未知，盲重做前协调效果；身份覆盖最长重投路径。','远端建问题调用超时。','当失败处理，用新键再建问题。','已记请求留未知，查远端请求结果身份，协调后仅经同一门控意图重试。','不确定确认不暗中复制外部动作。','恢复依赖目的地查询或幂等支持，无法协调须报告未定。')
case('question-to-signal','Question-to-signal observability','问题到信号的可观测性','tools','skills/observability-and-instrumentation/SKILL.md',27,54,
 'Choose instrumentation from the questions an operator must answer.','Name diagnostic questions first, then map each to an event, aggregate or path trace; omit signals with no declared use.','Instrument a background import workflow.','Dump every payload and add counters without a question.','Ask which imports fail, where time is spent and whether retries duplicate work; emit bounded status events, duration metrics and linked run traces.','Each signal has a concrete decision or investigation it supports.','The source logs/metrics/traces mnemonic is a heuristic; verify that actual data answers the question.','按操作人必须回答的问题选择仪表。','先命名诊断问题，再映事件、聚合或路径轨迹，无用途信号省略。','给后台导入流程加观测。','倾倒所有载荷，随意加计数。','问哪些失败、耗时在哪、重试是否重复；输出有界状态事件、时长指标和关联轨迹。','每信号支持具体决策或调查。','日志指标轨迹口诀是启发式，须验证真实数据能答问题。')
case('verify-instrumentation','Verify the evidence channel itself','验证证据通道自身','evaluation','skills/observability-and-instrumentation/SKILL.md',190,197,
 'Check the telemetry path by generating a known signal and finding it through the intended channel.','Use an authorized isolated test to induce an error/event, trace its identifier and verify structured fields, labels, propagation and alert delivery.','Add monitoring for an import failure.','Declare monitoring ready because the logging code exists.','Induce one test import failure, find its run ID in the aggregator, follow its trace and verify the test alert points to the right runbook.','Instrumentation availability is distinguished from a working evidence path.','Induced failures and notifications must stay within authorized test scope; this audit did not fire any alerts.','生成已知信号并从预期通道找回，以核对遥测路径。','在已授权隔离测试诱发错误事件，追身份并核结构字段标签传播与报警送达。','添加导入失败监控。','有日志代码就称监控就绪。','诱发一次测试失败，在聚合器找运行ID、追轨迹，并核测试报警指向正确手册。','区分仪表存在与证据路径工作。','诱错与通知须限授权测试，本审计未触发任何报警。')
case('mode-evidence-provenance','Preserve measurement source kinds','保留测量来源类型','output','agents/web-performance-auditor.md',12,53,
 'Separate static potential-impact findings from lab, field and trace measurements.','Select mode from available artifacts, label every populated value with its source kind, and leave unmeasured fields explicitly unmeasured.','Audit a web page from source and a Lighthouse report.','Invent a real-user p75 from a static scan or relabel the lab result as field data.','Mark static findings potential impact; show the report value as Lab with its conditions, and keep Field p75 not measured.','Numbers retain the meaning and limitations of their source.','A source label does not validate the artifact or make different populations/runs comparable.','区分静态潜在影响与实验室、真实用户、轨迹测量。','按可用产物选模式，各值标来源类型，未测字段明确未测。','凭源码和Lighthouse报告审网页。','静态扫描编真实用户p75，或把实验室结果改称用户数据。','静态发现标潜在影响，报告值标实验室及条件，用户p75留未测。','数字保留来源含义边界。','来源标签不验证产物，也不使不同群体运行可比。')
case('leaf-orchestration','Separate workflow, perspective and entry point','分离流程、视角与入口','orchestration','docs/agents.md',16,52,
 'Keep domain work in leaf roles and orchestration at the entry point that owns the decision.','Distinguish reusable process, reviewer perspective and user-facing command; choose direct invocation for one lens and flat fan-out plus main merge for independent lenses.','Review a release for code and security concerns.','Add coordinator personas that delegate through several paraphrasing layers.','Have the release entry point dispatch two independent leaf reports and reconcile them directly against the release contract.','Routing depth and decision ownership are explicit.','Flat independent reports fit known-artifact verdicts; shared hypothesis investigation may require interaction instead.','领域工作留叶角色，编排由拥有决策的入口承担。','区别可复用流程、评审视角、面向用户命令；单视角直调，多独立视角扁平分发主合并。','评审发布的代码与安全。','多层协调人格经反复转述再委派。','发布入口分发两个独立叶报告，并直接按发布契约协调。','路由深度与决策归属明确。','扁平独立报告适于已知产物判断，假设调查可能需交互。')
case('hypothesis-versus-verdict','Choose interaction by investigation shape','按调查形状选择交互','orchestration','references/orchestration-patterns.md',176,216,
 'Choose independent reports for a known artifact and interacting investigators for competing causal hypotheses.','Ask whether the artifact is known or must be found; preserve independent judgments for verdicts, and require falsifiable evidence exchange before investigative convergence.','Investigate an intermittent queue stall.','Run three isolated reviewers and count which theory receives two votes.','Assign distinct stall hypotheses, let investigators exchange discriminating observations, and verify the surviving prediction with a focused replay before convergence.','Consensus is tied to disproof evidence rather than opinion count.','Messaging or two-agent agreement alone does not establish a root cause; source host restrictions and efficacy claims are unverified.','已知产物用独立报告，竞争因果假设用交互调查。','先问产物已知还是待找；判断保留独立性，调查收敛前交换可证伪证据。','调查间歇队列停顿。','三个隔离评审，哪个理论两票就定。','分配不同停顿假设，交换区分性观察，收敛前以聚焦回放验证存活预测。','共识联系反证，不是意见计票。','互发消息或两人同意不证明根因，宿主限制效能声明未验证。')
case('task-and-standing-bar','Task acceptance and standing readiness','任务验收与常设就绪门','evaluation','references/definition-of-done.md',3,15,
 'Require the requested behavior and the standing project readiness bar separately.','Keep per-task acceptance distinct from reusable quality/integration/operational gates and check both before completion.','Add an export button to a production page.','Declare done because the button downloads one file.','Confirm the requested export behavior, then check the accepted project bar for errors, accessibility, integration and required release evidence.','A happy-path feature result does not conceal unmet readiness conditions.','Tailor the standing bar to the actual project and authorized scope; this is different from #193 checkable-plus-exhaustive criteria.','分别要求所需行为与项目常设就绪门。','每任务验收与可复用质量集成运维门分开，完成前两者都核。','给生产页加导出按钮。','按钮下载一次文件就宣称完成。','先确认导出所需行为，再核已接受项目门中的错误、可访问、集成、发布证据。','功能快乐路径不掩盖未满足就绪条件。','常设门按实际项目授权范围定，此不同于193可检查且穷尽。')
case('one-router','One active routing authority','一个有效路由权威','context','docs/getting-started.md',43,49,
 'Avoid stacking a full meta-router on top of a host that already selects the same skills natively.','Detect the actual host discovery capability and choose one active routing authority; keep reusable skills available on demand.','Configure a host with native skill discovery.','Preload two full lifecycle routers and let both dispatch the task.','Use the native router with the installed skill descriptions; load the meta-router only where the host lacks that capability.','The same task does not receive competing dispatch protocols.','Verify effective runtime discovery; installation or metadata alone is not proof that native routing works.','避免原生已选相同技能时再常驻完整元路由。','检测真实发现能力，只选一个有效路由权威，技能按需可用。','配置有原生技能发现的宿主。','常驻两个全生命周期路由让二者都分发。','使用原生路由和已装描述；仅宿主无该能力时载元路由。','同任务不承受竞争分发协议。','须验证有效运行发现，安装或元数据不证明原生路由工作。')
case('capability-verbs','Capability verbs over private tool workarounds','能力动词替代私有工具补丁','skill-authoring','docs/skill-anatomy.md',159,170,
 'Express a reusable procedure through required capabilities instead of one model private tool spelling.','State the observable action and evidence, and isolate exact runtime tool mappings in adapters.','Write a portable test workflow.','Call run_command with the exact serialization one model needed last week.','Run the repository focused-test command and retain the red output; let the host adapter select its execution tool.','The procedure retains its goal across different tool surfaces.','Fragile operations may need precise instructions; model-neutral wording is not permission to omit load-bearing constraints.','可复用流程写所需能力，不依赖单模型私有工具拼写。','说明可见动作证据，具体运行映射隔离到适配器。','编可移植测试流程。','按上周某模型补丁，固定run_command序列化。','运行仓库聚焦测试命令并保留失败输出；宿主适配器选执行工具。','流程在不同工具表面保留目标。','脆弱操作仍可能需精准步骤，中立措辞不可省关键约束。',ids=[171])
case('installed-reference-closure','Reference closure in the received artifact','接收产物中的参考闭包','context','docs/skill-anatomy.md',113,124,
 'Verify referenced material in the receiver installed layout rather than only the author repository.','List mandatory references and resolve them from the containing artifact under the shipped/handed-off layout; package or remap missing dependencies.','Hand one skill directory to another agent.','Copy the body while leaving its ../../references targets only in the author checkout.','Include the required references inside the handed-off package and validate their relative links from the received skill before use.','A context pointer remains reachable where the work actually runs.','Existing-file checks do not prove licensing, contents or current semantics; optional references need explicit fallback.','在接收安装布局核参考，而不只作者仓库。','清点必需参考，从所在产物在交付布局解析；缺依赖则打包或改映射。','把一个技能目录交给另一代理。','只复制正文，../../references仍在作者签出。','交付包包含所需参考，使用前从接收技能核相对链接。','上下文指针在实际工作处仍可达。','存在检查不证明许可内容或当前语义，可选参考须明确回退。')
case('consumer-parser-validation','Validate the consumer interpretation','验证消费者解释','evaluation','scripts/lib/skill-lint.js',196,227,
 'A local lenient reader passing is not proof that the real consumer accepts the same artifact.','Test the serialized artifact against the consumer grammar or a strict reference parser; retain accepted/rejected controls and explicit unsupported boundaries.','Publish skill frontmatter containing a colon-space description.','Accept it because a local split-on-first-colon helper reads a string.','Validate the full frontmatter with the target grammar; quote the scalar and test valid and invalid neighbors rather than trusting the helper parse.','Producer validation matches the receiver parsing requirement.','The observed checker implements only a narrow set of failure shapes, not full YAML conformance or all host behavior.','本地宽松读取通过不证明真实消费者接受同产物。','按消费者语法或严格参考解析器验序列化产物，保留合法非法对照及未支持边界。','发布描述含冒号空格的前言。','本地首冒号切分读出字符串就通过。','按目标语法验完整前言，给标量加引号，并测合法非法邻例，不仅信助手解析。','生产端验证吻合接收端要求。','观察检查器仅实现窄失败形状，不是完整YAML或所有宿主一致。')
case('exemption-authority','Exemption authority outside the constrained unit','豁免权在受约束单元之外','safety','scripts/lib/skill-lint.js',83,90,
 'A unit under validation cannot grant itself an exemption from that validation.','Keep reviewed exemption policy outside the unit, require an owned reason and use exact own-membership checks rather than inherited object keys.','Validate required sections of a submitted skill.','Let the skill declare exempt: sections or qualify through a constructor prototype key.','Consult the validator-owned reviewed exemption list; reject a self-declared exemption and require a documented policy change for a real exception.','The input cannot silently authorize its own bypass.','The policy repository must itself be review-protected; moving a list alone is not an authorization boundary.','被验证单元不能给自身验证豁免。','经审豁免政策在单元外，须负责人理由，用确切自有成员而非继承对象键。','验证提交技能的必需章节。','让技能自写exempt，或constructor原型键获得豁免。','查验证器持有的经审豁免表，自述豁免拒绝，真实例外须有记录政策变更。','输入不暗中授权自身绕过。','政策仓库本身须保护评审，移个表不构成授权边界。')
case('derived-path-ownership','Resolve confinement and ownership before destruction','破坏动作前解析范围与所有权','safety','references/security-checklist.md',65,102,
 'A well-formed derived path is a candidate target, not permission to delete it.','Resolve symlinks, require a strict descendant of an allowed root and prior authenticated ownership evidence; refuse without broader fallback and address check/use races.','Clean up a job directory named in a process argument.','Trust the OS-delivered path shape and delete it or fall back to the parent root.','Resolve the candidate under the job root, verify it is below that root and owned by the authorized job, then operate under an immutable hierarchy or safe descriptor.','Misderived or attacker-written target data does not enlarge cleanup scope.','A writable marker is self-attestation; protect its integrity and bind expected owner to authenticated state.','格式正确派生路径只是目标候选，不是删除许可。','解符号链接，要求允许根的严格后代与事先认证所有权，拒绝且不扩大回退，并处理检查使用竞争。','清理由进程参数命名的工作目录。','信OS传来路径形状并删除，或回退父根。','在工作根下解析，核严格下层与授权工作所有权，再在不变层级或安全描述符操作。','派生错误或攻击者写目标不扩大清理范围。','可写标记只是自述，须保护完整性并绑定认证期望身份。')
case('install-before-execution-gate','Review installation scripts before first execution','首次执行前审安装脚本','tools','references/security-checklist.md',144,167,
 'Inspect dependency execution at the actual installation boundary before running an ordinary install.','Corroborate workspace manager/lockfile/CI, bootstrap with scripts disabled, review exact versioned scripts and record only required approvals before frozen verification.','Initialize an unfamiliar workspace for an audit.','Run the default install to discover which lifecycle scripts exist.','Identify the workspace lockfile and pinned manager; install with scripts disabled, inspect pending scripts, approve narrowly and verify the resulting frozen install policy.','Unreviewed dependency code is not executed as discovery.','Native flags/defaults are version-sensitive; this corpus matrix is a snapshot, not current verified command advice.','在真实安装边界、普通安装前检查依赖执行。','核工作区管理器锁文件CI，禁脚本引导，审确切版本脚本，只记录必要批准再冻结验证。','为审计初始化陌生工作区。','默认安装后再发现有哪些生命周期脚本。','确定工作区锁与管理器固定版本，禁脚本安装，审待执行脚本、窄授权并核冻结政策。','不以执行未经审依赖代码来发现它。','原生标志默认随版本变化，该矩阵是快照，非当前核实命令建议。')
case('abuse-case-neighbor','Abuse cases beside intended use cases','滥用例与预期用例并列','evaluation','skills/security-and-hardening/SKILL.md',25,43,
 'Derive negative scenarios from each trust boundary before selecting controls.','Name writer, asset and boundary; ask how the intended action can be misused and turn that into a testable failure scenario.','Design an import-from-URL workflow.','Validate only a successful public HTTPS import.','Alongside success, test a redirect toward an internal address, oversized content and a caller lacking import rights; choose controls for those declared abuses.','Controls are justified by named misuse paths rather than a generic checklist alone.','These are scoped test scenarios, not permission to probe arbitrary live systems.','每信任边界先导负场景再选控制。','说明写者资产边界，问预期动作如何被滥用，再变成可测失败场景。','设计URL导入流程。','只验成功公网HTTPS导入。','成功旁测向内网重定向、超大内容、调用者无导入权；为这些滥用选控制。','控制有命名滥用途径依据，不仅通用清单。','这些为范围内测试例，不授权探任意真实系统。')
case('assumption-priority','Validate kill assumptions before secondary preferences','先验证致命假设再看次要偏好','workflow','skills/idea-refine/refinement-criteria.md',75,94,
 'Classify assumptions by what their failure would do to the proposed direction.','Validate dealbreakers before implementation, important adjustable bets next and secondary optimizations after the core is supported.','Plan a tool importing partner data.','Spend the first experiment choosing button colors while assuming the partner will supply a usable feed.','First test whether the partner can and will provide the required feed; next test the update model; defer cosmetic preferences until that core assumption holds.','The first experiment can falsify the direction before costly construction.','Assumption importance depends on the actual goal; source market hierarchies and numeric heuristics are not measured efficacy.','按失败对方向的影响给假设分级。','实施前验致命点，再验可调重要赌注，核心有支持后才次要优化。','规划导入伙伴数据的工具。','首实验选按钮色，默认伙伴能给可用数据。','先验伙伴能否且愿否提供所需数据，再验更新模型，核心成立后再看外观偏好。','首实验可在昂贵构建前否证方向。','重要度依实际目标，市场层级和数字启发式非实测效能。')
case('opaque-projection','Protected content through an editable projection','通过可编辑投影保护内容','context','hooks/SIMPLIFY-IGNORE.md',42,62,
 'Keep protected content in an authoritative store while the editing view contains explicit opaque references.','Preserve original bytes and identity, edit only the intended projection, then reconstruct and verify protected content and changed surroundings before applying.','Refactor a file containing a fixed vendor block.','Show all bytes with a vague do-not-edit warning, or compile a working file after replacing its logic with comments.','Use a separate editing view with stable vendor-block sentinel, retain the original, reconstruct the patch and verify the protected block digest before applying it.','The edit contract can check both intended changes and preservation.','The observed hook modifies working files in place and uses short/fuzzy IDs; that implementation is not a security boundary or guaranteed collision-free recovery.','权威库保留受保护内容，编辑视图含明确不透明引用。','保留原字节身份，仅编辑指定投影，应用前重建并验受护内容与周边变化。','重构含固定供应商块的文件。','给全文加含糊禁改提醒，或把工作文件逻辑替成注释后编译。','单独编辑视图用稳定供应商块哨兵，保留原文，重建补丁并验块摘要后应用。','编辑契约可同时检查预期变更与保留。','观察钩子原地改工作文件且短模糊ID，不是安全边界或无碰撞恢复保证。')

# Existing canonical mechanisms receive additional observed sources instead of duplicate entries.
for key,p,a,b,section in [
 ('core-actor-provenance-before-intent','skills/observability-and-instrumentation/SKILL.md',91,110,'entry-point identity versus correlation'),
 ('core-superpowers-progressive-reference-context','skills/security-and-hardening/SKILL.md',81,89,'load only the applicable hardening section'),
 ('core-independent-mutation-sensitive-oracle','skills/code-review-and-quality/SKILL.md',176,194,'deliberate temporary mutation to test the oracle'),
 ('core-independent-mutation-sensitive-oracle','evals/cases/test-driven-development.json',30,42,'independent earliest-share fairness oracle'),
 ('core-plan-owned-resumption-ledger','docs/getting-started.md',176,191,'restart only recorded complete task boundaries')]:
 c=next(x for x in DATA['candidates'] if x['key']==key)
 s=src(R,p,a,b,section)
 if not any(x['repo']==R and x['path']==p and x['line_start']==a for x in c['sources']):c['sources'].append(s)

rr=next(r for r in DATA['repositories'] if r['repo']==R)
for f in rr['coverage']:
 f['candidate_keys']=sorted(set(f.get('candidate_keys',[])+[c['key'] for c in DATA['candidates'] if any(s['repo']==R and s['path']==f['path'] for s in c['sources'])]))
finish_repo(R,['prompt','context','workflow','orchestration','tools','evaluation','output','safety','skill-authoring'],[
 'All 208 tracked paths closed: all 25 bodies, every shared/local reference and example, all personas/adapters, current hooks and validators, full tests/fixtures/plugin graders were semantically read. Only five equal-hash command mirrors were deduplicated; all four modified mirrors had full deltas reviewed.',
 'MIT applies locally. Source scripts, CLI installs, behavioral models, attacks and alert sends were never executed; all examples are independent teaching constructions and efficacy is editorial review only.',
 'Keep semantic variants: five-axis leverage ranking and deliberate reviewer mutation differ from Matt orthogonal axes and Superpowers no-retest reviewers; dialogue, static potential impact, lab, field and trace are distinct evidence kinds.',
 'Source limits include HEAD-after-derived-body cache races and question relevance; unsafe reset/secret-print examples; incomplete error-boundary snippets; contradictory wrapper paths/severity/role scope; short-hash/in-place/fuzzy projection and cross-session risks; narrow parser/validator guarantees; fixed timing, market, host/API, legal and model-effect claims unverified.'
])
save();print('Addy closed;',len(DATA['candidates']),'candidates')
