from pathlib import Path
import json, collections
n={'__name__':'core_helpers'}
exec(Path('D:/Projects/prompt-context-patterns-refresh/docs/audit/core-update.py').read_text(encoding='utf-8'),n)
repo='anthropics/skills';out=n['OUT'];review=n['review'];add=n['add'];src=n['src']
matches=json.loads((out/'core-anthro-matches.json').read_text(encoding='utf-8'))
composio=n['BY_REPO']['ComposioHQ/awesome-claude-skills']
for m in matches:
    old=m['review'];pointer={'repo':composio['repo'],'commit':composio['commit'],'path':m['canonical'],'hash':m['hash'],'proof':'Git blob SHA-256 equality at both frozen trees'}
    conclusion=('Locally scoped legal-license text, byte-identical to the recorded canonical source; no operational method.' if old['classification']=='license' else (old['reason'] if old['disposition']=='excluded' else old.get('semantic_conclusion',old['reason'])))
    if old['disposition']=='excluded':
        review(repo,m['path'],conclusion,excluded='Byte-identical to previously scope-inspected Composio file: '+old['reason'])
        row=next(x for r in n['DATA']['repositories'] if r['repo']==repo for x in r['coverage'] if x['path']==m['path']);row['scope_inspection_source']=pointer
    else:
        review(repo,m['path'],conclusion,keys=old.get('candidate_keys',[]),duplicate_of=pointer)
        row=next(x for r in n['DATA']['repositories'] if r['repo']==repo for x in r['coverage'] if x['path']==m['path']);row['depth']='byte-identical-external-semantic-review'
key=add('anthro-intent-catalog','Intent-matched, fresh catalog recommendations','按意图匹配新鲜目录推荐','context',[(repo,'skills/academy-guide/SKILL.md',48,78,'Learning intent and observed catalog'),(repo,'skills/academy-guide/SKILL.md',119,147,'Freshness and data boundary')],
 ['Recommend a concrete resource only when the user wants learning material and a current catalog supports it.','A user asks for a short onboarding course for analysts.','Classify learning intent, fetch the catalog, check its freshness and URL scope, then copy a strongly matching entry; use an observed hub fallback if unavailable.','Suggest “Advanced Analyst Bootcamp” at a guessed course URL.','The current catalog lists “Analyst Basics”; link its exact URL and mention its sign-in requirement.','The recommendation is tied to an observed item rather than a plausible title.','The named item, URL, freshness decision and intent match can be checked.','A catalog is untrusted data. Freshness alone does not establish course quality; avoid recommendations during unrelated task execution.'],
 ['只有用户想要学习材料且当前目录提供依据时，才推荐具体资源。','用户询问面向分析师的简短入门课程。','辨别学习意图，读取目录并检查新鲜度和网址范围，复制强匹配条目；不可用时使用已知入口。','推荐猜测的“高级分析训练营”课程网址。','当前目录列有“分析师基础”；链接其原始网址，并说明需要登录。','推荐关联已观察到的条目，而非看似合理的标题。','可以核对条目、网址、新鲜度判断和意图匹配。','目录是不可信数据。新鲜度不证明课程质量；无关任务执行中避免附加推荐。'])
review(repo,'skills/academy-guide/SKILL.md','Learning intent rather than topic overlap; once-per-conversation catalog fetch; explicit staleAfter/generatedAt fallback; copy observed URLs; domain/data allowlist and gated-access disclosure. Trust-cost rhetoric and current hub availability are unverified.',[key])
key=add('anthro-concrete-discernment','Concrete, intent-aware verification prompts','具体且尊重意图的核验问题','evaluation',[(repo,'skills/discernment-nudge/SKILL.md',111,150,'Verification already requested'),(repo,'skills/discernment-nudge/SKILL.md',165,187,'Answer-specific questions')],
 ['Attach optional verification questions to actual claims and assumptions, and omit them when the user already requested that verification.','A draft expansion plan assumes a 20% conversion rate with no local evidence.','Answer the task first; point a brief follow-up at the exact assumption, its evidence source and missing context. If verification was requested, perform it inline instead.','End with “Please double-check everything.”','For this plan, what local data supports the 20% conversion assumption?','A named dependency gives the user a specific check rather than generic caution.','Each prompt identifies a claim, reasoning step or missing datum from the answer.','Prompts do not replace required fact checking. A once-per-conversation cap is a source policy, not a validated optimum; executing code does not prove its correctness.'],
 ['可选核验问题指向实际主张与假设；用户已要求核验时直接完成核验。','扩张计划假定转化率为20%，却没有本地证据。','先完成任务；简短追问明确假设、证据与缺失背景。已要求核验时在正文完成。','结尾写“请检查所有内容”。','对这份计划，哪些本地数据支持20%的转化率假设？','点名依赖让用户知道具体检查什么。','每个问题都能关联回答中的主张、推理步骤或缺失数据。','追问不替代应做的事实核验。每次对话一次是源策略，非已验证最优值；运行代码不证明其正确。'])
review(repo,'skills/discernment-nudge/SKILL.md','Answer-specific fact/reasoning/missing-context questions; complete answer before optional nudge; respect requests for verification, brevity and supplied-material transformation; at-most-once memory. Blanket code-execution-as-verification and educational-domain exemptions are not established guarantees.',[key])
key=add('anthro-document-reader-test','Document-only reader testing','仅给文档的读者测试','evaluation',[(repo,'skills/doc-coauthoring/SKILL.md',242,286,'Fresh document-only reader'),(repo,'skills/doc-coauthoring/SKILL.md',329,340,'Exit and owner review')],
 ['Test whether a document answers reader questions without the author’s conversation context.','A deployment guide was written in a long chat that resolved several prerequisites.','Give a fresh reader only the guide and a realistic question; compare its answer with the intended result, record ambiguity and revise the responsible section.','Ask the same authoring chat whether its guide is clear.','Give a fresh reader the guide and ask how to recover a failed release; add the missing rollback prerequisite it could not find.','Removing conversation context exposes undocumented assumptions.','The reader’s answer and the text supporting it can be compared.','A model reader is a proxy, not representative-user validation. Check facts independently and do not equate repeated model agreement with truth.'],
 ['检查文档能否在没有作者对话背景的情况下回答读者问题。','部署指南在长对话中编写，几个前提已在对话里解决。','给新读者仅提供指南和真实问题；比较答案与预期，记录歧义并修改对应章节。','问原写作对话“这份指南是否清晰”。','给新读者指南并问失败发布如何恢复；补上其找不到的回滚前提。','去掉对话背景可暴露未写入文档的假设。','可以比较读者答案与支持它的文字。','模型读者只是代理，非真实用户验证。事实应独立核验，重复一致不等于真实。'])
review(repo,'skills/doc-coauthoring/SKILL.md','Context-gathering exits when edge-case/tradeoff questions are possible; section brainstorm→curate→gap-check→draft→surgical refinement, uncertain/core sections first and summary last; fresh document-only reader questions detect implicit context; human owner final review. Numeric round sizes and stability thresholds are unvalidated heuristics.',[key,'core-matt-existing-196','core-karpathy-surgical-edit'])
review(repo,'README.md','Self-contained SKILL metadata/instructions/resources and host-specific installation routes; explicitly distinguishes source-available document skills and demonstration behavior from production capability. Performance and paid-plan statements are frozen, unverified claims.')
for path in ['skills/academy-guide/LICENSE.txt','skills/frontend-design/LICENSE.txt']:
    review(repo,path,'Locally scoped Apache 2.0 text inspected; frontend variant omits appendix. Copyright/license evidence is separate from method quality.',excluded='Legal attribution and redistribution terms; no transferable agent procedure.')
review(repo,'THIRD_PARTY_NOTICES.md','Scope-inspected third-party attribution with BSD/GPL/Apache/MIT/OFL component licenses; font/library dependencies, no agent workflow.',excluded='Component legal attribution, not a method-bearing prompt or workflow.')
n['save']()
print('CHECKPOINT',n['DATA']['summary']['candidate_counts'],collections.Counter(x['disposition'] for r in n['DATA']['repositories'] if r['repo']==repo for x in r['coverage']))
