from pathlib import Path
exec(Path(__file__).with_name('core-matt-candidates.py').read_text(encoding='utf-8'),globals())

case('counterexample-guardrail','Guardrail negative-control proof','护栏反例证明','evaluation','skills/in-progress/setup-ts-deep-modules/SKILL.md',79,87,
 'Verify a guardrail rejects an intentional violation, then returns to clean success.','Observe pass on allowed input, fail on a temporary forbidden input, and pass after removal.','Install an import-boundary rule.','Check that the configuration file exists.','Run the clean package, inject a forbidden deep import and observe the named error, remove it and observe success.','The installed rule is demonstrably wired to the actual command.','One counterexample does not establish complete bypass resistance.','验证护栏会拒绝故意违规，并回到干净成功。','允许输入通过，临时禁止输入失败，移除后再通过。','安装导入边界规则。','检查配置文件存在。','跑干净包，注入深导入并看到指定错误，移除后再看通过。','已证明规则接入实际命令。','单个反例不证明完全防绕过。')
case('stateful-write-reread','Reread shared artifacts before incremental writes','增量写入前重读共享产物','workflow','skills/in-progress/writing-shape/SKILL.md',69,77,
 'Preserve intervening human edits while materializing agreed work incrementally.','Read current disk contents before each append or targeted rewrite; keep the input corpus separate.','Coauthor an article while the author edits it.','Keep a cached copy and rewrite the entire article after each paragraph.','Reread the article, append only the agreed paragraph, and apply a requested rewrite to that paragraph without replacing the rest.','The author edits survive subsequent agent writes.','Rereading is not an atomic concurrency lock; simultaneous writes need stronger coordination.','增量落地共识时保留人类中间修改。','每次追加或定向改写先重读磁盘；原材料单独保存。','作者编辑期间共同写文章。','缓存全文，每段后重写整个文件。','重读文章，只追加已同意段落；指定重写仅改该段，不覆盖其余。','后续代理写入保留作者修改。','重读不是原子并发锁；同时写入需要更强协调。')
case('evidence-learning-memory','Evidence-gated learning memory','证据门控学习记忆','context','skills/productivity/teach/LEARNING-RECORD-FORMAT.md',29,46,
 'Store demonstrated knowledge separately from material merely covered.','Record demonstrated use, explicit prior-knowledge depth or corrected misconceptions; supersede contrary records instead of erasing history.','Choose the next lesson after explaining transaction isolation.','Mark isolation mastered because the lesson was displayed.','Record which anomaly the learner correctly predicts; note the untested cases; supersede that record if later answers show a misconception.','Lesson selection can inspect evidence and its limits.','Self-reported prior knowledge is a claim with stated depth, not a demonstrated assessment.','将已证明知识与仅已讲过材料分开存储。','记实际运用、明确先验深度或纠正误解；相反记录以取代标记保留历史。','解释事务隔离后选下节课。','展示课程后即记为掌握隔离。','记录学员正确预测的异常及未测情况；后续显示误解则取代此记录。','课程选择可检查证据及其边界。','自述知识是有深度说明的声明，不是已证明测评。')
case('question-owner-gap','Question the knowledge owner through a send brief','通过发送简报询问知识持有者','workflow','skills/productivity/to-questionnaire/SKILL.md',7,20,
 'Ask the requester who holds missing knowledge and what decision needs it, then target the actual owner.','Interview recipient/context and required return, map every required fact to one fillable question ordered by decision importance.','Resolve a partner retention policy unknown to the developer.','Grill the developer until they guess the partner policy.','Ask who owns partner policy and which retention decision is blocked; draft focused questions for that person with uncertainty explicitly allowed.','The missing facts are routed to a person able to supply them.','One recipient may not own all answers; split by actual knowledge ownership.','先问请求者缺失知识归谁及支持何决策，再面向真正持有者。','询问接收人背景和所需答复，每个所需事实映射成一个可填问题并按决策重要度排序。','解决开发者不知的伙伴保留政策。','反复盘问开发者直到猜出伙伴政策。','询问政策归属及受阻决策；为该人写聚焦问题，明确可答未知。','缺失事实被送到能够提供的人。','单个接收人未必掌握全部，按知识归属拆分。')
case('branch-trigger-pointer','Branch-complete context pointers','覆盖分支的上下文指针','skill-authoring','skills/productivity/writing-for-agents/SKILL.md',10,18,
 'A context pointer names both its target and the distinct conditions that need it.','Write one trigger per branch and front-load its recognizable concept; deduplicate synonyms rather than distinct cases.','Route cancellation requests to a refund reference.','See refunds.md when relevant.','For full cancellation or partial return, consult refunds.md before calculating the refund; keep order lookup in its own branch.','Each declared refund branch has an explicit reference path.','Trigger wording must be tested in the real host; descriptions do not guarantee loading.','上下文指针同时说明目标和需要它的不同条件。','每分支一个触发条件，前置易认概念；去掉同义重述而非不同情形。','把取消请求路由到退款参考。','相关时看refunds.md。','完整取消或部分退货时，计算退款前查refunds.md；订单查询另成分支。','每个退款分支有明确参考路径。','须在真实宿主测试触发措辞；描述不保证载入。',id=100)
case('reference-colocation','Co-locate concept rules and caveats','同处组织概念规则与边界','context','skills/productivity/writing-for-agents/SKILL.md',29,43,
 'Keep one concept definition, decision rules and exceptions together after selecting its disclosure tier.','Separate ordered steps from reference, disclose branch-specific reference, and group each concept under one heading.','Write a retry-policy runbook.','Put the definition at the top, exceptions in setup notes and the decision table at the bottom.','Keep retryable definition, eligibility table and non-idempotent exception in one retry-policy reference linked at the retry decision.','Reading the decision rule also reveals its exception.','Co-location is not duplication; shared authoritative reference can still live in another file.','选择披露层级后把概念定义、规则和例外放在一起。','区分步骤与参考，分支参考按需披露，每概念同一标题组织。','编写重试操作手册。','定义放开头，例外放设置备注，决策表放末尾。','重试定义、资格表和非幂等例外同处参考，在重试决策处链接。','读决策规则也能看到例外。','同处不等于重复；共享权威参考仍可在别文件。')
case('environment-truth','Environment as instruction source of truth','环境作为指令事实源','skill-authoring','skills/productivity/writing-for-agents/SKILL.md',76,81,
 'Avoid maintaining a stale prose cache of cheap executable environment facts.','Reference inspectable config/help for scripts and paths; document only unwritten conventions or expensive lookups.','Document a project check command.','Copy the package scripts into several agent instruction files.','Tell the agent to read the check script in package.json; document separately why the integration fixture is required.','Changing the script needs one authoritative edit.','Cache a lookup when its cost is material, but identify its freshness obligation.','避免以文字维护便宜可查环境事实的陈旧缓存。','脚本路径查配置或帮助，只记录隐含约定或昂贵查询。','记录项目检查命令。','把包脚本复制到多个代理指令文件。','指向package.json中的检查脚本，另记集成夹具为何必需。','改脚本只需一处权威编辑。','查询昂贵可缓存，但须标明新鲜度责任。')
case('substitution-calibration','Dependency-calibrated verification adapters','按依赖性质校准验证适配器','tools','skills/engineering/codebase-design/DEEPENING.md',5,37,
 'Choose verification substitutes according to the dependency controlled by the module.','Distinguish in-process, local-substitutable, remote-owned and true external dependencies before choosing real stand-ins, ports or mocks.','Test an order module with database and third-party payments.','Mock every internal function to make tests fast.','Use a local database stand-in through the module interface; inject only the external payment port and verify observed outcomes.','The tested boundary reflects ownership and real failure surfaces.','A stand-in may differ from production; contract/integration checks remain necessary.','按模块控制的依赖选择验证替身。','先区别进程内、本地可替代、远端自有和真正外部，再选真实替身、端口或模拟。','测试有数据库和第三方付款的订单模块。','为速度模拟全部内部函数。','通过模块接口使用本地数据库替身；仅注入外部支付端口，并验证可见结果。','测试边界反映所有权与真实故障表面。','替身可异于生产，仍需契约或集成检查。')
case('deletion-probe','Deletion probe before abstraction','抽象前删除探针','prompt','skills/engineering/codebase-design/SKILL.md',77,100,
 'Challenge an abstraction by predicting where complexity would go if it vanished.','Trace caller obligations after hypothetical deletion; retain hidden reusable behavior and collapse pure pass-through layers.','Decide whether to keep a one-method parser wrapper.','Keep it because extra layers are cleaner.','Compare callers with and without the wrapper; collapse it if nothing is hidden, retain it if each caller would duplicate validation and ordering rules.','The recommendation cites an actual responsibility rather than layer count.','Hypothetical deletion is a reasoning aid; dependencies and compatibility still constrain actual removal.','预测抽象消失后复杂度去向以检验抽象。','追踪假想删除后的调用责任；保留隐藏的可复用行为，合并纯转发层。','决定是否保留单方法解析包装。','更多层更整洁，所以保留。','比较有无包装的调用者；无隐藏责任则合并；调用者需重复校验和排序则保留。','建议引用实际责任而非层数。','假想删除是推理工具；实际删除仍受依赖兼容约束。')
case('expand-contract-tickets','Compatibility-preserving migration tickets','保兼容迁移票据','workflow','skills/engineering/to-tickets/SKILL.md',29,40,
 'Use expand/migrate/contract stages when a broad mechanical change cannot land in independent vertical slices.','Introduce both forms, migrate callers in bounded batches, and remove the old form only after all callers migrate.','Rename a shared configuration field across packages.','Rename the field once and let every package ticket fail until integration.','Add new field alongside old, migrate each package while both work, then remove the old field after a caller inventory reaches zero.','Each staged batch has an explicit compatibility condition.','If batches cannot pass alone, use a declared integration-only verification gate.','广泛机械变化无法独立垂直落地时采用扩展迁移收缩。','新旧形式并存，分批迁移调用者，全部迁完才删旧形式。','跨包改共享配置字段名。','先统一改名，让每包票据一直失败到集成。','新旧字段并存，各包在两者可用时迁移，调用者清点归零后删除旧字段。','每批有明确兼容条件。','批次无法独立通过时明确仅集成验证的门槛。')
case('ui-comparison-context','Compare structural variants in shared context','共享现场比较结构变体','evaluation','skills/engineering/prototype/UI.md',14,30,
 'Compare design alternatives inside the real host context and hold data constant.','Vary structure through a shareable selector on one route while retaining host navigation, density and read-only data.','Choose a settings-page layout.','Show three empty screens with different colors.','Render different navigation and hierarchy variants on the populated settings route using the same data, and share each variant URL.','Differences can be attributed to structure within the actual surrounding page.','Real mutations need stubs; a prototype is not production-quality implementation.','在真实承载现场比较设计，固定数据。','同一路由通过可分享选择器变结构，保留导航、密度和只读数据。','选择设置页布局。','展示三个只换颜色的空页面。','在有数据的设置路由呈现不同导航层级，用同样数据并分享变体链接。','差异可归因于实际周边中的结构。','真实修改须用桩；原型不等于生产实现。')
case('fixture-intent','Explicit partial and invalid fixture intent','明确部分与非法夹具意图','evaluation','skills/misc/migrate-to-shoehorn/SKILL.md',65,103,
 'Distinguish incomplete valid fixtures from intentionally invalid input.','Use explicit fixture constructors for partial, invalid and exact shapes instead of erasing all types with the same cast.','Test request validation and a body-only handler.','Use as unknown as Request in every fixture.','Label body-only data as partial; label the numeric-id rejection case as intentionally invalid; use exact shape when completeness is what the test asserts.','The fixture communicates which constraint is deliberately relaxed.','Specific helper API behavior needs version verification; this method concerns test intent, not production type safety.','区分不完整有效夹具与刻意非法输入。','部分、非法和完整形状分别用明确构造器，不统一强制擦除类型。','测试请求校验和只读body的处理器。','全部夹具用as unknown as Request。','只含body标部分；数字id拒绝例标刻意非法；完整性是断言目标时用完整形状。','夹具说明刻意放宽的约束。','具体助手API须核版本；方法关乎测试意图而非生产类型安全。')
case('repitch-premise','Repair the missing premise before shortening','缩短前修补缺失前提','output','docs/productivity/wait-what.md',13,32,
 'Treat comprehension failure as a missing-context problem before optimizing word count.','Restate the decision in shared nouns and supply the premise the reader lacks, then trim redundancy.','Explain why a ticket must wait.','Blocked by dependency.','The exporter reads the new schema. That schema is not landed, so starting export now would build against the old format.','The reader can explain the dependency rather than receiving only a shorter label.','Clarity is audience-dependent; ask which premise remains unclear.','先把理解失败视为背景缺失，再优化字数。','用共享名词重述决定，补读者缺失前提，再删冗余。','解释票据为何要等。','被依赖阻塞。','导出器读取新模式；模式未落地，现在开始会按旧格式构建。','读者可解释依赖，不仅得到更短标签。','清楚程度依赖读者，仍需确认哪项前提不明。')
case('pr-consequence-brief','Consequence-aware change evidence','考虑后果的变更证据','output','skills/engineering/pr/SKILL.md',158,170,
 'Review a change through observed behavior plus reversibility of its real-world consequences.','Show before/after evidence, name one-way effects and identify affected callers or users.','Describe a bulk-email rollout.','Tests green; rollback is one commit.','Show the dry-run before/after count; state emails cannot be unsent and list the recipient scope plus rollout guard.','The review distinguishes code rollback from irreversible external effects.','An author risk classification is a claim for review, not independent proof.','以行为证据及现实后果可逆性评审变更。','展示前后证据，列不可逆影响及受影响调用者用户。','描述批量邮件上线。','测试通过；回滚一个提交即可。','展示演练前后数量；指出邮件不能撤回，并列收件范围及上线门槛。','评审区分代码回滚与不可逆外部影响。','作者的风险分类是待评审声明，不是独立证明。')
case('observations-not-secrets','Capture observations, keep credentials local','捕获观察、凭据留本地','safety','skills/engineering/diagnosing-bugs/SKILL.md',12,16,
 'Separate diagnostic signal from credentials before showing captured material.','Use environment variables for secrets, redact outputs first and capture only observations in the human loop.','Reproduce an authenticated export error.','Paste the full curl command, auth header and HAR into the brief.','Reference the token via environment variable; show redacted status and the signal-bearing error lines; let the human sign in without captured credentials.','The report retains the symptom while omitting the credential.','Redaction can remove required signal; explicitly request safe additional evidence when needed.','展示捕获材料前分开诊断信号与凭据。','秘密使用环境变量，先脱敏输出，人工环只捕获观察。','复现需认证的导出错误。','把完整curl、认证头和HAR贴进简报。','环境变量引用令牌；仅展示脱敏状态和有效错误行；人自行登录，不捕获凭据。','报告保留症状而无凭据。','脱敏可能移除必要信号，需要时明确请求安全补证。',id=11)

SUM={
'ask-matt':'Hand-maintained conditional router returns a flow and stops; ordered phase-boundary options preserve reasoning when needed. Dependency discovery and summary accuracy are not guaranteed.',
'code-review':'Resolve a supplied fixed ref and originating spec; independent standards/spec agents cite their own authority and keep per-axis rankings. HEAD-only diff excludes uncommitted changes; leaf-delegation guard is absent.',
'codebase-design':'Canonical module/interface/depth/seam/adapter vocabulary; deletion test, observable interface testing, adapter variation and rejected line-count framing. Optional alternative-interface briefs and dependency categories are distinct reference branches.',
'diagnosing-bugs':'Redact commands/output first; establish observed red-capable tight feedback, minimize repro, rank falsifiable hypotheses, probe one prediction at a time, tag instrumentation and remove it. Missing correct seam is a finding; fixed numerical reliability/context claims are unvalidated.',
'domain-modeling':'Continuously confront ambiguous domain terms and code contradictions; write settled glossary terms inline. Separate glossary from decisions; ADRs require hard-to-reverse, surprising and actual-tradeoff gates.',
'grill-with-docs':'Composition wrapper calls grilling and domain-modeling separately; no independent procedure beyond those referenced mechanisms.',
'implement-spec':'Dependency task graph, sparse file pointers, isolated background implementers, integration-branch merger and recomputed frontier; final two-axis review and one batch fixer. Tracker closure may lag landed commits; no bounded final-fix convergence guarantee.',
'implement':'Build already settled spec/ticket at pre-agreed seams; repeated targeted tests/typechecks, one final suite, review and commit. Review-before-commit conflicts with HEAD-only reviewer scope; no explicit ticket closure.',
'improve-codebase-architecture':'Prefer changed hotspots, apply deletion test, produce strength-labelled before/after candidate cards, ask selection, then interview and record durable domain decisions. Report CDN scripts weaken self-contained/offline claim.',
'pr':'Pick smallest explanatory representation, before/after evidence, real consequence reversibility and blast radius. Attribution credits observed show-me adaptation; earliest provenance unknown.',
'prototype':'Question picks logic/state or visual branch; scratch state, visible transitions, cheap startup, capture question/verdict and runnable evidence outside production. Blanket no-tests is a source heuristic, not universal.',
'research':'Background primary-source reading returns one cited Markdown artifact at repo convention. Source lacks leaf-agent/no-recursion and stopping guards; citations require support review.',
'retro':'Use session primary evidence to repair navigation, existing checks, tool economy and information access. Encode mechanical violations in deterministic checks; prose standards for judgment; remove behaviorally inert instructions.',
'setup-matt-pocock-skills':'Inspect environment before proposing tracker, role mappings and domain layout; skip resolved decisions; preserve existing instruction file and user edits. Templates configure labels but do not create platform labels.',
'tdd':'Public pre-agreed seams, independent expected values and red/green vertical slices; mock external boundaries, prefer real substitutes. Refactoring deliberately moved to review despite trigger description.',
'to-spec':'Synthesize settled conversation rather than re-interview; confirm seams, describe behavior/implementation/testing/out-of-scope. Durable named contracts preferred to volatile paths; decision-rich prototype snippets retained.',
'to-tickets':'Demoable complete vertical slices sized for fresh context, blocking edges and approval of granularity before publication; wide refactor uses expand/migrate/contract or explicit integration-only green gate.',
'triage':'Exactly one category and state role, external PR discovery distinct from explicitly named requests, full comments/diff and reproduction before durable brief. Built versus rejected versus deferred requests must not poison rejection memory.',
'wayfinder':'Destination-scoped decision map as index, on-demand detail, claimed dependency-ready frontier, typed HITL/AFK tickets, fog versus sharp blocked question versus out-of-scope. Agent-editable execution exemption weakens planning gate; assignment is not atomic lease.',
'wizard':'Derive stages/value routes from repo references, validate current manual path, fixed library with focused stages, hidden secret input, idempotent destination writes and skip report. Verify syntax/static trace without live human run; raw env serialization has limits.',
'claude-handoff':'Portable targeted summary, suggested skills and artifact pointers, redact sensitive material; direct summary interpolation into shell is a risk documented by handoff commentary.',
'loop-me':'Find recurring loops, specify only justified trigger/AI/checkpoint structure; prepare late decision-ready brief. Finish contract requires implementer-answerable spec, not merely an outline.',
'setup-ts-deep-modules':'Path-depth public-entry convention, tests through public interface, cycles forbidden, merge existing config and umbrella checks. Prove pass/fail/pass; config has a fifth tests-folder-private rule beyond body four-rule shorthand.',
'writing-beats':'Audience-grounded concept ledger drives reachable next beats; offer alternatives, write one agreed beat, reread user edits, retain raw pile until natural argument ends.',
'writing-fragments':'Explore without structure commitment; heterogeneous fragments and defined recurring concept label; append current disk without overwriting human edits. Causal leading-word claims are not efficacy evidence.',
'writing-shape':'Fixed read-only raw pile, separate exploit article, prerequisites and running grounded concepts, candidate openings, incremental agreed paragraphs and deliberate format tradeoffs; explicitly name missing material.',
'git-guardrails-claude-code':'Pre-tool hook integrates project/global settings without replacement, customizable denied patterns and negative sample. Bundled substring-regex matcher has option/whitespace bypasses and string false positives; not a shell parser.',
'migrate-to-shoehorn':'Test-only fixture constructors distinguish partial, invalid and exact intent; typecheck migrations. Particular APIs are frozen recipes rather than verified present library contracts.',
'scaffold-exercises':'Plan to convention-shaped variants, minimal nonempty linked readmes, lint/fix loop and order-preserving renumbering. Project course naming/lint specifics excluded from general method.',
'setup-pre-commit':'Detect package-manager/config and existing scripts; staged formatter then available typecheck/tests, preserve config, smoke-check real commit. Hook availability is not complete quality evidence.',
'grill-me':'Thin user-invoked wrapper delegates to shared grilling; absence of docs writes is part of its contract.',
'grilling':'Dependency-ready question frontier with recommended answers, wait for human decisions, research environmental facts in parallel and defer only dependents. Frontier judgment may miss dependencies; shared-understanding checkpoint remains human.',
'handoff':'Targeted portable document uses artifact references rather than duplicate detail, suggested skills and redaction; destination relevance chooses summary scope. Temp lifetime and shell interpolation limits matter.',
'teach':'Mission/resources/lessons/learning-evidence/reference/assets/preferences are separately typed; source-ground lessons and immediate practice feedback. Memory entries require evidence of use, not exposure; quiz formatting is cue-sensitive; no automatic schedule/assessment exists.',
'to-questionnaire':'Recipient and required decision/facts define the knowledge gap; requester is interviewed about the send, not unknowable subject. One question per need, important-first, unknown allowed and one recipient per file.',
'wait-what':'Repair failed comprehension using missing premise, simplified register and canonical nouns. Source claims about leading-word model effects are unverified; observable clarity is the editorial target.',
'writing-for-agents':'Branch-complete context pointers, invocation/context versus human load, ordered steps/reference/disclosure, concept co-location, checkable exhaustive gates, actual-context sequence cut, environment truth and behavior-based pruning. Leading-word causal claims remain rejected.'}
REF={
'skills/engineering/ask-matt/PHASE-BOUNDARIES.md':'Ordered context-transition decision tree at phase boundaries: relevance, original reasoning need, portability and HITL versus autonomous scope; fixed smart-zone number is unvalidated.',
'skills/engineering/codebase-design/DEEPENING.md':'Four dependency categories calibrate stand-ins, ports/adapters and external mocks; observable interface tests replace internal-layer tests, with production-substitute fidelity limits.',
'skills/engineering/codebase-design/DESIGN-IT-TWICE.md':'Same design problem and vocabulary, deliberately different optimizer briefs, required interface/usage/invariants/tradeoffs, then per-design presentation and recommendation.',
'skills/engineering/domain-modeling/ADR-FORMAT.md':'Minimal context-choice-reason record, three admission gates, optional sections only when useful, sequential identity and supersession status.',
'skills/engineering/domain-modeling/GLOSSARY-FORMAT.md':'Canonical project terms with rejected synonyms, compact definitions and context-map relations; lazy creation and only domain-specific concepts.',
'skills/engineering/diagnosing-bugs/scripts/hitl-loop.template.sh':'Step pauses versus captured parseable KEY=VALUE observations; sign-in remains human and credentials must not be captured. Values echo into output; no full redaction parser.',
'skills/engineering/prototype/LOGIC.md':'Visible question, pure portable logic separated from shell, labelled state/free play and resettable guided awkward scenarios; preserve verdict and original runnable demo.',
'skills/engineering/prototype/UI.md':'Structural variants inside real host context hold data/auth/navigation fixed, URL-selector comparison, focus-aware keyboard switcher, no real mutations, production-hidden selector and preserve exploration branch.',
'skills/engineering/improve-codebase-architecture/HTML-REPORT.md':'Representation selected by relationship shape, compact before/after cards, strength and dependency labels, top recommendation. Uses Tailwind/Mermaid remote scripts and loose Mermaid security; not offline self-contained.',
'skills/engineering/setup-matt-pocock-skills/domain.md':'Read relevant glossary/context-map and ADRs before work; silent graceful absence, canonical language and explicit ADR conflict disclosure.',
'skills/engineering/setup-matt-pocock-skills/issue-tracker-github.md':'Logical create/read/label/close/claim/block/resolve mapping to GitHub; external discovery distinct from explicit PR scope; database IDs distinguished from issue numbers. Current CLI fields/endpoints not verified.',
'skills/engineering/setup-matt-pocock-skills/issue-tracker-gitlab.md':'Same role protocol mapped to GitLab MR/issue surfaces, native blocking or textual fallback and comment-before-close; host tier/API facts are frozen observations only.',
'skills/engineering/setup-matt-pocock-skills/issue-tracker-local.md':'One local file per task with dependency-order identity, append-only history, explicit claim/resolution and map index; sequential first-ready selection, no atomic race protection.',
'skills/engineering/setup-matt-pocock-skills/triage-labels.md':'Canonical logical state roles map to configurable platform label strings, separating vocabulary from storage adapter; mapping alone does not create labels.',
'skills/engineering/tdd/mocking.md':'Boundary-only substitution, dependency injection and operation-specific adapter methods make fixture intent legible; mocks can still diverge from real systems.',
'skills/engineering/tdd/tests.md':'Public behavior versus internals/call counts/side-channel tests and independent literal oracle versus tautological recomputation; same-task counterexamples inspected.',
'skills/engineering/triage/AGENT-BRIEF.md':'Durable named interfaces plus current/desired behavior, independent acceptance and explicit exclusions; PR brief describes remaining work on existing diff. Path/line avoidance is for delayed contracts.',
'skills/engineering/triage/OUT-OF-SCOPE.md':'Concept-scoped substantive rejection rationale with linked requests; semantic matching is reviewed by maintainer; built features and temporary deferrals are excluded from rejection memory.',
'skills/engineering/wizard/template.sh':'Fixed staged interactive library; hidden versus visible inputs, destination upserts, authenticated CI writes with skipped-action ledger. Raw KEY=VALUE does not safely encode arbitrary multiline/metacharacter secrets; only stage count exists.',
'skills/in-progress/setup-ts-deep-modules/dependency-cruiser.config.cjs':'Regex path-depth rules for external versus same-package imports, public test surface, private fixtures and cycles, optional layering separate. Static semantics inspected; not run as source code.',
'skills/misc/git-guardrails-claude-code/scripts/block-dangerous-git.sh':'Reads hook command string and substring-regex matches dangerous patterns; deny exit code2, allow0. Does not parse shell or normalize Git global flags; bypass/false-positive risk prevents security-guarantee claim.',
'skills/productivity/teach/GLOSSARY-FORMAT.md':'Terms enter only after demonstrated understanding, aliases avoided, ambiguity scoped and definitions revised as learning changes.',
'skills/productivity/teach/LEARNING-RECORD-FORMAT.md':'Evidence/claimed prior-depth/corrected misconception/change of mission are admitted; exposure/logging is not. Contradicted records superseded with links.',
'skills/productivity/teach/MISSION-FORMAT.md':'Observable real-world learning outcomes, constraints, exclusions and revision as goals change; mission is compact compass rather than task plan.',
'skills/productivity/teach/RESOURCES-FORMAT.md':'Annotated source index encodes coverage/when-to-read, high-trust criteria, explicit gaps and pruning; knowledge/community guidance separated, preference respected.',
'skills/productivity/writing-for-agents/SKILL-MECHANICS.md':'User-only versus model-discovered invocation economics, trigger conditions and router hint-only scope; source host-specific semantics not treated as universal.'}

repo=next(r for r in DATA['repositories'] if r['repo']==R)
for f in repo['coverage']:
 p=f['path'];keys=[c['key'] for c in DATA['candidates'] if any(s['repo']==R and s['path']==p for s in c['sources'])]
 if p.endswith('/SKILL.md'):
  review(R,p,SUM[p.split('/')[-2]],keys)
 elif p in REF:review(R,p,REF[p],keys)
 elif p.startswith('docs/'):
  name=Path(p).stem
  s=SUM.get(name,'Archived intent-preserving merge procedure: trace both sides to commits/issues, retain compatible behavior and run repo checks; unconditional finish/no-abort and parallel-file advice are source opinions.')
  review(R,p,'Full explanatory/caveat text reviewed (URL presentation stripped only; exact source content retained). '+s+' Source anonymous user-report/model/host/API claims are unverified observations, not established facts.',keys)
  f['duplicate_blocks_reference']='core-matt-doc-blocks.json'
 elif p.endswith('openai.yaml'):
  body=p.replace('/agents/openai.yaml','/SKILL.md')
  review(R,p,'Host display metadata and optional allow_implicit_invocation:false mapping inspected; mirrors body invocation policy, adds no independent execution workflow.',[c['key'] for c in DATA['candidates'] if any(s['repo']==R and s['path']==body for s in c['sources'])])
 elif p=='AGENTS.md':
  review(R,p,'Git-tree symlink body is CLAUDE.md; target reference inspected as shared instruction adapter, not equal-hash content duplicate.')
  f.pop('duplicate_of',None)
 elif p=='LICENSE':review(R,p,'MIT license and 2026 Matt Pocock notice inspected; license applies locally; conceptual extraction uses independent teaching examples.')
 elif p=='.agents/writing-docs.md':review(R,p,'Skill docs use defining constraint, invocation boundary, observable tells and role/neighbors; seek real questions via primary linkbacks, avoid padded FAQs, absolute published links and archived notices. Suppressing author/source provenance is not adopted by this audit.',keys)
 elif p=='.agents/invocation.md':review(R,p,'Dual-host invocation metadata consistency, explicit composition calls, one named skill per call, dependency restrictions and passive versus active domain work; host/API and hit-rate claims remain frozen observations.',keys)
 elif p=='.agents/adr/0001-explicit-setup-pointer-only-for-hard-dependencies.md':review(R,p,'Distinguishes hard dependency whose absence invalidates output from optional domain vocabulary that degrades gracefully; explicit setup pointers reserved for former.',keys)
 elif p=='.agents/adr/0002-ship-as-a-claude-code-plugin.md':review(R,p,'Curated promoted-path packaging versus recursive single-root discovery, symlink/cache copy limitations and version/pinned-listing freshness. Source dates/version tests are attributed observations; current host behavior not verified.',keys)
 elif p in ['CLAUDE.md','GLOSSARY.md','README.md'] or p.endswith('/README.md') or p=='.agents/install-block.md':review(R,p,'Repository bucket/router/install/role vocabulary scope fully inspected; index points to reviewed bodies rather than new mechanism. README/metadata includes stale red-green-refactor shorthand; marketing efficacy, universal compatibility and installer-update promises not adopted.',keys)
 elif p=='skills/engineering/pr/CREDITS.md':review(R,p,'Explicit show-me adaptation credit scoped to representation menu/placement; observed attribution does not establish earliest invention.',keys)
 elif p.startswith('scripts/'):
  review(R,p,'Supporting packaging code fully read. '+('Symlink deployment skips misc/deprecated, includes beta, guards destination symlink loop, but deletes non-symlink targets; never executed.' if 'link-skills' in p else 'Inventory/version synchronization only; deterministic version check and narrow replacement validation, no independent prompt workflow.'),keys)
 elif p.startswith('.changeset/') or p in ['CHANGELOG.md','.github/workflows/release.yml','.claude-plugin/plugin.json','.claude-plugin/marketplace.json','package.json','package-lock.json','.gitignore']:
  review(R,p,'Scope inspected as repo release history/configuration/dependency lock or promoted-skill distribution metadata; current methods are reviewed at their canonical bodies and references. Historical efficacy/host claims are not adopted.',excluded='Repo-specific release/package/history metadata; no independent current method beyond canonical reviewed skills.')
 elif p.startswith('.out-of-scope/'):
  review(R,p,'Concrete durable rejection examples inspected: mainstream-tool maintenance cost, no hard interview cap and natural-language verify scope. These are repository business decisions, not universal methods.',excluded='Repo-specific rejected feature/business choices; general concept-based rejection memory extracted from canonical triage reference.')
 else:raise AssertionError(('Unhandled',p))

repo['summary']['source_flaws']=[
 'Secondary docs report redaction/tool-name portability issues already addressed in current bodies; read canonical source before accepting their unfixed-status claims.',
 'docs/codebase-design says no shipped import rule, but beta config exists; wizard docs claim time estimates removed from current template.',
 'Architecture report requires remote CDN scripts and loose Mermaid security despite self-contained wording.',
 'Git guardrail is substring regex, not normalized shell/Git parsing; wizard raw env serialization does not safely encode arbitrary values.',
 'HEAD-only code-review conflicts with implement review-before-commit; research/review leaf prompts lack recursion guard; final integration fix lacks explicit bounded convergence.',
 'Teaching root-relative paths can conflate installed-skill references and target workspace; quiz position randomization and explicit prior-level assessment are absent.'
]
flaws=repo['summary']['source_flaws']
finish_repo(R,['orchestration','context','skill-authoring','workflow','evaluation','tools','output','safety'],['All 37 bodies, all current method references/examples, all 37 host adapters and supporting code inspected. Every tracked path has an analyzed/duplicate/excluded disposition.','Documentation URL display stripped for reading; exact paragraph duplicate occurrences retained in core-matt-doc-blocks.json.','Fixed smart-zone/reliability numbers, anonymous field anecdotes, model/host claims, pedagogical efficacy and security scanner exoneration are not established facts.','MIT locally scoped; PR representation attribution to show-me retained as observed adaptation, original invention unknown.'])
repo['summary']['source_flaws']=flaws
save()
print(repo['summary'])
