from pathlib import Path
import json,collections
n={'__name__':'core_helpers'};exec(Path(__file__).with_name('core-update.py').read_text(encoding='utf-8'),n)
repo='anthropics/skills';add=n['add'];review=n['review'];merged=n['merged'];src=n['src'];out=n['OUT']
for c in n['DATA']['candidates']:
    if c['key']=='core-anthro-document-reader-test':
        c.update(status='merged',suggested_existing_ids=[107],reason='Exact document-only, fresh-reader method enriches existing reader testing; earliest origin remains unknown.')
key=add('anthro-coordinate-provenance','Preserve coordinate units through tool handoffs','工具交接保留坐标单位','tools',[(repo,'skills/pdf/forms.md',256,266,'Hybrid coordinate normalization'),(repo,'skills/pdf/scripts/fill_pdf_form_with_annotations.py',10,30,'Scale and origin conversion')],
 ['Carry units, dimensions and origin with positions; normalize mixed coordinate sources before a downstream operation.','A form combines rectangles found in PDF points and regions estimated from a raster preview.','Record page identity, source dimensions, units and origin; convert pixel coordinates to the common page system, then apply the consumer’s origin transform and inspect the result.','Combine pixel and point rectangles in one field list as if their numbers mean the same thing.','Scale the image rectangle by page/image dimensions, label all rectangles as top-origin points, then convert once for the annotation writer.','Numeric shape agreement does not imply coordinate meaning agreement.','The unit conversions, page mapping and rendered placement can be checked.','Rotation, cropping, nonzero page origins and inaccurate detection need additional handling. The source checker compares font points with raw image units and does not validate every geometry invariant.'],
 ['位置数据需携带单位、尺寸与原点；下游操作前统一混合来源坐标。','表单把PDF点单位的矩形与截图估算区域合并。','记录页身份、来源尺寸、单位和原点；先把像素转换为统一页坐标，再按消费者原点转换并检查结果。','把像素与点坐标放在同一字段列表，视为含义相同。','按页面与图片尺寸比例缩放截图矩形，将所有矩形标为上原点点坐标，再为注释写入器转换一次。','数字形状一致不代表坐标含义一致。','可核对单位转换、页面映射和渲染位置。','旋转、裁剪、非零页原点和误检需要额外处理。源检查器将字体点大小与原始图片单位比较，且未验证所有几何约束。'])
body_notes={
 'skills/algorithmic-art/SKILL.md':('Philosophy→implementation; fixed template shell vs request-specific algorithm/parameters; explicit seeded randomness and adjustable controls; reproducibility depends on full state/version, not seed alone. Repeated mastery rhetoric, 90/10 split and universal immediate-browser support are unproven; CDN and fonts contradict offline self-containment.', ['composio-creative-philosophy','composio-refinement-pass']),
 'skills/frontend-design/SKILL.md':('Subject/audience/job-grounded brief; compact palette/type/layout/principle plan, then compare a similar brief to expose defaults; structural markers encode actual sequence; quality floor includes keyboard focus and reduced motion; copy names user actions consistently. Hypothetical rejected-client history is framing, not actual user context; taste bans and numeric text widths are source preferences.', ['core-leon-declared-design-read','core-matt-existing-194']),
 'skills/docx/SKILL.md':('Creation/edit/read mode branches; actual import probe before installation; render output, edit package preserving text/format; merge fragmented runs, strip extracted symlinks, preserve tracked-change baseline and invisible comment anchors. Actual helper/reference behavior reviewed separately; dependency-presence/current library API claims unverified.', ['composio-capability-branch-routing','core-karpathy-surgical-edit']),
 'skills/pdf/SKILL.md':('Full PDF body read: task library/format routes and domain merge/split/OCR/watermark/encryption examples; field-filling references selected only when needed. Extraction may return None; broad glyph/font and current-library claims not established. Uppercase FORMS.md/REFERENCE.md pointers disagree with tracked lowercase paths on case-sensitive hosts.', ['composio-intent-reference-routing']),
 'skills/pptx/SKILL.md':('Create/read/edit branching; structure before content edits, fresh mutable option objects and instance per output; duplicate helpers preserve package registrations but alias chart parts; baseline-inherited failures separated from regressions; structural/content/full-resolution visual QA distinct; regenerate preview after edits; approximate font metrics disclosed. Native chart/readiness/current-runtime and fixed safe-font assurances are unverified.', ['composio-capability-branch-routing','composio-refinement-pass']),
 'skills/xlsx/SKILL.md':('Explicit formulas and assumptions; preserve existing conventions/inputs; actual import probes; original cached-value baseline to distinguish inherited errors; artifact status is distinct from exit code; formulas versus caches require different reads, cached-only save destroys computation; external links and spill outputs need preservation and semantic checks. Exact function-support and preinstalled runtime claims unverified.', ['core-anthro-existing-116']),
 'skills/mcp-builder/SKILL.md':('Task-centric naming/filtering/pagination/error contracts and structured output; capability/client-dependent primitive-vs-workflow tool tradeoff; annotations are hints, not authorization; SDK-specific routing; independent stable read-only evaluation questions. Global comprehensive-endpoint preference is a source judgment; exact current SDK/protocol/transport guarantees not verified.', ['composio-workflow-tool-design','composio-stable-readonly-evaluation']),
 'skills/slack-gif-creator/SKILL.md':('Upload intent separates direct use and inspiration; composable rendering primitives and measured output constraints; optimization dimensions explicitly change size/duration/quality and occur when requested. Helper contract checked separately; current Slack limits, frame rates and aesthetic superiority are unverified.', []),
 'skills/web-artifacts-builder/SKILL.md':('Complexity-based routing to scaffold/bundle helper; init/develop/package/show/test workflow; deterministic helper centralizes repeatable steps. Testing is optional and discouraged before presenting, a source preference rather than evidence quality verification is unnecessary; single-file output may retain external network dependencies.', ['composio-helper-blackbox']),
 'skills/skill-creator/SKILL.md':('Full lifecycle draft→real prompts→with-skill and baseline→artifact/trace grading→human qualitative review→revision/generalization; preserve old-version snapshot for improvements; activation and outcome tests distinct; near-miss trigger negatives and repeated runs; bundles repeated helpers after transcript evidence; plain language, rationale and progressive references. Numerical 500/300-line, 20-query, 60/40 and three-run heuristics unvalidated. Empty feedback is not proof of review; selecting iterations by the so-called test set uses it as validation.', [])
}
for path,(note,keys) in body_notes.items():review(repo,path,note,keys)
delta_notes={
 'skills/mcp-builder/reference/mcp_best_practices.md':'All98 changed target lines read;151 unchanged lines exact to reviewed Composio source. Contract/output/error/security/transport revisions; annotations explicitly hints; errors corrective. Local HTTP advice requires Origin/loopback, while Node example uses app.listen with no bind or Origin validation. Async error example omits await, so a rejected promise escapes its try/catch. Actual current protocol/API claims unverified.',
 'skills/mcp-builder/reference/node_mcp_server.md':'All126 changed target lines read;844 unchanged lines exact to reviewed Composio source. register* and structured output changes; current transport templates create stateless per-request objects and close on response close; one shared server instance/concurrent reconnect behavior unverified; examples lack best-practice Origin/loopback checks. Tool filtering, limits, errors and SDK contracts retain baseline conclusions.',
 'skills/mcp-builder/reference/python_mcp_server.md':'All7 changed target lines read;712 unchanged lines exact to reviewed Composio source. Transport changes and removed response code; existing schemas, task-oriented tools, pagination/errors retained. Current FastMCP APIs/deprecation statements not verified.',
 'skills/pdf/forms.md':'All190 changed target lines read;104 unchanged lines exact to reviewed Composio source. Structure first, field-specific visual fallback and zoom refinement; explicit crop-offset restoration, source dimensions and mixed-coordinate normalization; validate then render output. Bounding-box checker does not establish every claimed validity condition.'
}
ledger=json.loads((out/'core-anthro-deltas.json').read_text(encoding='utf-8'))
for row in ledger:
    row['delta_read']=True
    review(repo,row['path'],delta_notes[row['path']],[key] if row['path'].endswith('forms.md') else ['composio-workflow-tool-design'])
    cov=next(x for r in n['DATA']['repositories'] if r['repo']==repo for x in r['coverage'] if x['path']==row['path']);cov['exact_line_reuse']=row
(out/'core-anthro-deltas.json').write_text(json.dumps(ledger,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
pdf_notes={
 'check_bounding_boxes.py':'Pairwise label/entry intersection and height checks, capped diagnostics; failures printed with zero exit status. No bounds/ordering/page identity/units/text-width validation; pixel height vs font-point comparison mixes units.',
 'check_fillable_fields.py':'Actual get_fields result selects form capability; no argument/error handling. Output fallback claims visual determination despite newer structure-first route.',
 'convert_pdf_to_images.py':'All pages rendered at200DPI then resized to maximum1000 preserving aspect; output directory must already exist; no stale-output removal or exact image/PDF geometry manifest.',
 'create_validation_image.py':'Draws label/entry raw coordinates on selected page image without unit conversion or dimension check; valid only for image-coordinate inputs.',
 'extract_form_field_info.py':'Resolves inherited hierarchical IDs, types/states and page rectangles/radio groups; unknown fields and absent locations explicit but omitted. Some assumptions about pypdf indirect dereference/choice state shapes remain unverified.',
 'extract_form_structure.py':'Text, large-x-extent lines and small nearly-square rectangles generate structure/rows. Heuristic does not test horizontal y-delta or detect all controls; rounded coordinates and dimensions carried.',
 'fill_fillable_fields.py':'Validate actual opaque ID/page/allowed option before mutation; reject any error before clone/write; conditional choice monkeypatch. Visual/readback evidence still needed; empty lists or skipped fields are not complete-user-task proof.',
 'fill_pdf_form_with_annotations.py':'Dimensions/origin transforms for image versus top-origin PDF coordinates, create FreeText annotations then report count. pdf_width is a mode marker, not verified dimension consistency; rotations/cropped origins and actual downstream visibility not checked.'
}
for name,note in pdf_notes.items():review(repo,'skills/pdf/scripts/'+name,note,[key])
key108=merged('anthro-existing-108',108,[(repo,'skills/skill-creator/agents/comparator.md',3,35,'Producer-blind artifact comparison'),(repo,'skills/skill-creator/agents/analyzer.md',23,67,'Unblind only for post-hoc diagnosis')])
key119=merged('anthro-existing-119',119,[(repo,'skills/skill-creator/SKILL.md',169,205,'Same-task baseline and objective assertions'),(repo,'skills/skill-creator/SKILL.md',292,304,'Generalization and repeated-helper evidence')])
key=add('anthro-assertion-challenge','Challenge assertions with wrong outputs','用错误产物挑战断言','evaluation',[(repo,'skills/skill-creator/agents/grader.md',68,79,'Discriminating assertions'),(repo,'skills/skill-creator/agents/analyzer.md',211,239,'Per-assertion and per-case analysis')],
 ['Audit whether a passing assertion distinguishes task success from a concrete wrong output.','An extraction benchmark only checks that a CSV contains a customer name.','Construct a plausible incorrect output that passes; strengthen the assertion to compare the relevant values and relationship against the input, then inspect per-case results.','Pass a CSV because it contains “Mina”, even though that name is in a footer and the customer record is wrong.','Require Mina’s customer row to contain the input phone number and status; reject the footer-only counterexample.','The check measures the intended outcome rather than a coincidental token.','A named wrong output passes the weak check and fails the corrected check.','Improving an assertion may overfit to one failure. Maintain independent cases; a model grader’s evidence and accuracy still need calibration.'],
 ['审查通过断言能否区分任务成功与具体错误产物。','提取基准只检查CSV包含客户姓名。','构造能通过的合理错误产物；加强断言，按输入核对相关值与关系，再查看各案例结果。','CSV页脚出现“Mina”就通过，客户记录却错误。','要求Mina客户行包含输入中的电话和状态；拒绝仅页脚出现姓名的反例。','检查测量目标结果，而非偶然出现的词。','指定错误产物通过弱检查，却不能通过修正后的检查。','加强断言也可能对单一失败过拟合。保留独立案例，并校准模型评分证据和准确性。'])
key2=add('anthro-heldout-channel','Keep selection feedback out of revision prompts','修订提示隔离选择反馈','evaluation',[(repo,'skills/skill-creator/scripts/run_loop.py',189,218,'Blind history and selection'),(repo,'skills/skill-creator/scripts/improve_description.py',120,140,'Generalize intent instead of enumerating cases')],
 ['Keep withheld-case results out of the prompt that proposes revisions, and name the resulting selection set accurately.','A router description is revised from labeled training failures while candidate versions are compared on reserved queries.','Pass only training cases and history to the reviser; use the reserved results for candidate selection, label that set validation, and reserve a fresh final test for an unbiased final estimate.','Feed the reserved failures back into every rewrite and call the best reserved score an untouched test result.','Hide reserved fields from revision history; select the description on validation and report final performance on new cases.','Separating feedback channels makes direct case leakage visible and avoids mislabeling adaptive selection as final testing.','The revision prompt excludes reserved records; selection and final-test identities are recorded.','The source implements withheld revision fields but selects repeatedly on its “test” set, so its score is validation, not an independent final estimate. Split ratios and repeat counts require task-specific calibration.'],
 ['不把保留案例结果传给提出修订的模型，并准确命名用于选择的数据集。','路由描述按训练失败修订，候选版本在预留查询上比较。','修订器只接收训练案例与历史；预留结果用于候选选择，标为验证集，再留新的最终测试。','每次改写都提供预留失败，却称最佳预留分数是未触碰的测试结果。','修订历史隐藏预留字段；验证集选描述，新案例报告最终表现。','分离反馈通道可观察直接泄漏，并避免把自适应选择称为最终测试。','修订提示不含预留记录，且选择与最终测试身份有记录。','源代码隔离修订字段，却反复用“测试”集选择，所以这是验证分数，非独立最终估计。比例和重复次数需按任务校准。'])
notes={
 'agents/comparator.md':'Full producer-blind task/content/structure rubric; actual files inspected, assertion secondary, explicit tie allowed but urged rare. No order randomization or judge calibration; decisive preferences do not prove a true difference.',
 'agents/grader.md':'Full trace+actual-artifact inspection, factual/process/quality claims separately verified; insufficient evidence fails; substantive counterexamples challenge assertions; user uncertainty notes retained. No machine-enforced identity/coverage validation.',
 'agents/analyzer.md':'Full blind comparison then unblind skills/transcripts for hypothesis-grounded diagnosis; causation versus incidental differences explicitly asked; separate benchmark role surfaces per-assertion/per-case variance and cost patterns without causal speculation.',
 'references/schemas.md':'All eight schema examples and field descriptions read. Consumer grammar, identities, versions, results, per-case grades, timing and feedback separated. Example grading contains two rows but summary total3; benchmark model placeholders and fixed three runs are examples, not observed metrics.',
 'scripts/quick_validate.py':'Full safe YAML dictionary and allowed/required key/type/character checks. Empty stripped name/description pass; falsey wrong compatibility types bypass checking; no referenced-resource closure, security or behavioral validation.',
 'scripts/package_skill.py':'Full minimal-validation then recursive zip with global cache/dependency excludes and root-only eval exclusion. Follows file symlinks, no secret allowlist or output-self-inclusion prevention; packaging validation does not prove behavior or reference closure.',
 'scripts/utils.py':'Full ad-hoc frontmatter scalar/block parser; joins all block lines and strips quotes, not full YAML grammar. Parsed trigger text may differ from actual host interpretation.',
 'scripts/run_eval.py':'Full temporary unique-name placeholder command + real host CLI stream probe; pinned model optional, cleanup process/file on every exit. Stops at first tool/assistant result, so later activation missed; timeout/infrastructure failures become false and can pass negatives. Concurrent project command files compete; ambient project skills/config and duplicate-query coalescing confound isolated trigger claims. select-on-pipe portability unverified.',
 'scripts/run_loop.py':'Full stratified fixed-seed split, repeated query runs, on-disk history/live report and withheld test_* history fields. So-called test selects best repeatedly and is validation; train failures drive stopping, no independent final test. Query-string identity can overlap/coalesce conflicting labels; zero/invalid configuration not guarded.',
 'scripts/improve_description.py':'Full stdin CLI prompt from training failures + skill content + history; broader user intent instead of query enumeration; model output parsed and overlength rewritten once. No final hard-length revalidation, logs retain full prompts/results; “undertrigger” and configured host guarantees unverified.',
 'scripts/aggregate_benchmark.py':'Full run discovery, missing/invalid grade skips, trusted grader summaries, unweighted means and first-two-config delta. Default SKILL layout has no run-* subdirectories and is ignored; errors can yield empty-success report. Missing timing becomes zero; output characters mislabeled tokens, model placeholders and fixed3run metadata not actual observations.',
 'scripts/generate_report.py':'Full train/validation matrix, per-query polarity/retry counts, dynamic summary output. Escapes strings but some metadata/count fields raw; no schema checks. Empty history max() failure; external fonts contradict offline report claims.',
 'assets/eval_review.html':'Full editable positive/negative human-reviewed queries, toggles and JSON export. DOM text escaping exists, but raw placeholder replacement can break the enclosing script/HTML before that escaping runs; no domain or semantic validation.',
 'eval-viewer/generate_review.py':'Full recursive run/artifact embedding, previous iteration and benchmark linkage, static/download versus local HTTP feedback. Raw JSON embedded in script permits closing-script content before DOM escaping; follows directory symlinks without bound/ownership; kills any port listener before own server. Local POST schema only dict+reviews, no origin protection, atomic write or explicit reviewed identity.',
 'eval-viewer/viewer.html':'All1326 lines read. Separate artifact and metrics tabs, raw text via textContent, binary/image/PDF/XLSX previews, previous feedback/output, autosave and static export. submit emits empty feedback for every run without a visited/reviewed gate, so unseen and accepted remain indistinguishable; fetch then ignores HTTP failure status, can claim saved on500; metadata/numeric HTML and raw enclosing-script JSON remain tainted. Remote SheetJS/fonts mean standalone is not offline.'
}
for tail,note in notes.items():review(repo,'skills/skill-creator/'+tail,note,[key108,key119,key,key2])
review(repo,'skills/skill-creator/scripts/__init__.py','Empty module marker, no instructions or execution contract.',excluded='Empty package marker.')
rr=next(r for r in n['DATA']['repositories'] if r['repo']==repo)
rr['summary']['notes']=['Partial research: 19/20 skill bodies are closed; claude-api body and references remain pending. Exact Composio Git-blob reuse and all changed MCP/PDF reference lines are recorded. All skill-creator prose, schemas, scripts and viewer sources fully read; no source script/model evaluation executed.']
rr['source_flaw_evidence']=[
 {'claim':'Static inspection: trigger runtime failures are converted to false, so negative cases can pass without a valid host run; first-tool stopping misses later activation.','sources':[src(repo,'skills/skill-creator/scripts/run_eval.py',128,171,'Early stopping'),src(repo,'skills/skill-creator/scripts/run_eval.py',213,242,'Failure collapse and negative scoring')]},
 {'claim':'Static inspection: default SKILL output layout puts grades directly under with_skill, but aggregator only accepts run-* children and skips absent grades; empty results still generate a report.','sources':[src(repo,'skills/skill-creator/SKILL.md',173,186,'Default output layout'),src(repo,'skills/skill-creator/scripts/aggregate_benchmark.py',100,134,'Run discovery and grade skipping')]},
 {'claim':'Static inspection: the candidate-selection set is repeatedly used to choose the best version, so its so-called test score is validation; no fresh final test is implemented.','sources':[src(repo,'skills/skill-creator/scripts/run_loop.py',189,222,'Selection feedback boundary')]},
 {'claim':'Static inspection: feedback submission emits every run with empty text even if unseen, and HTTP failure statuses are treated as saved; empty feedback cannot prove human approval.','sources':[src(repo,'skills/skill-creator/eval-viewer/viewer.html',993,1060,'Feedback transport and submission')]},
 {'claim':'Static inspection: JSON is inserted raw into an HTML script; later DOM escaping does not protect the enclosing script boundary.','sources':[src(repo,'skills/skill-creator/eval-viewer/generate_review.py',270,281,'Raw JSON embedding'),src(repo,'skills/skill-creator/assets/eval_review.html',62,65,'Template script placeholder')]},
 {'claim':'Static inspection: the PDF bounding-box checker prints failures with zero exit status and mixes image pixels with font points; a green exit alone is not artifact correctness.','sources':[src(repo,'skills/pdf/scripts/check_bounding_boxes.py',43,65,'Height units and exit behavior'),src(repo,'skills/xlsx/SKILL.md',40,50,'Semantic result versus process exit')]}
]
n['save']();print('CHECKPOINT',collections.Counter(x['disposition'] for x in rr['coverage']),n['DATA']['summary']['candidate_counts'])
