from pathlib import Path
N={'__name__':'core_helpers'}
exec(Path(__file__).with_name('core-update.py').read_text(encoding='utf-8'),N)
globals().update({k:v for k,v in N.items() if k not in ['__name__','__file__']})
R='mattpocock/skills'

def case(key,en,zh,cat,p,a,b,desc,mechanism,scenario,bad,good,expected,boundary,zhdesc,zhmechanism,zhscenario,zhbad,zhgood,zhexpected,zhboundary,id=None):
 return add('matt-'+key,en,zh,cat,[(R,p,a,b,en)],
 [desc,scenario,mechanism,bad,good,'The contrast changes the decision procedure and makes its result inspectable.',expected,boundary],
 [zhdesc,zhscenario,zhmechanism,zhbad,zhgood,'对照明确改变决策过程，使结果可检查。',zhexpected,zhboundary],ids=[id] if id else [])

def legacy(id,p,a,b,case_data):
 row=next(x for x in LEGACY['patterns'] if x['id']==id)
 return case('existing-'+str(id),row['name_en'],row['name_zh'],row['category'],p,a,b,*case_data,id=id)

W='skills/productivity/writing-for-agents/SKILL.md'
legacy(189,W,61,74,('Use a defined compact concept consistently as a behavioral handle.','Define the term once and repeat the term at relevant decisions.','Write deployment instructions.','Be careful, reliable and thorough at every step.','Define reversible gate as a check that can be undone; require a reversible gate before each deployment stage.','Stages name the same defined gate.','A label is not evidence of efficacy; unknown terms need definitions.','以已定义的紧凑概念作为行为抓手。','定义一次，在相关决策处重复同一术语。','编写部署指令。','每步都要细心、可靠、周全。','定义可逆门为可撤销的检查；每个部署阶段先过可逆门。','各阶段使用相同的已定义门。','标签本身不证明有效；陌生词须解释。'))
legacy(190,'skills/productivity/writing-for-agents/SKILL-MECHANICS.md',5,22,('Choose discovery cost according to who must invoke the workflow.','Use an always-visible trigger only for autonomous discovery; keep human-only commands in a deliberate index.','Package a release helper and a reference used by other skills.','Make every helper always discoverable.','Keep release approval human-invoked; expose the shared schema reference to the skills that require it.','Unneeded triggers are removed while dependencies remain reachable.','Host invocation mechanics are frozen source observations, not universal API contracts.','按谁来调用流程选择发现成本。','自主发现才用常驻触发器；仅人工调用的命令放入明确索引。','打包发布助手和其他技能所需参考。','让所有助手都常驻可发现。','发布审批由人调用；共享模式参考可由依赖技能访问。','删除多余触发器，依赖仍可访问。','宿主调用规则只是冻结观察，并非通用接口承诺。'))
legacy(191,W,45,59,('Separate a tempting later phase across a real context boundary after sharpening the current completion predicate.','Define the current gate first; hand off only after it is met, withholding downstream steps from that context.','Audit records before writing a report.','Read records, then write the report; move on when ready.','Audit until every record has a disposition. Dispatch report writing in a new context only after that ledger closes.','The first context closes coverage before report generation.','Inline calls do not erase already visible later steps.','明确当前完成判据后，以真实上下文边界分隔诱人的后续阶段。','先定义当前门槛；满足后才交接，下游步骤不进入当前上下文。','先审计记录再写报告。','读记录后写报告；准备好就继续。','每条记录都有处置后才结束审计；台账闭合后在新上下文写报告。','报告生成前完成覆盖台账。','内联调用不能删除已可见的后续步骤。'))
legacy(192,W,76,81,('Prune instructions by whether they change behavior relative to a measured default.','Compare the same task with and without a sentence; remove behaviorally inert sentences.','Shorten a review prompt.','Delete whatever reads obvious to me.','Compare the review with and without cite each finding to a rule; retain it only if citation behavior changes.','Pruning decisions have observed behavioral contrasts.','The default depends on model, task and environment; a single run is weak evidence.','按指令是否改变已测默认行为进行删减。','同任务比较有无该句，删除行为不变的句子。','缩短评审提示。','删除我觉得显然的内容。','比较有无每个发现引用规则的评审；只有引用行为改变才保留。','删减决定有可观察的行为对照。','默认取决于模型、任务和环境；单次运行证据较弱。'))
legacy(193,W,45,52,('Completion must be checkable and cover the full required set.','Pair an observable predicate with an explicit universal scope.','Review changed settings.','Produce a useful settings summary.','Finish when every changed setting is mapped to its reader and its expected effect, with no unmapped row.','Coverage and closure can be checked separately.','An exhaustive set must be identifiable; unknown scope requires inventory first.','完成条件须可检查且覆盖全部要求。','把可观察判据与明确的全称范围结合。','评审变更设置。','产出有用的设置摘要。','每个变更设置映射到读取者与预期作用，且无未映射行，才完成。','可分别检查覆盖和闭合。','须先确定全集；范围未知时先清点。'))
legacy(194,'skills/engineering/codebase-design/SKILL.md',12,24,('Enforce one vocabulary and explicitly identify ambiguous substitutes.','Define a canonical term and list synonyms to avoid in names and contracts.','Write a billing spec.','Use customer, account and user interchangeably.','Define Customer as the billed organization and User as a login identity; use those names consistently.','The spec distinguishes billing identity from login identity.','Only enforce distinctions relevant to the domain; ordinary prose need not become rigid jargon.','统一词汇并明确歧义替代词。','定义规范词，列出命名与契约中禁用的同义词。','编写计费规格。','客户、账户、用户随意互换。','定义Customer为付费组织、User为登录身份，并一致使用。','规格区分计费身份与登录身份。','只约束领域相关区别，不把普通文字僵化成术语。'))
legacy(195,'skills/engineering/codebase-design/SKILL.md',105,109,('Record rejected framings with the reason they mislead.','Pair a preferred framing with a concrete explanation of the tempting alternative error.','Explain module depth.','Call a module deep if its implementation has many lines.','Judge depth by caller capability per learned interface; reject line-count depth because padding implementation would improve that score.','A padded implementation is not mistaken for a stronger interface.','A rejected framing is a local interpretive rule, not a ban on all alternative metrics.','记录被拒绝的框架及其误导原因。','将优选框架与诱人替代方案的具体错误成对说明。','解释模块深度。','实现行数多就是深模块。','按每单位接口学习获得的能力判断深度；拒绝行数指标，因为填充实现就能抬高分数。','不把填充实现误认成更好的接口。','拒绝框架是局部解释规则，不是禁止所有其他指标。'))
legacy(196,'skills/in-progress/writing-beats/SKILL.md',25,38,('Track concepts known to the audience before selecting the next explanation step.','Keep requires/grounds sets and admit a step only when all prerequisites are grounded.','Explain dependency scheduling to beginners.','Start with topological order and frontier convergence.','First ground blocker as a task that must finish; then introduce frontier as tasks with finished blockers; only then discuss scheduling.','No step depends on an unexplained concept.','A jargon-free sentence can still require an unknown concept; audience knowledge must be explicit.','选择下个解释步骤前跟踪读者已知概念。','维护需要/引入集合，前置概念已建立才允许该步骤。','向初学者解释依赖调度。','先讲拓扑序与前沿收敛。','先解释阻塞项是必须先完成的任务，再引入前沿为阻塞项已完成的任务，然后谈调度。','每步不依赖未解释概念。','没有术语的句子仍可依赖未知概念；须明确读者基础。'))
legacy(197,'skills/engineering/wayfinder/SKILL.md',82,101,('Plan only questions that are precise now while retaining visible in-scope uncertainty.','Keep sharp blocked questions as tickets, unsharp work as fog, and excluded work in a separate scope ledger.','Plan an uncertain data migration.','Create detailed tickets for every guessed future step.','Ticket choose identifier policy; keep revisit import strategy after that decision as fog; mark analytics redesign out of scope.','The frontier advances without speculative detail or hidden exclusions.','Fog is uncertainty within the destination; it is not a bucket for excluded work.','只把当前明确的问题做成计划，同时保留范围内不确定性。','明确但受阻的问题为票据，未明确的为迷雾，范围外的另记。','规划不确定的数据迁移。','为猜测的所有未来步骤建立细票。','建票选择标识策略；策略确定后再看导入方案留为迷雾；分析改版记为范围外。','前沿推进而无推测细节或隐藏排除。','迷雾属于目标范围内不确定性，不是范围外事项。'))
legacy(198,'skills/engineering/code-review/SKILL.md',74,87,('Keep independent review axes separately ranked and separately concluded.','Dispatch standards and specification reviews without sharing their findings; report the worst issue per axis.','Review a caching change.','Blend all findings into one severity list and declare it good overall.','Report Standards: naming compliant. Spec: stale results violate the freshness requirement. Give a conclusion for each axis.','A passing standards check cannot conceal a requirement failure.','The two axes do not replace runtime security or performance testing.','独立评审维度分别排序并分别下结论。','规范与规格评审不互传发现，每个维度各报最严重问题。','评审缓存变更。','混合所有发现统一排序，再宣布总体良好。','报告规范：命名合规；规格：陈旧结果违反新鲜度要求；各自下结论。','规范通过不能掩盖需求失败。','两维评审不替代运行时安全或性能测试。'))
legacy(199,'skills/in-progress/loop-me/SKILL.md',18,23,('Prepare the maximal reviewable result before the human checkpoint.','Push a required decision late and present a concise brief linking the prepared asset.','Design a newsletter approval workflow.','Ask approval before collecting each source and before drafting each paragraph.','Collect sources, draft and check links; present one brief with the draft link, rationale and the publish decision.','The human reviews a concrete asset in one decision.','Do not execute the action requiring approval before the checkpoint.','在人类检查点前准备最大可评审结果。','把必要决策后移，用简要简报链接已备妥产物。','设计通讯审批流程。','搜集每个来源、写每段前都请求审批。','搜集来源、起草并验链；用一份简报给出草稿链接、依据及发布决策。','人一次决策评审具体产物。','需要审批的动作不得在检查点前执行。'))
legacy(200,'skills/in-progress/writing-fragments/SKILL.md',7,17,('Give exploration and commitment different workflows and artifacts.','Collect raw alternatives first; hand a fixed read-only pile to the shaping phase.','Develop an article from interview notes.','Outline while collecting notes and keep rewriting the raw notes into prose.','Capture independent fragments without order; freeze that pile and create the article in a separate file during shaping.','Discovery can widen before a structure is chosen.','If new evidence changes the pile, explicitly return to exploration.','探索与定稿使用不同流程和产物。','先收集原始备选，再把固定只读材料交给塑形阶段。','把访谈笔记发展成文章。','收笔记时就定提纲，并把原始笔记反复改成正文。','先无序收集独立片段；冻结材料，在另文件塑形成文。','结构选定前发现空间可继续扩展。','新证据改变材料时明确返回探索。'))
legacy(201,'skills/engineering/diagnosing-bugs/SKILL.md',114,120,('Report the absence of a test seam that reaches the real failure instead of substituting a shallow test.','Attempt a call-site-sensitive regression; if no interface exposes it, record the missing seam and route architecture work.','Fix a queue retry race.','Test the retry delay helper and claim the race is covered.','Exercise the queue interaction; if no public interface can reproduce it, record that gap and the unverified race boundary.','The regression claim does not exceed what its test can detect.','Fixing the bug and redesigning the seam can be separate scoped work.','报告触及真实故障的测试接缝缺失，避免以浅测试代替。','尝试调用现场敏感回归；接口无法暴露时记录缺口并安排架构工作。','修复队列重试竞争。','测试延迟助手并声称竞争已覆盖。','测试队列交互；公共接口无法复现时记录缺口及未验证边界。','回归声明不超过测试可检测能力。','修错和重设接缝可作为不同范围工作。'))
legacy(202,'skills/engineering/diagnosing-bugs/SKILL.md',57,66,('Require an already observed failing signal before investigating causes.','Name and run the reproducer; hypotheses wait until it demonstrably detects the reported symptom.','Debug an intermittent duplicate charge.','Read code and guess the retry branch is wrong.','Run the captured request replay until duplicate charge is observed; record its output before ranking retry hypotheses.','Every hypothesis is tested against the same red-capable loop.','If no reproducer can be built, report the missing access or artifact instead of guessing.','调查原因前要求已观察到失败信号。','命名并运行复现器，证明能检测目标症状后才提假设。','调试间歇性重复扣款。','读代码后猜重试分支有错。','运行捕获请求回放，观察重复扣款并记录输出，再排列重试假设。','每个假设面对同一可失败反馈环。','无法建立复现器时报告缺失权限或产物，而非猜测。'))
legacy(203,'skills/engineering/wayfinder/SKILL.md',73,80,('Type tasks by whether a real human response is required.','Mark HITL versus autonomous work and leave human answers unresolved until the person supplies them.','Choose product naming and research an API limit.','Invent the stakeholder answers and close both tickets.','Research the limit autonomously; keep naming as HITL and close it only after the stakeholder chooses.','No fabricated stakeholder decision appears as resolved.','An absent human does not convert a HITL decision into autonomous work.','按是否需要真实人类回应为任务定型。','标明人参与与自主任务，人在答复前保持其决策未解决。','选择产品名并研究接口限额。','编造利益相关者答案并关闭两票。','自主研究限额；命名保留人参与类型，获得本人选择后才关闭。','无虚构人的决策被记为已解决。','人缺席不使人工决策变成自主任务。'))
legacy(204,'skills/engineering/wizard/SKILL.md',39,44,('Verify an interactive or consequential script by static flow tracing when executing it is inappropriate.','Check syntax and trace every captured value to its exact destination without running the human ceremony.','Review a credential setup wizard.','Run the whole wizard unattended and fill fake answers.','Check syntax; trace hidden token input to the intended environment variable and CI secret reference; hand the run to the human.','Every required value has a reviewed route without simulated interactive completion.','Static checks cannot prove current UI labels or successful live service writes.','不适合执行的交互或有影响脚本通过静态流程追踪验证。','检查语法，将每个输入追到确切目的地，不运行人工步骤。','评审凭据设置向导。','无人运行整个向导并填假答案。','检查语法；追踪隐藏令牌输入到环境变量及CI秘密引用；交人运行。','所有必需值路线已检查，无模拟交互完成。','静态检查不能证明当前界面标签或服务写入成功。'))
legacy(205,'skills/engineering/ask-matt/PHASE-BOUNDARIES.md',19,40,('Choose context transitions at phase boundaries according to relevance, portability and interaction needs.','Prefer continuation when reasoning must stay verbatim; otherwise distinguish clear, portable handoff, autonomous delegation and compaction.','Move from research to integration review.','Always compact after a fixed token count.','Keep research if the review needs its reasoning; use a portable handoff when changing harness; compact relevant same-harness context only when needed.','The chosen transition names what information must survive.','The source ~150k smart-zone figure is an unvalidated heuristic, not a model limit.','按相关性、可移植性和交互需求在阶段边界切换上下文。','需要原始推理则继续，否则区分清空、可移植交接、自主委派和压缩。','从研究转入集成评审。','达到固定令牌数就总是压缩。','评审需原推理则保留；换宿主用可移植交接；同宿主相关上下文只在需要时压缩。','切换选择明确必须保留的信息。','源中约150k聪明区是未验证启发式，并非模型限制。'))
legacy(206,'skills/engineering/domain-modeling/ADR-FORMAT.md',29,37,('Record decisions only when reversal cost, surprise and genuine tradeoff all justify durable rationale.','Apply all three gates and record context, choice and reason for qualifying decisions.','Decide whether to record a queue choice and a local rename.','Write an ADR for every edit.','Record the locked-in queue choice with rejected alternatives; omit the easily reversed local rename.','Decision records retain load-bearing rationale without a diary of routine edits.','A team may use other record conventions; this is an editorial gate, not a universal standard.','撤销成本、意外性和真实权衡共同成立才记录长期依据。','应用三道门，合格决策记录背景、选择和原因。','决定队列选择与局部改名是否记档。','每个编辑都写决策记录。','记录形成锁定的队列选择及替代方案；省略易撤销局部改名。','记录保留关键依据而非日常编辑日记。','团队可有其他约定；此为编辑门槛而非通用标准。'))

case('frontier-integration','Dependency-ready integration frontier','依赖就绪集成前沿','orchestration','skills/engineering/implement-spec/SKILL.md',13,38,
 'Run independent dependency-ready tasks in isolated contexts and serialize their integration.','Compute readiness from what has landed on the integration branch; dispatch that frontier and merge one result at a time.','Build schema, exporter and UI tickets with dependencies.','Start every ticket concurrently and trust tracker open/closed status for readiness.','Run independent schema and copy work in worktrees; after schema lands start exporter; serialize merges and recompute readiness from landed commits.','No task starts on an unmet implementation dependency, and all results converge on one branch.','Worktrees postpone shared-file conflicts; credentials and ignored fixtures may be absent.','独立就绪任务在隔离上下文并行，集成串行。','按集成分支已落地任务计算就绪前沿，调度该前沿并逐项合并。','构建有依赖的模式、导出器和界面票据。','所有票并发启动，只按跟踪器开关状态判断就绪。','模式与文案独立工树并行；模式落地后启动导出器；合并串行并按提交重算前沿。','任务不在依赖未满足时启动，结果汇聚一分支。','工树只推迟共享文件冲突；凭据和忽略夹具可能缺失。')
case('question-frontier','Dependency-ready question rounds','依赖就绪问题轮次','workflow','skills/productivity/grilling/SKILL.md',6,28,
 'Ask only decisions whose prerequisites have already settled, then recompute the next round.','Treat answers and factual explorations as prerequisite nodes; unresolved nodes block only their dependents.','Interview about a notification system.','Ask retention policy, database type and purge schedule all at once.','First settle legal retention and delivery needs; research provider limits independently; ask purge schedule only after retention is answered.','Later questions do not silently assume answers still pending.','A question tree can miss a branch; the empty frontier needs explicit scope review.','只问前置已定的决策，随后重算下一轮。','答案和事实探索均为依赖节点，未定节点仅阻塞下游。','访谈通知系统需求。','同时问保留政策、数据库类型和清理周期。','先定法规保留及交付需求；独立研究供应商限额；保留期答后才问清理周期。','后续问题不暗含尚未得到的答案。','问题树可能漏分支；前沿为空须核对范围。')
case('durable-contract','Durable behavioral agent contract','耐久行为代理契约','context','skills/engineering/triage/AGENT-BRIEF.md',9,37,
 'Describe behavior and named interfaces instead of volatile file locations in delayed task handoffs.','State current/desired behavior, independently testable acceptance criteria, interface names and exclusions.','Queue a JSON-output fix for next week.','Edit handler.ts line 80 and add a switch.','Under --json emit valid JSON for success and errors, preserve exit codes; modify the output interface; exclude other commands.','A renamed file does not invalidate the task contract.','Exact paths remain useful for immediate observations; durable handoffs still need version context.','延迟交接用行为和接口名代替易变文件位置。','明确当前/目标行为、独立可测验收、接口名和排除项。','把JSON输出修复排到下周。','编辑handler.ts第80行加switch。','--json下成功与错误均为有效JSON，保持退出码；修改输出接口；其他命令不在范围。','文件改名不使任务契约失效。','即时观察仍可用确切路径；耐久交接仍需版本背景。')
case('rejection-memory','Concept-scoped rejection memory','概念级拒绝记忆','context','skills/engineering/triage/OUT-OF-SCOPE.md',70,88,
 'Recall substantive rejected concepts without poisoning that memory with already implemented requests.','Match by concept, ask whether rationale still holds, and keep rejections distinct from built features and temporary deferrals.','Triage a night-theme request.','Close it because a vaguely similar issue is closed.','Find the durable theming rejection, show its rationale and ask whether it still holds; if the feature already exists, link implementation instead.','Repeated concepts reuse reviewed rationale without false rejection inference.','Similarity is a lead, not authority; maintainers may reconsider or distinguish the request.','回忆实质拒绝概念，不把已实现请求混入拒绝记忆。','按概念匹配，复核理由仍成立，并区别已实现与临时推迟。','分诊夜间主题请求。','相似问题已关闭就关闭新请求。','找到持久主题拒绝，展示依据并复核；若功能已实现则链接实现。','重复概念复用经审理由，无错误拒绝推断。','相似仅为线索，维护者可重议或认定不同。')
case('mechanical-enforcement','Mechanics to checks, judgment to review','机械规则检查、判断规则评审','evaluation','skills/engineering/retro/SKILL.md',15,23,
 'Turn syntactic mistakes into deterministic checks and reserve prose rules for judgment.','Inspect existing checks, repair their wiring first, then encode fixed patterns in the cheapest local guardrail.','Prevent forbidden deep imports.','Add remember not to deep import to the global prompt.','Wire the existing import checker into CI; add the forbidden-depth rule and verify it rejects a temporary violation.','The recurring violation is caught independently of instruction recall.','A check must distinguish forbidden from allowed cases; judgment cannot always be reduced to syntax.','语法错误转成确定检查，判断问题留给文字评审规则。','先检查现有检查并修接线，再用最便宜本地护栏编码固定模式。','防止禁止的深导入。','全局提示加入记得不深导入。','把已有导入检查接入CI，加深度规则并验证临时违规会失败。','重复违规不依赖记住指令即可拦截。','检查须区分允许与禁止；判断不总能化为语法。')
case('varied-interface-briefs','Differentiated design briefs','差异化设计简报','orchestration','skills/engineering/codebase-design/DESIGN-IT-TWICE.md',19,44,
 'Generate alternatives under intentionally different constraints instead of multiplying identical proposals.','Give each independent designer a different optimization objective, a shared vocabulary and the same required output schema.','Design a file-import interface.','Ask three agents to design the best interface.','Ask one to minimize entry points, one to support extensions, one to optimize the common caller; compare invariants, usage and hidden complexity.','Alternatives expose concrete tradeoffs rather than repeated first ideas.','Independent prompts do not guarantee independent ideas; compare actual differences.','用不同约束生成替代方案，而非倍增相同建议。','独立设计者各有优化目标，共享词汇与输出结构。','设计文件导入接口。','让三个代理各设计最佳接口。','一个最少入口，一个支持扩展，一个优化常见调用者；比较不变量、用法和隐藏复杂度。','备选揭示权衡而非重复首想法。','独立提示不保证独立思想，须比较实际差异。')
case('prototype-question','Question-shaped throwaway experiment','问题驱动的一次性实验','workflow','skills/engineering/prototype/SKILL.md',8,26,
 'Choose the prototype artifact by the uncertainty it must resolve and expose relevant state.','Distinguish logic/state from visual uncertainty; minimize setup, use scratch state and preserve the question and verdict.','Test whether undo semantics feel right.','Build a polished production-style UI with a real database.','Make one in-memory interactive state demo, show state after each action, exercise conflicting edits and capture the undo verdict.','The experiment answers the declared question with visible transitions.','A prototype verdict does not establish production robustness.','按待解不确定性选择原型产物，并暴露相关状态。','区别逻辑状态与视觉问题，最小启动成本，使用临时状态并保存问题和结论。','验证撤销语义是否合适。','构建精致生产界面并连接真实库。','一个内存状态交互演示，每动作展示状态，运行冲突编辑并保存撤销结论。','实验以可见转移回答声明问题。','原型结论不证明生产稳健性。')
case('anti-cue-evaluation','Remove presentation answer cues','消除呈现答案线索','evaluation','skills/productivity/teach/SKILL.md',99,110,
 'Keep an assessment from leaking its answer through presentation differences.','Make option lengths and formatting comparable, then give feedback based on the tested skill.','Create a retry-policy quiz.','Make the correct answer the only long, detailed option.','Use comparably detailed options, avoid unique emphasis and explain the policy only after the learner chooses.','Success is less attributable to option formatting alone.','Matching length cannot remove semantic clues or prove valid measurement.','避免测评通过呈现差异泄露答案。','选项长度格式可比，再按所测技能提供反馈。','编写重试策略测验。','正确选项是唯一冗长详细项。','选项详细程度相当，无独特强调，选择后才解释策略。','成功较少仅归因于格式线索。','长度相同不能去掉语义线索或证明测量有效。')

retired=next(c for c in DATA['candidates'] if c['key']=='core-matt-existing-189')
retired.update(status='rejected',reason='Retired legacy entry remains retired: the source causal claims about pretraining and attention are unverified. The narrower defined-vocabulary mechanism overlaps active #194 and does not justify a separate publication.',suggested_existing_ids=[189,194])
frontier=next(c for c in DATA['candidates'] if c['key']=='core-matt-frontier-integration')
frontier['sources'].append(src(R,'docs/engineering/implement-spec.md',54,68,'landed-commit frontier and isolated-worktree verification limits'))

# Persist fully read bodies and references; paths not yet semantically read remain pending.
read_bodies=['improve-codebase-architecture','pr','prototype','research','retro','setup-matt-pocock-skills','tdd','to-spec','to-tickets','triage','wayfinder','wizard']
read_bodies=['skills/engineering/'+x+'/SKILL.md' for x in read_bodies]
read_bodies += [f['path'] for f in BY_REPO[R]['files'] if f['path'].endswith('SKILL.md') and (f['path'].startswith('skills/in-progress/') or f['path'].startswith('skills/misc/') or f['path'].startswith('skills/productivity/'))]
read_refs=['skills/engineering/ask-matt/PHASE-BOUNDARIES.md','skills/engineering/codebase-design/DEEPENING.md','skills/engineering/codebase-design/DESIGN-IT-TWICE.md','skills/engineering/domain-modeling/ADR-FORMAT.md','skills/engineering/domain-modeling/GLOSSARY-FORMAT.md','skills/engineering/tdd/mocking.md','skills/engineering/tdd/tests.md','skills/engineering/triage/AGENT-BRIEF.md','skills/engineering/triage/OUT-OF-SCOPE.md','skills/productivity/writing-for-agents/SKILL-MECHANICS.md']
for p in read_bodies+read_refs:
 keys=[c['key'] for c in DATA['candidates'] if any(s['repo']==R and s['path']==p for s in c['sources'])]
 review(R,p,'Fully read procedure, input contract, branch/gate semantics, output, examples and limits. Extracted mechanisms linked below; skill wrappers remain composition evidence. Numeric context/reliability and learning-effect claims are not validated efficacy evidence.',keys)
save()
print(len(DATA['candidates']))
