from pathlib import Path
import json,collections,copy
n={'__name__':'core_helpers'};exec(Path(__file__).with_name('core-update.py').read_text(encoding='utf-8'),n)
r='anthropics/skills';p='skills/claude-api/shared/tool-use-concepts.md';src=n['src'];add=n['add']
k1=add('anthro-stream-commit-gate','Validate the whole streamed turn before acting','行动前验证完整流式轮次','tools',[(r,p,69,87,'Tolerant parser and final stop guard')],
 ['Gate client-side tool execution on completed generation, strict input parsing and the tool’s validation contract.','A streaming file-write call returns a parsed object while generation stopped at the output limit.','Accumulate the complete turn, inspect its termination state, reject refusal or cutoff, strictly parse available raw input, validate the contract, then apply the authorized effect.','Write the parsed file body immediately because the object has the required path and contents fields.','When the turn ended by cutoff, keep the destination unchanged, record incomplete generation, and retry under a bounded policy before any write.','A tolerant parse can produce a plausible object without proving the intended input was complete.','The final stop state, validation result and absence of premature effects can be checked.','Schema validity alone cannot detect every truncated-but-valid string. SDK parsing and streaming contracts vary; client gates cannot undo server-side effects already performed.'],
 ['客户端工具执行须通过生成完成、严格解析和工具契约验证。','流式写文件调用返回可解析对象，但生成因输出上限停止。','收集完整轮次，检查终止状态，拒绝拒绝响应或截断，严格解析可得原始输入并验证契约，再执行已授权副作用。','对象包含path与contents字段就立刻写入。','轮次因截断结束时保持目标不变，记录未完成生成，并在任何写入前按有界策略重试。','宽容解析可产生合理对象，却不证明原本输入完整。','可以检查终止状态、验证结果和无过早副作用。','模式正确无法发现所有截短但仍合法的字符串。SDK解析和流契约不同；客户端门禁不能撤销已发生的服务器副作用。'])
k2=add('anthro-contract-projection','Retain full validation beside a compatible schema','兼容模式旁保留完整验证','tools',[(r,p,537,562,'Wire subset and client constraints')],
 ['Keep the full business validation contract when a host accepts only a reduced schema representation.','A structured-output host accepts number types but does not enforce the owner’s nonnegative-price constraint.','Maintain the original validator, derive a compatible wire schema, and validate the returned data against every removed constraint before downstream use.','Trust the host’s strict-schema label after dropping the minimum-price constraint.','Send the supported schema projection, then reject a negative price with the original validator before creating the quote.','Transport compatibility does not imply the full policy was enforced.','The original constraints, omitted wire facets and final validation result can be compared.','The host’s actual supported subset must be verified. Full schema validation still does not prove source truth, authorization or semantic suitability.'],
 ['宿主仅接受缩减模式时，仍保留完整业务验证契约。','结构化输出宿主接受数字类型，却不执行非负价格约束。','保留原验证器，派生兼容传输模式；下游使用前核验被移除的每项约束。','删掉最低价格约束后，仍信任宿主严格模式标签。','发送支持的模式投影，报价创建前由原验证器拒绝负价格。','传输兼容不代表完整政策已经执行。','可以比较原约束、传输遗漏部分与最终验证结果。','需核实宿主实际支持子集。完整模式验证仍不证明来源真实、已授权或语义适合。'])
k3=add('anthro-complete-envelope','Preserve the complete protocol envelope','保留完整协议封套','context',[(r,p,130,147,'Full continuation state'),(r,p,442,452,'Opaque result union and replay')],
 ['Retain structured response state for continuation and derive human-readable text as a separate view.','An agent response contains readable text, a tool-call identity and an opaque continuation block.','Store the full envelope with typed blocks and matching identities; extract text for display while returning the unchanged required state on continuation.','Save only the first text block and rebuild the next request from its prose summary.','Display the text, but retain the raw tool and opaque blocks and bind the tool result to the original call identity.','Display text is not the complete operational state of a protocol.','The stored envelope, typed dispatch and result-to-call identity can be checked.','Retention, replay and signature rules are host-specific. Do not fabricate or decrypt opaque fields; apply data-handling rules and verify which transformations are allowed.'],
 ['续跑保留结构化响应状态，供人阅读文字另作视图。','代理响应含可读文字、工具调用身份与不透明续跑块。','完整保存类型化块和匹配身份；显示时抽取文字，续跑时按契约返回未修改的必要状态。','只保存首个文字块，再用摘要重建下个请求。','展示文字，但保留原工具块和不透明块，并把工具结果绑定原调用身份。','显示文字不是协议的完整操作状态。','可以检查保存封套、类型分派和结果对应调用身份。','保留、重放和签名规则依宿主而异。不可伪造或解密不透明字段；遵守数据处理规则并核实允许的变换。'])
composio=json.loads((n['OUT']/'harvest-composio.json').read_text(encoding='utf-8'))
old=next(c for c in composio['candidates'] if c['key']=='composio-error-directed-recovery');fields=['description','scenario','mechanism','bad','good','why','expected','boundaries']
k4=add('anthro-error-directed','Typed error-directed recovery','类型化错误指导恢复','tools',[(r,'skills/claude-api/shared/error-codes.md',203,267,'Typed category and subclass dispatch')],[old['content']['en'][f] for f in fields],[old['content']['zh'][f] for f in fields],legacy_keys=[old['key']],status='merged')
row=next(c for c in n['DATA']['candidates'] if c['key']==k4);row['reason']='Same error-class-directed recovery as the completed Composio method; exact SDK exception names remain frozen observations, not current API guarantees.'
for c in n['DATA']['candidates']:
 if c['key']=='core-anthro-coordinate-provenance':c['sources'].append(src(r,p,390,390,'Full screenshot coordinate space'))
ledger=n['OUT']/'core-anthro-api-blocks.json';d=json.loads(ledger.read_text(encoding='utf-8'))
for b in d['blocks']:
 if 1186<=b['id']<=1246 or 1332<=b['id']<=1335 or b['id'] in [574,881,883,890]:b['status']='read'
files={
 p:'Full578-line conceptual guide and all exact block occurrences read. Precise tool/parameter/routing contracts; eager streaming changes validation responsibility, tolerant parser can truncate silently, schema + stop + selective error guards before side effects; approval/interception hooks checked separately from loop ownership; full response and call-ID correlation, bounded paused-turn continuation; all multi-call results returned together; server/client execution boundaries, container reuse and actual return codes; dynamic discovery vs application-driven revocation, retained deferred definitions; memory per-user auth/storage and no-secret persistence; untrusted shell/path confinement; reduced wire schema versus full client validation and refusal/cutoff exceptions. Every current SDK hook/API namespace/version/model/availability/pricing/runtime isolation/no-retention guarantee and numeric threshold remains unverified. Schema-valid partial strings may still be silently incomplete; basename alone does not prove symlink-safe containment or collision-free downloads; executable allowlists plus operator rejection do not establish a safe shell capability boundary; paused-turn example replaces history rather than demonstrating general append-only continuity. Claimed measurable description lift has no local primary experiment.',
 'skills/claude-api/shared/error-codes.md':'Full276-line error guide and all exact block occurrences read. Structured error class/status and most-specific catch before base exception; deterministic auth/permission/shape errors require correction, transient quota/server/network classes have capped backoff; model/access ambiguity handled through metadata rather than guessed identifiers; wrong credentials/routes distinct from request-body faults. All exact HTTP/provider/model/API/deprecation/rate-header/error-class claims unverified. Blanket positive max_tokens and alternating-role advice disagree with newer documented zero-output and system-message forms elsewhere; API key embedded in code does not itself cause401 and leaked keys may still work. Network retries still require side-effect/idempotency analysis; fallback model changes invalidate model-comparison identity.'
}
for path,note in files.items():
 ids={o['block_id'] for o in d['occurrences'] if o['path']==path};pending=[i for i in ids if d['blocks'][i]['status']!='read'];assert not pending,(path,pending)
 n['review'](r,path,note,[k1,k2,k3] if path==p else [k4,'composio-metadata-capability-selection'])
 rr=next(x for rr in n['DATA']['repositories'] if rr['repo']==r for x in rr['coverage'] if x['path']==path);rr['exact_block_review']={'ledger':'core-anthro-api-blocks.json','unique_block_ids':sorted(ids),'all_occurrences_closed':True}
ledger.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
n['save']();print(n['DATA']['summary']['candidate_counts'],collections.Counter(b['status'] for b in d['blocks']))
