from pathlib import Path
import json,collections
n={'__name__':'core_helpers'};exec(Path(__file__).with_name('core-update.py').read_text(encoding='utf-8'),n)
r='anthropics/skills';p='skills/claude-api/shared/evals/cost-hillclimb.md';src=n['src']
k1=n['add']('anthro-joint-confirm','Confirm the selected configuration as a whole','整体确认选定配置','evaluation',[(r,p,307,314,'Joint configuration confirm'),(r,p,330,346,'Registered adoption gates')],
 ['After selecting interacting settings in separate stages, evaluate the final combination on fresh runs against criteria fixed before confirmation.','A search selects a model, revises its prompt and lowers its reasoning setting in three separate stages.','Freeze the complete selected tuple and the comparison basis; confirm quality, cost and required behavioral conditions together rather than adding the favorable stage results.','Add each stage’s best saving and quality gain and publish the sum as the final configuration’s performance.','Run the final model/prompt/setting tuple on the confirmation cases with fixed quality and cost criteria; report those results and any failed criterion.','Individually selected components can interact and favorable selection runs are not a joint observation.','The final configuration identity, predeclared criteria and confirmation records can be checked.','Fresh runs of reused selection cases are not an untouched test set. Confirmation requires adequate replication and comparable state; a predicted mechanism does not by itself prove production robustness.'],
 ['分阶段选择相互作用的设置后，对最终组合做新运行，并按确认前固定的标准评估。','搜索先选模型，再修提示，最后降低推理设置。','冻结完整配置与比较依据，同时确认质量、成本和所需行为，不把各阶段有利结果相加。','把各阶段最佳节省与质量提升相加，称为最终配置表现。','最终模型、提示、设置组合在确认案例上运行，使用固定质量和成本标准，报告结果与未通过条件。','分别选择的组成部分可能相互作用，最佳选择运行也不是整体观察。','可以检查最终配置身份、预先标准和确认记录。','重复选择案例的新运行不等于未触碰测试集。确认需充分重复与可比状态；预测机制本身不证明生产稳健性。'])
k2=n['add']('anthro-revisitable-pruning','Keep pruning assumptions and deferred choices','保留剪枝假设与暂缓选项','workflow',[(r,p,78,120,'Explicit monotonicity and conservative screen'),(r,p,161,185,'Noisy promotion and revisitable deferral'),(r,p,294,305,'Earlier verdict expires after context change')],
 ['Record the assumptions behind a search exclusion and retain the candidate so it can be reopened when evidence or prerequisites change.','A cost search skips a configuration using a measured profile from a different setting, then revises the prompt.','Store the profile and context identity behind the decision, name the ordering assumptions, keep uncertain candidates deferred, and re-probe affected choices after recalibration or prompt changes.','Permanently discard the configuration because one mismatched cost projection looked unfavorable.','Mark it deferred with the projection basis; after the prompt changes, use a matching profile and a bounded re-probe before ruling it out.','A contextual estimate is not a timeless verdict about an unmeasured candidate.','The deferred list, decision prerequisites and reopening trigger are inspectable.','Pruning can still miss a winner if ordering or projection assumptions fail. The source’s model/effort monotonicity and numeric error bands are unverified workload claims; this method does not guarantee a globally cheapest choice.'],
 ['记录搜索排除背后的假设，保留候选，以便证据或前提变化时重新打开。','成本搜索按另一设置的测量剖面跳过某配置，随后又修改提示。','保存决定依据的剖面与上下文身份，点名排序假设，不确定候选暂缓；校准或提示变化后重探受影响选择。','一次不匹配成本预测不利，就永久丢弃配置。','标记暂缓并记录预测依据；提示变化后使用匹配剖面并做有界重探，再决定排除。','情境估计不是对未测候选的永久判决。','可以检查暂缓列表、决定前提与重新打开触发条件。','排序或预测假设失效仍会漏掉赢家。源模型与推理设置单调性及数字误差带是未核验任务主张；此方法不保证全局最低成本。'])
for c in n['DATA']['candidates']:
 if c['key']=='core-anthro-heldout-channel':c['sources'].append(src(r,p,350,359,'Selection is not holdout'))
 if c['key']=='core-counter-semantics-before-totals':c['sources'].append(src(r,p,393,408,'Prompt echoes versus action census'))
 if 175 in c['suggested_existing_ids']:c['sources'].append(src(r,p,393,408,'Static instruction markers are not engagement receipts'))
ledger_path=n['OUT']/'core-anthro-api-blocks.json';d=json.loads(ledger_path.read_text(encoding='utf-8'))
for b in d['blocks']:
 if 1352<=b['id']<=1368 or 1556<=b['id']<=1567:b['status']='read'
ids={o['block_id'] for o in d['occurrences'] if o['path']==p};assert all(d['blocks'][i]['status']=='read' for i in ids)
ledger_path.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
n['review'](r,p,'Full442-line guide and all exact block occurrences read. Quality-constrained cost objective; check caching/config before comparisons and measured per-cell billing/usage; model×effort search names tier-monotonicity and cost assumptions, conservative uncertainty-aware inclusion and matched-profile deferral/reopening; noisy near-floor pass/fail repeats before pruning; costly quality reference separately declared; prompt tuning frozen to selected model, re-probe earlier failed cells after changed context, fresh joint confirm of model/prompt/setting with preregistered quality/cost/mechanism gates; selection set distinguished from true holdout, baseline/build variance, forecasts/falsifiers before measurements, whole-traffic router evaluation; engagement census excludes prompt echoes; instruction mass vs actions and output-quality tradeoffs. Numerous self-described internal measured programs, percentages, token/cost ratios, data-retention/API/effort/cache facts and model/topology superiority are unsupported by locatable raw experiments in this repo and are not admitted as efficacy. Cost/quality monotonicity can fail; fixed sample counts and best-baseline-repeat floor do not establish noninferiority. Constant action counts need not imply ignored preventive text; literal marker subtraction is weaker than actual tool-result evidence. “Near-zero engagement means dead weight” and cheaper-help-never-addition are overbroad. Pruning/search heuristics do not guarantee the best untested cell; apparent mechanism alone does not establish robustness.',[k1,k2,'core-anthro-heldout-channel','core-counter-semantics-before-totals'])
row=next(x for rr in n['DATA']['repositories'] if rr['repo']==r for x in rr['coverage'] if x['path']==p);row['exact_block_review']={'ledger':'core-anthro-api-blocks.json','unique_block_ids':sorted(ids),'all_occurrences_closed':True}
rr=next(x for x in n['DATA']['repositories'] if x['repo']==r);rr['source_flaw_evidence'].append({'claim':'Cost-hillclimb cites self-described internal programs and workload-specific monotonicity, savings and team-superiority numbers without locatable raw experiments; those are unverified source claims, while the registered and reversible comparison procedure can be extracted independently.','sources':[src(r,p,58,90,'Search regularities and measured claims'),src(r,p,187,214,'Internal program narrative'),src(r,p,316,326,'Topology superiority claim')]})
for c in n['DATA']['candidates']:
 seen=set();unique=[]
 for s in c['sources']:
  ident=(s['repo'],s['commit'],s['path'],s['line_start'],s['line_end'],s['section'])
  if ident not in seen:seen.add(ident);unique.append(s)
 c['sources']=unique
n['save']();print(n['DATA']['summary']['candidate_counts'],collections.Counter(b['status'] for b in d['blocks']))
