from pathlib import Path
_namespace={'__name__':'core_helpers'}
exec(compile(Path(__file__).with_name('core-update.py').read_text(encoding='utf-8'),'core-update.py','exec'),_namespace)
globals().update({k:v for k,v in _namespace.items() if not k.startswith('__')})

R='multica-ai/andrej-karpathy-skills';P='skills/karpathy-guidelines/SKILL.md'
keys=[]
keys.append(add('karpathy-assumption-disclosure','Disclose consequential assumptions before acting','行动前公开关键假设','workflow',[(R,P,13,21,'Think Before Coding')],
['Make uncertain requirements and competing interpretations explicit before an irreversible choice.','Implement an export request whose audience, fields and delivery destination are unspecified.','Inspect what is known, list the consequential unknowns, present plausible interpretations and resolve only the decisions that change the implementation.','Assume all records, every field and a public file destination without telling the user.','State the unresolved export scope and sensitive-field choice; offer concrete supported interpretations; use the selected scope in implementation.','The decision-maker sees choices that would otherwise be silently invented.','The resulting requirement record names chosen scope, fields and destination, with assumptions distinguished from facts.','Explore discoverable facts first; trivial settled details do not require an interview.'],
['在作出难以撤回的选择前，明确不确定需求和不同解释。','实现一个尚未明确受众、字段及交付位置的导出请求。','检查已知信息，列出关键未知项，呈现合理解释，仅解决会改变实现的决策。','不告知用户就假定导出全部记录、所有字段和公开文件。','指出导出范围与敏感字段尚未确定，给出具体可行解释，并按选定范围实现。','决策者能看到原本可能被默默虚构的选择。','需求记录注明范围、字段和位置，并区分假设与事实。','先探索可查事实；已明确的琐碎细节无需反复询问。'],legacy_keys=['K1']))
keys.append(add('karpathy-minimum-necessary-code','Implement only presently required complexity','只实现当前需求所需的复杂度','prompt',[(R,P,23,33,'Simplicity First')],
['Defer speculative features and abstractions until a concrete requirement justifies them.','Add one percentage-discount calculation to an existing service.','Implement the actual calculation with its required input rules, and introduce strategy/configuration layers only when a real use case needs them.','Add multiple strategy classes, plugin configuration and notifications for one requested percentage calculation.','Add a small percentage calculation with required validation; leave other discount modes outside this task.','The implementation complexity has a traceable reason.','Every introduced feature or abstraction corresponds to a present requirement.','Necessary safety, validation and existing architectural contracts still apply; fewer lines alone is not success.'],
['在具体需求证明必要之前，延后推测性的功能与抽象。','给现有服务增加一个百分比折扣计算。','实现真实计算与必要输入规则；只有实际用例需要时才引入策略或配置层。','为单一百分比计算增加多种策略类、插件配置与通知。','增加小范围百分比计算及必要验证，其他折扣模式留在任务之外。','实现的复杂度有可追溯理由。','新增功能和抽象均对应当前需求。','必要安全、验证和既有架构契约仍须遵守；代码少不等于成功。'],legacy_keys=['K2']))
keys.append(add('karpathy-surgical-edit','Make request-traceable surgical edits','让局部编辑逐行对应请求','safety',[(R,P,35,49,'Surgical Changes')],
['Bound authorized edits to the requested behavior and only clean up orphans created by those edits.','Fix empty-email handling in a validator with unrelated username logic.','Change the email defect, retain surrounding style and behavior, remove only newly unused code and report unrelated findings separately.','Fix email handling while reformatting the whole file and tightening username policy.','Change the empty-email path; keep username rules and formatting; remove only the import made unused by this fix.','The diff preserves nearby behavior outside the authorized change.','Every changed line is explained by the request or a direct consequence of the fix.','Necessary cross-file changes are allowed when causally required; this is a bounded-write rule, not a read-only prohibition.'],
['将已授权编辑限定在请求行为内，只清理本次编辑产生的孤立代码。','修复包含无关用户名逻辑的验证器中空邮件处理。','修改邮件缺陷，保留周边风格和行为，仅删除新增无用代码，并单独报告无关发现。','修复邮件时顺便格式化全文并加强用户名规则。','只改空邮件路径，保留用户名规则与格式，仅移除因本次修复不再使用的导入。','差异保留授权变更范围之外的相邻行为。','每条修改都能由请求或修复的直接结果解释。','因果上必要的跨文件修改允许进行；这是有界写入规则，不是只读禁止。'],legacy_keys=['K3']))
keys.append(add('karpathy-observable-goals','Reformulate tasks as observable goals','把任务改写为可观察目标','workflow',[(R,P,51,67,'Goal-Driven Execution')],
['Translate vague actions into observable success criteria and verify each meaningful step.','Fix sessions remaining active after a password change.','State the invalidation behavior, reproduce it with a failing oracle, implement the change and verify that the same oracle plus relevant regressions pass.','Review and improve authentication with no named failing behavior or check.','Specify old-session rejection after password change; demonstrate failure first; implement invalidation; run that check and relevant session regressions.','The loop terminates on evidence of the desired behavior rather than a narrative of activity.','The verification records show the stated defect before the change and the intended behavior after it.','The oracle must detect the defect; source tie-order examples checking only scores do not establish tied-identity order.'],
['把模糊动作转成可观察成功条件，并验证有意义的步骤。','修复修改密码后旧会话仍然有效的问题。','明确会话失效行为，用失败判据复现，再实现修改并验证原判据及相关回归通过。','没有指明失败行为或检查，就泛泛审查和改善认证。','指定改密码后旧会话被拒绝，先展示失败，再实现失效逻辑，运行该检查和相关会话回归。','循环依据目标行为的证据结束，而非活动叙述。','验证记录展示修复前的缺陷与修复后的预期行为。','判据必须检出缺陷；来源中仅检查分数的同分排序示例不能验证身份次序。'],legacy_keys=['K4','K6']))

for f in BY_REPO[R]['files']:
    p=f['path']
    if p.endswith('.json'):review(R,p,'Marketplace/plugin packaging metadata repeats identity, version and MIT declaration; no separate agent method.',excluded='Repository packaging manifest, not a method-bearing instruction body.')
    elif p=='CURSOR.md':review(R,p,'Harness-specific rule placement and alwaysApply wrapper differs from skill activation; mirrors should be kept synchronized. No extra substantive behavioral rule.',keys)
    elif p=='EXAMPLES.md':review(R,p,'All four principle examples reviewed, including hidden scope, speculative abstraction, style drift, orphan cleanup and per-step checks. Tie-order test at L468-486 checks only scores and cannot detect swapped tied identities; sample efficacy narrative is rejected, core verification principle retained.',keys)
    elif p=='README.zh.md':review(R,p,'Chinese translation reviewed against English principles and caution tradeoff. Same four methods, translated exposition/install guidance; no additional K5/K6 principles.',keys)
    else:review(R,p,'Four principle bodies reviewed; wrappers/installation exposition differ but core assumptions, required complexity, surgical edits and observable goals match. Observations are Karpathy-inspired secondary formulation, not efficacy experiments.',keys)
finish_repo(R,[{'key':'karpathy-four-principles','paths':[f['path'] for f in BY_REPO[R]['files'] if not f['path'].endswith('.json')],'candidate_keys':keys,'summary':'CLAUDE.md, Cursor rule and published skill carry the same four principles with distinct host wrappers; English/Chinese README and full examples provide exposition rather than additional original principles.'}],['All 9 tracked files dispositioned. No root LICENSE; MIT is declared in skill, README and plugin metadata.','One example oracle defect recorded; no claimed empirical improvement imported.'])
save()
