from pathlib import Path
import json
n={'__name__':'core_helpers'};exec(Path(__file__).with_name('core-update.py').read_text(encoding='utf-8'),n)
r='nextlevelbuilder/ui-ux-pro-max-skill';add=n['add'];src=n['src'];review=n['review']
def close(path,note,keys):
 meta=next(f for f in n['BY_REPO'][r]['files'] if f['path']==path);review(r,path,note,keys)
 row=next(f for rr in n['DATA']['repositories'] if rr['repo']==r for f in rr['coverage'] if f['path']==path);row['review_evidence']['read_range']={'line_start':1,'line_end':meta['lines']}
 for f in n['BY_REPO'][r]['files']:
  if f['path']==path or f['hash']!=meta['hash']:continue
  proof={'repo':r,'commit':n['BY_REPO'][r]['commit'],'path':path,'hash':meta['hash'],'proof':'Git-blob SHA-256 identity; canonical full body read'}
  review(r,f['path'],note,keys,duplicate_of=proof)
k=add('nextlevel-path-roots','Keep tool roots separate from project roots','工具根与项目根分开','tools',[(r,'.claude/skills/brand/SKILL.md',23,25,'Skill base versus project working directory'),(r,'.claude/skills/design-system/SKILL.md',51,53,'Shared helper path contract')],
 ['Resolve installed helper code from its skill base while resolving project artifacts from the declared project working directory.','A brand helper reads docs/brand-guidelines.md and writes project design tokens.','Name both roots; invoke the installed helper by its resolved path without changing the project cwd, and resolve its inputs and outputs according to the helper contract.','Change into the installed skill directory, then run the helper and accidentally write project files into the package.','Run the absolute helper path from the project root; verify docs/brand-guidelines.md and generated token files resolve inside that project.','The location of executable code is separated from the location of task data.','The invoked path, cwd and resolved artifact paths can be inspected.','Some helpers use explicit path arguments or another documented base. Check the actual contract; root separation alone does not enforce path confinement or permission.'],
 ['安装的辅助代码按技能根解析，项目产物按声明的项目工作目录解析。','品牌辅助工具读取docs/brand-guidelines.md并写入项目设计令牌。','明确两种根；使用解析后的工具绝对路径执行，保持项目cwd，按契约解析输入输出。','切换到安装技能目录执行工具，误把项目文件写进包内。','从项目根执行工具绝对路径，核对品牌文档和生成令牌都解析到该项目。','把可执行代码位置与任务数据位置分开。','可以检查调用路径、cwd与产物解析路径。','有些工具使用显式路径参数或其他基准，应检查实际契约。根分离本身不强制路径约束或权限。'])
k116=n['merged']('nextlevel-existing-116',116,[(r,'.claude/skills/banner-design/SKILL.md',56,62,'Text-free visual layer and editable HTML copy')])
k173=n['merged']('nextlevel-existing-173',173,[(r,'.claude/skills/banner-design/SKILL.md',64,70,'Capture gap returns source and pending export')])
close('.claude/skills/banner-design/SKILL.md','Full146-line body read. Narrow banner scope, gatherpurpose/format/content/verifiedbrand/style/variants; reference-directed art directions with supplied/CSS/authorizedgeneration fallback; image prompts text-free so copy remainseditableaccessibleHTML; actualviewportcapture/export-dimension/crop/font checks and honestcapturepending output; sidebyside alternatives anditeration. Platformdimensions/safezone/Meta-textpenalty/DPI/numericrules are unverified domain defaults; broad file-path disclosure ban conflicts with its outputfilepaths. No source tools or image generation executed.',[k116,k173])
close('.claude/skills/brand/SKILL.md','Full109-line body read. Skill-base helper paths versus projectcwd; source brandguideline→JSON/CSS tokens, stopbefore overwriting discoveredexistingtoken/CSS/Tailwind sources and reviewownership beforeintentionalforce; route namedsubcommand torefs, extractbrandcontext/validateassets/colorpalette through helpercontracts. Essentialrefs and runtime/data relationships remain pending appropriate inspection; no correctness/performance audit required.',[k,'core-leon-semantic-token-contract'])
close('.claude/skills/slides/SKILL.md','Full45-line body read. Taskscope and intent/subcommand→namedreference dispatch; explicit helperbase versus projectartifact paths; contextual layout/copy/strategy knowledge routedasneeded. Native64-bitcode/render imports are supporting domain bindings, not a new workflow; references pending.',[k,'composio-intent-reference-routing'])
close('.claude/skills/design-system/SKILL.md','Full249-line body read. Primitive→semantic→component tokencontracts, sharedbrand/sourceCSSauthority, parameter/state matrices and rolehandoff; projectdata roots distinct from skill/siblinghelperbases; stagedgoal/strategy→layout/type/color/background/animation→HTML→validation using contextualdatatables. Fixedsparkline/position heuristics and persuasion/engagementclaims are unverified; exemplar chart hardcodescolors despite token-onlydirection, CDN/background/workingexample remain supportingfacts not observedexecution. Essentialrefs and supportcode/data inspected separately.',[k,'core-leon-semantic-token-contract','composio-intent-reference-routing'])
n['save']();print(n['DATA']['summary']['candidate_counts'])
