"""Persist only manually reviewed support-role cohorts, with structural evidence."""
import json,pathlib
OUT=pathlib.Path('D:/Projects/prompt-context-patterns-refresh')
COMMIT='ef648e01899ba3e8dc6371642deaaf64b4477775'
rows=json.loads((OUT/'.tools/ecc/support-shapes.json').read_text(encoding='utf-8'))
decisions=json.loads((OUT/'docs/audit/ecc-scope-decisions.json').read_text(encoding='utf-8'))
by_path={r['path']:r for r in decisions}
def record(r,purpose,kind='excluded',extra=None):
 evidence={'commit':COMMIT,'hash':r['sha256'],'inspector':'ecc-support-shapes.mjs','method':'TypeScript AST parsed as data (zero parse diagnostics), then actual leading contract, imports/call relationship, declarations and representative assertion labels inspected. Long literal payload index inspected for purpose; ordinary fixtures, SQL and browser UI implementation are outside normative prompting scope. No upstream imports or execution.', 'leading_contract':r.get('leading_comment',r.get('first_lines','')),'imports':r.get('imports',[]),'declarations':r.get('symbols',[]),'representative_assertions':r.get('checks',[])[:3], 'literal_locators':[{'start_line':l['start'],'end_line':l['end'],'hash':l['sha256'],'owners':l['owners']} for l in r.get('literals',[]) if l['chars']>=300], 'execution':'none'}
 if extra:evidence.update(extra)
 by_path[r['path']]={'path':r['path'],'depth':'scope-inspected-excluded' if kind=='excluded' else 'contract-ranges-reviewed','disposition':kind,'classification':'local-test-or-test-support' if r['path'].startswith('tests/') else 'implementation-support','reason':purpose,'proof':evidence,'review_kind':'scoped-relevance','review_evidence':{'ledger':'ecc-scope-decisions.json','record':r['path'],'method':'See concrete leading contract, import/declaration/assertion/literal locator evidence in proof.'}}
# Reviewed all 0..363 test-role rows; non-AST Python/JSON fixtures are separate.
for r in rows:
 if r['path'].startswith('tests/') and 'parse_errors' in r:
  assert not r['parse_errors']
  relationship=', '.join(x for x in r.get('imports',[]) if x.startswith('.'))
  label='; '.join(r.get('checks',[])[:2])
  purpose='Local deterministic regression, static surface assertion, fixture fake or test runner support. '
  if relationship:purpose+='It imports/tests '+relationship+'. '
  if label:purpose+='Actual assertion examples: '+label+'. '
  else:purpose+='The reviewed declarations/leading contract identify '+', '.join(x['name'] for x in r.get('symbols',[])[:5])+' as fixture or test dispatch logic. '
  purpose+='Scope inspected as implementation evidence, not a completed test run, normative instruction corpus or experimental efficacy result. Embedded long payloads inspected as generated metadata, synthetic protocol/session/config states, SQL or child-process fakes; no distinct unreviewed agent/judge workflow was identified in this partition. Canonical instructions and actual provider-evaluation methodology are reviewed separately. A test title/assertion string does not prove live native behavior.'
  record(r,purpose)
full_js={'scripts/lib/context-profile-proposal.js','scripts/lib/context-profile-interactive.js','scripts/dev/generate-skill-triggers.js'}
range_methods={
 'scripts/claw.js':([[82,184]],'Complete prompt composition and calling boundary read: heading-labeled system/history/user blocks are one ordinary prompt, not native roles. Caller input remains data; current tool/provider permission is not created by session storage. Token estimate is a character proxy. Reuses scoped-memory, compositional slots and typed launch; no new method.'),
 'scripts/lib/llm-summary.js':([[116,178]],'Complete session-summary prompt and output contract read: decisions, solved problems, changed files, unfinished tasks and next-session context are distinct durable slots. Recorded conversation is prior evidence, not new task authority; prose format is not factual verification. Subprocess skip markers provide cooperative self-event recursion protection, not host containment. Shared memory/phase-compaction methods.'),
 'scripts/hooks/session-start.js':([[695,761]],'Complete prior-session historical-only injection boundary read. Match current project/worktree before injecting, freeze summary with explicit stale-by-default skill arguments, recheck current working-tree state and require current user intent before reexecution. Prior work almost-certainly-done is an unsupported heuristic, not proof. Shared current-state-memory/untrusted-source-data methods; the rest is scoped lifecycle implementation.'),
}
for r in rows:
 if not r['path'].startswith('scripts/') or 'parse_errors' not in r or r['path'] in full_js:continue
 assert not r['parse_errors']
 contract=r.get('leading_comment','').replace('\n',' ').strip()
 relationship=', '.join(x for x in r.get('imports',[]) if x.startswith('.'))
 symbols=', '.join(x['name'] for x in r.get('symbols',[])[:10])
 purpose='Purpose inspected from actual AST/source contract: '+(contract[:420] if contract else 'Declared '+symbols)+'. '
 if relationship:purpose+='Calls/consumes '+relationship+'. '
 purpose+='This is ECC CLI dispatch, configuration/installation/session persistence, declared-output projection, local hook/tool plumbing, browser UI or deterministic validation support. Reviewed declarations, imports and literal-role index connect it to separately reviewed canonical instructions; pure SQL, CSS/HTML, GraphQL, argv, help text and fixture state do not create an independent prompt method. Runtime completeness, native host permissions, model efficacy and all branches/tests are not claimed. No source code or child process executed.'
 if r['path'] in range_methods:
  ranges,detail=range_methods[r['path']];purpose=detail+' '+purpose
  record(r,purpose,'analyzed',{'read_ranges':ranges,'scope_method':'Actual complete embedded prompt range plus AST purpose/relationships.'})
 else:record(r,purpose)
full_python={'src/llm/prompt/builder.py','src/llm/prompt/templates/__init__.py','src/llm/tools/executor.py'}
for r in json.loads((OUT/'.tools/ecc/python-shapes.json').read_text(encoding='utf-8')):
 if r['path'] in full_python:continue
 purpose=(r['doc'] or 'Local typed module/test support')+'. Actual imports: '+', '.join(r['imports'][:8])+'. Actual declarations: '+', '.join(s['name'] for s in r['symbols'][:10])+'. '
 purpose+='Python AST/docstring/complete long literal scope inspected as data. This is provider SDK adaptation, local UI/terminal utility, or deterministic regression/fixture implementation; its relationship to the separately fully read prompt builder, tool executor and canonical skills is explicit in imports/declarations. Embedded SDK/operator setup contracts and synthetic SQL were read, not executed; no independent reusable prompt method. Provider compatibility, detector accuracy, 100% local-processing statements and marketing model counts remain unverified. Complete runtime correctness and all assertion bodies are outside this analysis.'
 by_path[r['path']]={'path':r['path'],'depth':'scope-inspected-excluded','disposition':'excluded','classification':'python-implementation-or-test-support','reason':purpose,'proof':{'commit':COMMIT,'hash':r['sha256'],'inspector':'ecc-python-scope.py','doc':r['doc'],'imports':r['imports'],'declarations':r['symbols'],'literal_locators':[{'start_line':l['start'],'end_line':l['end'],'hash':l['sha256']} for l in r['literals']],'execution':'none'},'review_kind':'scoped-relevance','review_evidence':{'ledger':'ecc-scope-decisions.json','record':r['path'],'method':'Python AST and actual module relationships plus complete long string/docstring payload review.'}}
full_docker={'docker/context-profiles/README.md','docker/context-profiles/complex-eval/DESIGN.md','docker/context-profiles/ai-eval-lib.js','docker/context-profiles/complex-eval/verify-checks.js','docker/context-profiles/complex-eval/build-corpus.js','docker/context-profiles/complex-eval/cases3/chained-tickets/files/CONTRIBUTING.md','docker/context-profiles/complex-eval/cases3/production-ready/files/docs/production-bar.md','docker/context-profiles/complex-eval/reference4/recurring-incident/docs/handoff.md','docker/context-profiles/complex-eval/reference4/recurring-incident/docs/runbooks/idempotency.md','docker/context-profiles/complex-eval/naive4/recurring-incident/HANDOFF.md'}
json_rows=json.loads((OUT/'.tools/ecc/json-shapes.json').read_text(encoding='utf-8'))
json_index={r['path']:r for r in json_rows}
virtual=json.loads((OUT/'.tools/ecc/json-virtual-shapes.json').read_text(encoding='utf-8'))
blob_index={r['path']:r for r in json.loads((OUT/'.tools/ecc/support-blobs.json').read_text(encoding='utf-8'))}
queries={s['text'].strip():{'path':r['path'],'pointer':s['pointer'],'body_hash':s['hash']} for r in json_rows for s in r['method_fields'] if s['pointer'].endswith('/query')}
for r in rows:
 if not r['path'].startswith('docker/') or r['path'] in full_docker or r['path'].endswith('.json'):continue
 if r['path'].endswith('/query.md'):
  body=blob_index[r['path']]['text'].strip();match=queries.get(body);assert match,r['path']
  by_path[r['path']]={'path':r['path'],'depth':'complete-query-body-reviewed-via-verified-corpus-equivalence','disposition':'analyzed','classification':'evaluation-query-example','reason':'The entire task query was actually read in the frozen JSON corpus. Compared complete occurrence body after outer-whitespace normalization; only final newline/outer whitespace differs. Concrete task: '+body+' This is a domain evaluation example of protected acceptance, preserving contract and scoped work; it is not promoted to a separate domain API pattern. No task executed.','proof':{'commit':COMMIT,'hash':r['sha256'],'canonical':match,'equivalence':'Entire Markdown text stripped of outer whitespace equals the actually read corpus query; no other body or wrapper exists.','execution':'none'},'review_kind':'verified-equivalence','review_evidence':{'ledger':'ecc-scope-decisions.json','record':r['path'],'method':'Complete body equality to actually read corpus task field, plus explicit whitespace-only occurrence delta.'}}
 elif 'parse_errors' in r:
  purpose='Development fixture/grader/native-discovery/deployment acceptance support. Actual source contract: '+r.get('leading_comment',r['first_lines']).replace('\n',' ')[:360]+'. Actual declarations: '+', '.join(s['name'] for s in r.get('symbols',[])[:8])+'. Imports: '+', '.join(r.get('imports',[]))+'. '
  purpose+='Relationships and complete literal-role index scoped; fixture/reference implementations, HTTP/crypto/payment/math recipes, local assertions and environment plumbing are outside normative skill prompting. The fully read DESIGN and ai-eval-lib own the experiment methodology. No grader, SDK, install or runtime test was run, and no efficacy or production-safety claim is inferred.'
  record(r,purpose)
 elif r['path'].endswith(('.md','.txt')):
  text=blob_index[r['path']]['text'];headings=[l for l in text.splitlines() if l.startswith('#')]
  by_path[r['path']]={'path':r['path'],'depth':'scope-inspected-excluded','disposition':'excluded','classification':'domain-evaluation-fixture-document','reason':'Actual opening content and complete heading structure inspected: '+r['first_lines'].replace('\n',' ')[:350]+'. This document is fixture/API/domain evidence or generated changelog input/output for the separately reviewed hidden-graded experiment; it specifies a synthetic service contract or incident, not an additional reusable prompt/context method. Its fixture/reference role is declared by DESIGN and build-corpus. No production fact or financial guarantee adopted; full product/domain correctness audit is outside scope.','proof':{'commit':COMMIT,'hash':r['sha256'],'read_ranges':[[1,min(22,r['lines'])]],'headings':headings,'relationship':'complex-eval/build-corpus.js collects fixture files; ai-eval-lib.js stages them as data; hidden graders/reference overlays judge the same synthetic task.','execution':'none'},'review_kind':'scoped-relevance','review_evidence':{'ledger':'ecc-scope-decisions.json','record':r['path'],'method':'Actual fixture text opening/structure and explicit evaluator relationship.'}}
for r in json_rows:
 corpus=r['path'].startswith('docker/context-profiles/') and '/tasks/' in ' '.join(s['pointer'] for s in r['method_fields'])
 embedded=[v for v in virtual if v['path'].split('#',1)[0]==r['path'] and not v['path'].startswith('package.json#')]
 purpose='Complete JSON structure parsed as data. Actual top-level fields: '+', '.join(r['top_keys'])+'. '
 if corpus:
  purpose+='All selection/task query, sampling and expected-route fields were read in full, including no-workflow/mention-only/exclusion/policy-negative probes and versioned sequential-ticket/recurring-incident variants. Embedded source/grader payloads were AST scoped by real declarations, imports and literal roles; pure domain API code is excluded, not claimed fully audited. Reference/panel methodology is owned by DESIGN and ai-eval-lib; IDs and expected routes are authored labels, not evidence of retrieval efficacy. '
 elif r['path'].startswith('schemas/'):
  purpose+='Machine validation shape consumed by the actual typed configuration, hook, memory, installer and state-store modules. Required keys, enums, bounds and additionalProperties are declarative data contracts; schema presence alone does not prove enforcement, provider support, authorization or factual correctness. No independent prompt method. '
 elif r['path'].startswith('manifests/'):
  purpose+='Configuration/catalog/curation metadata consumed by context registry, profile compiler, build-pi-core and install manifests. This selects reviewed source resources and discovery modes; paths, trigger phrases and installation capabilities are metadata, not extra authority or proof of live readiness. Exact canonical instructions were separately read. '
 elif r['path'].startswith('hooks/'):
  purpose+='Actual event/matcher/runtime registration and sidecar metadata used by hooks-config plus bootstrap/dispatchers. Event/phase and sync/async lanes are inspected as interface configuration; current host semantics are not established by a config file. Production versus reference hook graph and silent-output contract are reviewed separately in hooks/README. '
 elif r['path']=='greptile.json':
  purpose+='All four custom review instructions were read in full: privileged-workflow trust, untrusted CLI/path/URL inputs, agent prompt/permission/persistence review and accurate distribution claims. These instantiate already captured failure-proof, trust-boundary and live-state methods; the remaining fields configure review UI/routing rather than new prompting logic. '
 else:
  purpose+='Package/plugin/MCP/project-stack/generated-command-registry or synthetic test fixture data. Actual fields and representative authored descriptions establish its role; it is consumed by the reviewed CLI/install/schema/test interfaces. Domain reference implementations are local grader controls, not published independent skill patterns. '
 purpose+='No external service, provider, installer or fixture was executed; configured support, historical counts and vendor capability descriptions remain source assertions.'
 by_path[r['path']]={'path':r['path'],'depth':'json-contract-and-method-fields-reviewed' if corpus or r['path']=='greptile.json' else 'scope-inspected-excluded','disposition':'analyzed' if corpus or r['path']=='greptile.json' else 'excluded','classification':'evaluation-corpus-data' if corpus else 'configuration-schema-or-fixture-support','reason':purpose,'proof':{'commit':COMMIT,'hash':r['sha256'],'inspector':'ecc-json-scope.py','top_keys':r['top_keys'],'all_keys':r['all_keys'],'method_fields':[{'pointer':s['pointer'],'hash':s['hash'],'chars':s['chars']} for s in r['method_fields']],'embedded_source_scope':[{'pointer':v['path'].split('#',1)[1],'hash':v['sha256'],'imports':v.get('imports',[]),'declarations':v.get('symbols',[]),'parse_errors':v.get('parse_errors',[])} for v in embedded],'execution':'none'},'review_kind':'scoped-relevance','review_evidence':{'ledger':'ecc-scope-decisions.json','record':r['path'],'method':'Structured-field role inspection and actual consumer relationship; corpus queries fully read, embedded domain source scoped through AST.'}}
for r in json.loads((OUT/'.tools/ecc/shell-shapes.json').read_text(encoding='utf-8')):
 method=r['path'] in {'scripts/gan-harness.sh','scripts/orchestrate-codex-worker.sh','scripts/sync-ecc-to-codex.sh'}
 purpose='Actual shell/PowerShell header, declarations, real CLI call relationship and all heredoc bodies inspected as data. Opening contract: '+r['first_lines'].replace('\n',' ')[:350]+'. '
 if method:
  purpose+='Complete embedded worker/tool/rule prompt bodies reviewed: task-file plus bounded ownership/output slots; source-file canonical rule delegation; generator/evaluator task, same rubric and bounded feedback/plateau loop. Reuses lane ownership, source pointers, protected acceptance and bounded optimization. Prose authority and current host execution flags are not native containment; histogram/weighted score and source existence are not verified functional success. '
 else:purpose+='This is configuration patching, installer delegation, Git gate, local acceptance environment or release/version maintenance implementation, linked to the separately reviewed canonical skill/command/host contract. No independent normative prompting mechanism beyond the inspected output/operator snippets. '
 purpose+='No shell or PowerShell source was executed, no upstream files/install state changed, and no native host or provider behavior was tested. Full runtime correctness is outside this analysis.'
 by_path[r['path']]={'path':r['path'],'depth':'contract-ranges-reviewed' if method else 'scope-inspected-excluded','disposition':'analyzed' if method else 'excluded','classification':'shell-with-reviewed-embedded-prompts' if method else 'shell-install-deployment-or-test-support','reason':purpose,'proof':{'commit':COMMIT,'hash':r['sha256'],'inspector':'ecc-shell-scope.py','read_ranges':[[1,min(30,r['lines'])]]+([[198,343]] if r['path']=='scripts/gan-harness.sh' else [])+[[h['start'],h['end']] for h in r['heredocs']],'declarations':r['symbols'],'cli_call_relationships':r['calls'],'execution':'none'},'review_kind':'scoped-relevance','review_evidence':{'ledger':'ecc-scope-decisions.json','record':r['path'],'method':'Actual shell source purpose/relationships and complete embedded heredoc/model-prompt ranges.'}}
full_notes=json.loads((OUT/'docs/audit/ecc-other-reviews.json').read_text(encoding='utf-8'))
for r in json.loads((OUT/'.tools/ecc/metadata-shapes.json').read_text(encoding='utf-8')):
 if r['path'] in full_notes:continue
 purpose='Parsed packaging/deployment/configuration role from actual source opening, complete field structure and concrete declared consumers: '+r['opening'].replace('\n',' ')[:300]+'. '
 if r['path'].startswith('.github/workflows/'):
  purpose+='The named CI/release/maintenance jobs invoke the reviewed validation/install/package/announcement scripts. Job permissions, action pins, tested archive outputs and step command dependencies are declarative deployment contracts, not agent prompt bodies or live verified execution. Exact artifact promotion and output-versus-authority methods are reviewed in release runbooks; historical rollout correctness and every inline script branch are outside this analysis. '
 elif r['path'].startswith('docker/'):
  purpose+='Actual image/package copies, user, read-only/network/capability and command fields provision the opt-in disposable native/packed acceptance fixtures described in the fully reviewed Docker README and DESIGN. Declared flags are not a performed containment test or model outcome. '
 else:
  purpose+='Actual version, exports/skill routing, dependency/tool pins, ownership/funding, private-report links, ignore/format policies or blank credential-variable declarations support packaging and local project setup. This data refers to canonical bodies and SDK modules already reviewed; no distinct reusable prompting method. A published identifier, preferred model name or ignore pattern is not native authority, complete secret protection or current availability evidence. '
 purpose+='No workflow, install, source mutation, network request or message was executed.'
 by_path[r['path']]={'path':r['path'],'depth':'scope-inspected-excluded','disposition':'excluded','classification':'packaging-deployment-or-configuration-support','reason':purpose,'proof':{'commit':COMMIT,'hash':r['sha256'],'inspector':'ecc-metadata-scope.py','read_ranges':[[1,min(30,r['lines'])]],'fields':r['keys'],'declared_relationships':[{'pointer':s['pointer'],'content_excerpt':s['text'][:200]} for s in r['relationships'][:30]],'declarations':r['declarations'],'execution':'none'},'review_kind':'scoped-relevance','review_evidence':{'ledger':'ecc-scope-decisions.json','record':r['path'],'method':'Safe YAML/TOML parsing, actual field/step/consumer relationships and concrete source purpose.'}}
archive_exact={'docs/releases/2.0.0-rc.1/release-notes.md','docs/releases/2.2.0/ecc-2.2-release-readiness.tdd.md','docs/releases/2.2.1/release-notes.md','docs/design/context-carriers.tdd.md','docs/design/context-profile-delivery.tdd.md','docs/design/context-profiles.tdd.md','docs/architecture/agentshield-enterprise-research-roadmap.md','docs/architecture/platform-value-loop.md','docs/design/agent-proximity.md','docs/design/ecc-pro-fleet-dashboard.md'}
for r in json.loads((OUT/'.tools/ecc/document-shapes.json').read_text(encoding='utf-8')):
 p=r['path']
 eligible=p in archive_exact or p.startswith('docs/releases/2.0.0-rc.1/operator-readiness-dashboard-') or p.startswith('docs/releases/2.0.0-rc.1/publication-evidence-')
 if not eligible or p in full_notes:continue
 purpose='Actual opening and section-content role inspected: '+r['opening'].replace('\n',' ')[:380]+'. '
 if 'operator-readiness-dashboard-' in p:purpose+='Generated historical operator snapshot from scripts/operator-readiness-dashboard.js, containing current-status/checklist/evidence/gap/action tables. It reports observed or asserted source readiness, not approval. '
 elif '/publication-evidence-' in p:purpose+='Historical dry-run/publication-readiness record with explicit source commit, recorded queue/registry/CI/packaging/operator results and remaining blockers. It is an evidence snapshot consumed by release gates, not new agent instructions or a live publication action. '
 elif '.tdd.md' in p:purpose+='Recorded local RED/GREEN, development/packed/coverage/checkpoint evidence for the separately reviewed context/runtime contract. Reported results are preserved as source assertions and not reexecuted here; synthetic infrastructure validation does not establish model efficacy. '
 elif p.endswith('/agent-proximity.md'):purpose+='Product-specific edit/line/tree/import risk math, TCAS advisory thresholds, visualization and runtime wiring into scripts/lib/agent-proximity plus control-pane. Mathematical/model implementation relevance is scoped; probabilistic efficacy and intervention benefit are unproved, with transferable shadow-label/intervention comparison already captured in coordination-inventory. '
 elif p.endswith('/ecc-pro-fleet-dashboard.md'):purpose+='Draft hosted product API/data/auth/pricing/UI design grounded in AgentShield scan/telemetry shapes. This is an external SaaS implementation proposal; domain endpoints, pricing and tenant model are excluded from independent prompt patterns. '
 elif p.endswith('/agentshield-enterprise-research-roadmap.md'):purpose+='External security-product backlog and capability/buyer/compliance/adaptation research proposal. Concrete baseline-drift/evidence-bundle/category gates repeat already sourced bounded evaluation, audience separation and live-state methods; product rollout/market claims are not verified. '
 elif p.endswith('/platform-value-loop.md'):purpose+='Platform-business positioning and three-layer commercial integration thesis, release lanes and product contribution model. Public/personal/hosted boundaries relate to separately read skills; this commercial strategy does not supply a separate prompt mechanism or current economic fact. '
 else:purpose+='Historical release/change/scope/upgrade copy with source provenance boundaries. Product/vendor/count/availability claims are not current verification or independent prompting methods. '
 purpose+='Scoped support/data relevance excludes a comprehensive historical incident, correctness, commercial or source-security audit. No workflow/service/provider/publication action executed.'
 by_path[p]={'path':p,'depth':'document-purpose-and-section-scope-inspected','disposition':'excluded','classification':'historical-evidence-or-product-design-support','reason':purpose,'proof':{'commit':COMMIT,'hash':r['sha256'],'inspector':'ecc-document-scope.py','read_ranges':[[1,min(22,r['lines'])]],'sections':[{'line':s['line'],'end':s['end'],'heading':s['heading'],'opening_excerpt':s['opening'][:150],'section_hash':s['section_hash']} for s in r['sections']],'relationships':r['links'],'execution':'none'},'review_kind':'scoped-relevance','review_evidence':{'ledger':'ecc-scope-decisions.json','record':p,'method':'Actual dated producer/consumer evidence, document content role and section-opening/structure inspection; not claimed full semantic read.'}}
remaining_support={
 'CHANGELOG.md':'Historical release history. The actual opening records naming-only Pi regeneration and bounded npm-registry propagation polling, while section bodies list release changes and reported checkpoints. This is shipped-change metadata referencing separately reviewed canonical methods; historical current counts, audit results and vulnerability statements are not new experimentally verified patterns.',
 'CODE_OF_CONDUCT.md':'Contributor Covenant community participation, harassment reporting, enforcement responsibilities and graduated community sanctions. Actual pledge/standards/enforcement/attribution text concerns human community administration; it is outside transferable agent prompt/context/workflow methods and supplies no permission to message or moderate.',
 'COMMANDS-QUICK-REF.md':'Navigation/command registry tables and simple task-to-command decision tree. All94 canonical command bodies and retired shims were fully read. Command counts/global installation statements and table descriptions are catalog metadata, not invocation evidence; CLI memory/install rows are explicitly separate from slash commands.',
 'SPONSORING.md':'OSS sponsorship tiers, funding purpose, reportable download/reliability metrics and maintainer ownership expectations. Commercial packaging and local reporting copy, not a prompt or evaluation mechanism; dated prices and economics remain unverified.',
 'SPONSORS.md':'Sponsor identity/logo/date/price/perk roster and grandfathering copy. This is funding metadata rather than instructional skill material; source supporter lists and pricing are not current independently verified facts or pattern efficacy.',
 'docs/ECC-2.0-GA-ROADMAP.md':'Durable mirror of a dated multi-repository Linear/product roadmap, with large source-state/checkpoint/PR/billing tables. Actual operating rules L1048–1068 and status-update slots L1109–1115 were also read: source-fresh evidence, salvage attribution and blocked remaining gates reuse live-state/source memory methods. Recorded complete statuses, audit80/80 and queue-zero goals are historical local assertions, not current approval or runtime evidence.',
 'docs/ECC-2.0-REFERENCE-ARCHITECTURE.md':'External-reference-to-ECC-backlog mapping for worktrees, HUD, evaluation, AgentShield and commercial review surfaces. Actual source declares a planning artifact with dated reference pressures and future adapters/checks. Product architecture and backlog items instantiate separately sourced task/memory/evidence methods, not extra independent prompt patterns or proof external libraries were inspected.',
 'docs/ECC-PRO-SECURITY-ROADMAP.md':'Draft commercial/security product roadmap from a secondary multi-agent survey. Actual funnel/theme/now-next-later/triage text prioritizes hosted scanning, policy, review and business conversion features. External competitor/customer/MRR/pricing assertions are not primary verified evidence; no market plan becomes a new prompt method.',
 'docs/ROADMAP.md':'Maintainer planning draft explicitly distinguishing source inclusion from released/live capability. Condense/evidence/operator/distribution tracks and calendar milestones are product planning data; OS-executor prerequisite and exact-byte promotion refer to separately fully read contracts. Targets and local backlog status are not measured efficacy.',
 'docs/SELECTIVE-INSTALL-ARCHITECTURE.md':'Installer module/API/data architecture with actual request-normalizer/resolver/target-planner/operation-executor/state/lifecycle relationships. These interface layers are implemented by the previously AST-scoped install modules and manifests. Desired-versus-installed/drift/ownership methods recur in canonical configure-ecc and resource-layout contracts; pure installer implementation design is excluded from a comprehensive correctness audit or new domain recipe cards.',
 'docs/business/team-agent-orchestration-content-pack.md':'Prepared article/video/social positioning and distribution copy around agent boards/control panes. Actual source is a public content pack, not agent instructions; shared skill/observable evidence motifs repeat fully reviewed brand/content/orchestration sources. Predictions and promotional claims are not experimental results and no copy was published.',
 'docs/design/ecc-ito-compute-integration.md':'Product-specific external CLI bridge/setup/economic operation and serving-capability contract. Actual implemented-versus-unavailable boundary, canonical client delegation, RFQ-versus-reservation distinction and publication blocker are documented. Full canonical ito-compute/inference/training skills were already read; external provisioning/API/economics recipes are excluded as independent prompt methods. No live financial/provider action.',
 'docs/legacy-artifact-inventory.md':'Historical artifact/legacy workspace/shim classification and source attribution ledger, consumed by stale-work and release-readiness checks. Actual states distinguish landed/milestone/salvage/archive and private-workspace import boundaries. Reuses source-memory/current-state/retirement context; historical absence of legacy paths is bounded dated scan evidence, not current filesystem truth.',
 'docs/stale-pr-salvage-ledger.md':'Historical PR salvage/disposition table and explicit useful-compatible-versus-stale/localization manual-review classification. Source opening requires fresh compatible porting and contributor credit instead of treating closed work as discarded. This repeats the fully reviewed evaluator-RAG scenario and source-preserving cleanup method; dated PR outcomes are metadata, not executed evidence here.',
 'docs/security/ecc-039-powershell-gateguard-plan.md':'Product runtime classifier/router/audit-consumer hardening specification and reported verification. Actual source defines one shared pure PowerShell classification API, consumer-specific fail/guard semantics and a command-class acceptance matrix. Runtime shell parsing correctness and every threat variant are outside prompting scope; bounded source purpose/consumer relationships suffice, and no safety guarantee is inferred from plan or reported tests.',
 'docs/releases/2.0.0-rc.1/naming-and-publication-matrix.md':'Dated release identity/registry/plugin/live-versus-gated surface matrix and recorded evidence output. This is historical package migration metadata; source current-state and promotion motifs are already in fully reviewed release runbook and owner packet. Source presence and names do not prove installation, serving or authorization.',
 'docs/releases/2.0.0-rc.1/partner-sponsor-talks-pack.md':'Prepared sponsor/partner/consulting/talk/article/CTA copy plus public URL prerequisites. These are domain marketing output examples of the already reviewed brand/profile/source claim methods. Revenue/prices/product superiority and publication-readiness claims remain source assertions; draft text grants no send/post authority.',
 'docs/releases/2.0.0-rc.1/preview-pack-manifest.md':'Dated release content inventory, capability boundaries and approval/live-link checks. Actual artifact-role-gate tables are consumed by scripts/preview-pack-smoke.js/release-approval-gate.js. This is package/publication support data repeating reviewed live-state and exact-artifact contracts, not model execution evidence.',
 'docs/releases/2.0.0-rc.1/publication-readiness.md':'Historical release checklist and evidence register; its opening expressly says the checklist itself is not evidence and exact-commit fresh outputs are required. Distribution/owner/copy/URL gates instantiate the fully read runbook and owner packet. Remaining product-state rows and commands are package-specific operational metadata; no approval/publication inferred.',
 'docs/releases/2.0.0-rc.1/release-name-plugin-publication-checklist-2026-05-18.md':'Dated naming/repository/package refresh decisions, surface-evidence matrix and publication order. Source references required/readback/blocked release actions already fully read elsewhere. This does not substantiate current vendor distribution status or authorize changes.',
 'docs/releases/2.0.0-rc.1/video-suite-production.md':'Release-video product claim/source inventory/deliverables/assembly/browser footage/self-eval and publication blockers. Actual editing workflow reuses canonical video-editing and ui-demo sources, which were fully reviewed. Asset basenames, runtime/media durations and reported validator states are domain production data, not independent prompt/effectiveness patterns; no media generated or published.',
 'docs/releases/2.0.0/ecc-2-hypergrowth-release-command-center.md':'Dated product release/funnel/content-distribution execution map and owner action boundaries. It ties drafts and live gates to existing reports/runbooks rather than adding a novel prompt method. Commercial predictions, growth numbers and future platform behavior remain unverified source assertions; no outward action.',
 'docs/releases/2.2.1/patch-execution.md':'Historical authorized maintenance/review/integration sequence with original failed and later green checkpoint evidence, source attribution and explicit pending publication boundaries. Prior user authorization in this record belongs to that task, not this analysis. Product patch history and runtime bug investigation are outside new prompting patterns; failure artifacts/serialized integration/source identity methods are already captured.',
}
doc_rows={r['path']:r for r in json.loads((OUT/'.tools/ecc/document-shapes.json').read_text(encoding='utf-8'))}
for p,purpose in remaining_support.items():
 r=doc_rows[p]
 by_path[p]={'path':p,'depth':'document-purpose-and-section-scope-inspected','disposition':'excluded','classification':'catalog-business-history-or-product-implementation-support','reason':purpose+' Actual opening, section-content excerpts, source links and declared producer/consumer role were inspected. Full historical/product correctness or every domain recipe is not claimed. No source execution or external changes.','proof':{'commit':COMMIT,'hash':r['sha256'],'inspector':'ecc-document-scope.py','read_ranges':[[1,min(22,r['lines'])]]+([[1048,1068],[1109,1115]] if p=='docs/ECC-2.0-GA-ROADMAP.md' else []),'section_scope':[{'line':s['line'],'heading':s['heading'],'opening_excerpt':s['opening'][:150],'section_hash':s['section_hash']} for s in r['sections']],'relationships':r['links'],'execution':'none'},'review_kind':'scoped-relevance','review_evidence':{'ledger':'ecc-scope-decisions.json','record':p,'method':'Actual purpose/content/producer-consumer relationship inspection, bounded domain/support exclusion; full semantic correctness not claimed.'}}
for p,ranges,reason,kind in [
 ('README.md',[[484,612],[1076,1273]],'Primary product catalog, installer onramp and canonical skill/command/guide navigation. Fully read manual resource/hook/MCP/runtime boundaries and agents/skills/TDD/trust-scoped memory examples. These point to the already fully reviewed canonical methods rather than introduce a second workflow. Remaining exhaustive catalog/business/platform listing is support data; native availability, model benefits and current counts are not verified by a README.','scoped-relevance'),
 ('README.zh-CN.md',[[638,694]],'Chinese root catalog/onramp materially compared to current canonical manual boundary. CN preserves old unnamespaced rules, advises raw hooks.json settings copy, old MCP list/settings target and omitted live-versus-install-filter distinction; canonical README L495–589 requires ECC rule namespace, resolved idempotent hook installer, CLI-managed live state and one default connector. These actual permission/interface/config deltas are recorded, not called equivalent. Remaining translated catalog/pricing/metadata is support data; no current native claims adopted.','difference-review')]:
 r=doc_rows[p];by_path[p]={'path':p,'depth':'method-and-interface-ranges-reviewed-with-catalog-role-scope','disposition':'analyzed','classification':'catalog-with-reviewed-context-and-interface-contracts','reason':reason+' Source tree and section-content role inspected; no upstream installation or provider operation.','proof':{'commit':COMMIT,'hash':r['sha256'],'read_ranges':ranges,'section_headings':[{'line':s['line'],'heading':s['heading']} for s in r['sections']],'comparison_context':{'path':'README.md','ranges':[[495,589]]} if kind=='difference-review' else None,'execution':'none'},'review_kind':kind,'review_evidence':{'ledger':'ecc-scope-decisions.json','record':p,'method':'Concrete complete method/interface ranges and actual catalog-role inspection; Chinese substantive deltas separately compared.'}}
# Preserve stronger full reads when a later batch closes a formerly scoped artifact.
for p in full_notes:by_path.pop(p,None)
(OUT/'docs/audit/ecc-scope-decisions.json').write_text(json.dumps(list(by_path.values()),ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('Scoped outcomes persisted',len(by_path))
