import runpy,json,pathlib
module=runpy.run_path(str(pathlib.Path(__file__).with_name('ecc-candidates.py')),run_name='ecc_data')
add=module['add']; candidates=module['candidates']; OUT=module['OUT']

add('source-derived-profile','Reusable Source-Derived Voice Profile','可复用的来源风格档案','prompt','brand-voice',19,54,'Source Priority / Collection / Output Contract',[83,101],
('Extract a compact style profile from real writing and reuse it across related outputs.','Draft release notes and a newsletter in the same author’s voice from five supplied samples.','Identify sentence rhythm, claim strength, transition and vocabulary norms; distinguish public/private registers and reuse the confirmed profile.','Ask for “professional LinkedIn style” and rewrite the author into generic platform clichés.','Derive “short concrete claims, qualified numbers, no bait questions” from the supplied samples; apply that same profile to the release note and newsletter, adding only medium-specific context.','The adaptation follows source evidence while keeping a single reusable style contract.','Both drafts can be compared to cited source features and one profile.','Style is contextual; do not treat an author fingerprint as universal policy or persist private samples without authorization.'),
('从真实文字提取短风格档案，跨相关输出复用。','用提供的五篇样稿，以同一作者风格写发布说明和通讯。','识别句子节奏、主张强度、衔接与用词约定，区分公开和私人语域，复用已确认档案。','要求“专业 LinkedIn 风格”，把作者改成平台套话。','从样稿得到“短而具体、数字有条件、不用互动诱饵”，两份稿件复用，只补媒介所需背景。','改写跟随来源证据，并保持唯一风格契约。','两份稿都能对照有出处的特征与同一档案。','风格有情境；不能当通用政策，也不能未经授权保存私人样稿。'),['voice','source-grounding'])

add('adaptive-saturation-interview','Probe-to-Saturation Interview','探问至饱和的访谈','workflow','brand-discovery',41,67,'Interview discipline',[84,111],
('Ask one focused follow-up at a time until the current topic stops producing new information.','Elicit a founder’s product positioning from vague claims such as “we care about quality.”','Paraphrase the answer, ask a why or concrete-example probe, and close the topic only when repeated probes add no information.','Send twenty abstract questions at once, then synthesize “quality-focused” from one generic answer.','Ask for one customer incident, paraphrase the consequence, probe why it mattered, and stop after two follow-ups add no new evidence.','The dialogue deepens an actual answer rather than collecting shallow checklist responses.','The notes contain the concrete incident, inferred value and explicit saturation evidence.','Saturation is an interview heuristic, not proof the domain is exhaustively known; respect a request to change topic.'),
('逐次提出聚焦追问，当前主题不再产生新信息时结束。','从“我们重视质量”等空泛表述中提炼创始人定位。','复述回答，追问原因或具体例子，只有重复探问不添信息时才收束。','一次发二十个抽象问题，再从空泛回答总结“质量导向”。','询问一个客户事件，复述后果，追问为何重要，两次追问无新证据后结束。','对话深化真实答案，避免浅层清单回答。','笔记保留具体事件、推断价值和饱和依据。','饱和是访谈启发式，不证明领域已穷尽；尊重用户换话题。'),['elicitation','saturation'])

add('raw-synthesis-separation','Raw Evidence and Synthesis Separation','原始证据与综合结论分离','context','brand-discovery',61,67,'End of module',[196],
('Store original statements separately from interpretations, candidate formulations and unresolved contradictions.','Two stakeholders describe the same feature’s audience differently.','Capture attributable raw answers first, then synthesize convergences and divergences without editing the source statements.','Replace both answers with one confident “target audience is enterprise” conclusion.','Raw: A says startups, B says enterprise; Synthesis: audience unresolved, two candidate positions, and a focused alignment question.','The reader can distinguish what was said from what the agent inferred.','Every synthesis claim can be checked against preserved attributable evidence.','Avoid storing sensitive verbatim data unnecessarily; raw capture does not turn a statement into truth.'),
('原话与解释、候选表达、未解矛盾分开保存。','两个利益相关者对同一功能的受众描述不同。','先保存有归属的原始回答，再综合一致点和分歧，不修改原话。','用“目标受众就是大企业”的自信结论替代两份回答。','原始：A 说创业公司，B 说企业；综合：受众未定，列两个候选定位及一个对齐问题。','读者能区分实际陈述与代理推断。','每条综合主张可追溯保留的归属证据。','避免不必要保存敏感原话；记录不使陈述自动成为事实。'),['provenance','synthesis'])

add('decision-enabling-audit','Decision-Enabling Audit Reasons','可执行审计理由','skill-authoring','skill-stocktake',116,145,'Verdict criteria / Reason quality requirements',[],
('Make keep, improve, retire and merge verdicts state the evidence, action and replacement rather than a vague label.','Review two overlapping deployment skills and one stale tool wrapper.','For merge, name target and transferable section; for retire, identify defect and replacement; for improve, specify the section and required change.','Verdicts: “old,” “too long,” “overlaps,” with no path or consequence.','Merge wrapper A into deployment B’s rollback section; retire stale command C because its verified replacement is D; cite the checked paths and missing mechanism.','A subsequent implementer can act without reconstructing the audit’s intention.','Each disposition has a concrete target, change and evidential reason.','Usage frequency alone is not quality; cached unchanged verdicts must preserve their original evidence.'),
('保留、改进、撤下或合并结论写出证据、动作与替代，不只给标签。','审核两份重叠部署技能和一个过期工具包装。','合并说明目标与可迁内容；撤下指出缺陷与替代；改进指定小节和所需变更。','只给“旧”“太长”“重叠”，没有路径和后果。','A 合并到 B 的回滚节；C 因核实替代 D 而撤下，注明已查路径与缺失机制。','后续实现者不用重建审计者意图。','每个处置都有具体目标、变更与证据理由。','使用次数不等于质量；缓存未变结论也应保留原依据。'),['audit','deduplication'])

add('trace-compliance','Pressure-Level Behavioral Trace Evaluation','压力层级行为轨迹评测','evaluation','skill-comply',11,17,'Compliance measurement pipeline',[149,169],
('Test instruction-following under supportive, neutral and competing requests using actual behavior traces.','Check whether a research skill still searches before coding when the request pressures the agent to skip search.','Define expected behavioral steps, prepare the three request conditions, capture tool calls, classify them and check temporal ordering separately.','Judge compliance from a final answer saying “I followed the skill.”','Compare three traces: supportive prompt searches first; neutral and competing prompts must also show a real search call before any edit; report missing and misordered steps.','Compliance is observed in execution, not inferred from polished self-report.','The report retains prompts, expected sequence, classified calls and deterministic order results.','Classification can be wrong; inspect disputed labels, separate call identity from semantic judgment and bound any model-test cost.'),
('用支持、中性和竞争请求，结合真实行为轨迹测试遵从。','检查研究技能在“跳过检索赶快写代码”压力下是否仍先查后写。','定义预期步骤，准备三种请求，记录工具调用，分类后单独验证时间顺序。','仅凭最终答复“我遵守了技能”评分。','比较三份轨迹：支持请求先检索；中性与竞争也应有真实检索先于编辑，报告缺失和乱序步骤。','遵从从执行观察，不从漂亮自述推断。','报告保存请求、预期序列、分类调用与确定性顺序结果。','分类可能错，争议标签须复查；调用身份与语义判断分开，付费评测受预算限制。'),['pressure-testing','tool-traces'])

add('cross-skill-distillation','Cross-Skill Evidence Distillation','跨技能证据蒸馏','skill-authoring','rules-distill',74,92,'Extraction Criteria / Matching & Verdict',[],
('Promote only recurring actionable principles with a stated failure consequence and a comparison against existing rules.','Three skills repeat an instruction to preserve raw source evidence, while a fourth contains only one vendor-specific command.','Cross-read candidate skills and current rules; require repeated evidence, behavior change and violation risk; merge semantic duplicates and keep narrow recipes local.','Turn every heading into a global rule and duplicate existing policy with new wording.','Promote “retain source and observation time before memory reuse” with the two source sections and stale-recall risk; keep the vendor CLI command inside its own skill.','The filter reduces abstraction that has no transferable action or new value.','The proposal lists source sections, risk, matching existing rule and append/revise/local verdict.','Recurrence alone does not prove a rule is correct; retain exceptions and the project’s normal policy-review authority.'),
('只提升重复、可行动、有失败后果且与现有规则比较过的原则。','三份技能反复要求保留原始证据，另一份仅含厂商专用命令。','跨读技能和现有规则，要求重复证据、行为变化与违规风险，合并语义重复，狭窄步骤留本地。','每个标题都变全局规则，用新措辞重复旧政策。','两处来源节加旧记忆风险支持“复用前保留来源与观察时间”；厂商 CLI 命令留技能内部。','过滤没有可迁行动或新增价值的抽象。','提案列来源小节、风险、已有规则与增补/修订/本地结论。','重复不证明正确；保留例外和项目规则审核权。'),['distillation','recurrence'])

add('golden-file-pointers','Golden-File Convention Pointers','黄金样例文件指针','context','inherit-legacy-style',56,84,'Scan Dimensions / Generate Rules',[54,23],
('Anchor project conventions to current concrete exemplar files, with explicit differences and anti-patterns.','Add a connector to a legacy project with inconsistent old and new layouts.','Compare current exemplars across file anatomy, state flow, infrastructure and errors; resolve meaningful conflicts and cite the chosen model.','Copy the oldest connector wholesale, including obsolete error handling.','Cite current connector A for registration and B for retry behavior; state the old layout is superseded and flag its bug rather than reproduce it.','Pointers show the convention’s actual mechanism and distinguish evolution from accidental inconsistency.','The change can be reviewed against named exemplar paths and concrete rules.','Popularity does not prove correctness; never transplant bugs merely to match style.'),
('项目约定指向当前具体样例，说明差异和反例。','旧项目新增连接器，历史与新布局不一致。','比较文件结构、状态流、基础设施和错误处理，解决重要冲突，引用所选模型。','整份复制最旧连接器，连过期错误处理也带来。','A 示范注册，B 示范重试；说明旧布局已替代，指出旧 bug 而不复刻。','指针展示实际机制，区分演进与偶然不一致。','变更能对照样例路径和具体规则审核。','多数用法不证明正确；匹配风格不能照搬缺陷。'),['exemplars','conventions'])

add('technical-vs-product-constraints','Technical Facts vs Product Constraints','技术事实与产品约束分离','prompt','intent-driven-development',61,96,'Operating Rules',[],
('Keep discovered implementation behavior separate from intended business constraints and explicit assumptions.','A developer asks to add export functionality, and code happens to cap queries at 100 rows.','Inspect current technical behavior; obtain product limits from an authoritative brief or user; label unresolved limits as assumptions rather than business facts.','Conclude “free users may export 100 rows” solely because a query uses LIMIT 100.','Record “query currently fetches 100 rows”; separately note “export entitlement limit unspecified,” and request or document the material product decision before enforcing a new cap.','Observed code explains current behavior without manufacturing a requirement.','The brief has separate discovered facts, supplied product constraints and unresolved assumptions.','A product artifact in the repo can be authoritative; this separation does not require asking about facts already supplied.'),
('将发现的实现行为与业务期望、显式假设分开。','开发者要求导出，现有查询恰好 LIMIT 100。','检查技术行为；产品限制来自权威说明或用户；未定限制标假设而非业务事实。','只因 LIMIT 100 就断言“免费用户只能导出 100 行”。','记“查询当前取 100 行”；另记“导出权益上限未指定”，实施新限制前获取重要产品决策或明确假设。','代码解释当前行为，不能凭空制造需求。','简报分列发现事实、提供的产品约束和未解假设。','仓库内产品文档也可权威；已提供事实无需重新提问。'),['assumptions','requirements'])

add('live-state-proof','Configured vs Verified Capability State','已配置与已验证能力状态','tools','automation-audit-ops',32,94,'Guardrails / Classify / Proof Path',[175,177],
('Distinguish configuration presence, authentication and observed working capability before claiming availability.','An integration appears in a config file but has expired credentials.','Inventory the surface, label configured/authenticated/recently verified/stale/missing separately, and attach the evidence for each claimed state.','Tell the user the integration is operational because its server name appears in config.','Report configured=true, authenticated=unknown, smoke-test=blocked by expired token; provide the concrete failure and next repair.', 'Presence and operational behavior are different observations with different proof requirements.', 'The inventory retains the configuration path and actual smoke-test result without a false success claim.', 'Use only authorized harmless checks; installation or a passing config validator is not end-to-end operational proof.'),
('在声明可用前，区分配置存在、认证和实际运行能力。','集成写在配置中，但凭证已过期。','盘点界面，分别标已配置、已认证、近期验证、陈旧、缺失，并附各状态证据。','看到服务器名就告诉用户集成可运行。','报告 configured=true、authenticated=unknown、smoke-test=凭证过期阻塞，给具体失败与下一修复。','存在与运行是不同观察，需要不同证明。','表保留配置路径与真实冒烟结果，不虚报成功。','仅做授权无害检查；安装或配置校验通过不证明端到端正常。'),['capability','provenance'])

add('typed-launch-plan','Shell-Free Executable and Argument Plan','无 Shell 的可执行参数计划','tools','terminal-opener',8,15,'Executable and argument boundaries',[134],
('Preserve executable, arguments, working directory and environment assumptions as a reviewable launch plan.','A terminal task includes a path with spaces and a user-provided filename.','Inspect a non-launching plan, pass each argument separately, avoid shell interpolation, and preserve unsupported-capability errors.','Concatenate the filename into one shell command string and launch it immediately.','Plan executable=viewer, argv=[--file, the exact filename], cwd=the approved directory; review it and launch through a shell-free adapter only when authorized.','Argument boundaries prevent data from being reinterpreted as shell syntax.', 'A fixture containing spaces and shell metacharacters remains one unchanged argument in the plan.', 'Shell-free launch still inherits environment and does not make an untrusted executable safe; sanitize secrets at the calling boundary.'),
('把可执行程序、参数、工作目录和环境假设保留为可审计划。','终端任务包含带空格路径和用户文件名。','先查看不启动的计划，参数分项传递，避免 shell 插值，保留能力不支持错误。','将文件名拼进 shell 字符串并马上启动。','计划 executable=viewer、argv=[--file,原始文件名]、cwd=授权目录；审后仅在授权时经无 shell 适配器启动。','参数边界防止数据重新解释成 shell 语法。','带空格和 shell 元字符样例在计划中保持一个原始参数。','无 shell 仍继承环境，且不能使不可信程序安全；凭证需在调用边界隔离。'),['argv','safe-execution'])

add('measurement-unit-boundary','Measurement Unit and Scope Boundaries','度量单位与范围边界','evaluation','context-budget',86,94,'Persisted bytes are not active context',[],
('State what a measurement actually counts before using it as evidence for a different resource or behavior.','A JSONL snapshot is 1,000 bytes, of which800 are attachment records; someone asks how much model context remains.','Label persisted-byte categories and their complete total; obtain active token/headroom from the harness instead of converting byte share into a context claim.','Report “attachments consume80% of the model context, leaving20% room.”','Report “800/1,000 persisted bytes are attachment records; active token usage and remaining context were not measured,” then use the authorized harness usage surface if available.','A reproducible byte ratio does not establish a token ratio or runtime loading policy.','The report names byte units, snapshot scope, uncategorized records and the separate unknown active-context measure.','Do not imply that a valid byte calculation is useless; it answers storage questions within its actual scope.'),
('使用度量前，说明它实际计算的对象，避免证明另一种资源或行为。','一个 JSONL 快照共1,000字节，其中800字节为附件记录；用户问剩余模型上下文。','标明落盘字节分类和完整总量，活跃 token 与剩余空间另由运行时获取，不用字节占比替代。','报告“附件占模型上下文80%，还剩20%”。','报告“落盘1,000字节中附件记录800字节；未测活跃 token 和剩余空间”，可用时再查询授权运行时用量。','可复算字节比不证明 token 比或运行时加载策略。','报告说明字节单位、快照范围、未分类记录和独立未知的活跃上下文指标。','正确字节计算能回答其范围内的存储问题，不能因边界限制就否定它。'),['metrics','context-budget'])

add('assigned-diversity','Explicit Diversity Assignment','显式多样性分配','orchestration','autonomous-loops',160,208,'Spec Analysis / Parallel Deployment / Uniqueness via Assignment',[],
('Assign each parallel generation worker a distinct approach and output identity while holding the shared specification fixed.','Generate three navigation concepts for the same compact documentation site.','Give all workers the same requirements; assign editorial, dense-reference and search-first approaches plus separate output paths; compare results against the same constraints.','Tell three workers “make it distinctive” and let them choose the same card grid and filename.','Assign A editorial navigation → concept-a, B dense reference → concept-b, C search-first → concept-c; all must retain language switching and keyboard access.','The orchestrator makes the variation dimension explicit and avoids conflicting outputs.','The result set has three named approaches, distinct artifacts and a common acceptance comparison.','Assignment encourages variety but does not prove semantic uniqueness or quality; reject variants that violate shared requirements.'),
('并行生成时明确分配不同方案和输出身份，同时保持共同规范。','为同一个紧凑文档站生成三种导航概念。','所有人共享要求；分别分配编辑式、密集参考式、搜索优先式方向和独立路径，再按同一约束比较。','只对三人说“做得独特”，结果都用同一卡片网格和文件名。','A 编辑导航 → concept-a；B 密集参考 → concept-b；C 搜索优先 → concept-c；都保留语言切换与键盘访问。','编排者明确变化维度并避免输出冲突。','产物有三种命名方案、独立文件和共同验收比较。','分配促进差异，但不证明语义唯一或质量；违反共同要求的候选应拒。'),['generation','diversity'])

add('thin-vertical-slice','First Verifiable Vertical Slice','首个可验证纵向切片','workflow','orch-build-mvp',21,39,'Spec intake / First end-to-end slice',[],
('Build one small end-to-end user path from the existing specification before expanding all layers.','Implement an MVP that accepts a request, stores it and shows its status.','Read locked decisions, choose one complete user path with its acceptance check, scaffold that path, evaluate it, then add the next slice.','Implement every data model first and every view next; no user path runs until the end.','First deliver submit request → persistence → status page for one request type with a real error-path check; evaluate that slice before adding other types.','The slice exposes integration and contract failures while the change surface is still bounded.','One complete user journey is demonstrable with its test and artifact before the second slice starts.','A vertical slice is not license to invent product behavior; use the existing spec and keep shared architecture decisions intact.'),
('先按已有规范完成一条小而完整的用户路径，再扩展各层。','实现一个接受请求、保存并显示状态的 MVP。','读取已定决策，选择一个完整路径及验收，先搭建和评测，再追加切片。','先写全部模型再写全部页面，到最后才有能跑的用户路径。','先交付一种请求的提交 → 保存 → 状态页，包含实际错误路径验证；评测后再添其他类型。','范围尚小时就暴露整合与契约失败。','第二切片前，首个完整旅程已有演示、测试和产物。','切片不授权编造产品行为；沿现有 spec 并保留共同架构决策。'),['decomposition','integration'])

(OUT/'ecc-candidates-batch.json').write_text(json.dumps(candidates,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(f'{len(candidates)} candidates written')
