"""Editorially authored ECC teaching examples; source repositories are read-only."""
import json,pathlib,subprocess,sys
sys.stdout.reconfigure(encoding='utf-8')
OUT=pathlib.Path('D:/Projects/prompt-context-patterns-refresh/docs/audit')
ROOT=pathlib.Path('D:/Projects/open-skills/affaan-m/ECC')
COMMIT='ef648e01899ba3e8dc6371642deaaf64b4477775'
REPO='affaan-m/ECC'
candidates=[]
def add(key,name_en,name_zh,category,skill,start,end,section,ids,en,zh,tags=()):
    fields=('description','scenario','mechanism','bad','good','why','expected','boundaries')
    assert len(en)==len(zh)==8
    path=skill if '/' in skill or skill.endswith('.md') else f'skills/{skill}/SKILL.md'
    candidates.append({'key':f'ecc-{key}','name_en':name_en,'name_zh':name_zh,'category':category,'tags':['ecc',*tags],
      'summary_en':en[0],'summary_zh':zh[0],'content':{'en':dict(zip(fields,en)),'zh':dict(zip(fields,zh))},
      'example_origin':'editorial-teaching-example','decision':'active','decision_reason':'Concrete reusable mechanism; teaching contrast uses the same task and conditions. Integrate with suggested existing IDs when their full semantics match.',
      'suggested_existing_ids':ids,'scores':{'scenario':2,'mechanism':2,'contrast':2,'observable':2,'boundaries':2},
      'sources':[{'repo':REPO,'commit':COMMIT,'path':path,'start_line':start,'end_line':end,'section':section,'license':'MIT','role':'observed-example','url':f'https://github.com/{REPO}/blob/{COMMIT}/{path}#L{start}-L{end}'}]})

add('iterative-gap-retrieval','Gap-Driven Iterative Retrieval','缺口驱动的迭代检索','context','iterative-retrieval',52,140,'DISPATCH / EVALUATE / REFINE / LOOP',[],
('Refine retrieved context using explicit missing-information notes instead of choosing a fixed file set upfront.',
 'Add rate limiting to API endpoints in a codebase that calls its existing limiter “throttle.”',
 'Search broadly, assess each result against the task, list gaps, add discovered terminology, and stop at a bounded sufficient context set.',
 'Search “rate limit” once; report that no limiter exists and write a new one.',
 'Search “rate limit”; inspect middleware references, discover “throttle,” retrieve throttle.ts and its router wiring, and stop when the ownership and call path are known.',
 'The second query follows observed vocabulary and a named missing call path rather than repeating the initial query.',
 'A reviewer can inspect the final relevant paths, gap log, and stopping condition.',
 'Use a fixed retrieval budget; retain unresolved gaps. Source relevance numbers are illustrative, not calibrated probabilities.'),
 ('通过明确的信息缺口调整检索上下文，不提前猜定全部文件。','为 API 端点添加限流，代码库将现有限流器称为 throttle。','先广泛搜索，再评估结果与任务的关联，列出缺口，加入实际术语，在有限轮次内满足所需上下文。','只搜一次 rate limit，断言没有限流器并重新实现。','先搜 rate limit，沿中间件引用发现 throttle，再读取 throttle.ts 与路由接线；确认归属与调用链后停止。','下一轮依据观察到的术语和缺失调用链，不重复原查询。','可检查最终路径、缺口记录与停止条件。','设置检索预算并保留未解缺口；来源中的相关性数字只是示例，不是校准概率。'),['retrieval','bounded-loop'])

add('phase-compaction','Phase-Boundary Compaction','阶段边界压缩','context','strategic-compact',76,122,'Compaction Decision Guide / Best Practices',[128,137],
('Compact after a durable phase artifact exists, preserving the task state needed for the next phase.','A long authentication migration has completed research and is about to begin implementation.','Write the plan, decisions, active constraints, and next action to a file; compact at that transition; reopen the durable state.','Compact halfway through editing auth.ts with unwritten decisions and a partial repair.','Save migration-plan.md with the approved contract, changed files and pending checks; compact before implementation and read it back.','The phase artifact supplies recovery state that transient conversation may lose.','The resumed session can name the goal, constraints and first pending step from the saved file.','Do not assume a harness todo list exists or survives; avoid compaction while tightly coupled changes are unfinished.'),
('先保存持久阶段产物，再压缩上下文，保留下一阶段需要的任务状态。','认证迁移完成调研，即将进入实现，当前会话已很长。','将计划、决策、当前约束和下一步写入文件，在阶段交接点压缩，再读取保存状态。','修改 auth.ts 到一半时压缩，关键决策和修复状态都没保存。','保存 migration-plan.md，写明已定契约、变更文件和待验证项；实现前压缩并重新读取。','文件提供恢复状态，避免仅依赖临时对话。','恢复后的会话能从文件指出目标、约束和首个待办步骤。','不要假设工具待办列表存在或能保留；紧密关联修改未完成时避免压缩。'),['compaction','handoff'])

add('budget-inventory','Loaded-Context Inventory','已加载上下文盘点','context','context-budget',22,44,'Inventory',[37],
('Inventory the context carriers actually used by a task before optimizing token overhead.','A project loads many rules, skills and tool schemas before a small API edit.','List agents, skill bodies, rules, instructions and tool schemas; identify duplication; separate always-needed from on-demand guidance.','Delete a large but necessary schema because its file is the biggest.', 'Record that duplicate style rules appear in two carriers; retain API constraints and move unrelated deployment guidance behind a task trigger.', 'Component purpose and duplicated content guide reductions rather than file size alone.', 'The inventory shows which content remains always loaded, which loads on demand and why.', 'Character and word estimates are heuristics; persisted transcript bytes do not establish active tokens or billing.'),
('先盘点任务实际使用的上下文载体，再优化其开销。','修改一个 API 前，项目已加载大量规则、技能和工具 schema。','列出代理、技能正文、规则、指令及工具 schema，识别重复，再区分常驻与按需内容。','因为某 schema 文件最大，就删掉这个必需契约。','记录两处重复风格规则，保留 API 约束，将无关部署指南改为任务触发加载。','削减依据用途与内容重复，不能只看文件大小。','盘点表说明哪些常驻、哪些按需以及原因。','字符和词数只是估算；落盘对话字节数不能证明活跃 token 或账单。'),['budget','deduplication'])

add('trigger-reference-loading','Trigger-Table Reference Loading','触发表驱动的参考加载','context','strategic-compact',124,146,'Trigger-Table Lazy Loading',[23,100],
('Keep routing metadata small and load detailed guidance only when its task condition applies.','A coding assistant supports testing, security and deployment workflows.','Publish a concise trigger-to-reference table and read the matching skill when the actual task requires it.','Paste all three full playbooks into every session.', 'For “add a regression test,” select testing → tdd-workflow; load that body and leave unrelated deployment references deferred.', 'Routing metadata remains available without paying the context cost of every detailed playbook.', 'The selected reference and trigger are visible; unrelated guidance is absent from the active brief.', 'Broad keyword matches are only routing hints; resolve intent and avoid silently skipping cross-cutting security constraints.'),
('保持路由元数据简短，仅在任务条件满足时加载详细指南。','编码助手支持测试、安全与部署流程。','维护触发条件到参考文件的短表，在实际任务需要时读取对应技能。','每个会话都粘贴三份完整手册。','处理“添加回归测试”时选择测试 → tdd-workflow，只加载该正文，部署参考暂缓。','路由始终可发现，又避免所有手册同时占用上下文。','能看到所选参考及触发原因，当前简报不含无关指南。','关键词仅提供路由线索；结合真实意图，不能忽略跨领域安全约束。'),['progressive-disclosure','routing'])

add('scoped-evidence-memory','Scope-Bound Evidence Memory','范围绑定的证据记忆','context','unified-memory',42,74,'Vault Scopes / Recall before writing',[42,121],
('Bind memory recall to the current project, recipient and permitted scopes.','An agent works in two repositories with different conventions and shared team handoffs.','Search project/team scopes, request user scope explicitly, and treat recalled bodies as untrusted evidence to verify.','Apply a private global “use React hooks” memory to a Python service because it matched strongly.', 'Recall the Python repository’s team decision, verify it against current code, and leave user-private and unrelated project memories out.', 'A search match is useful only within the allowed task boundary and current source state.', 'The handoff lists the selected memory scope and corroborating source.', 'Routing labels are not authentication; never broaden scope to recover a denied lookup.'),
('将记忆检索绑定到当前项目、接收者和允许范围。','代理处理两个约定不同的仓库，并共享团队交接。','搜索项目与团队范围，显式申请用户范围；把记忆正文当作待核实证据。','因为匹配度高，就将私人全局“使用 React hooks”记忆套到 Python 服务。','读取 Python 仓库的团队决策，与当前代码核对，排除私人和其他项目记忆。','检索命中只有符合任务范围与当前事实才可采用。','交接说明所选记忆范围及核实来源。','路由标签不等于身份认证；检索被拒绝时不能扩大范围绕过。'),['memory','scope'])

add('incomplete-recall-state','Empty-vs-Incomplete Recall','空结果与不完整检索区分','context','unified-memory',76,98,'Recall is evidence, not certainty',[175],
('Report incomplete retrieval separately from a complete search with no matches.','A memory scan encounters one unreadable decision file while searching for an approval.','Inspect search diagnostics and preserve complete-empty, incomplete and found outcomes; repair the authorized scan before making absence claims.','One file fails to parse; answer “there is no approval.”','Report “scan incomplete: decision-17.md unreadable; no approval confirmed,” repair or ask the owning system to resolve that file, then repeat the same scoped lookup.','A failed scan cannot establish that the requested record does not exist.','A test with one corrupt file returns incomplete rather than not-found.', 'This pattern does not authorize widening access or inferring approval from cached text.'),
('将不完整检索与完整搜索后的无命中分开报告。','检索批准记录时，有一个决策文件无法读取。','检查诊断，保留命中、完整空结果和不完整三种状态；修复允许范围内的扫描再判断不存在。','一个文件解析失败，就回答“没有批准”。','报告“扫描不完整：decision-17.md 无法读取，尚未确认批准”；修复后在相同范围重查。','扫描失败不能证明记录不存在。','加入损坏文件的测试应返回不完整，不能返回未找到。','此方法不授权扩大访问，也不能从缓存文本推断批准。'),['retrieval','uncertainty'])

add('memory-current-state','Recall Freshness and Supersession','记忆时效与显式替代','context','unified-memory',88,102,'Recall is evidence, not certainty',[196],
('Check current authority and explicit supersession before reusing a saved decision.','A saved deployment decision predates a rollback and later correction.','Verify present source state, record observation time, and mark superseded entries explicitly; keep historical reads distinguishable from active recall.','Repeat the old approved rollout because its saved hash is intact.', 'Read the current rollback issue, report the old record as historical, and link a corrected handoff that states the rollback and next verification.', 'Integrity of bytes does not prove freshness, truth or continuing approval.', 'Normal recall excludes superseded records while historical lookup preserves their status.', 'Links alone do not supersede records; current authorization still comes from the owning system.'),
('复用保存决策前，核对当前权威来源及显式替代状态。','保存的部署决策早于一次回滚和后续纠正。','核实当前来源状态，记录观察时间，显式标记旧条目已被替代；历史读取与当前检索分开。','因为保存哈希没变，就重复旧的部署批准。','读取当前回滚 issue，将旧记录标为历史，链接说明回滚及下一验证动作的新交接。','字节完整不证明时效、事实或持续批准。','普通检索排除已替代条目，历史读取保留其状态。','仅建立链接不会自动替代旧记录；授权仍来自实际拥有者。'),['memory','freshness'])

add('atomic-learning','Atomic Trigger-Action Lessons','原子触发行动经验','skill-authoring','continuous-learning-v2',48,79,'The Instinct Model',[95],
('Store a learned behavior as one trigger, one action and the observations supporting it.','The user repeatedly corrects use of exceptions in one service’s domain layer.','Capture the local trigger, specific replacement action, evidence and tentative confidence rather than a whole-session transcript.','Create a global skill saying “never throw exceptions anywhere.”','Record project=payments, trigger=domain validation, action=return Result, evidence=the two cited corrections; leave other projects unaffected.', 'The lesson retains its original boundary and can be inspected or contradicted later.', 'The record contains an actionable trigger, action, project and cited observations.', 'Observation frequency is evidence for a local habit, not proof of universal correctness.'),
('把经验保存为一个触发条件、一个行动及支持它的观察。','用户反复纠正某服务领域层的异常用法。','记录局部触发、替代动作、证据和暂定置信，避免保存整段对话。','创建全局技能：“任何地方都不许抛异常”。','记录 project=payments，触发=领域校验，动作=返回 Result，证据=两次具体纠正；不影响其他项目。','经验保留原适用范围，后续可检查或反驳。','记录包含可执行触发、行动、项目和观察出处。','出现频率能支持局部习惯，不能证明普遍正确。'),['learning','atomicity'])

add('evidence-promotion','Evidence-Gated Rule Promotion','证据门槛下的规则提升','skill-authoring','continuous-learning-v2',287,342,'Scope Decision Guide / Instinct Promotion',[119],
('Promote a local learned behavior only after checking recurrence, scope and counter-evidence.','A local input-validation lesson appears in two independent services.','Compare compatible triggers and actions across projects, retain evidence and scope, and downgrade or withhold promotion on contradictory corrections.','Make a React-only convention global after one successful use.', 'Compare matching validation lessons from both services, confirm applicability, and propose a broader rule with the two observations and known exceptions.', 'Promotion is based on cross-context recurrence rather than the confidence of one session.', 'The proposal cites the contributing projects, observations and exclusions.', 'Repository confidence thresholds are operational settings, not calibrated probabilities; governed policy still needs its normal review.'),
('提升局部经验前，检查跨环境重复、适用范围和反证。','两个独立服务都出现输入校验经验。','比较兼容的触发与行动，保留证据和范围；存在相反纠正时降低置信或暂缓提升。','React 约定只成功一次，就提升为全局规则。','比较两个服务的相同校验经验，确认通用性，带上两次观察和例外，提出更广规则。','提升依据跨环境重复，不依据一次会话的自信。','提案能指出贡献项目、观察和排除条件。','来源阈值是运行配置，不是校准概率；正式政策仍走原有审核。'),['learning','promotion'])

add('transient-retry','Transient-Only Retry Policy','仅重试暂时性失败','tools','cost-aware-llm-pipeline',80,104,'Narrow Retry Logic',[15,41],
('Retry only failures that can change without changing the request, with an explicit cap.','A batch LLM call returns either a rate limit or an invalid API credential.','Classify errors before retry; back off on temporary service failures, stop immediately on invalid input or authentication failures.','Retry the same invalid credential five times.', 'Stop on 401 and report missing valid authentication; for a temporary 429, apply the configured bounded backoff and preserve the final failure.', 'The retry decision follows error cause instead of treating every exception as recoverable.', 'A test shows zero retries for 401 and a capped number for the transient fixture.', 'Do not retry irreversible side effects merely because transport failed; unknown delivery requires reconciliation.'),
('只重试不改请求就可能恢复的失败，并设置上限。','批量 LLM 调用可能返回限流，也可能返回无效凭证。','重试前分类；暂时服务故障使用退避，无效输入或认证立即停止。','同一个无效凭证重试五次。','401 立即报告需要有效认证；暂时 429 按配置有限退避，最终失败保留。','重试由错误原因决定，不把所有异常当可恢复。','测试确认 401 无重试、暂时故障重试次数受限。','不可逆操作的传输失败不能直接重试；未知投递需核对。'),['retry','recovery'])

add('deterministic-fallback','Deterministic Parse with Uncertain-Case Escalation','确定性解析与疑难项升级','tools','regex-vs-llm-structured-text',86,184,'Confidence Scoring / LLM Validator / Hybrid Pipeline',[],
('Run a deterministic parser first and send only structurally uncertain items for model review.','Extract numbered quiz questions whose normal format is stable but some entries have missing answers.','Parse known structures, validate required fields, retain raw text, escalate failed or uncertain records, and revalidate model repairs.','Send every quiz item to a model and accept whatever fields it returns.', 'Parse the stable question syntax locally; mark a missing-answer record uncertain; ask the model only about that raw record and validate the returned schema.', 'The model handles bounded ambiguity while ordinary extraction stays reproducible.', 'Fixtures identify which records escalate, and all accepted outputs pass the same validation.', 'Do not apply a rigid parser to unrestricted prose; source success percentages are not transferable guarantees.'),
('先用确定性解析器，只有结构不确定的项进入模型审阅。','提取编号试题，大多数格式稳定，少数缺答案。','解析已知结构，校验必需字段，保留原文，升级失败或疑难记录，并再校验模型修复。','全部试题送给模型，返回什么字段都接受。','本地解析固定语法；缺答案记录标疑难；模型只处理该原文，输出继续过相同 schema。','模型处理有限歧义，常规提取仍可重复。','样例测试指出哪些记录升级，所有接受结果经过同一校验。','自由散文不宜硬套解析；来源成功率不可当通用保证。'),['hybrid','validation'])

add('typed-tool-recovery','Typed Tool Observation and Recovery Contract','工具观察与恢复契约','tools','agent-harness-construction',20,46,'Action Space / Observation / Recovery',[144],
('Make tool results expose status, artifacts and a safe next action instead of opaque prose.','An agent’s export tool cannot reach the target service.','Use stable tool inputs and typed observations with a summary, artifact IDs, recoverability hint and stop condition.','Return “something went wrong,” causing the agent to repeat export indefinitely.', 'Return status=error, cause=service unavailable, artifact=draft-17, next_action=check health, retry_limit=1; preserve the existing draft.', 'The agent can distinguish a failed operation from a partial artifact and choose a bounded recovery.', 'A failure fixture produces the same typed status and one permitted follow-up.', 'An error hint is not proof of root cause; high-risk actions need enforcement in the actual runtime.'),
('工具返回状态、产物和安全下一步，避免不透明的文字。','导出工具无法连接目标服务。','保持输入稳定；输出类型化状态、摘要、产物 ID、可恢复提示与停止条件。','只返回“出错了”，代理无限重复导出。','返回 status=error、cause=服务不可用、artifact=draft-17、next_action=检查健康、retry_limit=1，保留草稿。','代理区分失败操作与已有产物，并选择有限恢复。','失败样例产生稳定类型状态和一次允许的跟进。','提示不证明根因；高风险操作需实际运行时强制。'),['tool-design','typed-output'])

add('failure-capture','Capture Before Retrying','重试前记录失败','workflow','agent-introspection-debugging',35,102,'Failure Capture / Diagnosis / Contained Recovery',[202],
('Record the failing state and run one discriminating check before retrying.','An agent repeatedly reports that a just-written file is missing.','Capture the goal, last successful and failed commands, cwd, branch and path; select a hypothesis and validate it with the smallest observation.','Repeat the write with slightly different wording three times.', 'Record expected path src/auth.ts and actual cwd tools/; inspect the resolved path, correct the working directory, then retry once.', 'A direct environment check separates a state mismatch from a broken write tool.', 'The report contains the hypothesis, check, correction and resulting file evidence.', 'Capture does not justify destructive resets or unsupported claims of automatic healing.'),
('先记录失败状态，再做一次能区分假设的检查，之后才重试。','代理反复说刚写入的文件不存在。','记录目标、最后成功与失败命令、cwd、分支和路径；选定假设，用最小观察验证。','换三种措辞重复写入。','记录预期 src/auth.ts、实际 cwd=tools/；检查解析后的路径，修正工作目录，再重试一次。','直接环境检查区分状态错配与写入工具故障。','报告包含假设、检查、纠正和实际文件证据。','记录失败不授权破坏性重置，也不能声称不存在的自动修复。'),['diagnosis','evidence'])

add('bounded-optimization','Baseline-Gated One-Hypothesis Optimization','基线门控的单假设优化','evaluation','benchmark-optimization-loop',15,71,'Required Baseline / Loop / Promotion Gate',[176,202],
('Compare bounded variants against a repeatable baseline and unchanged correctness gate.','Reduce the runtime of a parser while preserving every accepted record.','Fix the input and correctness gate, measure baseline, change one hypothesis per variant, keep a run ledger and repeat baseline versus winner.','Change batching, parser and data filtering together; report faster completion after dropping difficult records.', 'Run the same fixture and record count; test only batch size first; reject count mismatch, then repeat the faster valid variant against baseline.', 'The measured delta is attributable and cannot be bought by silently losing correctness.', 'The ledger includes commands, inputs, timings, correctness and selected variant.', 'Stop within budget or noise; “best measured safe variant” does not mean global optimum.'),
('使用可重复基线和不变正确性门槛比较有限候选。','缩短解析器耗时，同时保留所有已接受记录。','固定输入与校验，测基线，每个候选只改变一个假设，保存记录，并重复基线与胜者对比。','同时改批次、解析和过滤，丢掉难记录后声称变快。','同一 fixture 和记录总数，先只试批次大小；总数不符即拒绝，再复测更快且有效候选。','差异可归因，不能靠丢失正确性换速度。','记录包含命令、输入、耗时、正确性和所选候选。','达到预算或噪声范围即停；“已测安全最优”不等于全局最优。'),['benchmark','baseline'])

add('protected-acceptance','Protected Acceptance Conditions','受保护的验收条件','evaluation','loop-design-check',44,85,'Machine-Decidable Goal / Plan Build Judge',[],
('Separate implementation from the authority that defines and verifies its completion criteria.','A nightly repair agent must fix failing tests without weakening the test suite.','Define machine-checkable success plus forbidden changes; an independent verifier runs fixed acceptance checks; bounded failures escalate.','Goal: make tests green; allow the fixer to delete the failing assertions.', 'Goal: tests green AND no acceptance file weakened AND a change list exists; CI independently checks the protected baseline before accepting the patch.', 'The fixer cannot satisfy the score by changing the definition of success.', 'A fixture that deletes a failing assertion is rejected even when the local test command succeeds.', 'Protection must exist in the checker/runtime, not only in prose; human sign-off follows the task’s actual authorization policy.'),
('将实现工作与定义、验证完成条件的权威分开。','夜间修复代理要修好测试，不能削弱测试集。','规定机器可检查成功条件及禁止变更，由独立验证者运行固定验收，有限失败后升级。','目标只有“测试变绿”，修复者可以删除失败断言。','目标=测试绿且验收文件未弱化且有变更清单；CI 对保护基线独立检查后接受补丁。','修复者不能通过改成功定义赢得评分。','删除失败断言的样例，即便本地测试通过也被拒绝。','保护必须由检查器或运行时实现，不能仅写在 prompt；人工签署沿任务授权执行。'),['independent-verifier','anti-goodhart'])

add('eval-before-build','Versioned Task Evals Before Implementation','实现前版本化任务评测','evaluation','eval-harness',21,91,'Philosophy / Eval Types / Grader Types',[119],
('Write capability and regression criteria before changing a prompt, model or agent workflow.','A new agent routing rule should choose the test tool without breaking existing security routing.','Version representative task fixtures and deterministic checks first; add rubric or human judgment only where outputs require it.','Tune the prompt until one demonstration looks right, then invent a score.', 'Before tuning, save test-routing positive and security-routing regression fixtures with expected tool sequences; run both after the change.', 'Success criteria remain comparable across changes and include old behavior.', 'The report shows per-fixture pass/fail, version and grader rather than a single favorable anecdote.', 'Do not overfit to known examples; a passing utility test does not prove candidate containment or production readiness.'),
('修改 prompt、模型或代理流程前，先写能力与回归验收。','新路由规则应选测试工具，同时保持已有安全路由。','先版本化代表性任务与确定性检查；只有开放输出才补量表或人工判断。','反复调整到一个演示看起来对，再临时编分数。','调整前保存测试路由正例与安全路由回归例，规定工具顺序，修改后都运行。','前后成功标准可比较，且涵盖旧行为。','报告逐样例显示结果、版本和 grader，不只给好看的例子。','避免对已知样例过拟合；工具单测通过不证明隔离或生产就绪。'),['eval-driven','regression'])

add('reliability-metrics','Retry Success vs Repeated Reliability','重试成功与重复可靠性','evaluation','eval-harness',93,105,'pass@k / pass^k',[],
('Distinguish succeeding once with retries from succeeding on every repeated trial.','A release gate compares two routing prompts across three runs of the same fixture.','Record individual results and report at-least-one success separately from all-trials success, keeping task and budget fixed.','Results pass, fail, fail; claim “three-run reliable” because one run succeeded.', 'Record [pass, fail, fail]: success within three attempts=true; all three trials successful=false; retain costs and failures.', 'The two measures answer different operational questions and cannot substitute for each other.', 'The raw sequence reproduces both reported outcomes.', 'Do not label a three-run observation as a population probability or infer universal reliability from a small sample.'),
('区分多次尝试中成功一次，与每次重复都成功。','发布门槛比较两个路由 prompt，各跑同一 fixture 三次。','保存每次结果，分别报告至少一次成功和全部成功，固定任务与预算。','结果为通过、失败、失败，因为成功一次就称“三次可靠”。','记录 [通过,失败,失败]：三次内成功=true，三次全部成功=false，同时保留成本与失败。','两个指标回答不同运营问题，不能互替。','原始序列能复算两种结果。','三次观察不能写成总体概率，小样本不证明普遍可靠。'),['metrics','retries'])

add('evidence-scorecard','Evidence-Anchored Independent Scorecard','独立维度证据评分','evaluation','agent-self-evaluation',22,88,'Evaluation Axes / Evidence / Workflow',[27,28,53],
('Score each requested quality dimension independently and tie a low score to a fixable gap.','An agent has delivered an API change with code and test output.','Review actual requested output, score one axis at a time, cite concrete evidence and choose one improvement per weak axis.','Give every axis 5 because the implementation “looks solid.”', 'Completeness=3: error response case absent; accuracy=4: focused test passes; add the missing error-path assertion before finalizing.', 'The scorecard exposes actionable omissions instead of laundering confidence through numbers.', 'Each non-perfect score names a specific gap and verification step.', 'Self-evaluation is editorial reflection, not an independent proof or release gate; exclude unrequested scope from scoring.'),
('逐维度独立评分，把低分绑定到可修复缺口。','代理交付 API 变更、代码和测试结果。','评估实际要求的产物，一次评一个维度，引用证据，每个弱项选一个改进。','因为实现“看起来稳”，所有维度给 5。','完整性=3：缺错误响应测试；准确性=4：聚焦测试通过；最终交付前补缺失错误路径断言。','量表揭示可操作遗漏，避免用数字包装自信。','非满分项说明具体缺口与验证步骤。','自评是编辑反思，不是独立证明或发布门槛；不因未要求范围扣分。'),['rubric','self-review'])

add('independent-behavior-review','Independent Behavioral Evaluator','独立行为评审','evaluation','gan-style-harness',82,108,'Generator Agent / Evaluator Agent',[115,156],
('Let a separate evaluator test the produced artifact against the same requirements without becoming its author.','An agent implements a form with success, loading and failure states.','Give the evaluator the spec and runnable artifact; require real interactions and structured findings; let the implementer own repairs.','The implementer declares the form works after looking at its own screenshot.', 'The evaluator submits a valid form, exercises the failure fixture, records a stuck loading state, and returns that reproduction to the implementer.', 'A behavioral observation can reveal a missing transition that static appearance does not show.', 'The finding includes the interaction, expected and actual states and reproduction artifact.', 'Separate agents do not eliminate all bias; evaluation access and destructive journeys remain bounded by the task.'),
('独立评审者按相同要求测试产物，避免同时成为作者。','代理实现包含成功、加载与失败状态的表单。','向评审者提供 spec 和可运行产物，要求真实交互与结构化发现，由实现者负责修复。','实现者看自己的截图就宣布表单正常。','评审者提交有效表单，再走失败 fixture，记录加载状态卡住，交还复现给实现者。','行为观察能发现静态外观无法展示的状态缺失。','发现包含交互、预期与实际状态、复现产物。','代理分离不消除全部偏差；评测访问和破坏性操作仍受任务范围约束。'),['review','behavior'])

add('cleanup-pass','Focused Cleanup Pass','专注清理阶段','workflow','autonomous-loops',318,372,'The De-Sloppify Pattern',[102],
('Use a separate bounded pass to remove unneeded implementation scaffolding while retaining meaningful behavior tests.','A feature patch includes tests of framework internals and redundant runtime checks.','Finish the required behavior, then review additions for unnecessary scaffolding and rerun the unchanged meaningful acceptance checks.','Ask for speed, then remove all tests including the feature’s error-path check.', 'Keep the required success/error tests; remove only the test that re-proves a TypeScript primitive type and a duplicate guard; rerun acceptance.', 'Cleanup targets specific redundancy rather than weakening verification wholesale.', 'The final diff names removed scaffolding and retains the behavior assertions.', 'Do not generalize the source’s superiority claims; cleanup cannot override security checks or required behavior.'),
('以独立且有限的阶段去掉多余脚手架，保留有意义行为测试。','功能补丁包含框架内部测试和重复运行时检查。','完成所需行为后，审阅多余新增代码，清理并重跑不变验收。','为了快，连功能错误路径测试也全部删掉。','保留成功与错误测试，只删重复证明 TypeScript 基元类型的测试和冗余 guard，再跑验收。','清理针对具体重复，不整体削弱验证。','最终 diff 说明删除的脚手架，并保留行为断言。','不要泛化来源的优势结论；清理不能覆盖安全校验与必需行为。'),['refinement','minimality'])

add('parallel-lane-ownership','Dependency and Write-Surface Lane Matrix','依赖与写入范围矩阵','orchestration','parallel-execution-optimizer',16,53,'Core Pattern / Lane Matrix',[127,167],
('Parallelize only lanes whose dependencies and write surfaces are compatible.','Two agents implement frontend and backend work that also share an API contract.','List lane inputs, dependencies, owned paths and verification; run independent reads together and sequence shared contract changes first.','Tell both agents to finish fast and let both rewrite api-schema.json.', 'Owner A changes the canonical schema first; frontend and backend consume it in disjoint directories; integration waits for both evidence reports.', 'The matrix turns concurrency into an explicit dependency decision and prevents overlapping authorship.', 'Each lane has an owner, input artifact and verification result; shared writes are serialized.', 'A worktree separates checkout state, not shared services, credentials or external side effects.'),
('只并行依赖与写入范围兼容的工作道。','两个代理分别实现前后端，同时共享 API 契约。','列出输入、依赖、归属路径和验证，独立读取并行，共享契约先顺序变更。','只要求快，让两人同时重写 api-schema.json。','A 先负责契约，前后端在分离目录消费该契约；整合等待两份证据报告。','矩阵明确并发决策，防止写入归属重叠。','每条道有负责人、输入产物和验证结果；共享写入串行。','worktree 隔离检出状态，不隔离共享服务、凭证或外部效果。'),['parallel','ownership'])

add('model-tier-routing','Measured Complexity-Tiered Model Routing','按复杂度分层的模型路由','orchestration','cost-aware-llm-pipeline',21,43,'Model Routing by Task Complexity',[35,38],
('Use a configurable model tier appropriate to the task and escalate on evidenced failure.','Classify short labels and analyze long ambiguous support incidents in one pipeline.','Define explicit complexity signals, log the chosen tier, cap budget and measure outcomes before tuning routing.','Use the highest-cost model for every label and hardcode its name in each call.', 'Route simple label extraction through the configured low-cost tier; escalate ambiguous incidents under the budget and log the reason.', 'Routing policy becomes inspectable and tunable rather than an implicit per-call choice.', 'Test fixtures produce expected routing reasons and budget refusal behavior.', 'Model names, prices and thresholds change; this is a policy mechanism, not a universal cheapest-model recommendation.'),
('按任务复杂度使用可配置模型层级，失败有证据时再升级。','同一流水线既分类短标签，也分析复杂客服事件。','明确复杂度信号，记录层级选择，限制预算，并依据测量调整路由。','每个短标签都用最高成本模型，名称硬写在所有调用。','简单提取走配置的低成本层，含糊事件在预算内升级并记原因。','路由可审查可调节，不靠每次隐含选择。','样例测试得到预期路由原因和预算拒绝行为。','型号、价格与阈值会变化；这是策略机制，不是通用最低价推荐。'),['routing','cost'])

add('research-before-building','Adopt-Extend-Compose-Build Decision','采用扩展组合自建决策','workflow','search-first',54,86,'Decision Matrix / Preflight / Quick Mode',[103],
('Check existing local and external solutions before writing a new utility, then explain the chosen reuse strategy.','Add dead-link checking to a documentation repository.','Inspect local helpers, available registries and maintained source implementations; compare fit and choose adopt, extend, compose or build.','Write a new link checker without looking at existing maintenance scripts.', 'Find the existing checker, verify anchor coverage, extend its missing locale handling, and state which search channels were available.', 'The task reuses the current architecture and exposes the reason custom work is still needed.', 'The decision lists candidate sources, compatibility and the selected path.', 'An unavailable channel is not evidence of no solution; packages must be reviewed before execution.'),
('新建工具前检索本地与外部方案，并说明采用哪种复用策略。','为文档仓库添加死链检查。','读取本地辅助工具、可用注册源与维护实现，比较适配度，选择采用、扩展、组合或自建。','没看维护脚本就重写链接检查器。','找到现有检查器，核实锚点覆盖，扩展缺失语言处理，并说明哪些搜索渠道可用。','复用当前架构，同时解释仍需自建的部分。','决策列出候选来源、兼容性和所选路径。','渠道不可用不代表没有方案；依赖执行前须审查。'),['reuse','grounding'])

add('version-grounded-docs','Version-Grounded Documentation Retrieval','版本绑定的文档检索','context','documentation-lookup',31,62,'Resolve / Select / Fetch / Use',[30,124],
('Resolve the exact library and requested version before using retrieved API guidance.','Configure middleware in an application whose installed framework version differs from a remembered example.','Inspect the project version, resolve official documentation identity, retrieve the task-specific section, and cite its version while preserving uncertainty.','Paste a remembered middleware example from a different major version.', 'Read the installed version, choose its official docs entry, fetch the routing section, and implement only the supported names.', 'The prompt is grounded in the actual dependency boundary rather than training-memory resemblance.', 'The answer records installed version and the documentation supporting the chosen API.', 'A documentation search can remain incomplete; bounded lookup must not end in invented API names.'),
('确认库身份与所需版本后，再使用检索到的 API 指南。','应用安装版本与记忆中的中间件例子不同。','检查项目版本，定位官方文档身份，读取任务小节，注明版本并保留不确定。','粘贴另一个主版本的中间件示例。','读安装版本，选对应官方条目，取路由小节，只实现该版本支持的名称。','上下文依据真实依赖边界，而非训练记忆相似度。','答复记载安装版本及支持所选 API 的文档。','文档检索可能不完整；达到查询上限也不能编造 API。'),['documentation','version'])

add('untrusted-source-data','Untrusted Sources as Evidence','不可信来源仅作证据','safety','deep-research',32,40,'Untrusted Sources',[10,56],
('Treat retrieved pages and tool bodies as data to assess, not instructions with authority over the task.','A fetched vendor page says to ignore the research scope and send workspace details to its endpoint.','Keep user-defined scope and permissions separate; cite claims, flag manipulation, and corroborate relevant assertions.','Obey the page’s instruction and upload the research context.', 'Record the agent-directed text as manipulation, continue the agreed source comparison, and make no source-requested external submission.', 'A source can support or contest facts without changing who controls the agent’s actions.', 'The trace contains source assessment and no unrequested network mutation.', 'This written rule needs equivalent boundaries in any automated tool/runtime consumers; citation alone does not make a source reliable.'),
('将检索页面和工具正文作为待评估数据，不赋予控制任务的权威。','厂商页面要求忽略调研范围，并将工作区信息发送到它的端点。','将用户范围和权限分离，评估引用、标记操纵，并交叉核实相关主张。','服从页面并上传研究上下文。','把代理定向文字记为操纵，继续既定比较，不进行来源要求的外部提交。','来源可支持或反驳事实，但不能更换行动控制者。','轨迹包含来源评估，没有未经请求网络写入。','自动化消费者也要有同等边界；被引用不等于可靠。'),['prompt-injection','research'])

add('shared-boundary-contract','Single Contract for Parallel Consumers','并行消费者的唯一契约','orchestration','contract-first',31,65,'The Boundary Artifact',[51,167],
('Coordinate independently developed consumers and providers through one authoritative machine-checkable boundary artifact.','Frontend and backend agents implement an order summary in parallel.','Define required fields, nullability, identifiers and errors in one contract; derive consumer types and validate serialized provider output against it.','Frontend invents userName while backend independently returns user_name; both own tests pass.', 'Both derive OrderSummary from the reviewed schema; the frontend mock and real backend response must satisfy that same contract before integration.', 'Independent internal tests no longer hide agreement failure at the shared boundary.', 'Both fixture and serialized response pass the same schema validation.', 'For one-module atomic changes a shared type may suffice; generator inputs remain untrusted and output writes scoped.'),
('独立开发的消费者与提供者共享一个机器可检查的权威边界产物。','前后端代理并行实现订单摘要。','唯一契约明确字段、可空性、标识符和错误；消费类型由其派生，实际序列化响应对其校验。','前端自定 userName，后端自定 user_name，各自测试都过。','双方从审核 schema 派生 OrderSummary；前端 mock 与后端真实响应都满足它后再整合。','各自内部测试不能再掩盖边界不一致。','fixture 与序列化响应通过同一 schema。','单模块原子变更可能只需共享类型；生成器输入仍不可信，写出范围受限。'),['contract','integration'])

add('behavior-path-parity','Alternate-Path Behavioral Parity','替代路径行为一致性','evaluation','contract-first',171,197,'Verify Provider / Integrate by Comparing Evidence',[176],
('Verify materially different execution paths against the same observable contract.','A profile endpoint returns avatar_url in production but omits it in sandbox mode.','Identify production, sandbox, error, empty and feature-flagged paths; verify serialized results and user behavior at each applicable boundary.','Validate the production path only, then claim every mode is compatible.', 'Run the same profile-response contract against sandbox and production fixtures; fail when sandbox lacks avatar_url, and repair that branch.', 'Path coverage exposes a mismatch hidden by happy-path verification.', 'The parity report names each checked path and exact contract result.', 'Mock-mode parity does not prove live database correctness; report untested paths rather than infer coverage.'),
('对实际不同执行路径使用相同可观察契约验证。','资料端点生产模式有 avatar_url，沙盒模式却缺失。','列出生产、沙盒、错误、空值及 feature flag 路径，按边界校验序列化结果和行为。','只验证生产路径，就声称所有模式兼容。','同一响应契约分别验证沙盒与生产 fixture；缺 avatar_url 时失败并修复该分支。','路径覆盖揭示快乐路径检查隐藏的错配。','一致性报告列出每条已检路径与契约结果。','mock 一致不证明真实数据库正确；未测试路径须明确。'),['alternate-paths','regression'])

add('hashed-approval','Exact-Draft Epoch-Bound Approval','精确草稿版本绑定批准','safety','operator-approval-loop',25,98,'Objects / Filing / Deciding',[8,129],
('Bind approval to the exact draft bytes, destination and current revision so stale decisions cannot release rewritten text.','An operator approves a supplier reply while an agent concurrently shortens the draft.','Hash the draft, rotate its revision on edits, and transactionally bind an authorized decision to immutable text and destination.','Use yesterday’s approval flag to send the new shorter draft.', 'Draft v2 gets a new hash and epoch; the v1 decision is stale, and transport can use only the approved snapshot’s exact text and destination.', 'Approval follows the reviewed artifact instead of a mutable document identity.', 'A stale-epoch or changed-text fixture is refused before dispatch.', 'Hashes prove binding, not operator authority; the owning decision writer must authenticate approval.'),
('批准绑定精确文本、目标与当前版本，防止旧决定放行改写草稿。','代理缩短供应商回复的同时，操作者点了批准。','草稿计算哈希，修改推进版本，授权决定事务性绑定不可变文本和目标。','用昨天的批准标志发送新的短草稿。','v2 获得新哈希与 epoch；v1 决定失效，传输只能使用批准快照的精确文本和目标。','批准跟随已审产物，不跟随可变文档身份。','旧 epoch 或文本改动样例在派送前被拒。','哈希证明绑定，不证明操作者权威；批准写入者仍须认证。'),['approval','version-binding'])

add('unknown-delivery-hold','Unknown Delivery Outcome Hold','未知投递结果冻结','safety','operator-approval-loop',109,148,'Delivering',[],
('Hold an irreversible dispatch with an unknown outcome for reconciliation instead of automatically retrying.','A supplier message transport times out after dispatch begins and before the receipt is saved.','Reserve one authorized attempt, record dispatch state, mark uncertainty on timeout, and reconcile provider evidence before any new attempt.','No receipt exists, so send the approved message again.', 'Mark the attempt unknown, block automatic retry, and ask the trusted reconciliation path to verify a provider delivery coordinate.', 'Absence of a receipt does not prove the external effect failed.', 'Timeout and crash fixtures never reopen dispatch; confirmed reconciliation records the same attempt.', 'This is at-most-one automatic attempt, not exactly-once delivery; zero sends may remain blocked until verified.'),
('不可逆派送结果未知时，冻结并核对，不自动重试。','供应商消息已开始派送，但回执保存前传输超时。','预留一次授权尝试，记派送状态，超时标未知，任何新尝试前核实服务端证据。','没有回执就再发一次批准消息。','标记 attempt=unknown，阻止自动重试，由可信核对路径确认服务端投递坐标。','无回执不能证明外部操作没成功。','超时或崩溃样例不会重开放行；确认核对记录同一次尝试。','保证至多一次自动尝试，不是恰好一次投递；零次发送也可能等待核实。'),['side-effects','reconciliation'])

add('audience-separation','Audience, Participation and Delivery Separation','受众参与与投递授权分离','safety','counterparty-channel-discipline',20,85,'Trusted Destination / Participation / Delivery',[60,131],
('Keep audience trust, permission to participate and permission to deliver as separate checks.','An agent appears in an external group whose display name resembles an internal operations channel.','Resolve destination from trusted adapter identity, require scoped participation, classify output for its audience, and recheck the delivery grant at transport.','Treat a channel label “Internal” and a prior bot reply as permission to post debug traces.', 'Use the actual external channel ID; a current agent mention permits a scoped business reply, while internal traces stay on the verified operator surface.', 'A display name or historical presence cannot supply authentication, consent or send authority.', 'Fixtures cover human-addressed silence, agent-addressed response and changed-destination refusal.', 'Prompt guidance alone is not a transport guard; enforce all send, edit and stream paths in the owning runtime.'),
('将受众可信度、参与许可和投递授权分别检查。','外部群聊显示名像内部运营频道，代理也在其中。','用可信适配器身份解析目标，要求范围内参与许可，按受众分类输出，并在传输前再查授权。','把“Internal”标签与历史机器人回复当成发布调试轨迹的许可。','读取真实外部频道 ID；当前 @ 请求允许业务答复，内部轨迹留在核实的操作者界面。','显示名或历史出现不提供身份、同意或发送权。','样例覆盖问人时静默、问代理时回复、目标变化时拒绝。','prompt 不是传输 guard；实际运行时须覆盖发送、编辑和流式路径。'),['audience','authorization'])

if __name__=='__main__':
    (OUT/'ecc-candidates-batch.json').write_text(json.dumps(candidates,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    print(f'{len(candidates)} candidates written')
