"""Pin actual, locally reviewed mechanism exemplars; no external skills are executed."""
import json,pathlib
OUT=pathlib.Path(__file__).resolve().parent; BASE=pathlib.Path('D:/Projects/open-skills'); result={}
def add(ids,repo,path,start,end,license,section):
    for id in ids:
        result.setdefault(str(id),[]).append(dict(repo=repo,path=path,start_line=start,end_line=end,license=license,section=section))
def needle(ids,repo,path,text,span,license):
    lines=(BASE/repo/path).read_text(encoding='utf-8-sig').splitlines()
    start=next(i+1 for i,line in enumerate(lines) if text in line)
    add(ids,repo,path,start,min(len(lines),start+span-1),license,text)
A='anthropics/skills'; S='obra/superpowers'; M='mattpocock/skills'; E='affaan-m/ECC'; C='ComposioHQ/awesome-claude-skills'; G='garrytan/gstack'
creator='skills/skill-creator/SKILL.md'; sdd='skills/subagent-driven-development/SKILL.md'; reviewer='skills/subagent-driven-development/task-reviewer-prompt.md'; writer='skills/productivity/writing-for-agents/SKILL.md'
needle([1],A,creator,'#### Anatomy of a Skill',15,'Apache-2.0')
needle([14,25,112],A,creator,'**Defining output formats**',24,'Apache-2.0')
needle([100,117,118,172],A,creator,'#### Progressive Disclosure',28,'Apache-2.0')
needle([119],A,creator,'### Step 1: Spawn all runs',27,'Apache-2.0')
needle([23,114],A,creator,'└── Bundled Resources',8,'Apache-2.0')
needle([52],A,'skills/skill-creator/agents/grader.md','### Step 3: Evaluate Each Assertion',27,'Apache-2.0')
needle([27,108],A,'skills/skill-creator/agents/comparator.md','### Step 3: Generate Evaluation Rubric',49,'Apache-2.0')
needle([2],S,'skills/writing-plans/SKILL.md','## Step Granularity',9,'MIT')
needle([18,36,126],S,sdd,'**Why subagents:**',5,'MIT')
needle([32],S,sdd,'digraph process',62,'MIT')
needle([35,38,161],S,sdd,'## Model Selection',40,'MIT')
needle([70,128,162],S,sdd,'Conversation memory does not survive',31,'MIT')
needle([41],S,sdd,'Five rounds maximum per task',22,'MIT')
needle([150],S,sdd,'**Continuous execution:**',18,'MIT')
needle([164],S,sdd,'If the final whole-branch review returns findings',11,'MIT')
needle([156],S,sdd,'Do not pre-judge findings',6,'MIT')
needle([157],S,reviewer,'## Do Not Trust the Report',9,'MIT')
needle([159],S,reviewer,'Do not crawl the broader codebase',8,'MIT')
needle([160],S,reviewer,'## Tests',23,'MIT')
needle([158],S,reviewer,'If the plan or brief explicitly mandates',7,'MIT')
needle([12],S,reviewer,'Your review is read-only',3,'MIT')
needle([43],S,'skills/using-git-worktrees/SKILL.md','#### Create the Worktree',12,'MIT')
needle([28,102,186],S,'skills/subagent-driven-development/implementer-prompt.md','## Before Reporting Back: Self-Review',29,'MIT')
needle([165],S,'skills/writing-plans/SKILL.md','## Task Right-Sizing',9,'MIT')
needle([166],S,'skills/writing-plans/SKILL.md','## Global Constraints',8,'MIT')
needle([167],S,'skills/writing-plans/SKILL.md','**Interfaces:**',7,'MIT')
needle([47,65],G,'review/SKILL.md','### Pre-emit verification gate',15,'MIT')
needle([144],A,'skills/mcp-builder/SKILL.md','**API Coverage vs. Workflow Tools:**',17,'Apache-2.0')
needle([101],A,'skills/canvas-design/SKILL.md','## DESIGN PHILOSOPHY CREATION',20,'Apache-2.0')
needle([103],A,'skills/webapp-testing/SKILL.md','## Reconnaissance-Then-Action Pattern',18,'Apache-2.0')
needle([104],A,'skills/webapp-testing/SKILL.md','**Always run scripts with',4,'Apache-2.0')
needle([87,106],A,'skills/doc-coauthoring/SKILL.md','**For each section:**',80,'Apache-2.0')
needle([107],A,'skills/doc-coauthoring/SKILL.md','### Step 2: Test with Sub-Agent',15,'Apache-2.0')
needle([51],A,'skills/pptx/SKILL.md','### File QA (required)',22,'LicenseRef-Anthropic-source-available')
needle([115],A,'skills/pptx/SKILL.md','### Visual QA',19,'LicenseRef-Anthropic-source-available')
needle([116],A,'skills/xlsx/SKILL.md','**Use formulas, never hardcoded results.**',6,'LicenseRef-Anthropic-source-available')
needle([143],A,'skills/theme-factory/SKILL.md','## Create your Own Theme',5,'Apache-2.0')
add([128,137],E,'skills/strategic-compact/SKILL.md',76,122,'MIT','Phase-boundary compaction and preserved state')
add([35],E,'skills/cost-aware-llm-pipeline/SKILL.md',21,43,'MIT','Complexity-based model routing')
add([42,95],E,'skills/continuous-learning-v2/SKILL.md',287,342,'MIT','Project-scoped instincts and learning')
add([26,36],E,'skills/unified-memory/SKILL.md',60,102,'MIT','Memory sources, evidence and scope')
add([11],E,'skills/hermes-imports/SKILL.md',21,49,'MIT','Secret and content sanitization')
add([127],E,'skills/dmux-workflows/SKILL.md',105,117,'MIT','Parallel-safe file ownership')
add([175],E,'skills/terminal-ops/SKILL.md',30,36,'MIT','Exact execution and repository-state reporting')
add([173],C,'composio-skills/ring-central-automation/SKILL.md',11,34,'Apache-2.0 (repository README declaration; per-skill license not supplied)','Unavailable capabilities and unrelated search results')
add([109],C,'composio-skills/alpha-vantage-automation/SKILL.md',14,80,'Apache-2.0 (repository README declaration; per-skill license not supplied)','Discovery, active connection and validated execution')
needle([13],S,'skills/writing-skills/SKILL.md','**Purpose:** Your agent reads the description',47,'MIT')
needle([149],S,'skills/writing-skills/SKILL.md','## Testing All Skill Types',17,'MIT')
needle([145],S,'skills/verification-before-completion/SKILL.md','## The Iron Law',26,'MIT')
needle([146],S,'skills/verification-before-completion/SKILL.md','## Rationalization Prevention',18,'MIT')
needle([148,74],S,'skills/receiving-code-review/SKILL.md','## Forbidden Responses',26,'MIT')
needle([7],S,'skills/brainstorming/SKILL.md','## Establish Shared Understanding',24,'MIT')
needle([8,151],S,'skills/brainstorming/SKILL.md','<HARD-GATE>',19,'MIT')
needle([152],S,'skills/brainstorming/SKILL.md','```dot',22,'MIT')
needle([192,193,191],M,writer,'## Steps and completion criteria',11,'MIT')
needle([192],M,writer,'Hunt **no-ops** sentence by sentence',1,'MIT')
needle([190],M,'skills/productivity/writing-for-agents/SKILL-MECHANICS.md','## Invocation',10,'MIT')
needle([194],M,'skills/engineering/domain-modeling/SKILL.md','### Sharpen fuzzy language',4,'MIT')
needle([206],M,'skills/engineering/domain-modeling/SKILL.md','### Offer ADRs sparingly',10,'MIT')
needle([197],M,'skills/engineering/wayfinder/SKILL.md','## Fog of war',14,'MIT')
needle([203],M,'skills/engineering/wayfinder/SKILL.md','Every ticket is either',3,'MIT')
needle([198],M,'skills/engineering/code-review/SKILL.md','Both axes run as',4,'MIT')
needle([201],M,'skills/engineering/diagnosing-bugs/SKILL.md','**If no correct seam exists',7,'MIT')
needle([202],M,'skills/engineering/diagnosing-bugs/SKILL.md','### Completion criterion',14,'MIT')
needle([6],S,'skills/receiving-code-review/SKILL.md','## Forbidden Responses',13,'MIT')
out=(json.dumps(result,ensure_ascii=False,indent=2)+'\n').replace('\n','\r\n').encode('utf-8');(OUT/'legacy-source-map.json').write_bytes(out)
print('Mapped',len(result),'legacy IDs to observed examples')
