"""Record page-level remediation from the legacy full-text audit."""
import pathlib,json,hashlib,re
ROOT=pathlib.Path(__file__).resolve().parents[2];OUT=ROOT/'docs/audit'
recommendations={
'token-level-techniques':('rewrite','Useful structure and example techniques are mixed with invented attention distributions and deterministic-behavior claims.','Keep task-level guidance and examples; remove illustrative probabilities presented as observed behavior, hidden-chain-of-thought recipes, universal XML superiority and attention-position explanations without experimental support. Link #3/#14/#25/#100/#152; retain vendor advice only as vendor-scoped guidance.'),
'anti-laziness':('rewrite','Its eight defenses overlap reference pointers, scripts, isolation and validation; numerical skip-rate examples have no reproducible local outputs.','Describe observable reference-skipping, not model motivation. Consolidate into #23/#100/#104/#42/#51/#119, use explicit read evidence, and remove claims that scripts or subagents eliminate failure or provide perfect safety.'),
'branching-stability':('rewrite','The practical routing examples are useful, but the reported five-run outputs are not available; branch-stability labels overgeneralize.','Preserve routing fixtures and unknown branch; remove unsupported 5/5 findings or mark them historical reported observations with raw outputs unavailable. Separate shape/schema enforcement from branch structure and link #3/#20/#51/#152.'),
'good-vs-bad-template':('rewrite','Specific contracts are useful, but the static csproj example overclaims deterministic behavior and hardcodes domain rules that are not universal.','Turn it into the editorial teaching-example template: same task and known facts, concrete failure, improved action, observable result and boundary. Replace XML/attention causal assertions and universal package assumptions; distinguish static checks from build verification.'),
'skill-architecture':('rewrite','Packaging observations are useful, but historical repository counts and quantitative prevalence lack a frozen coverage ledger; the text still addresses another migration plugin.','Use frozen source inventory for current counts and repository-specific licenses. Replace plugin-specific names and instructions with generic packaging guidance, and link #1/#13/#19/#23/#100/#109/#190. Do not call Anthropic document skills open source or infer efficacy from their complexity.'),
'reference-skip-playbook':('rewrite','Eleven solution shapes are worthwhile variants but duplicate the anti-laziness page and make unsupported guarantees about attention and hooks.','Keep one reference-reading guide with a trace-based diagnosis, conditional pointer, inline essential rule, script interface and actual validation. Treat naked-hop/pre-satisfaction/optional framing as hypotheses to test. Remove perfect-determinism claims and retain host-specific hooks as scoped examples.'),
'quality-standards':('rewrite','The page contains orphaned command/rule references from a separate migration plugin, fixed line/token quotas and claims that forks always start fresh.','Replace with project editorial rules and maintained source policy. Require concrete scenarios, paired examples, observation/origin separation, bilingual completeness and checkable links. Vendor up-to-30-percent advice is a vendor-reported complex-long-context result, not a general project guarantee.'),
'review-checklist':('rewrite','Its evidence structure is useful, but several review checks treat heuristics as universal obligations and enforce unverifiable effects.','Review against project editorial rules and original task separately. Remove mandatory XML, chain-of-thought exposure, fixed skill size thresholds and invented 30-percent/5-percent deviations. Check source pins, claims, fixtures, authorization scope and actual validator outcomes.'),
'2026-04-19-decision-tree-pattern':('revise-historical','The 20-run numeric results cannot be recomputed because raw outputs are absent; action enums and explicit schema also change between prompt variants.','Keep date, fixtures and the motivation for output-contract tests. Remove numerical superiority claims or explicitly label them previously reported/unverified. Explain confounding: literal action strings differ, so the result cannot isolate tree-versus-prose format. Link current #14/#20/#152 and Patternfoo.'),
'2026-04-19-prompt-engineering-patterns':('revise-historical','The article reproduces fabricated token probabilities and overstates transformer attention mechanisms as guarantees.','Retain date and practical prompt-structure examples; replace causal/quantitative explanations with bounded hypotheses and links to the current catalog and cited primary vendor guidance.'),
'2026-05-26-prompt-pattern-catalog':('revise-historical','The claimed at-least-three-independent-plugins admission rule conflicts with many single-source catalog entries; example IDs 23 and 45 do not match actual catalog identities.','Preserve the historical release description with a revision note; remove unrecoverable 500-plus production-corpus and prevalence assertions, fix examples to #41 and relevant current review/gate entries, and route readers to the current source/audit methodology.'),
'2026-07-08-harvest-2026-07':('revise-historical','The historical 51 names exist, but confidence labels are not calibrated efficacy; no-change source claims lack recorded old/new SHAs and the malicious-credential criterion is oversimplified.','Keep 155-to-206 as a historical catalog change, point to decisions for all IDs, remove unstored commit-comparison claims, and distinguish suspicious routing from confirmed malicious intent. Show current canon through generated links, not a permanent total.')}
pages=[]
for directory in ('catalog/techniques','catalog/standards','_posts'):
    for path in sorted((ROOT/directory).glob('*.md')):
        stem=path.stem.removesuffix('-zh');decision,reason,rec=recommendations[stem]
        data=path.read_bytes();text=data.decode('utf-8-sig')
        pages.append({'path':path.relative_to(ROOT).as_posix(),'decision':decision,'reason':reason,'recommendation':rec,'language':'zh' if path.stem.endswith('-zh') else 'en','reviewed_sha256':hashlib.sha256(data).hexdigest(),'line_count':len(text.splitlines()),'review_method':'full-text structural and claim audit; bilingual companion checked for matching remediation','unsupported_numeric_claims':[line.strip() for line in text.splitlines() if re.search(r'(?:\d+%|\d+ percent|\b(?:35|30|25|92|47|832|2290|2,290)\b)',line)][:25]})
for relative in ('catalog/README.md','catalog/README-zh.md','catalog/catalog-index.md','catalog/catalog-index-zh.md','catalog/index.md','catalog/browse.md','catalog/patterns-156-206.md','catalog/patterns-156-206-zh.md'):
    p=ROOT/relative;data=p.read_bytes()
    pages.append({'path':relative,'decision':'regenerate','reason':'Duplicated counts, taxonomy and hand-maintained detail links drift from the actual canonical corpus.','recommendation':'Generate from active canonical metadata with stable routes, bilingual pairs, explicit merged/withdrawn aliases and source-state filters; never count compatibility pages as active patterns.','language':'zh' if p.stem.endswith('-zh') else 'en','reviewed_sha256':hashlib.sha256(data).hexdigest(),'line_count':len(data.decode('utf-8-sig').splitlines()),'review_method':'metadata and route audit'})
(OUT/'legacy-nonpattern-pages.json').write_bytes((json.dumps(pages,ensure_ascii=False,indent=2)+'\n').replace('\n','\r\n').encode('utf-8'))
print(f'Recorded {len(pages)} page decisions')
